---
permalink: switch-cisco-3232c/cn1610-migrate-to-3232c-overview.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Antes de configurar os switches Cisco Nexus 3232c, revise uma visão geral do processo e da nomenclatura. 
---
= Requisitos de migração
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Os switches Cisco Nexus 3232C podem ser usados como switches de cluster no seu cluster AFF ou FAS . Os switches de cluster permitem que você crie clusters ONTAP com mais de dois nós.


NOTE: O procedimento requer o uso de comandos ONTAP e comandos dos switches Cisco Nexus série 3000; os comandos ONTAP são usados, a menos que indicado de outra forma.

Caso necessário, consulte as informações a seguir para obter mais detalhes:

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 e CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet da Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== Requisitos de migração CN1610

Os switches de cluster suportam as seguintes conexões de nó:

* NetApp CN1610: portas 0/1 a 0/12 (10 GbE)
* Cisco Nexus 3232C: portas e1/1-30 (40 ou 100 ou 4x10GbE)


Os switches do cluster utilizam as seguintes portas de enlace entre switches (ISL).

* NetApp CN1610: portas 0/13 a 0/16 (10 GbE)
* Cisco Nexus 3232C: portas 1/31-32 (100GbE)


[NOTE]
====
É necessário usar cabos breakout 4x10G no switch de cluster Cisco Nexus 3232C.

====
A tabela a seguir mostra as conexões de cabeamento necessárias em cada etapa durante a transição dos switches NetApp CN1610 para os switches de cluster Cisco Nexus 3232C:

|===
| Estágio | Descrição | Cabos necessários 


 a| 
Inicial
 a| 
CN1610 para CN1610 (SFP+ para SFP+)
 a| 
4 cabos de fibra óptica SFP+ ou cabos de cobre de conexão direta



 a| 
Transição
 a| 
CN1610 para 3232C (QSFP para SFP+)
 a| 
1 cabo breakout de fibra óptica QSFP e 4 cabos breakout de cobre SFP+



 a| 
Final
 a| 
3232C para 3232C (QSFP para QSFP)
 a| 
2 cabos de fibra óptica QSFP ou cabos de cobre de conexão direta

|===
Você deve ter baixado os arquivos de configuração de referência (RCFs) aplicáveis.  O número de portas 10 GbE e 40/100 GbE está definido nos RCFs disponíveis emlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download do arquivo de configuração de referência do switch de rede de cluster Cisco"^] .

As versões do ONTAP e do NX-OS compatíveis com este procedimento estão listadas emlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet da Cisco"^] .

As versões do ONTAP e do FASTPATH ​​compatíveis com este procedimento estão listadas emlink:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["Switches NetApp CN1601 e CN1610"^] .

.Sobre os exemplos utilizados
Os exemplos no procedimento de migração utilizam quatro nós:

* Dois nós utilizam quatro portas de interconexão de cluster 10 GbE: *e0a*, *e0b*, *e0c* e *e0d*.
* Os outros dois nós usam dois cabos de fibra óptica de interconexão de cluster de 40 GbE: *e4a* e *e4e*.
+
Olink:https://hwu.netapp.com/["_Universo do Hardware_"^] Contém informações sobre os cabos de fibra óptica para clusters em suas plataformas.



Os exemplos neste procedimento utilizam a seguinte nomenclatura de interruptor e nó:

* Os nós são *n1*, *n2*, *n3* e *n4*.
* Os resultados dos comandos podem variar dependendo das diferentes versões do software ONTAP .
* Os interruptores CN1610 a serem substituídos são *CL1* e *CL2*.
* Os switches Nexus 3232C para substituir os switches CN1610 são *C1* e *C2*.
* *n1_clus1* é a primeira interface lógica de cluster (LIF) que está conectada ao switch de cluster 1 (CL1 ou C1) para o nó *n1*.
* *n1_clus2* é a primeira LIF de cluster que está conectada ao switch de cluster 2 (CL2 ou C2) para o nó *n1*.
* *n1_clus3* é a segunda LIF que está conectada ao switch de cluster 2 (CL2 ou C2) para o nó *n1*.
* *n1_clus4* é a segunda LIF que está conectada ao switch de cluster 1 (CL1 ou C1) para o nó *n1*.
* O número de portas 10 GbE e 40/100 GbE está definido nos arquivos de configuração de referência (RCFs) disponíveis emlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download do arquivo de configuração de referência do switch de rede de cluster Cisco"^] .


.O que vem a seguir?
link:cn1610-prepare-to-migrate.html["Prepare-se para a migração"].
