---
permalink: switch-cisco-3232c/cn5596-complete-migration.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Você pode usar switches Cisco Nexus 3232C como switches de cluster em seu cluster AFF ou FAS . 
---
= Conclua sua migração de switches 5596 para switches 3232C.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conclua os seguintes passos para finalizar a migração dos switches Nexus 5596 para switches Nexus 3232C.

.Passos
. Verifique se os switches de cluster apropriados estão sendo monitorados:
+
`system cluster-switch show`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network    10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. Se você desativou a criação automática de casos, reative-a enviando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que vem a seguir?
Após concluir a migração do seu switch, você poderálink:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"] .
