---
permalink: switch-cisco-3232c/configure-reqs-3232c.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Você pode usar switches Cisco Nexus 3232C como switches de cluster em seu cluster AFF ou FAS . 
---
= Requisitos de configuração para switches Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalação e manutenção do switch Cisco Nexus 3232C, certifique-se de revisar os requisitos de configuração e de rede.



== Requisitos de configuração

Para configurar seu cluster, você precisa da quantidade e do tipo adequados de cabos e conectores de cabos para seus switches.  Dependendo do tipo de switch que você estiver configurando inicialmente, será necessário conectar-se à porta de console do switch com o cabo de console incluído; você também precisará fornecer informações específicas da rede.



== Requisitos de rede

Você precisa das seguintes informações de rede para todas as configurações de switch:

* Sub-rede IP para tráfego de rede de gerenciamento
* Nomes de host e endereços IP para cada um dos controladores do sistema de armazenamento e todos os switches aplicáveis
* A maioria dos controladores de sistema de armazenamento são gerenciados por meio da interface e0M, conectando-se à porta de serviço Ethernet (ícone de chave inglesa). Nos sistemas AFF A800 e AFF A700 , a interface e0M utiliza uma porta Ethernet dedicada.


Consulte o https://hwu.netapp.com["Hardware Universe"^] Para obter as informações mais recentes.

.O que vem a seguir
Após confirmar os requisitos de configuração, você poderá revisar olink:required-documentation-3232c.html["documentação necessária"] .
