---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: Ao substituir switches de cluster CN1610 por switches de cluster Cisco Nexus 3232C, é preciso estar ciente de certas informações de configuração, conexões de porta e requisitos de cabeamento. 
---
= Requisitos de migração para switches de cluster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de migrar para switches de cluster Cisco Nexus 3232C, revise as informações de configuração, as conexões de porta e os requisitos de cabeamento.



== Requisitos de migração CN1610

Os switches de cluster suportam as seguintes conexões de nó:

* NetApp CN1610: portas 0/1 a 0/12 (10 GbE)
* Cisco Nexus 3232C: portas e1/1-30 (40 ou 100 ou 4x10GbE)


Os switches do cluster utilizam as seguintes portas de enlace entre switches (ISL).

* NetApp CN1610: portas 0/13 a 0/16 (10 GbE)
* Cisco Nexus 3232C: portas 1/31-32 (100GbE)


[NOTE]
====
É necessário usar cabos breakout 4x10G no switch de cluster Cisco Nexus 3232C.

====
A tabela a seguir mostra as conexões de cabeamento necessárias em cada etapa durante a transição dos switches NetApp CN1610 para os switches de cluster Cisco Nexus 3232C:

|===
| Estágio | Descrição | Cabos necessários 


 a| 
Inicial
 a| 
CN1610 para CN1610 (SFP+ para SFP+)
 a| 
4 cabos de fibra óptica SFP+ ou cabos de cobre de conexão direta



 a| 
Transição
 a| 
CN1610 para 3232C (QSFP para SFP+)
 a| 
1 cabo breakout de fibra óptica QSFP e 4 cabos breakout de cobre SFP+



 a| 
Final
 a| 
3232C para 3232C (QSFP para QSFP)
 a| 
2 cabos de fibra óptica QSFP ou cabos de cobre de conexão direta

|===
Você deve ter baixado os arquivos de configuração de referência (RCFs) aplicáveis.  O número de portas 10 GbE e 40/100 GbE está definido nos RCFs disponíveis emlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download do arquivo de configuração de referência do switch de rede de cluster Cisco"^] .

As versões do ONTAP e do NX-OS compatíveis com este procedimento estão listadas emlink:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet da Cisco"^] .

As versões do ONTAP e do FASTPATH ​​compatíveis com este procedimento estão listadas emlink:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["Switches NetApp CN1601 e CN1610"^] .



== Requisitos CN5596

Os switches do cluster utilizam as seguintes portas para conexões com os nós:

* Portas e1/1-40 (10 GbE): Nexus 5596
* Portas e1/1-30 (10/40/100 GbE): Nexus 3232C
+
** Os switches do cluster utilizam as seguintes portas de Inter-Switch Link (ISL):


* Portas e1/41-48 (10 GbE): Nexus 5596
* Portas e1/31-32 (40/100 GbE): Nexus 3232C
+
** Olink:https://hwu.netapp.com/["_Universo do Hardware_"^] Contém informações sobre a cablagem compatível com os switches Nexus 3232C:


* Os nós com conexões de cluster de 10 GbE requerem cabos breakout de fibra óptica QSFP para SFP+ ou cabos breakout de cobre QSFP para SFP+.
* Os nós com conexões de cluster 40/100 GbE requerem módulos ópticos QSFP/QSFP28 compatíveis com cabos de fibra óptica ou cabos de cobre QSFP/QSFP28 de conexão direta.
+
** Os switches do cluster utilizam a cablagem ISL apropriada:


* Início: Nexus 5596 (SFP+ para SFP+)
+
** 8 cabos de conexão direta SFP+ em fibra óptica ou cobre


* Interino: Nexus 5596 para Nexus 3232C (adaptador QSFP para 4xSFP+)
+
** 1 cabo breakout de fibra óptica ou de cobre QSFP para SFP+


* Versão final: Nexus 3232C para Nexus 3232C (QSFP28 para QSFP28)
+
** 2 cabos de fibra óptica ou cobre QSFP28 com conexão direta
+
*** Nos switches Nexus 3232C, você pode operar as portas QSFP/QSFP28 nos modos 40/100 Gigabit Ethernet ou 4 x10 Gigabit Ethernet.
+
Por padrão, existem 32 portas no modo Gigabit Ethernet 40/100.  Essas 40 portas Gigabit Ethernet são numeradas seguindo uma convenção de nomenclatura de 2 elementos.  Por exemplo, a segunda porta Ethernet de 40 Gigabits é numerada como 1/2.  O processo de alterar a configuração de Ethernet de 40 Gigabit para Ethernet de 10 Gigabit é chamado de _breakout_ e o processo de alterar a configuração de Ethernet de 10 Gigabit para Ethernet de 40 Gigabit é chamado de _breakin_.  Ao dividir uma porta Gigabit Ethernet de 40/100 em 10 portas Gigabit Ethernet, as portas resultantes são numeradas usando uma convenção de nomenclatura de 3 elementos.  Por exemplo, as portas de conexão da segunda porta Gigabit Ethernet 40/100 são numeradas como 1/2/1, 1/2/2, 1/2/3 e 1/2/4.

*** No lado esquerdo dos switches Nexus 3232C encontram-se duas portas SFP+, denominadas 1/33 e 1/34.
*** Você configurou algumas portas nos switches Nexus 3232C para operar em 10 GbE ou 40/100 GbE.
+
[NOTE]
====
Você pode configurar as seis primeiras portas para o modo 4x10 GbE usando o `interface breakout module 1 port 1-6 map 10g-4x` comando.  Da mesma forma, você pode reagrupar as seis primeiras portas QSFP+ da configuração de breakout usando o `no interface breakout module 1 port 1-6 map 10g-4x` comando.

====
*** Você já realizou o planejamento, a migração e leu a documentação necessária sobre a conectividade de 10 GbE e 40/100 GbE dos nós aos switches de cluster Nexus 3232C.
*** As versões do ONTAP e do NX-OS suportadas neste procedimento são as seguintes:link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet da Cisco"^] .





