---
permalink: switch-cisco-3232c/migrate-from-cisco-nexus-5596.html 
sidebar: sidebar 
keywords: migrate, cisco nexus 5596 switch, 3232c 
summary: Para substituir os switches de cluster Cisco Nexus 5596 existentes em um cluster por switches de cluster Nexus 3232C, você deve executar uma sequência específica de tarefas. 
---
= Migre de um switch de cluster Cisco Nexus 5596 para um switch de cluster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para migrar os switches de cluster Cisco Nexus 5596 existentes em um cluster com switches de cluster Nexus 3232C.



== Rever os requisitos

Antes da migração, certifique-se de rever link:migrate-requirements-3232c.html["Requisitos de migração"]o .

[NOTE]
====
O procedimento requer o uso de comandos ONTAP e comandos Cisco Nexus 3000 Series switches; os comandos ONTAP são usados, a menos que indicado de outra forma.

====
Para obter mais informações, consulte:

* http://support.netapp.com/NOW/download/software/cm_switches/["Página de descrição do comutador Ethernet Cisco"^]
* http://hwu.netapp.com["Hardware Universe"^]




== Migrar o switch

.Sobre os exemplos
Os exemplos neste procedimento descrevem a substituição de switches Cisco Nexus 5596 por switches Cisco Nexus 3232C. Você pode usar estas etapas (com modificações) para outras centrais Cisco mais antigas (por exemplo, 3132Q-V).

O procedimento também usa a seguinte nomenclatura de switch e nó:

* As saídas de comando podem variar dependendo de diferentes versões do ONTAP.
* Os switches Nexus 5596 a serem substituídos são CL1 e CL2.
* Os switches Nexus 3232C para substituir os switches Nexus 5596 são C1 e C2.
* N1_clus1 é a primeira interface lógica de cluster (LIF) conetada ao switch de cluster 1 (CL1 ou C1) para o nó n1.
* N1_clus2 é o primeiro cluster de LIF conetado ao switch de cluster 2 (CL2 ou C2) para o nó n1.
* N1_clus3 é o segundo LIF conetado ao switch de cluster 2 (CL2 ou C2) para o nó n1.
* N1_clus4 é o segundo LIF conetado ao switch de cluster 1 (CL1 ou C1) para o nó n1.-
* O número de portas 10 GbE e 40/100 GbE é definido nos arquivos de configuração de referência (RCFs) disponíveis na https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Download do arquivo de configuração de referência do comutador de rede de cluster Cisco"^] página.
* Os nós são n1, n2, n3 e n4.


Os exemplos neste procedimento usam quatro nós:

* Dois nós usam quatro portas de interconexão de cluster de 10 GbE: e0a, e0b, e0c e e0d.
* Os outros dois nós usam duas portas de interconexão de cluster de 40 GbE: e4a, e4e. A link:https://hwu.netapp.com/["_Hardware Universe_"^] lista as portas de cluster reais em suas plataformas.


.Cenários
Este procedimento abrange os seguintes cenários:

* O cluster começa com dois nós conectados e funcionando em dois switches de cluster Nexus 5596.
* O interrutor do cluster CL2 a ser substituído por C2 (passos 1 a 19):
+
** O tráfego em todas as portas de cluster e LIFs em todos os nós conectados ao CL2 é migrado para as primeiras portas de cluster e LIFs conetadas ao CL1.
** Desconete o cabeamento de todas as portas de cluster em todos os nós conectados ao CL2 e use o cabeamento de saída compatível para reconetar as portas ao novo switch de cluster C2.
** Desconete o cabeamento entre as portas ISL entre CL1 e CL2 e, em seguida, use o cabeamento de saída suportado para reconetar as portas de CL1 a C2.
** O tráfego em todas as portas de cluster e LIFs conetadas ao C2 em todos os nós é revertido.


* O interrutor do cluster CL2 a ser substituído por C2.
+
** O tráfego em todas as portas de cluster ou LIFs em todos os nós conectados ao CL1 é migrado para as segundas portas de cluster ou LIFs conetadas ao C2.
** Desconete o cabeamento de todas as portas de cluster em todos os nós conectados ao CL1 e reconete, usando o cabeamento de saída compatível, ao novo switch de cluster C1.
** Desconete o cabeamento entre as portas ISL entre CL1 e C2 e reconete usando o cabeamento suportado, de C1 a C2.
** O tráfego em todas as portas de cluster ou LIFs conetadas ao C1 em todos os nós é revertido.


* Dois nós de FAS9000 foram adicionados ao cluster com exemplos mostrando detalhes do cluster.




=== Passo 1: Prepare-se para a migração

. Se o AutoSupport estiver ativado neste cluster, suprimir a criação automática de casos invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ é a duração da janela de manutenção em horas.

+
[NOTE]
====
A mensagem AutoSupport notifica o suporte técnico desta tarefa de manutenção para que a criação automática de casos seja suprimida durante a janela de manutenção.

====
. Exiba informações sobre os dispositivos em sua configuração:
+
`network device-discovery show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra quantas interfaces de interconexão de cluster foram configuradas em cada nó para cada switch de interconexão de cluster:

[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1      N5K-C5596UP
            e0b    CL2                 Ethernet1/1      N5K-C5596UP
            e0c    CL2                 Ethernet1/2      N5K-C5596UP
            e0d    CL1                 Ethernet1/2      N5K-C5596UP
n2         /cdp
            e0a    CL1                 Ethernet1/3      N5K-C5596UP
            e0b    CL2                 Ethernet1/3      N5K-C5596UP
            e0c    CL2                 Ethernet1/4      N5K-C5596UP
            e0d    CL1                 Ethernet1/4      N5K-C5596UP
8 entries were displayed.
----
====
. Determine o status administrativo ou operacional de cada interface de cluster.
+
.. Exibir os atributos da porta de rede:
+
`network port show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir exibe os atributos da porta de rede nos nós n1 e n2:

[listing, subs="+quotes"]
----
cluster::*> *network port show –role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
.. Exibir informações sobre as interfaces lógicas:
+
`network interface show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir exibe as informações gerais sobre todas as LIFs no cluster, incluindo suas portas atuais:

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
.. Exibir informações sobre os switches de cluster descobertos:
+
`system cluster-switch show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra os switches do cluster ativo:

[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch show*

Switch                        Type               Address         Model
----------------------------- ------------------ --------------- ---------------
CL1                           cluster-network    10.10.1.101     NX5596
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP
CL2                           cluster-network    10.10.1.102     NX5596
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP

2 entries were displayed.
----
====


. Verifique se o RCF e a imagem apropriados estão instalados nos novos switches 3232C conforme necessário para seus requisitos e faça as personalizações essenciais do site, como usuários e senhas, endereços de rede e outras personalizações.
+
[NOTE]
====
Neste momento, tem de preparar ambos os interrutores.

====
+
Se você precisar atualizar o RCF e a imagem, você deve concluir as seguintes etapas:

+
.. Vá para a página _switches Ethernet Cisco_ no site de suporte da NetApp.
+
http://support.netapp.com/NOW/download/software/cm_switches/["Switches Ethernet Cisco"^]

.. Observe o switch e as versões de software necessárias na tabela nessa página.
.. Baixe a versão apropriada do RCF.
.. Clique em *CONTINUAR* na página *Descrição*, aceite o contrato de licença e siga as instruções na página *Download* para baixar o RCF.
.. Transfira a versão apropriada do software de imagem.
+
Consulte a página __ONTAP 8.x ou mais recente de transferência de ficheiros de configuração de comutador de rede de gestão e cluster e, em seguida, clique na versão apropriada.

+
Para encontrar a versão correta, consulte a página de download do comutador de rede de cluster _ONTAP 8.x ou posterior_.



. Migrar os LIFs associados ao segundo switch Nexus 5596 a ser substituído:
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _source-node-name_ - destination-node _node-name_ -destination-port _destination-port-name_`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra as LIFs sendo migradas para os nós n1 e n2; a migração de LIF deve ser feita em todos os nós:

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 -
destination-node n1 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 -
destination-node n1 -destination-port e0d*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 -
destination-node n2 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 -
destination-node n2 -destination-port e0d*
----
====
. Verifique a integridade do cluster:
+
`network interface show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra o status atual de cada cluster:

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====




=== Etapa 2: Configurar portas

. Encerre as portas de interconexão de cluster que estão fisicamente conetadas ao switch CL2:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Mostrar exemplo
[%collapsible]
====
Os comandos a seguir desligam as portas especificadas no n1 e no n2, mas as portas devem ser fechadas em todos os nós:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin false*
cluster::*> *network port modify -node n1 -port e0c -up-admin false*
cluster::*> *network port modify -node n2 -port e0b -up-admin false*
cluster::*> *network port modify -node n2 -port e0c -up-admin false*
----
====
. Verifique a conectividade das interfaces de cluster remotas:


[role="tabbed-block"]
====
.ONTAP 9.9,1 e posterior
--
Você pode usar o `network interface check cluster-connectivity` comando para iniciar uma verificação de acessibilidade para conetividade de cluster e, em seguida, exibir os detalhes:

`network interface check cluster-connectivity start` e `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* espere alguns segundos antes de executar o comando show para exibir os detalhes.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Todos os lançamentos do ONTAP
--
Para todas as versões do ONTAP, você também pode usar o `cluster ping-cluster -node <name>` comando para verificar a conetividade:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step3]] encerre ISLs 41 a 48 no CL1, o switch Nexus 5596 ativo, usando o comando Cisco `shutdown`.
+
Para obter mais informações sobre comandos Cisco, consulte o guia apropriado no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra ISLs 41 a 48 sendo encerradas no Nexus 5596 switch CL1:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/41-48*
(CL1)(config-if-range)# *shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Crie um ISL temporário entre CL1 e C2 usando os comandos Cisco apropriados.
+
Para obter mais informações sobre comandos Cisco, consulte o guia apropriado no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra uma ISL temporária sendo configurada entre CL1 e C2:

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface port-channel 2*
C2(config-if)# *switchport mode trunk*
C2(config-if)# *spanning-tree port type network*
C2(config-if)# *mtu 9216*
C2(config-if)# *interface breakout module 1 port 24 map 10g-4x*
C2(config)# *interface e1/24/1-4*
C2(config-if-range)# *switchport mode trunk*
C2(config-if-range)# *mtu 9216*
C2(config-if-range)# *channel-group 2 mode active*
C2(config-if-range)# *exit*
C2(config-if)# *exit*
----
====
. Em todos os nós, remova todos os cabos conetados ao switch Nexus 5596 CL2.
+
Com o cabeamento compatível, reconecte as portas desconetadas em todos os nós ao switch Nexus 3232C C2.

. Remova todos os cabos do switch Nexus 5596 CL2.
+
Conete o Cisco QSFP apropriado aos cabos de conexão Ethernet 1/24 no novo switch Cisco 3232C, C2, às portas 45 a 48 no Nexus 5596, CL1 existente.

. Abra as portas ISLs 45 a 48 no switch Nexus 5596 ativo CL1.
+
Para obter mais informações sobre comandos Cisco, consulte o guia apropriado no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas ISLs 45 a 48 estão sendo criadas:

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/45-48*
(CL1)(config-if-range)# *no shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Verifique se os ISLs estão `up` no switch Nexus 5596 CL1.
+
Para obter mais informações sobre comandos Cisco, consulte o guia apropriado no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra as portas eth1/45 a eth1/48 indicando (P), o que significa que as portas ISL `up` estão no canal de porta.

[listing, subs="+quotes"]
----
CL1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/41(D)   Eth1/42(D)   Eth1/43(D)
                                    Eth1/44(D)   Eth1/45(P)   Eth1/46(P)
                                    Eth1/47(P)   Eth1/48(P)
----
====
. Verifique se as interfaces eth1/45-48 já têm o modo "Channel-group 1 ativo" em sua configuração em execução.
. Em todos os nós, abra todas as portas de interconexão de cluster conetadas ao switch 3232C C2:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra as portas especificadas sendo criadas nos nós n1 e n2:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin true*
cluster::*> *network port modify -node n1 -port e0c -up-admin true*
cluster::*> *network port modify -node n2 -port e0b -up-admin true*
cluster::*> *network port modify -node n2 -port e0c -up-admin true*
----
====
. Em todos os nós, reverta todas as LIFs de interconexão de cluster migradas conetadas ao C2:
+
`network interface revert -vserver Cluster -lif _lif-name_`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra as LIFs de cluster migradas sendo revertidas para suas portas iniciais:

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n1_clus3*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus3*
----
====
. Verifique se todas as portas de interconexão de cluster estão agora revertidas para sua casa:
+
`network interface show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que os LIFs no clus2 reverteram para suas portas residenciais e mostra que os LIFs são revertidos com êxito se as portas na coluna porta atual tiverem um status de `true` na `Is Home` coluna. Se o `Is Home` valor for `false`, o LIF não foi revertido.

[listing]
----
cluster::*> *network interface show -role cluster*
(network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. Verifique se as portas em cluster estão conetadas:
+
`network port show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra o resultado do comando anterior `network port modify`, verificando se todas as interconexões de cluster são `up`:

[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
. Verifique a conectividade das interfaces de cluster remotas:


[role="tabbed-block"]
====
.ONTAP 9.9,1 e posterior
--
Você pode usar o `network interface check cluster-connectivity` comando para iniciar uma verificação de acessibilidade para conetividade de cluster e, em seguida, exibir os detalhes:

`network interface check cluster-connectivity start` e `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* espere alguns segundos antes de executar o `show` comando para exibir os detalhes.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Todos os lançamentos do ONTAP
--
Para todas as versões do ONTAP, você também pode usar o `cluster ping-cluster -node <name>` comando para verificar a conetividade:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step15]] em cada nó no cluster, migre as interfaces associadas ao primeiro switch Nexus 5596, CL1, para ser substituído:
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _source-node-name_
-destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra as portas ou LIFs que estão sendo migradas nos nós n1 e n2:

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1 -
destination-node n1 -destination-port e0b*
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus4 -source-node n1 -
destination-node n1 -destination-port e0c*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2 -
destination-node n2 -destination-port e0b*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus4 -source-node n2 -
destination-node n2 -destination-port e0c*
----
====
. Verifique o status do cluster:
+
`network interface show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as LIFs de cluster necessárias foram migradas para portas de cluster apropriadas hospedadas no switch de cluster, C2:

[listing, subs="+quotes"]
----
cluster::*> *network interface show*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0b     false
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0c     false
            n2_clus1   up/up      10.10.0.5/24       n2            e0b     false
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0c     false
8 entries were displayed.

----- ------- ----
----
====
. Em todos os nós, encerre as portas dos nós que estão conectadas ao CL1:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra as portas especificadas que estão sendo encerradas nos nós n1 e n2:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin false*
cluster::*> *network port modify -node n1 -port e0d -up-admin false*
cluster::*> *network port modify -node n2 -port e0a -up-admin false*
cluster::*> *network port modify -node n2 -port e0d -up-admin false*
----
====
. Desligue o ISL 24, 31 e 32 no interrutor 3232C ativo C2.
+
Para obter mais informações sobre comandos Cisco, consulte o guia apropriado no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra ISLs sendo encerradas:

[listing, subs="+quotes"]
----
C2# *configure*
C2(Config)# *interface e1/24/1-4*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *interface 1/31-32*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config-if)# *exit*
C2#
----
====
. Em todos os nós, remova todos os cabos conetados ao switch Nexus 5596 CL1.
+
Com o cabeamento compatível, reconecte as portas desconetadas em todos os nós ao switch Nexus 3232C C1.

. Remova o cabo multicondutor QSFP das portas E1/24 do Nexus 3232C C2.
+
Conete as portas E1/31 e E1/32 no C1 às portas E1/31 e E1/32 no C2 usando fibra ótica Cisco QSFP ou cabos de conexão direta.

. Restaure a configuração na porta 24 e remova o Canal de porta temporário 2 no C2.
+
Para obter mais informações sobre comandos Cisco, consulte o guia apropriado no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra a configuração na porta M24 sendo restaurada usando os comandos Cisco apropriados:

[listing, subs="+quotes"]
----
C2# configure
C2(config)# *no interface breakout module 1 port 24 map 10g-4x*
C2(config)# *no interface port-channel 2*
C2(config-if)# *int e1/24*
C2(config-if)# *description 40GbE Node Port*
C2(config-if)# *spanning-tree port type edge*
C2(config-if)# *spanning-tree bpduguard enable*
C2(config-if)# *mtu 9216*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. Abra as portas ISL 31 e 32 no C2, o switch 3232C ativo, inserindo o seguinte comando Cisco: `no shutdown`
+
Para obter mais informações sobre comandos Cisco, consulte o guia apropriado no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra os comandos Cisco `switchname configure` apresentados no interrutor 3232C C2:

[listing, subs="+quotes"]
----
C2# configure
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# no shutdown
----
====
. Verifique se as conexões ISL estão `up` no interrutor 3232C C2.
+
Para obter mais informações sobre comandos Cisco, consulte o guia apropriado no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
As portas eth1/31 e eth1/32 devem indicar (P), o que significa que ambas as portas ISL estão no canal de porta

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----

C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Em todos os nós, abra todas as portas de interconexão de cluster conetadas ao novo switch 3232C C1:
+
`network port modify`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra todas as portas de interconexão de cluster sendo criadas para n1 e n2 no switch 3232C C1:

[listing]
----

cluster::*> network port modify -node n1 -port e0a -up-admin true
cluster::*> network port modify -node n1 -port e0d -up-admin true
cluster::*> network port modify -node n2 -port e0a -up-admin true
cluster::*> network port modify -node n2 -port e0d -up-admin true
----
====
. Verifique o status da porta do nó do cluster:
+
`network port show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra verifica se todas as portas de interconexão de cluster em todos os nós no novo switch 3232C C1 estão em funcionamento:

[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
. Em todos os nós, reverta as LIFs de cluster específicas para suas portas iniciais:
+
`network interface revert -server Cluster -lif _lif-name_`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra as LIFs de cluster específicas sendo revertidas para suas portas iniciais nos nós n1 e n2:

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n1_clus4
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus4
----
====
. Verifique se a interface está em casa:
+
`network interface show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra o status das interfaces de interconexão de cluster são `up` e `Is Home` para n1 e n2:

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. Verifique a conectividade das interfaces de cluster remotas:


[role="tabbed-block"]
====
.ONTAP 9.9,1 e posterior
--
Você pode usar o `network interface check cluster-connectivity` comando para iniciar uma verificação de acessibilidade para conetividade de cluster e, em seguida, exibir os detalhes:

`network interface check cluster-connectivity start` e `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* espere alguns segundos antes de executar o `show` comando para exibir os detalhes.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.Todos os lançamentos do ONTAP
--
Para todas as versões do ONTAP, você também pode usar o `cluster ping-cluster -node <name>` comando para verificar a conetividade:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step29]] expanda o cluster adicionando nós aos switches de cluster Nexus 3232C.
+
Os exemplos a seguir mostram que os nós n3 e n4 têm portas de cluster de 40 GbE conetadas às portas E1/7 e E1/8, respetivamente, nos dois switches de cluster Nexus 3232C, e ambos os nós aderiram ao cluster. As portas de interconexão de cluster de 40 GbE usadas são e4a e e4e.

+
Exiba as informações sobre os dispositivos em sua configuração:

+
** `network device-discovery show`
** `network port show -role cluster`
** `network interface show -role cluster`
** `system cluster-switch show`


+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    C1                 Ethernet1/1/1    N3K-C3232C
            e0b    C2                 Ethernet1/1/1    N3K-C3232C
            e0c    C2                 Ethernet1/1/2    N3K-C3232C
            e0d    C1                 Ethernet1/1/2    N3K-C3232C
n2         /cdp
            e0a    C1                 Ethernet1/1/3    N3K-C3232C
            e0b    C2                 Ethernet1/1/3    N3K-C3232C
            e0c    C2                 Ethernet1/1/4    N3K-C3232C
            e0d    C1                 Ethernet1/1/4    N3K-C3232C
n3         /cdp
            e4a    C1                 Ethernet1/7      N3K-C3232C
            e4e    C2                 Ethernet1/7      N3K-C3232C
n4         /cdp
            e4a    C1                 Ethernet1/8      N3K-C3232C
            e4e    C2                 Ethernet1/8      N3K-C3232C
12 entries were displayed.
----
E

[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
12 entries were displayed.
----
E

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
12 entries were displayed.
----
E

[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

CL1                           cluster-network   10.10.1.101     NX5596
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP
CL2                           cluster-network    10.10.1.102     NX5596
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP

4 entries were displayed.
----
====
. Extrair o Nexus 5596 substituído com `system cluster-switch delete` o comando, se não for extraído automaticamente:
+
`system cluster-switch delete -device switch-name`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch delete –device CL1
cluster::> system cluster-switch delete –device CL2
----
====




=== Passo 3: Conclua o procedimento

. Verifique se os switches de cluster adequados são monitorados:
+
`system cluster-switch show`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.103      NX3232C
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.104      NX3232C
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. Se você suprimiu a criação automática de casos, reative-a invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que se segue?
link:../switch-cshm/config-overview.html["Configurar o monitoramento de integridade do switch"].
