---
permalink: switch-cisco-3232c/replace-cluster-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3232c, cluster switch 
summary: Você pode substituir sem interrupções um switch Cisco Nexus 3232C com defeito em um cluster executando uma sequência específica de tarefas. 
---
= Substitua um switch de cluster Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estas etapas para substituir um switch Cisco Nexus 3232C com defeito em um cluster. Este é um procedimento sem interrupções.



== Rever os requisitos

.O que você vai precisar
Certifique-se de que o cluster e a configuração de rede existentes tenham as seguintes caraterísticas:

* A infraestrutura de cluster do Nexus 3232C é redundante e totalmente funcional em ambos os switches.
+
A página de switches Ethernet Cisco tem as versões mais recentes de RCF e NX-os em seus switches.

* Todas as portas de cluster devem estar no estado *up*.
* A conetividade de gerenciamento deve existir em ambos os switches.
* Todas as interfaces lógicas de cluster (LIFs) estão no estado *up* e não são migradas.


O interrutor de substituição Cisco Nexus 3232C tem as seguintes caraterísticas:

* A conetividade de rede de gerenciamento é funcional.
* O acesso do console ao interrutor de substituição está no lugar.
* A imagem apropriada do sistema operacional RCF e NX-os é carregada no switch.
* A personalização inicial do switch está concluída.


.Para mais informações
Veja o seguinte:

* http://support.netapp.com/NOW/download/software/cm_switches/["Página de descrição do comutador Ethernet Cisco"^]
* http://hwu.netapp.com["Hardware Universe"^]




== Ativar o registo da consola

O NetApp recomenda fortemente que você ative o log do console nos dispositivos que você está usando e execute as seguintes ações ao substituir o switch:

* Deixe o AutoSupport ativado durante a manutenção.
* Acione um AutoSupport de manutenção antes e depois da manutenção para desativar a criação de casos durante a manutenção. Consulte este artigo da base de dados de Conhecimento https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: Como suprimir a criação automática de casos durante as janelas de manutenção programada"^] para obter mais detalhes.
* Ativar o registo de sessão para quaisquer sessões CLI. Para obter instruções sobre como ativar o registo de sessão, consulte a secção "saída de sessão de registo" neste artigo da base de dados de conhecimento https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para uma conetividade ideal aos sistemas ONTAP"^] .




== Substitua o interrutor

.Sobre esta tarefa
Este procedimento de substituição descreve o seguinte cenário:

* Inicialmente, o cluster tem quatro nós conectados a dois switches de cluster Nexus 3232C, CL1 e CL2.
* Pretende substituir o interrutor do cluster CL2 por C2 (passos 1 a 21):
+
** Em cada nó, você migra as LIFs de cluster conetadas ao switch de cluster CL2 para as portas de cluster conetadas ao switch de cluster CL1.
** Desconete o cabeamento de todas as portas do switch de cluster CL2 e reconete o cabeamento às mesmas portas do switch de cluster de substituição C2.
** Você reverte as LIFs de cluster migradas em cada nó.




.Sobre os exemplos
Este procedimento de substituição substitui o segundo switch de cluster Nexus 3232C CL2 com o novo switch 3232C C2.

Os exemplos deste procedimento utilizam a seguinte nomenclatura de switch e nó:

* Os quatro nós são n1, n2, n3 e n4.
* N1_clus1 é a primeira interface lógica de cluster (LIF) conetada ao switch de cluster C1 para o nó n1.
* N1_clus2 é o primeiro cluster LIF conetado ao switch de cluster CL2 ou C2 para o nó n1.
* N1_clus3 é o segundo LIF conetado ao switch de cluster C2 para o nó n1.-
* N1_clus4 é o segundo LIF conetado ao switch de cluster CL1, para o nó n1.


O número de portas 10 GbE e 40/100 GbE é definido nos arquivos de configuração de referência (RCFs) disponíveis na https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Download do arquivo de configuração de referência do comutador de rede de cluster Cisco"^] página.

Os exemplos neste procedimento de substituição usam quatro nós. Dois dos nós usam quatro portas de interconexão de cluster de 10 GB: e0a, e0b, e0c e e0d. Os outros dois nós usam duas portas de interconexão de cluster de 40 GB: e4a e e4e. Consulte link:https://hwu.netapp.com["Hardware Universe"^]para verificar as portas de cluster corretas para a sua plataforma.



=== Etapa 1: Exiba e migre as portas do cluster para o switch

. Se o AutoSupport estiver ativado neste cluster, suprimir a criação automática de casos invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ é a duração da janela de manutenção em horas.

+
[NOTE]
====
A mensagem AutoSupport notifica o suporte técnico desta tarefa de manutenção para que a criação automática de casos seja suprimida durante a janela de manutenção.

====
. Exiba informações sobre os dispositivos em sua configuração:
+
`network device-discovery show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface         Platform
----------- ------ ------------------- ----------------  ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1/1    N3K-C3232C
            e0b    CL2                 Ethernet1/1/1    N3K-C3232C
            e0c    CL2                 Ethernet1/1/2    N3K-C3232C
            e0d    CL1                 Ethernet1/1/2    N3K-C3232C

n2         /cdp
            e0a    CL1                 Ethernet1/1/3    N3K-C3232C
            e0b    CL2                 Ethernet1/1/3    N3K-C3232C
            e0c    CL2                 Ethernet1/1/4    N3K-C3232C
            e0d    CL1                 Ethernet1/1/4    N3K-C3232C

n3         /cdp
            e4a    CL1                 Ethernet1/7      N3K-C3232C
            e4e    CL2                 Ethernet1/7      N3K-C3232C

n4         /cdp
            e4a    CL1                 Ethernet1/8      N3K-C3232C
            e4e    CL2                 Ethernet1/8      N3K-C3232C
----
====
. Determine o status administrativo ou operacional de cada interface de cluster.
+
.. Exibir os atributos da porta de rede:
+
`network port show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
(network port show)
Node: n1
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- ------------
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- ------------
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
----
====
.. Exibir informações sobre as interfaces lógicas (LIFs):
+
`network interface show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
             Logical    Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port   Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e0a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e0e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e0a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e0e     true
----
====
.. Exibir os switches do cluster descobertos:
+
`system cluster-switch show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo de saída a seguir exibe os switches de cluster:

[listing, subs="+quotes"]
----
cluster::> *system cluster-switch show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                         cluster-network    10.10.1.101      NX3232C
        Serial Number: FOX000001
         Is Monitored: true
               Reason: None
     Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
       Version Source: CDP

CL2                         cluster-network    10.10.1.102      NX3232C
        Serial Number: FOX000002
         Is Monitored: true
               Reason: None
     Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
       Version Source: CDP
----
====


. Verifique se o RCF e a imagem apropriados estão instalados no novo switch Nexus 3232C e faça as personalizações necessárias do local.
+
.. Vá para o site de suporte da NetApp.
+
http://mysupport.netapp.com/["mysupport.NetApp.com"^]

.. Vá para a página *switches Ethernet Cisco* e anote as versões de software necessárias na tabela.
+
https://mysupport.netapp.com/NOW/download/software/cm_switches/["Switches Ethernet Cisco"^]

.. Baixe a versão apropriada do RCF.
.. Clique em *CONTINUAR* na página *Descrição*, aceite o contrato de licença e navegue até a página *Download*.
.. Transfira a versão correta do software de imagem a partir da página de transferência do ficheiro de configuração de referência do comutador de rede de gestão e de Cluster *Cisco*.
+
http://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Download do arquivo de configuração de referência do comutador de rede de gerenciamento e cluster Cisco"^]



. Migre as LIFs de cluster para as portas de nó físico conetadas ao switch de substituição C2:
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _node-name_ -destination-node _node-name_ -destination-port _port-name_`

+
.Mostrar exemplo
[%collapsible]
====
Você deve migrar todas as LIFs de cluster individualmente, conforme mostrado no exemplo a seguir:

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 -destination-
node n1 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 -destination-
node n1 -destination-port e0d*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 -destination-
node n2 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 -destination-
node n2 -destination-port e0d*
cluster::*> *network interface migrate -vserver Cluster -lif n3_clus2 -source-node n3 -destination-
node n3 -destination-port e4a*
cluster::*> *network interface migrate -vserver Cluster -lif n4_clus2 -source-node n4 -destination-
node n4 -destination-port e4a*
----
====
. Verifique o estado das portas do cluster e respetivas designações de origem:
+
`network interface show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4a     false
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4a     false
----
====
. Encerre as portas de interconexão do cluster que estão fisicamente conetadas ao switch original CL2:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas de interconexão de cluster estão fechadas em todos os nós:

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin false*
cluster::*> *network port modify -node n1 -port e0c -up-admin false*
cluster::*> *network port modify -node n2 -port e0b -up-admin false*
cluster::*> *network port modify -node n2 -port e0c -up-admin false*
cluster::*> *network port modify -node n3 -port e4e -up-admin false*
cluster::*> *network port modify -node n4 -port e4e -up-admin false*
----
====
. Faça ping nas interfaces de cluster remoto e execute uma verificação de servidor RPC:
+
`cluster ping-cluster -node _node-name_`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra o nó n1 sendo inserido e o status RPC indicado posteriormente:

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1 Getting addresses from network interface table...
Cluster n1_clus1 n1        e0a    10.10.0.1
Cluster n1_clus2 n1        e0b    10.10.0.2
Cluster n1_clus3 n1        e0c    10.10.0.3
Cluster n1_clus4 n1        e0d    10.10.0.4
Cluster n2_clus1 n2        e0a    10.10.0.5
Cluster n2_clus2 n2        e0b    10.10.0.6
Cluster n2_clus3 n2        e0c    10.10.0.7
Cluster n2_clus4 n2        e0d    10.10.0.8
Cluster n3_clus1 n4        e0a    10.10.0.9
Cluster n3_clus2 n3        e0e    10.10.0.10
Cluster n4_clus1 n4        e0a    10.10.0.11
Cluster n4_clus2 n4        e0e    10.10.0.12
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11
10.10.0.12 Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12
Larger than PMTU communication succeeds on 32 path(s) RPC status:
8 paths up, 0 paths down (tcp check)
8	paths up, 0 paths down (udp check)
----
====




=== Passo 2: Migrar ISLs para o switch CL1 e C2

. Encerre as portas 1/31 e 1/32 no interrutor do cluster CL1.
+
Para obter mais informações sobre comandos Cisco, consulte os guias listados no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/31-32*
(CL1)(config-if-range)# *shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Remova todos os cabos conetados ao switch do cluster CL2 e reconete-os ao switch de substituição C2 para todos os nós.
. Retire os cabos de ligação entre interrutores (ISL) das portas E1/31 e E1/32 no interrutor do cluster CL2 e volte a ligá-los às mesmas portas no interrutor de substituição C2.
. Abra as portas ISL 1/31 e 1/32 no interrutor do cluster CL1.
+
Para obter mais informações sobre comandos Cisco, consulte os guias listados no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface e1/31-32*
(CL1)(config-if-range)# *no shutdown*
(CL1)(config-if-range)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. Verifique se os ISLs estão acima em CL1.
+
Para obter mais informações sobre comandos Cisco, consulte os guias listados no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
As portas eth1/31 e eth1/32 devem indicar `(P)`, o que significa que as portas ISL estão no canal de porta:

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
CL1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Verifique se os ISLs estão ativos no switch de cluster C2.
+
Para obter mais informações sobre comandos Cisco, consulte os guias listados no https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Referências de comando Cisco Nexus 3000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
As portas eth1/31 e eth1/32 devem indicar (P), o que significa que ambas as portas ISL estão no canal de porta.

[listing, subs="+quotes"]
----
C2# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. Em todos os nós, abra todas as portas de interconexão de cluster conetadas ao switch de substituição C2:
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin true*
cluster::*> *network port modify -node n1 -port e0c -up-admin true*
cluster::*> *network port modify -node n2 -port e0b -up-admin true*
cluster::*> *network port modify -node n2 -port e0c -up-admin true*
cluster::*> *network port modify -node n3 -port e4e -up-admin true*
cluster::*> *network port modify -node n4 -port e4e -up-admin true*
----
====




=== Passo 3: Reverter todos os LIFs para portas originalmente atribuídas

. Reverter todas as LIFs de interconexão de cluster migradas em todos os nós:
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.Mostrar exemplo
[%collapsible]
====
Você deve reverter todas as LIFs de interconexão de cluster individualmente, conforme mostrado no exemplo a seguir:

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver cluster -lif n1_clus3*
cluster::*> *network interface revert -vserver cluster -lif n2_clus2*
cluster::*> *network interface revert -vserver cluster -lif n2_clus3*
Cluster::*> *network interface revert -vserver cluster -lif n3_clus2*
Cluster::*> *network interface revert -vserver cluster -lif n4_clus2*
----
====
. Verifique se as portas de interconexão de cluster estão agora revertidas para sua casa:
+
`network interface show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todos os LIFs foram revertidos com sucesso porque as portas listadas na `Current Port` coluna têm um status de `true` na `Is Home` coluna. Se uma porta tiver um valor de `false`, o LIF não foi revertido.

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
             n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
             n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
             n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
             n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
             n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
             n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
             n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
             n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
             n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
             n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
             n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
             n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
----
====
. Verifique se as portas do cluster estão conetadas:
+
`network port show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
 --------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
----
====
. Faça ping nas interfaces de cluster remoto e execute uma verificação de servidor RPC:
+
`cluster ping-cluster -node _node-name_`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra o nó n1 sendo inserido e o status RPC indicado posteriormente:

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1 Getting addresses from network interface table...
Cluster n1_clus1 n1        e0a    10.10.0.1
Cluster n1_clus2 n1        e0b    10.10.0.2
Cluster n1_clus3 n1        e0c    10.10.0.3
Cluster n1_clus4 n1        e0d    10.10.0.4
Cluster n2_clus1 n2        e0a    10.10.0.5
Cluster n2_clus2 n2        e0b    10.10.0.6
Cluster n2_clus3 n2        e0c    10.10.0.7
Cluster n2_clus4 n2        e0d    10.10.0.8
Cluster n3_clus1 n3        e0a    10.10.0.9
Cluster n3_clus2 n3        e0e    10.10.0.10
Cluster n4_clus1 n4        e0a    10.10.0.11
Cluster n4_clus2 n4        e0e    10.10.0.12
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11 10.10.0.12
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12
Larger than PMTU communication succeeds on 32 path(s) RPC status:
8 paths up, 0 paths down (tcp check)
8	paths up, 0 paths down (udp check)
----
====




=== Etapa 4: Verifique se todas as portas e o LIF estão migrados corretamente

. Exiba as informações sobre os dispositivos em sua configuração digitando os seguintes comandos:
+
Você pode executar os seguintes comandos em qualquer ordem:

+
** `network device-discovery show`
** `network port show -role cluster`
** `network interface show -role cluster`
** `system cluster-switch show`


+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    C1                 Ethernet1/1/1    N3K-C3232C
            e0b    C2                 Ethernet1/1/1    N3K-C3232C
            e0c    C2                 Ethernet1/1/2    N3K-C3232C
            e0d    C1                 Ethernet1/1/2    N3K-C3232C
n2         /cdp
            e0a    C1                 Ethernet1/1/3    N3K-C3232C
            e0b    C2                 Ethernet1/1/3    N3K-C3232C
            e0c    C2                 Ethernet1/1/4    N3K-C3232C
            e0d    C1                 Ethernet1/1/4    N3K-C3232C
n3         /cdp
            e4a    C1                 Ethernet1/7      N3K-C3232C
            e4e    C2                 Ethernet1/7      N3K-C3232C

n4         /cdp
            e4a    C1                 Ethernet1/8      N3K-C3232C
            e4e    C2                 Ethernet1/8      N3K-C3232C

cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

cluster::*> *network interface show -role cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            nm1_clus1  up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true

cluster::*> *system cluster-switch show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                          cluster-network   10.10.1.101      NX3232C
             Serial Number: FOX000001
              Is Monitored: true
                    Reason: None
          Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
            Version Source: CDP
CL2                          cluster-network   10.10.1.102      NX3232C
             Serial Number: FOX000002
              Is Monitored: true
                    Reason: None
          Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
            Version Source: CDP

C2                          cluster-network    10.10.1.103      NX3232C
             Serial Number: FOX000003
              Is Monitored: true
                    Reason: None
          Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
            Version Source: CDP 3 entries were displayed.
----
====
. Elimine o interrutor de cluster substituído CL2 se não tiver sido removido automaticamente:
+
`system cluster-switch delete -device cluster-switch-name`

. Verifique se os switches de cluster adequados são monitorados:
+
`system cluster-switch show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que os switches do cluster são monitorados porque o `Is Monitored` estado é `true`.

[listing, subs="+quotes"]
----
cluster::> *system cluster-switch show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                         cluster-network    10.10.1.101      NX3232C
            Serial Number: FOX000001
             Is Monitored: true
                   Reason: None
         Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
           Version Source: CDP

C2                          cluster-network    10.10.1.103      NX3232C
            Serial Number: FOX000002
             Is Monitored: true
                   Reason: None
         Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
           Version Source: CDP
----
====
. Se você suprimiu a criação automática de casos, reative-a invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que se segue?
link:../switch-cshm/config-overview.html["Configurar o monitoramento de integridade do switch"]
