---
permalink: switch-cisco-3232c/replace-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: Você pode substituir um switch de storage Cisco Nexus 3232C com defeito sem interrupções, executando uma sequência específica de tarefas. 
---
= Substitua um switch de storage Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estas etapas para substituir um switch de armazenamento Cisco Nexus 3232C com defeito. Este é um procedimento sem interrupções.



== Rever os requisitos

A configuração de rede existente deve ter as seguintes caraterísticas:

* A página de switches Ethernet Cisco tem as versões mais recentes de RCF e NX-os em seus switches.
* A conetividade de gerenciamento deve existir em ambos os switches.
+
[NOTE]
====
Certifique-se de que todas as etapas de solução de problemas foram concluídas para confirmar que o switch precisa ser substituído.

====


O switch Cisco Nexus 3232C de substituição deve ter as seguintes caraterísticas:

* A conetividade de rede de gerenciamento deve estar funcional.
* O acesso do console ao interrutor de substituição deve estar no lugar.
* A imagem apropriada do sistema operacional RCF e NX-os deve ser carregada no switch.
* A personalização inicial do switch deve estar concluída.




== Substitua o interrutor

Este procedimento substitui o segundo switch de armazenamento Nexus 3232C S2 com o novo switch 3232C NS2. Os dois nós são node1 e node2.



=== Etapa 1: Confirmar se o interrutor a ser substituído é S2

. Se o AutoSupport estiver ativado neste cluster, suprimir a criação automática de casos invocando uma mensagem AutoSupport:
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ é a duração da janela de manutenção em horas.

+
[NOTE]
====
A mensagem AutoSupport notifica o suporte técnico desta tarefa de manutenção para que a criação automática de casos seja suprimida durante a janela de manutenção.

====
. Verifique o status de integridade das portas do nó de storage para garantir que haja conexão com o switch de armazenamento S1:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
node1
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
node2
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
====
. Verifique se o comutador de armazenamento S1 está disponível:
+
`network device-discovery show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
----
====
. Execute o `show lldp neighbors` comando no switch de trabalho para confirmar que você pode ver ambos os nós e todas as gavetas:
+
`show lldp neighbors`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
node1                   Eth1/1          121        S           e3a
node2                   Eth1/2          121        S           e3a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
====




=== Etapa 2: Configurar o cabeamento

. [[Five]]Verifique as portas de gaveta no sistema de armazenamento:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  S1
3.20   1   -            -
3.20   2   Ethernet1/6  S1
3.20   3   -            -
3.30   0   Ethernet1/7  S1
3.20   1   -            -
3.30   2   Ethernet1/8  S1
3.20   3   -            -
----
====
. Remova todos os cabos conetados ao interrutor de armazenamento S2.
. Volte a ligar todos os cabos ao interrutor de substituição NS2.




=== Passo 3: Verifique todas as configurações do dispositivo no interrutor NS2

. Verifique o status de integridade das portas do nó de storage:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. Verifique se ambos os switches estão disponíveis:
+
`network device-discovery show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/1       NX3232C
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
            e7b    NS2                       Ethernet1/1       -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/2       NX3232C
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
            e7b    NS2                       Ethernet1/2       -
----
====
. Verifique as portas do compartimento no sistema de storage:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 S1
3.20  1  Ethernet1/5 NS2
3.20  2  Ethernet1/6 S1
3.20  3  Ethernet1/6 NS2
3.30  0  Ethernet1/7 S1
3.20  1  Ethernet1/7 NS2
3.30  2  Ethernet1/8 S1
3.20  3  Ethernet1/8 NS2
----
====
. Se você suprimiu a criação automática de casos, reative-a invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que se segue?
link:../switch-cshm/config-overview.html["Configurar o monitoramento de integridade do switch"]
