---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: Se você deseja documentar as plataformas suportadas, deve preencher a planilha de cabeamento em branco usando a planilha de cabeamento de exemplo preenchida como guia.  Cada switch pode ser configurado como uma única porta 100GbE, uma porta 40GbE ou quatro portas 10GbE. 
---
= Folha de exercícios completa de cabeamento do Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você deseja documentar as plataformas suportadas, baixe o PDF desta página e preencha a planilha de cabeamento.

A planilha de cabeamento de exemplo fornece exemplos de atribuições de portas recomendadas dos switches aos controladores.  A planilha em branco fornece um modelo que você pode usar para configurar seu cluster.

Cada switch pode ser configurado como uma única porta 100GbE, uma porta 40GbE ou quatro portas 10GbE.



== Exemplo de folha de exercícios de cabeamento

A definição da porta de exemplo em cada par de switches é a seguinte:

[cols="1, 1, 1, 1"]
|===
2+| Chave seletora de cluster A 2+| Chave seletora de cluster B 


| Porta de comutação | Utilização de nós e portas | Porta de comutação | Utilização de nós e portas 


 a| 
1
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
1
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
2
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
2
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
3
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
3
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
4
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
4
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
5
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
5
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
6
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
6
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
7
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
7
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
8
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
8
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
9
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
9
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
10
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
10
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
11
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
11
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
12
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
12
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
13
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
13
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
14
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
14
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
15
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
15
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
16
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
16
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
17
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
17
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
18
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE
 a| 
18
 a| 
Nó 4x10GbE/4x25GbE ou 40/100GbE



 a| 
19
 a| 
Nó 19 de 40G/100GbE
 a| 
19
 a| 
Nó 19 de 40G/100GbE



 a| 
20
 a| 
Nó 20 de 40G/100GbE
 a| 
20
 a| 
Nó 20 de 40G/100GbE



 a| 
21
 a| 
Nó 21 de 40G/100GbE
 a| 
21
 a| 
Nó 21 de 40G/100GbE



 a| 
22
 a| 
Nó 22 de 40G/100GbE
 a| 
22
 a| 
Nó 22 de 40G/100GbE



 a| 
23
 a| 
Nó 23 de 40G/100GbE
 a| 
23
 a| 
Nó 23 de 40G/100GbE



 a| 
24
 a| 
Nó 24 de 40G/100GbE
 a| 
24
 a| 
Nó 24 de 40G/100GbE



 a| 
25 a 30
 a| 
Reservado
 a| 
25 a 30
 a| 
Reservado



 a| 
31
 a| 
ISL de 100GbE para a porta 31 do switch B
 a| 
31
 a| 
ISL de 100GbE para switch A porta 31



 a| 
32
 a| 
ISL de 100GbE para a porta 32 do switch B
 a| 
32
 a| 
ISL de 100GbE para switch A porta 32

|===


== Folha de exercícios de cabeamento em branco

Você pode usar a planilha de cabeamento em branco para documentar as plataformas que são suportadas como nós em um cluster.  A seção _Conexões de cluster suportadas_ do https://hwu.netapp.com["Hardware Universe"^] Define as portas do cluster utilizadas pela plataforma.

[cols="1, 1, 1, 1"]
|===
2+| Chave seletora de cluster A 2+| Chave seletora de cluster B 


| Porta de comutação | Utilização de nós/portas | Porta de comutação | Utilização de nós/portas 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25 a 30
 a| 
Reservado
 a| 
25 a 30
 a| 
Reservado



 a| 
31
 a| 
ISL de 100GbE para a porta 31 do switch B
 a| 
31
 a| 
ISL de 100GbE para switch A porta 31



 a| 
32
 a| 
ISL de 100GbE para a porta 32 do switch B
 a| 
32
 a| 
ISL de 100GbE para switch A porta 32

|===
.O que vem a seguir
Depois de concluir suas planilhas de cabeamento, você link:install-switch-3232c.html["instalar o interruptor"].
