---
permalink: switch-cisco-3232c/smart-call-home-3232c.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Você pode usar os switches Cisco Nexus 3232C como switches de cluster no seu cluster AFF ou FAS. 
---
= Requisitos para Smart Call Home
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para usar o Smart Call Home, você deve configurar um switch de rede de cluster para se comunicar por e-mail com o sistema Smart Call Home. Além disso, você pode opcionalmente configurar seu switch de rede de cluster para aproveitar o recurso de suporte Smart Call Home incorporado da Cisco.

O Smart Call Home monitora os componentes de hardware e software na sua rede. Quando ocorre uma configuração crítica do sistema, ele gera uma notificação por e-mail e envia um alerta para todos os destinatários configurados no seu perfil de destino.

Antes de usar o Smart Call Home, esteja ciente dos seguintes requisitos:

* Um servidor de e-mail deve estar no lugar.
* O switch deve ter conetividade IP com o servidor de e-mail.
* É necessário configurar o nome do contacto (contacto do servidor SNMP), o número de telefone e as informações do endereço da rua. Isso é necessário para determinar a origem das mensagens recebidas.
* Um ID de CCO deve ser associado a um contrato de serviço Cisco SMARTnet apropriado para a sua empresa.
* O Serviço SMARTnet da Cisco deve estar em vigor para que o dispositivo seja registrado.


O http://www.cisco.com/c/en/us/products/switches/index.html["Site de suporte da Cisco"^] contém informações sobre os comandos para configurar Smart Call Home.
