---
sidebar: sidebar 
permalink: switch-cisco-9336c-shared/9336c_migrate_from_a_switchless_cluster_with_dat_storage_by_adding_two_new_shared_switches.html 
keywords:  
summary:  
---
= Migre de um cluster sem switch com armazenamento DAT adicionando dois novos switches compartilhados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/




==== Migrar de um cluster sem switch com armazenamento DAT

Você precisa estar ciente de certas informações de configuração, conexões de porta e requisitos de cabeamento ao migrar um cluster sem switch de dois nós, sem interrupções, para um cluster com switches de cluster Cisco Nexus 9336C-FX2. O procedimento usado depende se você tem duas portas de rede de cluster dedicadas em cada controlador ou uma única porta de cluster em cada controlador. O processo documentado funciona para todos os nós que usam portas óticas ou Twinax, mas não é suportado neste switch se os nós estiverem usando portas integradas 10Gb BASE-T RJ45 para as portas de cluster-rede.

A maioria dos sistemas requer duas portas de rede de cluster dedicadas em cada controlador. Consulte  https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco"] para obter mais informações.

Se você tiver um ambiente de cluster sem switch de dois nós existente, poderá migrar para um ambiente de cluster comutado de dois nós usando os switches Cisco Nexus 9336C-FX2 para permitir que você escale além de dois nós no cluster.

.Antes de começar
* Configuração sem switch de dois nós:
+
** A configuração sem switch de dois nós deve estar configurada e funcionando corretamente.
** Os nós precisam estar executando o ONTAP 9.8 e posterior.
** Todas as portas de cluster devem estar no estado *up*.
** Todas as interfaces lógicas de cluster (LIFs) devem estar no estado *up* e em suas portas *home*.


* Configuração do switch Cisco Nexus 9336C-FX2:
+
** Ambos os switches devem ter conetividade de rede de gerenciamento.
** Deve haver acesso ao console aos switches do cluster.
** As conexões de switch de nó para nó Nexus 9336C-FX2 e switch para switch devem usar cabos Twinax ou de fibra.
** O NetApp https://hwu.netapp.com["Hardware Universe"] contém mais informações sobre cabeamento.
** Os cabos ISL (Inter-Switch Link) devem ser conetados às portas 1/35 e 1/36 em ambos os switches 9336C-FX2.


* A personalização inicial dos switches 9336C-FX2 deve ser concluída. Para que:
+
** Os switches 9336C-FX2 estão executando a versão mais recente do software
** Os ficheiros de configuração de referência (RCFs) foram aplicados aos comutadores
** Qualquer personalização de site, como SMTP, SNMP e SSH, deve ser configurada nos novos switches.




.Sobre esta tarefa
Os exemplos deste procedimento utilizam a seguinte nomenclatura de nó e switch de cluster:

* Os nomes dos switches 9336C-FX2 são _CS1_ e _CS2_.
* Os nomes dos SVMs do cluster são _node1_ e _node2_.
* Os nomes dos LIFs são _node1_clus1_ e _node1_clus2_ no nó 1 e _node2_clus1_ e _node2_clus2_ no nó 2 respetivamente.
* O prompt cluster1::*> indica o nome do cluster.
* As portas de cluster usadas neste procedimento são _E3A_ e _e3b_, de acordo com o controlador AFF A400. O https://hwu.netapp.com["Hardware Universe"] contém as informações mais recentes sobre as portas de cluster reais para as suas plataformas.


.Passos
. Se o AutoSupport estiver ativado neste cluster, suprimir a criação automática de casos invocando uma mensagem AutoSupport:  `system node autosupport invoke -node * -type all -message MAINT=xh`.
+
onde x é a duração da janela de manutenção em horas.




NOTE: A mensagem AutoSupport notifica o suporte técnico desta tarefa de manutenção para que a criação automática de casos seja suprimida durante a janela de manutenção.

. [[step2]]altere o nível de privilégio para avançado, inserindo y quando solicitado a continuar:
`set -privilege advanced`
+
É apresentado o aviso avançado (*>).

. Desative todas as portas voltadas para o nó (não portas ISL) nos novos switches de cluster CS1 e CS2. Não deve desativar as portas ISL.
+
O exemplo a seguir mostra que as portas 1 a 34 voltadas para o nó estão desativadas no switch CS1:



[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e/1-34
cs1(config-if-range)# shutdown
----
. [[step4]]Verifique se o ISL e as portas físicas no ISL entre os dois switches 9336C-FX2 CS1 e CS2 estão acima nas portas 1/35 e 1/36:
`show port-channel summary`
+
O exemplo a seguir mostra que as portas ISL estão acima no interrutor CS1:



[listing]
----
cs1# show port-channel summary
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
O exemplo a seguir mostra que as portas ISL estão acima no interrutor CS2:

[listing]
----
       cs2# show port-channel summary
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
. [[step5]]Exibir a lista de dispositivos vizinhos:
`show cdp neighbors`.
+
Este comando fornece informações sobre os dispositivos que estão conetados ao sistema. O exemplo a seguir lista os dispositivos vizinhos no switch CS1:



[listing]
----
cs1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
O exemplo a seguir lista os dispositivos vizinhos no switch CS2:

[listing]
----
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
. [[step6]]Verifique se todas as portas de cluster estão ativas:
`network port show - ipspace Cluster`
+
Cada porta deve ser exibida para Link e Healthy for Health Status:



[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
. [[step7]]Verifique se todas as LIFs de cluster estão ativas e operacionais:
`network interface show - vserver Cluster`
+
Cada LIF de cluster deve exibir True para `Is Home` e ter um Admin de Status/Oper de up/up.



[listing]
----
cluster1::*> network interface show -vserver Cluster
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
. [[step8]]Verifique se a reversão automática está ativada em todas as LIFs do cluster:
`network interface show - vserver Cluster -fields auto-revert`


[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
. [[step9]]Desconete o cabo da porta do cluster E3A no node1 e conete o E3A à porta 1 no switch do cluster CS1, usando o cabeamento apropriado suportado pelos switches 9336C-FX2.
+
O NetApp https://hwu.netapp.com["Hardware Universe"] contém mais informações sobre cabeamento.

. Desconete o cabo da porta de cluster E3A no node2 e conete o E3A à porta 2 no switch de cluster CS1, usando o cabeamento apropriado suportado pelos switches 9336C-FX2.
. Habilite todas as portas voltadas para o nó no switch de cluster CS1.
+
O exemplo a seguir mostra que as portas 1/1 a 1/34 estão ativadas no switch CS1:



[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1-34
cs1(config-if-range)# no shutdown
----
. [[step12]]Verifique se todas as LIFs de cluster são *up*, operacionais e exibidas como True para `Is Home`:
`network interface show - vserver Cluster`
+
O exemplo a seguir mostra que todos os LIFs são *up* em node1 e node2 e que `Is Home` os resultados são *true*:



[listing]
----
cluster1::*> network interface show -vserver Cluster
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
. [[step13]]exibe informações sobre o status dos nós no cluster:
`cluster show`
+
O exemplo a seguir exibe informações sobre a integridade e a elegibilidade dos nós no cluster:



[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
. [[step14]]Desconete o cabo da porta do cluster e3b no node1 e conete o e3b à porta 1 no switch do cluster CS2, usando o cabeamento apropriado suportado pelos switches 9336C-FX2.
. Desconete o cabo da porta de cluster e3b no node2 e conete o e3b à porta 2 no switch de cluster CS2, usando o cabeamento apropriado suportado pelos switches 9336C-FX2.
. Habilite todas as portas voltadas para o nó no switch de cluster CS2.
+
O exemplo a seguir mostra que as portas 1/1 a 1/34 estão ativadas no switch CS2:



[listing]
----
cs2# config
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# interface e1/1-34
cs2(config-if-range)# no shutdown
----
. [[step17]]Verifique se todas as portas de cluster estão ativas:
`network port show - ipspace Cluster`
+
O exemplo a seguir mostra que todas as portas do cluster estão em node1 e node2:



[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
. [[step18]]Verifique se todas as interfaces são exibidas verdadeiras para `Is Home`:
`network interface show - vserver Cluster`



NOTE: Isso pode levar vários minutos para ser concluído.

O exemplo a seguir mostra que todos os LIFs são *up* em node1 e node2 e que `Is Home` os resultados são verdadeiros:

[listing]
----
cluster1::*> network interface show -vserver Cluster
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
. [[step19]]Verifique se ambos os nós têm uma conexão para cada switch:
`show cdp neighbors`
+
O exemplo a seguir mostra os resultados apropriados para ambos os switches:



[listing]
----
cs1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
. [[step20]]Mostre informações sobre os dispositivos de rede descobertos em seu cluster:
`network device-discovery show -protocol cdp`


[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
. [[step21]]Verifique se a configuração de armazenamento do par HA 1 (e par HA 2) está correta e livre de erros:
`system switch ethernet show`


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step22]]Verifique se as configurações estão desativadas:
`network options switchless-cluster show`



NOTE: Pode demorar vários minutos para o comando ser concluído. Aguarde até que o anúncio "3 minutos de duração expire".

A `false` saída no exemplo a seguir mostra que as configurações estão desativadas:

[listing]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: false
----
. [[step23]]Verifique o status dos membros do nó no cluster:
`cluster show`
+
O exemplo a seguir mostra informações sobre a integridade e a elegibilidade dos nós no cluster:



[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
. [[step24]]Certifique-se de que a rede de cluster tem conetividade total:
`cluster ping-cluster -node node-name`


[listing]
----
cluster1::*> cluster ping-cluster -node node2
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
...
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
...
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. [[step25]]altere o nível de privilégio de volta para admin:
`set -privilege admin`
. Ative o recurso de coleta de log do monitor de integridade do switch Ethernet para coletar arquivos de log relacionados ao switch, usando os comandos:
+
** `system switch ethernet log setup-password`
** `system switch ethernet log enable-collection`




[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.

Choose from the following list:
cs1
cs2
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system  switch ethernet log enable-collection
Do you want to enable cluster log collection for all nodes in the cluster? {y|n}: [n] y
Enabling cluster switch log collection.
cluster1::*>
----


==== Configure o switch compartilhado

Os exemplos deste procedimento utilizam a seguinte nomenclatura de switch e nó:

* Os nomes dos dois switches compartilhados são _SH1_ e _SH2_.
* Os nós são _node1_ e _node2_.



NOTE: O procedimento requer o uso de comandos ONTAP e comandos Cisco Nexus 9000 Series switches, os comandos ONTAP são usados, a menos que indicado de outra forma.

.Passos
. Verifique se a configuração de armazenamento do par HA 1 (e par HA 2) está correta e sem erros:
`system switch ethernet show`


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step2]]Verifique se as portas do nó de storage estão íntegras e operacionais:
`storage port show -port-type ENET`


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step3]]mova as portas do par HA 1, NSM224 caminho A para o intervalo de portas SH1 11-22.
. Instale um cabo do par HA 1, node1, caminho A até o intervalo de portas SH1 11-22. Por exemplo, o caminho Que uma porta de armazenamento em um AFF A400 é e0c.
. Instale um cabo do par HA 1, node2, caminho A até o intervalo de portas SH1 11-22.
. Verifique se as portas dos nós estão íntegras e operacionais:
`storage port show -port-type ENET`


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step7]]Verifique se não há problemas de cabeamento ou switch de armazenamento no cluster:
`system health alert show -instance`


[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. [[step8]]mova as portas do par HA 1, NSM224 caminho B para o intervalo de portas SH2 11-22.
. Instale um cabo do par HA 1, node1, caminho B para o intervalo de portas SH2 11-22. Por exemplo, a porta de armazenamento de caminho B em um AFF A400 é e5b.
. Instale um cabo do par HA 1, node2, caminho B para o intervalo de portas SH2 11-22.
. Verifique se as portas dos nós estão íntegras e operacionais:
`storage port show -port-type ENET`


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step12]]Verifique se a configuração de armazenamento do par HA 1 está correta e livre de erros:
`system switch ethernet show`


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step13]]reconfigure as portas de storage secundário não utilizadas (controladora) no par de HA 1 do storage para a rede. Se mais de um NS224 foi conetado diretamente, haverá portas que devem ser reconfiguradas.


[listing]
----
storage port modify –node [node name] –port [port name] –mode network
----
Para colocar portas de armazenamento em um domínio de broadcast:

* `network port broadcast-domain create` (para criar um novo domínio, se necessário)
* `network port broadcast-domain add-ports` (para adicionar portas a um domínio existente)


. [[step14]]se você suprimiu a criação automática de casos, reative-a invocando uma mensagem AutoSupport:
`system node autosupport invoke -node * -type all -message MAINT=END`

