---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: Saiba mais sobre os novos switches para sistemas FAS e AFF. 
---
= O que há de novo para switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre os novos switches para sistemas FAS e AFF.



== Novo suporte do interrutor

[cols="25h,~,~"]
|===
| Interrutores | Descrição | Disponível a partir do início 


 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco de 36 portas de 100 GbE (X190200)"]
 a| 
Dá suporte a uma infraestrutura compartilhada (cluster, HA e storage conectado a switch) no mesmo par de switches Cisco Nexus 9336C-FX2, incluindo suporte para configurações IP MetroCluster.
 a| 
ONTAP 9.9,1



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco de 36 portas de 100 GbE (X190200 e X190210)"]
 a| 
Switch de interconexão de cluster Cisco Nexus 9336C-FX2X compatível com switch de storage e switch de storage para controladores AFF/FAS, bem como para conectividade de dados de front-end.
 a| 
ONTAP 9,8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Broadcom BES-53248 (X190005 e X190005R)"]
 a| 
Suporte ao switch de interconexão de cluster BES-53248 Broadcom para controladores AFF/FAS com portas de 40 GbE/100GbE GbE.
 a| 
ONTAP 9,8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco de 36 portas de 100 GbE (X190200)"] https://hwu.netapp.com/Switch/Index["Switch Cisco de 32 portas de 100 GbE (X190100 e X190100R)"]
 a| 
O switch Cisco Nexus 100 GbE pode ser usado como um switch de storage dedicado para conectar gavetas de unidade NVMe NS224 às seguintes plataformas:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9,8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Broadcom BES-53248 (X190005 e X190005R)"]
 a| 
Suporte ao switch de interconexão de cluster BES-53248 Broadcom para controladores AFF/FAS com portas de 10 GbE/25GbE GbE.
 a| 
ONTAP 9.5P8

|===