---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, switches, fas, aff systems 
summary: Conheça as novas opções de comutação para os sistemas FAS e AFF . 
---
= O que há de novo para switches?
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre os novos switches para sistemas de armazenamento ONTAP. Para obter informações adicionais sobre os switches, consulte link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^].



[[july-2026]]
== Julho de 2026



[[new-cisco-nexus-9808-switch-for-afx-2k]]
=== Novo switch Cisco Nexus 9808 para AFX 2K

Os novos switches Cisco 9808 conectam-se aos nós controladores AFX 2K com os storage shelves. Este novo switch permite que você construa clusters ONTAP com mais de dois nós. Protocolos avançados são usados para otimizar o desempenho. O design é baseado em VLAN tagging com múltiplos caminhos de rede, assim como configurações de tech-refresh, para garantir operação contínua e facilidade de upgrade.

São switches Cisco de 36 portas 400GbE com 1 módulo Supervisor, 7 módulos Fabric e 4 unidades de alimentação (PSU) (X-N9K-C9808-B1-A) compatíveis com ONTAP 9.19.1 e versões posteriores.



[[2025-releases]]
== Lançamentos de 2025

.Outubro 2025
[%collapsible]
====
.Switches Cisco Nexus 9332D-GX2B e 9364D-GX2A para AFX 1K
Os switches Cisco 9364D-GX2A e Cisco 9332D-GX2B permitem que você construa clusters ONTAP com mais de dois nós. Protocolos avançados são usados para otimizar o desempenho. O design é baseado em VLAN tagging com múltiplos caminhos de rede, assim como configurações de tech-refresh, para garantir operação contínua e facilidade de upgrade.

São switches Cisco de 32 e 64 portas com 400GbE (X190300-CS-PI, X190300-PE e X190310-CS-PI) compatíveis com ONTAP 9.17.1 e versões posteriores.

O novo NetApp AFX sistema de storage oferece uma solução desagregada projetada para atender aos rigorosos requisitos de cargas de trabalho NAS e S3 de alto desempenho, incluindo aplicações de IA/ML. Os sistemas AFX oferecem recursos especializados para clientes que necessitam de storage de arquivos e objetos escalável e com alta taxa de transferência.

====
.Maio de 2025
[%collapsible]
====
.Switch de storage Cisco Nexus 9336C-FX2-T
Esses são switches de storage Cisco de 12 portas 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI) compatíveis com ONTAP 9.10.1 e versões posteriores. Eles suportam configurações de storage 100GbE (storage conectado ao switch).

====


[[2023-release]]
== Versão de 2023

.Maio de 2023
[%collapsible]
====
.Switch de cluster Cisco Nexus 9336C-FX2-T
Esses são switches de cluster Cisco de 12 portas 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI) compatíveis com ONTAP 9.10.1 e versões posteriores. Eles suportam configurações de cluster 10/25/40/100GbE.

====


[[2022-release]]
== Versão de 2022

.Outubro 2022
[%collapsible]
====
.Switch NVIDIA SN2100
O NVIDIA SN2100 é um switch NVIDIA de 16 portas 100GbE (X190006-PE e X190006-PI) que permite que você construa clusters ONTAP com mais de dois nós, compatível com ONTAP 9.10.1 e versões posteriores. Ele é um switch de interconexão de cluster NVIDIA e switch de storage, incluindo suporte para configurações de IP do MetroCluster.

====


[[2021-release]]
== Lançamento de 2021

.Maio de 2021
[%collapsible]
====
.Switch Cisco Nexus 9336C-FX2
O Cisco Nexus 9336C-FX2 é um switch Cisco de 36 portas 100GbE (X190200-CS-PE e X190200-CS-PI). Ele suporta uma infraestrutura compartilhada (interconexão de cluster, alta disponibilidade e storage conectado ao switch) no mesmo par de switches Cisco Nexus 9336C-FX2, incluindo suporte para configurações IP do MetroCluster, compatível com ONTAP 9.9.1 e versões posteriores.

====


[[2019-release]]
== Lançamento de 2019

.Maio de 2019
[%collapsible]
====
.Switch Broadcom BES-53248
O switch Broadcom BES-53248 (X190005 e X190005R) suporta controladores AFF/FAS com portas 10/25GbE e 40/100GbE, compatíveis com ONTAP 9.8 e versões posteriores.

====
.Março de 2019
[%collapsible]
====
.Switches de cluster e storage Cisco Nexus 3232C da Cisco
O switch Cisco Nexus 3232C é um switch Cisco de 36 portas 100GbE (X190200) e um switch Cisco de 32 portas 100GbE (X190100 e X190100R). O switch de storage Cisco Nexus 3232C suporta conexões com as seguintes prateleiras de unidades NS224 NVMe e sistemas de storage AFF e ASA:

* AFF A800/ AFF ASA A800
* AFF A700/ AFF ASA A700
* AFF A400/ AFF ASA A400


Eles são compatíveis com ONTAP 9.8 e posteriores.

====