---
permalink: switch-nvidia-sn2100/components-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Se você deseja criar clusters ONTAP com mais de dois nós, precisará de dois switches de rede de cluster compatíveis.  Você pode usar interruptores de gerenciamento adicionais, que são opcionais. 
---
= Componentes e números de peça para switches NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para a instalação e manutenção do switch NVIDIA SN2100, certifique-se de consultar a lista de componentes e os números de peça do gabinete e do kit de trilhos.



== Detalhes do gabinete

Você instala o switch NVIDIA SN2100 (X190006) no gabinete de switch duplo/simples da NVIDIA com os suportes padrão que acompanham o switch.



== Detalhes do kit de trilhos

A tabela a seguir lista o número da peça e a descrição dos interruptores e kits de trilhos SN2100:

[cols="1,2"]
|===
| Número da peça | Descrição 


 a| 
X190006-PE
 a| 
Cluster Switch, NVIDIA SN2100, 16PT 100GbE, PTSX



 a| 
X190006-PI
 a| 
Cluster Switch, NVIDIA SN2100, 16PT 100GbE, PSIN



 a| 
X-MTEF-KIT-D
 a| 
Kit de trilhos, interruptor duplo NVIDIA lado a lado



 a| 
X-MTEF-KIT-E
 a| 
Kit de trilhos, NVIDIA Single Switch de profundidade reduzida

|===

NOTE: Consulte a documentação da NVIDIA para obter detalhes sobre https://docs.nvidia.com/networking/display/sn2000pub/Installation["Instalando seu kit de trilhos e interruptor SN2100"^] .

.O que vem a seguir?
Após confirmar os componentes e os números de peça, você pode revisar o link:required-documentation-sn2100-cluster.html["documentação necessária"].
