---
permalink: switch-nvidia-sn2100/components-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Identifique os componentes e os números de peça dos switches de cluster NVIDIA SN2100 para dar suporte à instalação e à manutenção contínua de hardware. 
---
= Analise os componentes e os números de peça dos switches de cluster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Identifique os componentes e os números de peça dos switches de cluster NVIDIA SN2100 para dar suporte à instalação e à manutenção contínua de hardware.



[[cabinet-details]]
== Detalhes do gabinete

Você instala o switch NVIDIA SN2100 (X190006) no gabinete de switch duplo/simples da NVIDIA com os suportes padrão que acompanham o switch.



[[rail-kit-details]]
== Detalhes do kit de trilhos

A tabela a seguir lista o número da peça e a descrição dos interruptores e kits de trilhos SN2100:

[cols="1,2"]
|===
| Número da peça | Descrição 


 a| 
X190006-PE
 a| 
Cluster Switch, NVIDIA SN2100, 16PT 100GbE, PTSX



 a| 
X190006-PI
 a| 
Cluster Switch, NVIDIA SN2100, 16PT 100GbE, PSIN



 a| 
X-MTEF-KIT-D
 a| 
Kit de trilhos, interruptor duplo NVIDIA lado a lado



 a| 
X-MTEF-KIT-E
 a| 
Kit de trilhos, NVIDIA Single Switch de profundidade reduzida

|===

NOTE: Consulte a documentação da NVIDIA para obter detalhes sobre link:https://networking-docs.nvidia.com/sn2000hw/latest/installation["Instalando seu kit de trilhos e interruptor SN2100"^].

.O que vem a seguir?
Após confirmar os componentes e os números de peça, você pode revisar o link:required-documentation-sn2100-cluster.html["documentação necessária"].
