---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Para a instalação e manutenção do switch NVIDIA SN2100, certifique-se de revisar todos os requisitos e a documentação recomendada. 
---
= Requisitos de configuração para switches NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalação e manutenção do switch NVIDIA SN2100, certifique-se de revisar todos os requisitos de configuração.



== Requisitos de instalação

Se você deseja criar clusters ONTAP com mais de dois nós, precisará de dois switches de rede de cluster compatíveis.  Você pode usar interruptores de gerenciamento adicionais, que são opcionais.

Você instala o switch NVIDIA SN2100 (X190006) no gabinete de switch duplo/simples da NVIDIA com os suportes padrão que acompanham o switch.

Para diretrizes de cabeamento, consultelink:cabling-considerations-sn2100-cluster.html["Analise as considerações sobre cabeamento e configuração."] .



== Suporte para ONTAP e Linux

O switch NVIDIA SN2100 é um switch 10/25/40/100GbE que executa o Cumulus Linux.  O switch suporta o seguinte:

* ONTAP 9.10.1P3 e versões posteriores
+
O switch SN2100 atende a aplicações de Cluster e Armazenamento no ONTAP 9.10.1P3 e versões posteriores em diferentes pares de switches.

* Versões do sistema operacional Cumulus Linux (CL)
+
** A NetApp qualifica e suporta versões específicas do CL.  Para obter informações atualizadas sobre compatibilidade, consulte olink:https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Informações sobre switches Ethernet da NVIDIA"^] página ou alink:https://hwu.netapp.com["Hardware Universe da NetApp"^] .
** Para baixar o software SN2100 Cumulus da NVIDIA, você precisa ter credenciais de login para acessar o Portal de Suporte Empresarial da NVIDIA.  Consulte o artigo da Base de Conhecimento. https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access["Como se cadastrar no Portal de Suporte Empresarial da NVIDIA para obter acesso."^] .




* Você pode instalar o Cumulus Linux quando o switch estiver executando o Cumulus Linux ou o ONIE.


.O que vem a seguir?
Após analisar os requisitos de configuração, você poderá confirmar sua solicitação. link:components-sn2100-cluster.html["componentes e números de peças"].
