---
permalink: switch-nvidia-sn2100/configure-overview-sn2100-cluster.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: O switch NVIDIA SN2100 é um switch Ethernet de 10/25/40/100 GbE que executa o Cumulus Linux. O switch SN2100 serve aplicativos de cluster e armazenamento no ONTAP 9.10,1 em diferentes pares de switches. 
---
= Visão geral da instalação e configuração dos switches NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O NVIDIA SN2100 é um switch de cluster que permite criar clusters do ONTAP com mais de dois nós.



== Visão geral da configuração inicial

Para configurar um switch NVIDIA SN2100 em sistemas que executam o ONTAP, siga estas etapas:

. link:install-hardware-sn2100-cluster.html["Instale o hardware do switch NVIDIA SN2100"].
+
As instruções estão disponíveis no _Guia de Instalação do comutador NVIDIA_.

. link:configure-sn2100-cluster.html["Configure o interrutor"].
+
As instruções estão disponíveis na documentação do NVIDIA.

. link:cabling-considerations-sn2100-cluster.html["Analise as considerações sobre cabeamento e configuração"].
+
Revise os requisitos para conexões óticas, o adaptador QSA e a velocidade do switchport.

. link:install-cable-shelves-sn2100-cluster.html["Prenda as NS224 gavetas como storage conetado a switch"].
+
Siga os procedimentos de cabeamento se você tiver um sistema no qual os NS224 compartimentos de unidades precisam ser cabeados como storage conectado a switch (não storage com conexão direta).

. link:install-cumulus-mode-sn2100-cluster.html["Instale o Cumulus Linux no modo Cumulus"] ou link:install-onie-mode-sn2100-cluster.html["Instale o Cumulus Linux no modo ONIE"].
+
Você pode instalar o SO Cumulus Linux (CL) quando o switch estiver executando o Cumulus Linux ou ONIE.

. link:install-rcf-sn2100-cluster.html["Instale o script RCF (Reference Configuration File)"].
+
Existem dois scripts RCF disponíveis para aplicativos de agrupamento e armazenamento. O procedimento para cada um é o mesmo.

. link:setup-install-cshm-file.html["Instale o arquivo CSHM"].
+
Você pode instalar o arquivo de configuração aplicável para o monitoramento de integridade do switch Ethernet dos switches de cluster NVIDIA.





== Informações adicionais

Antes de iniciar a instalação ou manutenção, certifique-se de rever o seguinte:

* link:configure-reqs-sn2100-cluster.html["Requisitos de configuração"]
* link:components-sn2100-cluster.html["Componentes e números de peça"]
* link:required-documentation-sn2100-cluster.html["Documentação necessária"]
* https://hwu.netapp.com["Hardware Universe"^] Para todas as versões suportadas do ONTAP.

