---
permalink: switch-nvidia-sn2100/install-cable-shelves-sn2100-cluster.html 
sidebar: sidebar 
keywords: sn2100 cabling setup, msn2100 sn2100 switches configuration, cumulus linux 
summary: Conecte os gabinetes de unidades NS224 como armazenamento conectado a switches usando os switches de cluster NVIDIA SN2100 quando o armazenamento conectado diretamente não for utilizado. 
---
= Conecte os compartimentos de unidades NS224 como armazenamento conectado a switch para os switches de cluster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conecte os gabinetes de unidades NS224 como armazenamento conectado a switches usando os switches de cluster NVIDIA SN2100 quando o armazenamento conectado diretamente não for adequado para sua configuração.

* O cabo NS224 aciona as prateleiras através dos switches de armazenamento:
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580["Compartimentos de unidades NS224 conectados por switch de cabeamento"^]

* Confirme o hardware compatível, como switches de armazenamento e cabos, para o modelo da sua plataforma. Consulte a link:https://hwu.netapp.com/["Hardware Universe"^] para obter detalhes.


.O que vem a seguir?
Depois de instalar os cabos nas suas prateleiras, você podelink:configure-sn2100-cluster.html["configurar o switch"] .
