---
permalink: switch-nvidia-sn2100/install-cumulus-mode-sn2100-cluster.html 
sidebar: sidebar 
keywords: install cumulus mode, sn2100 SN2100 switches setup, cumulus linux, cumulus mode 
summary: 'O sistema operacional Cumulus Linux (CL) pode ser instalado tanto quando o switch estiver executando Cumulus Linux quanto ONIE.' 
---
= Instale o Cumulus Linux no modo Cumulus.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para instalar o sistema operacional Cumulus Linux (CL) quando o switch estiver em modo Cumulus.


NOTE: O sistema operacional Cumulus Linux (CL) pode ser instalado quando o switch estiver executando Cumulus Linux ou ONIE (consultelink:install-onie-mode-sn2100-cluster.html["Instalar no modo ONIE"] ).

.Antes de começar
Certifique-se de ter o seguinte:

* Conhecimento intermediário de Linux.
* Familiaridade com edição básica de texto, permissões de arquivos UNIX e monitoramento de processos.  Diversos editores de texto vêm pré-instalados, incluindo: `vi` e `nano` .
* Acesso a um shell Linux ou UNIX.  Se você estiver usando o Windows, utilize um ambiente Linux como ferramenta de linha de comando para interagir com o Cumulus Linux.
* A taxa de transmissão (baud rate) exigida no switch de console serial para acesso ao console do switch NVIDIA SN2100 é de 115200, conforme segue:
+
** 115200 baud
** 8 bits de dados
** 1 bit de parada
** paridade: nenhuma
** Controle de fluxo: nenhum




.Sobre esta tarefa
Esteja ciente do seguinte:


NOTE: Cada vez que o Cumulus Linux é instalado, toda a estrutura do sistema de arquivos é apagada e reconstruída.


CAUTION: A senha padrão para a conta de usuário cumulus é *cumulus*.  Na primeira vez que você fizer login no Cumulus Linux, você deverá alterar esta senha padrão.  Certifique-se de atualizar todos os scripts de automação antes de instalar uma nova imagem.  O Cumulus Linux oferece opções de linha de comando para alterar a senha padrão automaticamente durante o processo de instalação.

.Passos
[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
. Faça login no switch.
+
O primeiro acesso ao switch requer o nome de usuário/senha *cumulus*/*cumulus*. `sudo` privilégios.

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Verifique a versão do Cumulus Linux: `net show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show system*
Hostname......... cumulus
Build............ *Cumulus Linux 4.4.3*
Uptime........... 0:08:20.860000
Model............ Mlnx X86
CPU.............. x86_64 Intel Atom C2558 2.40GHz
Memory........... 8GB
Disk............. 14.7GB
ASIC............. Mellanox Spectrum MT52132
Ports............ 16 x 100G-QSFP28
Part Number...... MSN2100-CB2FC
Serial Number.... MT2105T05177
Platform Name.... x86_64-mlnx_x86-r0
Product Name..... MSN2100
ONIE Version..... 2019.11-5.2.0020-115200
Base MAC Address. 04:3F:72:43:92:80
Manufacturer..... Mellanox
----
. Configure o nome do host, o endereço IP, a máscara de sub-rede e o gateway padrão.  O novo nome de host só entra em vigor após reiniciar o console/sessão SSH.
+

NOTE: Um switch Cumulus Linux fornece pelo menos uma porta Ethernet dedicada para gerenciamento, chamada `eth0` .  Esta interface destina-se especificamente à gestão fora de banda.  Por padrão, a interface de gerenciamento usa DHCPv4 para endereçamento.

+

CAUTION: Não utilize sublinhado (_), apóstrofo (') ou caracteres não ASCII no nome do host.

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net add hostname sw1*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip address 10.233.204.71/24*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *net pending*
cumulus@cumulus:mgmt:~$ *net commit*
----
+
Este comando modifica ambos os `/etc/hostname` e `/etc/hosts` arquivos.

. Confirme se o nome do host, o endereço IP, a máscara de sub-rede e o gateway padrão foram atualizados.
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Configure a data, a hora, o fuso horário e o servidor NTP no switch.
+
.. Verifique o fuso horário atual:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *cat /etc/timezone*
----
.. Atualização para o novo fuso horário:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure --frontend noninteractive tzdata*
----
.. Verifique seu fuso horário atual:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. Para definir o fuso horário usando o assistente guiado, execute o seguinte comando:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Configure o relógio do software de acordo com o fuso horário configurado:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. Defina o valor atual do relógio do software para o valor do relógio do hardware:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *sudo hwclock -w*
----
.. Adicione um servidor NTP, se necessário:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add time ntp server _<cumulus.network.ntp.org>_ iburst*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
.. Verifique se `ntpd` está em execução no sistema:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. Especifique a interface de origem NTP.  Por padrão, a interface de origem que o NTP utiliza é `eth0` .  Você pode configurar uma interface de origem NTP diferente da seguinte forma:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add time ntp source _<src_int>_*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----


. Instale o Cumulus Linux 4.4.3:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*
----
+
O instalador inicia o download. Digite *y* quando solicitado.

. Reinicie o switch NVIDIA SN2100:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. A instalação inicia automaticamente e as seguintes opções da tela GRUB são exibidas.  Não faça nenhuma seleção.
+
** Cumulus-Linux GNU/Linux
** ONIE: Instalar SO
** CUMULUS-INSTALAÇÃO
** Cumulus-Linux GNU/Linux


. Repita os passos de 1 a 4 para fazer login.
. Verifique se a versão do Cumulus Linux é 4.4.3: `net show version`
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u0
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3"*
----
. Crie um novo usuário e adicione-o ao `sudo` grupo.  Este usuário só entra em vigor após a reinicialização da sessão de console/SSH.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----


--
.Cumulus Linux 5.4.0
--
. Faça login no switch.
+
O primeiro acesso ao switch requer o nome de usuário/senha *cumulus*/*cumulus*. `sudo` privilégios.

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Verifique a versão do Cumulus Linux: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.3.0  system build version
uptime              6 days, 8:37:36      system uptime
timezone            Etc/UTC              system time zone
----
. Configure o nome do host, o endereço IP, a máscara de sub-rede e o gateway padrão.  O novo nome de host só entra em vigor após reiniciar o console/sessão SSH.
+

NOTE: Um switch Cumulus Linux fornece pelo menos uma porta Ethernet dedicada para gerenciamento, chamada `eth0` .  Esta interface destina-se especificamente à gestão fora de banda.  Por padrão, a interface de gerenciamento usa DHCPv4 para endereçamento.

+

CAUTION: Não utilize sublinhado (_), apóstrofo (') ou caracteres não ASCII no nome do host.

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip address 10.233.204.71/24*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *nv config apply*
cumulus@cumulus:mgmt:~$ *nv config save*
----
+
Este comando modifica ambos os `/etc/hostname` e `/etc/hosts` arquivos.

. Confirme se o nome do host, o endereço IP, a máscara de sub-rede e o gateway padrão foram atualizados.
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Configure o fuso horário, a data, a hora e o servidor NTP no switch.
+
.. Defina o fuso horário:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set system timezone US/Eastern*
cumulus@sw1:~$ *nv config apply*
----
.. Verifique seu fuso horário atual:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. Para definir o fuso horário usando o assistente guiado, execute o seguinte comando:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Configure o relógio do software de acordo com o fuso horário configurado:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. Defina o valor atual do relógio do software para o valor do relógio do hardware:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo hwclock -w*
----
.. Adicione um servidor NTP, se necessário:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp mgmt listen eth0*
cumulus@sw1:~$ *nv set service ntp mgmt server <server> iburst on*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----
+
Consulte o artigo da Base de Conhecimento.link:https://kb.netapp.com/on-prem/Switches/Nvidia-KBs/NTP_Server_configuration_is_not_working_with_NVIDIA_SN2100_Switches["A configuração do servidor NTP não está funcionando com switches NVIDIA SN2100."^] Para obter mais detalhes.

.. Verifique se `ntpd` está em execução no sistema:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. Especifique a interface de origem NTP.  Por padrão, a interface de origem que o NTP utiliza é `eth0` .  Você pode configurar uma interface de origem NTP diferente da seguinte forma:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp default listen _<src_int>_*
cumulus@sw1:~$ *nv config apply*
----


. Instale o Cumulus Linux 5.4.0:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-5.4-mlx-amd64.bin*
----
+
O instalador inicia o download. Digite *y* quando solicitado.

. Reinicie o switch NVIDIA SN2100:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. A instalação inicia automaticamente e as seguintes opções da tela GRUB são exibidas.  Não faça nenhuma seleção.
+
** Cumulus-Linux GNU/Linux
** ONIE: Instalar SO
** CUMULUS-INSTALAÇÃO
** Cumulus-Linux GNU/Linux


. Repita os passos de 1 a 4 para fazer login.
. Verifique se a versão do Cumulus Linux é 5.4.0: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0  system build version
uptime              6 days, 13:37:36     system uptime
timezone            Etc/UTC              system time zone
----
. Verifique se cada nó possui conexão com cada switch:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost                          RemotePort
---------  -----  ----------  ----------------------------------  -----------
eth0       100M   Mgmt        mgmt-sw1                            Eth110/1/29
swp2s1     25G    Trunk/L2    node1                               e0a
swp15      100G   BondMember  sw2                                 swp15
swp16      100G   BondMember  sw2                                 swp16
----
. Crie um novo usuário e adicione-o ao `sudo` grupo.  Este usuário só entra em vigor após a reinicialização da sessão de console/SSH.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. Adicione grupos de usuários adicionais para o usuário administrador acessar. `nv` comandos:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user 'admin' to group 'nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
Ver https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["Contas de usuário NVIDIA"^] para mais informações.



--
.Cumulus Linux 5.11.0
--
. Faça login no switch.
+
Ao fazer login no switch pela primeira vez, é necessário inserir o nome de usuário e a senha *cumulus*/*cumulus*. `sudo` privilégios.

+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Verifique a versão do Cumulus Linux: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0  system build version
uptime              6 days, 8:37:36      system uptime
timezone            Etc/UTC              system time zone
----
. Configure o nome do host, o endereço IP, a máscara de sub-rede e o gateway padrão.  O novo nome de host só entra em vigor após reiniciar o console/sessão SSH.
+

NOTE: Um switch Cumulus Linux fornece pelo menos uma porta Ethernet dedicada para gerenciamento, chamada `eth0` .  Esta interface destina-se especificamente à gestão fora de banda.  Por padrão, a interface de gerenciamento usa DHCPv4 para endereçamento.

+

CAUTION: Não utilize sublinhado (_), apóstrofo (') ou caracteres não ASCII no nome do host.

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv unset interface eth0 ip address dhcp*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip address 10.233.204.71/24*
cumulus@cumulus:mgmt:~$ *nv set interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *nv config apply*
cumulus@cumulus:mgmt:~$ *nv config save*
----
+
Este comando modifica ambos os `/etc/hostname` e `/etc/hosts` arquivos.

. Confirme se o nome do host, o endereço IP, a máscara de sub-rede e o gateway padrão foram atualizados.
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Configure o fuso horário, a data, a hora e o servidor NTP no switch.
+
.. Defina o fuso horário:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set system timezone US/Eastern*
cumulus@sw1:~$ *nv config apply*
----
.. Verifique seu fuso horário atual:
+
[listing, subs="+quotes"]
----
cumulus@switch:~$ *date +%Z*
----
.. Para definir o fuso horário usando o assistente guiado, execute o seguinte comando:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Configure o relógio do software de acordo com o fuso horário configurado:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo date -s "Tue Oct 28 00:37:13 2023"*
----
.. Defina o valor atual do relógio do software para o valor do relógio do hardware:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo hwclock -w*
----
.. Adicione um servidor NTP, se necessário:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp mgmt listen eth0*
cumulus@sw1:~$ *nv set service ntp mgmt server <server> iburst on*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----
+
Consulte o artigo da Base de Conhecimento.link:https://kb.netapp.com/on-prem/Switches/Nvidia-KBs/NTP_Server_configuration_is_not_working_with_NVIDIA_SN2100_Switches["A configuração do servidor NTP não está funcionando com switches NVIDIA SN2100."^] Para obter mais detalhes.

.. Verifique se `ntpd` está em execução no sistema:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *ps -ef | grep ntp*
ntp       4074     1  0 Jun20 ?        00:00:33 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 101:102
----
.. Especifique a interface de origem NTP.  Por padrão, a interface de origem que o NTP utiliza é `eth0` .  Você pode configurar uma interface de origem NTP diferente da seguinte forma:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set service ntp default listen _<src_int>_*
cumulus@sw1:~$ *nv config apply*
----


. Instale o Cumulus Linux 5.11.0:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-5.11.0-mlx-amd64.bin*
----
+
O instalador inicia o download. Digite *y* quando solicitado.

. Reinicie o switch NVIDIA SN2100:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. A instalação inicia automaticamente e as seguintes opções da tela GRUB são exibidas.  Não faça nenhuma seleção.
+
** Cumulus-Linux GNU/Linux
** ONIE: Instalar SO
** CUMULUS-INSTALAÇÃO
** Cumulus-Linux GNU/Linux


. Repita os passos de 1 a 4 para fazer login.
. Verifique se a versão do Cumulus Linux é 5.11.0:
+
`nv show system`

+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied                description
------------------- ---------------------- ---------------------
build               Cumulus Linux 5.11.0
uptime              153 days, 2:44:16
hostname            cumulus                cumulus
product-name        Cumulus Linux
product-release     5.11.0
platform            x86_64-mlnx_x86-r0
system-memory       2.76 GB used / 2.28 GB free / 7.47 GB total
swap-memory         0 Bytes used / 0 Bytes free / 0 Bytes total
health-status       not OK
date-time           2025-04-23 09:55:24
status              N/A
timezone            Etc/UTC
maintenance
  mode              disabled
  ports             enabled
version
  kernel            6.1.0-cl-1-amd64
  build-date        Thu Nov 14 13:06:38 UTC 2024
  image             5.11.0
  onie              2019.11-5.2.0020-115200
----
. Verifique se cada nó possui conexão com cada switch:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv show interface lldp*

LocalPort  Speed  Mode        RemoteHost                          RemotePort
---------  -----  ----------  ----------------------------------  -----------
eth0       100M   eth   mgmt-sw1                                  Eth110/1/14
swp2s1     25G    Trunk/L2    node1                               e0a
swp1s1     10G    swp   sw2                                       e0a
swp9       100G   swp   sw3                                       e4a
swp10      100G   swp   sw4                                       e4a
swp15      100G   swp   sw5                                       swp15
swp16      100G   swp   sw6                                       swp16
----


Ver https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-511/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["Contas de usuário NVIDIA"^] para mais informações.

--
====
.O que vem a seguir?
Depois de instalar o Cumulus Linux no modo Cumulus, você link:install-rcf-sn2100-cluster.html["Instale o script do Arquivo de Configuração de Referência (RCF)."].
