---
permalink: switch-nvidia-sn2100/install-onie-mode-sn2100-cluster.html 
sidebar: sidebar 
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode 
summary: 'O sistema operacional Cumulus Linux (CL) pode ser instalado tanto quando o switch estiver executando Cumulus Linux quanto ONIE.' 
---
= Instale o Cumulus Linux no modo ONIE.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para instalar o sistema operacional Cumulus Linux (CL) quando o switch estiver em modo ONIE.


NOTE: O sistema operacional Cumulus Linux (CL) pode ser instalado quando o switch estiver executando ONIE ou Cumulus Linux (consultelink:install-cumulus-mode-sn2100-cluster.html["Instalar no modo Cumulus"] ).

.Sobre esta tarefa
Você pode instalar o Cumulus Linux usando o Open Network Install Environment (ONIE), que permite a descoberta automática de uma imagem de instalação de rede.  Isso facilita o modelo de sistema para proteger switches com uma opção de sistema operacional, como o Cumulus Linux.  A maneira mais fácil de instalar o Cumulus Linux com ONIE é através da descoberta HTTP local.


NOTE: Se o seu host estiver habilitado para IPv6, certifique-se de que ele esteja executando um servidor web.  Se o seu host estiver habilitado para IPv4, certifique-se de que ele esteja executando o DHCP além de um servidor web.

Este procedimento demonstra como atualizar o Cumulus Linux depois que o administrador inicializou o sistema no ONIE.

.Passos
[role="tabbed-block"]
====
.Cumulus Linux 4.4.3
--
. Faça o download do arquivo de instalação do Cumulus Linux para o diretório raiz do servidor web.  Renomeie este arquivo para: `onie-installer` .
. Conecte seu computador à porta Ethernet de gerenciamento do switch usando um cabo Ethernet.
. Ligue o interruptor.
+
O switch baixa o instalador de imagem ONIE e inicializa.  Após a conclusão da instalação, a tela de login do Cumulus Linux aparece na janela do terminal.

+

NOTE: Cada vez que o Cumulus Linux é instalado, toda a estrutura do sistema de arquivos é apagada e reconstruída.

. Reinicie o switch SN2100:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. Na tela do GNU GRUB, pressione a tecla *Esc* para interromper o processo normal de inicialização, selecione *ONIE* e pressione *Enter*.
. Na tela seguinte, selecione *ONIE: Instalar SO*.
. O processo de descoberta do instalador ONIE é executado em busca da instalação automática.  Pressione *Enter* para interromper temporariamente o processo.
. Quando o processo de descoberta for concluído:
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. Se o serviço DHCP estiver em execução na sua rede, verifique se o endereço IP, a máscara de sub-rede e o gateway padrão estão atribuídos corretamente:
+
`ifconfig eth0`

+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
. Se o esquema de endereçamento IP for definido manualmente, faça o seguinte:
+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. Repita o passo 9 para verificar se as informações estáticas foram inseridas corretamente.
. Instalar o Cumulus Linux:
+
[listing]
----
# onie-nos-install http://<web-server>/<path>/cumulus-linux-4.4.3-mlx-amd64.bin
----
+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. Após a conclusão da instalação, faça login no switch.
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Verifique a versão do Cumulus Linux: `net show version`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----


--
.Cumulus Linux 5.x
--
. Faça o download do arquivo de instalação do Cumulus Linux para o diretório raiz do servidor web.  Renomeie este arquivo para: `onie-installer` .
. Conecte seu computador à porta Ethernet de gerenciamento do switch usando um cabo Ethernet.
. Ligue o interruptor.
+
O switch baixa o instalador de imagem ONIE e inicializa.  Após a conclusão da instalação, a tela de login do Cumulus Linux aparece na janela do terminal.

+

NOTE: Cada vez que o Cumulus Linux é instalado, toda a estrutura do sistema de arquivos é apagada e reconstruída.

. Reinicie o switch SN2100:
+
[listing]
----
cumulus@cumulus:mgmt:~$ sudo reboot
.
.
GNU GRUB version 2.06-3
+-------------------------------------------------------------------------+
| Cumulus-Linux GNU/Linux                                                 |
| Advanced options for Cumulus-Linux GNU/Linux                            |
| ONIE                                                                    |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
+-------------------------------------------------------------------------+
----
. Na tela do GNU GRUB, pressione a tecla Esc para interromper o processo normal de inicialização, selecione ONIE e pressione Enter.
+
[listing]
----
.
.
Loading ONIE ...

GNU GRUB version 2.02
+-------------------------------------------------------------------------+
| ONIE: Install OS                                                        |
| ONIE: Rescue                                                            |
| ONIE: Uninstall OS                                                      |
| ONIE: Update ONIE                                                       |
| ONIE: Embed ONIE                                                        |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
|                                                                         |
+-------------------------------------------------------------------------+
----
+
Selecione ONIE: *Instalar SO.*

. O processo de descoberta do instalador ONIE é executado em busca da instalação automática.  Pressione *Enter* para interromper temporariamente o processo.
. Quando o processo de descoberta for concluído:
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. Configure o endereço IP, a máscara de sub-rede e o gateway padrão:
+
`ifconfig eth0`

+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff
ONIE:/ #
ONIE:/ # *ifconfig eth0 10.228.140.27 netmask 255.255.248.0*
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet HWaddr B8:CE:F6:5E:05:E6
       inet addr:10.228.140.27 Bcast:10.228.143.255 Mask:255.255.248.0
       inet6 addr: fd20:8b1e:b255:822b:bace:f6ff:fe5e:5e6/64 Scope:Global
       inet6 addr: fe80::bace:f6ff:fe5e:5e6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
       RX packets:18813 errors:0 dropped:1418 overruns:0 frame:0
       TX packets:491 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:1339596 (1.2 MiB) TX bytes:49379 (48.2 KiB)
       Memory:dfc00000-dfc1ffff
ONIE:/ # *route add default gw 10.228.136.1*
ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.228.136.1    0.0.0.0         UG    0      0      0   eth0
10.228.136.1    *               255.255.248.0   U     0      0      0   eth0
----
. Instale o Cumulus Linux 5.4:
+
`# onie-nos-install http://<web-server>/<path>/cumulus-linux-5.4-mlx-amd64.bin`

+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-5.4-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-5.4-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. Após a conclusão da instalação, faça login no switch.
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
. Verifique a versão do Cumulus Linux: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational         applied              description
------------------- -------------------- ---------------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0  system build version
uptime              6 days, 13:37:36     system uptime
timezone            Etc/UTC              system time zone
----
. Crie um novo usuário e adicione-o ao `sudo` grupo.  Este usuário só entra em vigor após a reinicialização da sessão de console/SSH.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. Adicione grupos de usuários adicionais para o usuário administrador acessar. `nv` comandos:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user `admin' to group `nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
Ver https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["Contas de usuário NVIDIA"^] para mais informações.



--
====
.O que vem a seguir?
Após instalar o Cumulus Linux no modo ONIE, você podelink:install-rcf-sn2100-cluster.html["Instale o script do Arquivo de Configuração de Referência (RCF)."] .
