---
permalink: switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched NVIDIA SN2100 cluster environment,switchless cluster environments,NVIDIA SN2100 switches 
summary: Se você tiver um ambiente de cluster sem switch de dois nós existente, poderá migrar para um ambiente de cluster comutado de dois nós usando os switches NVIDIA SN2100 para permitir que você escale além de dois nós no cluster. 
---
= Migre para um cluster comutado de dois nós com os switches de cluster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você tiver um ambiente de cluster sem switch de dois nós existente, poderá migrar para um ambiente de cluster comutado de dois nós usando os switches NVIDIA SN2100 para permitir que você escale além de dois nós no cluster.

O procedimento usado depende se você tem duas portas de rede de cluster dedicadas em cada controlador ou uma única porta de cluster em cada controlador. O processo documentado funciona para todos os nós que usam portas óticas ou Twinax, mas não é suportado neste switch se os nós estiverem usando portas 10GBASEBASE-T RJ45 integradas para as portas de cluster-rede.



== Rever os requisitos

.Configuração sem switch de dois nós
Certifique-se de que:

* A configuração sem switch de dois nós está configurada e funcionando corretamente.
* Os nós estão executando o ONTAP 9.10.1P3 e posterior.
* Todas as portas de cluster estão no estado *up*.
* Todas as interfaces lógicas de cluster (LIFs) estão no estado *up* e em suas portas domésticas.


.Configuração do switch de cluster do NVIDIA SN2100
Certifique-se de que:

* Ambos os switches têm conetividade de rede de gerenciamento.
* Existe acesso à consola aos interrutores do cluster.
* As conexões de switch de nó para nó NVIDIA SN2100 e switch para switch usam cabos Twinax ou fibra.
+

IMPORTANT: link:cabling-considerations-sn2100-cluster.html["Analise as considerações sobre cabeamento e configuração"]Consulte para ver as ressalvas e mais detalhes. O https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - interrutores"^] também contém mais informações sobre cabeamento.

* Os cabos ISL (Inter-Switch Link) são conetados às portas swp15 e swp16 em ambos os switches NVIDIA SN2100.
* A personalização inicial de ambos os switches SN2100 está concluída, de modo que:
+
** Os switches SN2100 estão executando a versão mais recente do Cumulus Linux
** Os arquivos de configuração de referência (RCFs) são aplicados aos switches
** Qualquer personalização de site, como SMTP, SNMP e SSH, é configurada nos novos switches.
+
O https://hwu.netapp.com["Hardware Universe"^] contém as informações mais recentes sobre as portas de cluster reais para as suas plataformas.







== Migrar os switches

.Sobre os exemplos
Os exemplos deste procedimento utilizam a seguinte nomenclatura de nó e switch de cluster:

* Os nomes dos switches SN2100 são _SW1_ e _SW2_.
* Os nomes dos SVMs do cluster são _node1_ e _node2_.
* Os nomes dos LIFs são _node1_clus1_ e _node1_clus2_ no nó 1 e _node2_clus1_ e _node2_clus2_ no nó 2 respetivamente.
* O `cluster1::*>` prompt indica o nome do cluster.
* As portas de cluster usadas neste procedimento são _E3A_ e _e3b_.
* As portas breakout tomam o formato: swp[port]s[breakout port 0-3]. Por exemplo, quatro portas breakout no swp1 são _swp1s0_, _swp1s1_, _swp1s2_ e _swp1s3_.




=== Passo 1: Prepare-se para a migração

. Se o AutoSupport estiver ativado neste cluster, suprimir a criação automática de casos invocando uma mensagem AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=xh`
+
onde _x_ é a duração da janela de manutenção em horas.

. Altere o nível de privilégio para avançado, inserindo `y` quando solicitado a continuar: `set -privilege advanced`
+
(`*>`É apresentado o aviso avançado ).





=== Etapa 2: Configurar portas e cabeamento

[role="tabbed-block"]
====
.Cumulus Linux 4,4.x
--
. Desative todas as portas voltadas para o nó (não portas ISL) nos novos switches de cluster SW1 e SW2.
+
Não deve desativar as portas ISL.

+
Os comandos a seguir desativam as portas voltadas para o nó nos switches SW1 e SW2:

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*

cumulus@sw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
. Verifique se o ISL e as portas físicas no ISL entre os dois switches SN2100 SW1 e SW2 estão acima nas portas swp15 e swp16:
+
`net show interface`

+
Os comandos a seguir mostram que as portas ISL estão ativadas nos switches SW1 e SW2:

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw2 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw2 (swp16)  Master: cluster_isl(UP)

cumulus@sw2:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw1 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw1 (swp16)  Master: cluster_isl(UP)
----


--
.Cumulus Linux 5.x
--
. Desative todas as portas voltadas para o nó (não portas ISL) nos novos switches de cluster SW1 e SW2.
+
Não deve desativar as portas ISL.

+
Os comandos a seguir desativam as portas voltadas para o nó nos switches SW1 e SW2:

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state down*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*

cumulus@sw2:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state down*
cumulus@sw2:~$ *nv config apply*
cumulus@sw2:~$ *nv config save*
----
. Verifique se o ISL e as portas físicas no ISL entre os dois switches SN2100 SW1 e SW2 estão acima nas portas swp15 e swp16:
+
`nv show interface`

+
Os exemplos a seguir mostram que as portas ISL estão ativadas nos switches SW1 e SW2:

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface*

Interface     MTU    Speed  State  Remote Host  Remote Port                          Type    Summary
------------- ------ -----  ------ ------------ ------------------------------------ ------- -------
...
...
+ swp14       9216          down                                                     swp
+ swp15       9216   100G   up     ossg-rcf1    Intra-Cluster Switch ISL Port swp15  swp
+ swp16       9216   100G   up     ossg-rcf2    Intra-Cluster Switch ISL Port swp16  swp


cumulus@sw2:~$ *nv show interface*

Interface     MTU    Speed  State  Remote Host  Remote Port                          Type    Summary
------------- ------ -----  ------ ------------ ------------------------------------ ------- -------
...
...
+ swp14       9216          down                                                     swp
+ swp15       9216   100G   up     ossg-rcf1    Intra-Cluster Switch ISL Port swp15  swp
+ swp16       9216   100G   up     ossg-rcf2    Intra-Cluster Switch ISL Port swp16  swp
----


--
====
. [[step3]] Verifique se todas as portas de cluster estão ativas:
+
`network port show`

+
Cada porta deve ser exibida `up` para `Link` e saudável para `Health Status`.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show*

Node: node1

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. Verifique se todas as LIFs de cluster estão ativas e operacionais:
+
`network interface show`

+
Cada LIF de cluster deve exibir true para `Is Home` e ter um `Status Admin/Oper` de `up/up`.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. Desativar a reversão automática nos LIFs do cluster:
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   false
          node1_clus2   false
          node2_clus1   false
          node2_clus2   false

----
====
. Desconete o cabo da porta de cluster E3A no node1 e conete o E3A à porta 3 no switch de cluster SW1, usando o cabeamento apropriado suportado pelos switches SN2100.
+
O https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - interrutores"^] contém mais informações sobre cabeamento.

. Desconete o cabo da porta de cluster E3A no node2 e conete o E3A à porta 4 no switch de cluster SW1, usando o cabeamento apropriado suportado pelos switches SN2100.


[role="tabbed-block"]
====
.Cumulus Linux 4,4.x
--
. [[step8]] no switch SW1, habilite todas as portas voltadas para o nó.
+
Os comandos a seguir habilitam todas as portas voltadas para o nó no switch SW1.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----


. [[step]] no switch SW1, verifique se todas as portas estão ativas:
+
`net show interface all`

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3a)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3a)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----


--
.Cumulus Linux 5.x
--
. [[step8]] no switch SW1, habilite todas as portas voltadas para o nó.
+
Os comandos a seguir habilitam todas as portas voltadas para o nó no switch SW1.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state up*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----


. [[step9]] no switch SW1, verifique se todas as portas estão ativas:
+
`nv show interface`

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface*

Interface    State  Speed  MTU    Type      Remote Host                 Remote Port  Summary
-----------  -----  -----  -----  --------  --------------------------  -----------  ----------
...
...
swp1s0       up     10G    9216   swp       odq-a300-1a                         e0a
swp1s1       up     10G    9216   swp       odq-a300-1b                         e0a
swp1s2       down   10G    9216   swp
swp1s3       down   10G    9216   swp
swp2s0       down   25G    9216   swp
swp2s1       down   25G    9216   swp
swp2s2       down   25G    9216   swp
swp2s3       down   25G    9216   swp
swp3         down          9216   swp
swp4         down          9216   swp
...
...
swp14        down          9216   swp
swp15        up     100G   9216   swp       ossg-int-rcf10                    swp15
swp16        up     100G   9216   swp       ossg-int-rcf10                    swp16
----


--
====
. [[step10]] Verifique se todas as portas de cluster estão ativas:
+
`network port show -ipspace Cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todas as portas do cluster estão em node1 e node2:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. Exibir informações sobre o status dos nós no cluster:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir exibe informações sobre a integridade e a elegibilidade dos nós no cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

----
====
. Desconete o cabo da porta de cluster e3b no node1 e conete o e3b à porta 3 no switch de cluster SW2, usando o cabeamento apropriado suportado pelos switches SN2100.
. Desconete o cabo da porta de cluster e3b no node2 e conete o e3b à porta 4 no switch de cluster SW2, usando o cabeamento apropriado suportado pelos switches SN2100.


[role="tabbed-block"]
====
.Cumulus Linux 4,4.x
--
. [[step14]] no switch SW2, habilite todas as portas voltadas para o nó.
+
Os comandos a seguir habilitam as portas voltadas para o nó no switch SW2:

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
. [[step15]] no switch SW2, verifique se todas as portas estão ativas:
+
`net show interface all`

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3b)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3b)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----


. [[step16]] em ambos os switches SW1 e SW2, verifique se ambos os nós têm uma conexão para cada switch:
+
`net show lldp`

+
O exemplo a seguir mostra os resultados apropriados para ambos os switches SW1 e SW2:



[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3b
swp4       100G   Trunk/L2    node2              e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
--
.Cumulus Linux 5.x
--
. [[step14]] no switch SW2, habilite todas as portas voltadas para o nó.
+
Os comandos a seguir habilitam as portas voltadas para o nó no switch SW2:

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state up*
cumulus@sw2:~$ *nv config apply*
cumulus@sw2:~$ *nv config save*
----
. [[step15]] no switch SW2, verifique se todas as portas estão ativas:
+
`nv show interface`

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *nv show interface*

Interface    State  Speed  MTU    Type      Remote Host                 Remote Port  Summary
-----------  -----  -----  -----  --------  --------------------------  -----------  ----------
...
...
swp1s0       up     10G    9216   swp       odq-a300-1a                         e0a
swp1s1       up     10G    9216   swp       odq-a300-1b                         e0a
swp1s2       down   10G    9216   swp
swp1s3       down   10G    9216   swp
swp2s0       down   25G    9216   swp
swp2s1       down   25G    9216   swp
swp2s2       down   25G    9216   swp
swp2s3       down   25G    9216   swp
swp3         down          9216   swp
swp4         down          9216   swp
...
...
swp14        down          9216   swp
swp15        up     100G   9216   swp       ossg-int-rcf10                    swp15
swp16        up     100G   9216   swp       ossg-int-rcf10                    swp16
----


. [[step16]] em ambos os switches SW1 e SW2, verifique se ambos os nós têm uma conexão para cada switch:
+
`nv show interface --view=lldp`

+
Os exemplos a seguir mostram os resultados apropriados para ambos os switches SW1 e SW2:

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface --view=lldp*

Interface    Speed  Type      Remote Host                         Remote Port
-----------  -----  --------  ----------------------------------  -----------
...
...
swp1s0       10G    swp       odq-a300-1a                         e0a
swp1s1       10G    swp       odq-a300-1b                         e0a
swp1s2       10G    swp
swp1s3       10G    swp
swp2s0       25G    swp
swp2s1       25G    swp
swp2s2       25G    swp
swp2s3       25G    swp
swp3                swp
swp4                swp
...
...
swp14               swp
swp15        100G   swp       ossg-int-rcf10                      swp15
swp16        100G   swp       ossg-int-rcf10                      swp16

cumulus@sw2:~$ *nv show interface --view=lldp*

Interface    Speed  Type      Remote Host                         Remote Port
-----------  -----  --------  ----------------------------------  -----------
...
...
swp1s0       10G    swp       odq-a300-1a                         e0a
swp1s1       10G    swp       odq-a300-1b                         e0a
swp1s2       10G    swp
swp1s3       10G    swp
swp2s0       25G    swp
swp2s1       25G    swp
swp2s2       25G    swp
swp2s3       25G    swp
swp3                swp
swp4                swp
...
...
swp14               swp
swp15        100G   swp       ossg-int-rcf10                      swp15
swp16        100G   swp       ossg-int-rcf10                      swp16
----


--
====
. [[step17]] exiba informações sobre os dispositivos de rede descobertos em seu cluster:
+
`network device-discovery show -protocol lldp`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
====
. Verifique se todas as portas do cluster estão ativas:
+
`network port show -ipspace Cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todas as portas do cluster estão em node1 e node2:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

----
====




=== Etapa 3: Verifique a configuração

. Ativar a reversão automática em todas as LIFs do cluster:
+
`net interface modify -vserver Cluster -lif * -auto-revert true`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *net interface modify -vserver Cluster -lif * -auto-revert true*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
----
====
. Verifique se todas as interfaces são exibidas `true` para `Is Home`:
+
`net interface show -vserver Cluster`

+

NOTE: Isso pode levar um minuto para ser concluído.

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todos os LIFs estão em node1 e node2 e que `Is Home` os resultados são verdadeiros:

[listing, subs="+quotes"]
----
cluster1::*> *net interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true

----
====
. Verifique se as definições estão desativadas:
+
`network options switchless-cluster show`

+
.Mostrar exemplo
[%collapsible]
====
A saída falsa no exemplo a seguir mostra que as configurações estão desativadas:

[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: *false*
----
====
. Verifique o status dos membros do nó no cluster:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra informações sobre a integridade e a elegibilidade dos nós no cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Verifique a conectividade das interfaces de cluster remotas:


[role="tabbed-block"]
====
.ONTAP 9.9,1 e posterior
--
Você pode usar o `network interface check cluster-connectivity` comando para iniciar uma verificação de acessibilidade para conetividade de cluster e, em seguida, exibir os detalhes:

`network interface check cluster-connectivity start` e `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* espere alguns segundos antes de executar o `show` comando para exibir os detalhes.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todos os lançamentos do ONTAP
--
Para todas as versões do ONTAP, você também pode usar o `cluster ping-cluster -node <name>` comando para verificar a conetividade:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node1
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step6]] altere o nível de privilégio de volta para admin:
+
`set -privilege admin`

. Se você suprimiu a criação automática de casos, reative-a invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que se segue?
Depois de migrar seus switches, vocêlink:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"] .
