---
permalink: switch-nvidia-sn2100/required-documentation-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Analise a documentação necessária para instalar e manter os switches de cluster NVIDIA SN2100. 
---
= Analise os requisitos de documentação para os switches de cluster NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Analise a documentação do switch e do controlador necessária para configurar os switches de cluster NVIDIA SN2100 e configurá-los em um cluster ONTAP.

[cols="1,2"]
|===
| Título | Descrição 


 a| 
link:https://networking-docs.nvidia.com/sn2000hw/latest["Guia de Instalação do NVIDIA Switch"^]
 a| 
Este guia descreve como instalar seus switches NVIDIA SN2100.



 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580["Guia de cabeamento para gaveta de unidades NVMe NS224"^]
 a| 
Visão geral e ilustrações mostrando como configurar a cablagem para gavetas de unidades de disco.

|===


[[ontap-systems-documentation]]
== Documentação dos sistemas ONTAP

Para configurar um sistema ONTAP, você precisa dos seguintes documentos para a sua versão do sistema operacional.

[cols="1,2"]
|===
| Nome | Descrição 


 a| 
Instruções de instalação e configuração específicas do controlador
 a| 
Descreve como instalar o hardware da NetApp .



 a| 
link:https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^]
 a| 
Fornece informações detalhadas sobre todos os aspectos das versões do ONTAP .



 a| 
link:https://hwu.netapp.com/["Hardware Universe"^]
 a| 
Permite que você confirme o hardware compatível, como switches de cluster e cabos, para o modelo da sua plataforma.

|===