---
permalink: switch-nvidia-sn2100/upgrade-cl-version.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Siga os passos abaixo para atualizar sua versão do Cumulus Linux. 
---
= Atualizar versões do Cumulus Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga o procedimento abaixo para atualizar sua versão do Cumulus Linux, conforme necessário.

.Antes de começar
Certifique-se de ter o seguinte:

* Conhecimento intermediário de Linux.
* Familiaridade com edição básica de texto, permissões de arquivos UNIX e monitoramento de processos.  Diversos editores de texto vêm pré-instalados, incluindo: `vi` e `nano` .
* Acesso a um shell Linux ou UNIX.  Se você estiver usando o Windows, utilize um ambiente Linux como ferramenta de linha de comando para interagir com o Cumulus Linux.
* A taxa de transmissão (baud rate) exigida no switch de console serial para acesso ao console do switch NVIDIA SN2100 é de 115200, conforme segue:
+
** 115200 baud
** 8 bits de dados
** 1 bit de parada
** paridade: nenhuma
** Controle de fluxo: nenhum




.Sobre esta tarefa
Esteja ciente do seguinte:


NOTE: Cada vez que o Cumulus Linux é atualizado, toda a estrutura do sistema de arquivos é apagada e reconstruída.  Sua configuração atual será apagada.  Você deve salvar e registrar a configuração do seu switch antes de atualizar o Cumulus Linux.


CAUTION: A senha padrão para a conta de usuário cumulus é *cumulus*.  Na primeira vez que você fizer login no Cumulus Linux, você deverá alterar esta senha padrão.  Você deve atualizar todos os scripts de automação antes de instalar uma nova imagem.  O Cumulus Linux oferece opções de linha de comando para alterar a senha padrão automaticamente durante o processo de instalação.

Ver https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-510/Installation-Management/Installing-a-New-Cumulus-Linux-Image/["Instalando uma nova imagem do Cumulus Linux"^] Para obter mais informações.

.Passos
[role="tabbed-block"]
====
.Cumulus Linux 4.4.x para Cumulus Linux 5.4.0
--
. Conecte o switch do cluster à rede de gerenciamento.
. Utilize o comando ping para verificar a conectividade com o servidor que hospeda o Cumulus Linux e o RCF.
. Exibir as portas do cluster em cada nó que estão conectadas aos switches do cluster:
+
`network device-discovery show`

. Verifique o status administrativo e operacional de cada porta do cluster.
+
.. Verifique se todas as portas do cluster estão ativas e com status íntegro:
+
`network port show -role cluster`

.. Verifique se todas as interfaces de cluster (LIFs) estão na porta principal:
+
`network interface show -role cluster`

.. Verifique se o cluster exibe informações para ambos os switches do cluster:
+
`system cluster-switch show -is-monitoring-enabled-operational true`



. Desative a reversão automática nos LIFs do cluster.  As LIFs do cluster são transferidas para o switch do cluster parceiro em caso de failover e permanecem lá enquanto você executa o procedimento de atualização no switch de destino:
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

. Verifique a versão atual do Cumulus Linux e as portas conectadas:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show system*
Hostname......... cumulus
Build............ *Cumulus Linux 4.4.3*
Uptime........... 0:08:20.860000
Model............ Mlnx X86
CPU.............. x86_64 Intel Atom C2558 2.40GHz
Memory........... 8GB
Disk............. 14.7GB
ASIC............. Mellanox Spectrum MT52132
Ports............ 16 x 100G-QSFP28
Part Number...... MSN2100-CB2FC
Serial Number.... MT2105T05177
Platform Name.... x86_64-mlnx_x86-r0
Product Name..... MSN2100
ONIE Version..... 2019.11-5.2.0020-115200
Base MAC Address. 04:3F:72:43:92:80
Manufacturer..... Mellanox

cumulus@cumulus:mgmt:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                    Summary
-----  ------  ----  -----  ----------  ----------------------  --------------------
.
.
UP     swp1    100G  9216   Trunk/L2    node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2    node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2    SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2    SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2    SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2    SHFFG1826000102 (e0b)   Master: bridge(UP))
.
.
----
. Baixe a imagem do Cumulux Linux 5.4.0:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo onie-install -a -i http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin*
[sudo] password for cumulus:
Fetching installer: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin
Downloading URL: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin
######################################################################### 100.0%
Success: HTTP download complete.
EFI variables are not supported on this system
Warning: SecureBoot is not available.
Image is signed.
.
.
.
Staging installer image...done.
WARNING:
WARNING: Activating staged installer requested.
WARNING: This action will wipe out all system data.
WARNING: Make sure to back up your data.
WARNING:
Are you sure (y/N)? *y*
Activating staged installer...done.
Reboot required to take effect.
----
. Reinicie o switch:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. Alterar a senha:
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password:
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)

ZTP in progress. To disable, do 'ztp -d'
----
. Verifique a versão do Cumulus Linux: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
           operational    applied
---------- -------------- ----------
hostname   cumulus        cumulus
build      Cumulus Linux 5.4.0
uptime     14:07:08
timezone   Etc/UTC
----
. Alterar o nome do host:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv config apply*
Warning: The following files have been changed since the last save, and they WILL be overwritten.
- /etc/nsswitch.conf
- /etc/synced/synced.conf
.
.
----
. Saia da sessão e entre novamente no switch para ver o nome atualizado do switch no prompt:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *exit*
logout

Debian GNU/Linux 10 cumulus ttyS0

cumulus login: *cumulus*
Password:
Last login: Tue Dec 15 21:43:13 UTC 2020 on ttyS0
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)


ZTP in progress. To disable, do 'ztp -d'

cumulus@sw1:mgmt:~$
----
. Defina o endereço IP:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip address 10.231.80.206/22*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip gateway 10.231.80.1*
cumulus@sw1:mgmt:~$ *nv config apply*
applied [rev_id: 2]
cumulus@sw1:mgmt:~$ *ip route show vrf mgmt*
default via 10.231.80.1 dev eth0 proto kernel
unreachable default metric 4278198272
10.231.80.0/22 dev eth0 proto kernel scope link src 10.231.80.206
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Crie um novo usuário e adicione-o ao `sudo` grupo.  Este usuário só entra em vigor após a reinicialização da sessão de console/SSH.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. Adicione grupos de usuários adicionais para o usuário administrador acessar. `nv` comandos:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user `admin' to group `nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
Ver https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["Contas de usuário NVIDIA"^] para mais informações.



--
.Cumulus Linux 5.x para Cumulus Linux 5.4.0
--
. Conecte o switch do cluster à rede de gerenciamento.
. Utilize o comando ping para verificar a conectividade com o servidor que hospeda o Cumulus Linux e o RCF.
. Exibir as portas do cluster em cada nó que estão conectadas aos switches do cluster:
+
`network device-discovery show`

. Verifique o status administrativo e operacional de cada porta do cluster.
+
.. Verifique se todas as portas do cluster estão ativas e com status íntegro:
+
`network port show -role cluster`

.. Verifique se todas as interfaces de cluster (LIFs) estão na porta principal:
+
`network interface show -role cluster`

.. Verifique se o cluster exibe informações para ambos os switches do cluster:
+
`system cluster-switch show -is-monitoring-enabled-operational true`



. Desative a reversão automática nos LIFs do cluster.  As LIFs do cluster são transferidas para o switch do cluster parceiro em caso de failover e permanecem lá enquanto você executa o procedimento de atualização no switch de destino:
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

. Verifique a versão atual do Cumulus Linux e as portas conectadas:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv show system*
                    operational          applied
------------------- -------------------- -----------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.3.0
uptime              6 days, 8:37:36
timezone            Etc/UTC

cumulus@sw1:mgmt:~$ *nv show interface*
Interface     MTU   Speed State Remote Host         Remote Port- Type      Summary
------------- ----- ----- ----- ------------------- ------------ --------- -------------
+ cluster_isl 9216  200G  up                                      bond
+ eth0        1500  100M  up    mgmt-sw1            Eth105/1/14   eth       IP Address: 10.231.80 206/22
  eth0                                                                      IP Address: fd20:8b1e:f6ff:fe31:4a0e/64
+ lo          65536       up                                      loopback  IP Address: 127.0.0.1/8
  lo                                                                        IP Address: ::1/128
+ swp1s0      9216 10G    up cluster01                e0b         swp
.
.
.
+ swp15      9216 100G    up sw2                      swp15       swp
+ swp16      9216 100G    up sw2                      swp16       swp
----
. Baixe a imagem do Cumulux Linux 5.4.0:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin*
[sudo] password for cumulus:
Fetching installer: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin
Downloading URL: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin
######################################################################### 100.0%
Success: HTTP download complete.
EFI variables are not supported on this system
Warning: SecureBoot is not available.
Image is signed.
.
.
.
Staging installer image...done.
WARNING:
WARNING: Activating staged installer requested.
WARNING: This action will wipe out all system data.
WARNING: Make sure to back up your data.
WARNING:
Are you sure (y/N)? *y*
Activating staged installer...done.
Reboot required to take effect.
----
. Reinicie o switch:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. Alterar a senha:
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password:
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)

ZTP in progress. To disable, do 'ztp -d'
----
. Verifique a versão do Cumulus Linux: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational    applied
-------------- ----------------
hostname       cumulus cumulus
build          Cumulus Linux 5.4.0
uptime         14:07:08
timezone       Etc/UTC
----
. Alterar o nome do host:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv config apply*
Warning: The following files have been changed since the last save, and they WILL be overwritten.
- /etc/nsswitch.conf
- /etc/synced/synced.conf
.
.
----
. Saia da sessão e entre novamente no switch para ver o nome atualizado do switch no prompt:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *exit*
logout

Debian GNU/Linux 10 cumulus ttyS0

cumulus login: *cumulus*
Password:
Last login: Tue Dec 15 21:43:13 UTC 2020 on ttyS0
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)


ZTP in progress. To disable, do 'ztp -d'

cumulus@sw1:mgmt:~$
----
. Defina o endereço IP:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv unset interface eth0 ip address dhcp*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip address 10.231.80.206/22*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip gateway 10.231.80.1*
cumulus@sw1:mgmt:~$ *nv config apply*
applied [rev_id: 2]
cumulus@sw1:mgmt:~$ *ip route show vrf mgmt*
default via 10.231.80.1 dev eth0 proto kernel
unreachable default metric 4278198272
10.231.80.0/22 dev eth0 proto kernel scope link src 10.231.80.206
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. Crie um novo usuário e adicione-o ao `sudo` grupo.  Este usuário só entra em vigor após a reinicialização da sessão de console/SSH.
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. Adicione grupos de usuários adicionais para o usuário administrador acessar. `nv` comandos:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user `admin' to group `nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
Ver https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["Contas de usuário NVIDIA"^] para mais informações.



--
.Cumulus Linux 5.4.0 para Cumulus Linux 5.11.0
--
. Conecte o switch do cluster à rede de gerenciamento.
. Utilize o comando ping para verificar a conectividade com o servidor que hospeda o Cumulus Linux e o RCF.
. Exibir as portas do cluster em cada nó que estão conectadas aos switches do cluster:
+
`network device-discovery show`

. Verifique o status administrativo e operacional de cada porta do cluster.
+
.. Verifique se todas as portas do cluster estão ativas e com status íntegro:
+
`network port show -role cluster`

.. Verifique se todas as interfaces de cluster (LIFs) estão na porta principal:
+
`network interface show -role cluster`

.. Verifique se o cluster exibe informações para ambos os switches do cluster:
+
`system cluster-switch show -is-monitoring-enabled-operational true`



. Desative a reversão automática nos LIFs do cluster.  As LIFs do cluster são transferidas para o switch do cluster parceiro em caso de failover e permanecem lá enquanto você executa o procedimento de atualização no switch de destino:
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

. Verifique a versão atual do Cumulus Linux e as portas conectadas:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv show system*
                    operational          applied
------------------- -------------------- -----------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0
uptime              6 days, 8:37:36
timezone            Etc/UTC

cumulus@sw1:mgmt:~$ *nv show interface*
Interface     MTU   Speed State Remote Host         Remote Port- Type      Summary
------------- ----- ----- ----- ------------------- ------------ --------- -------------
+ cluster_isl 9216  200G  up                                      bond
+ eth0        1500  100M  up    mgmt-sw1            Eth105/1/14   eth       IP Address: 10.231.80 206/22
  eth0                                                                      IP Address: fd20:8b1e:f6ff:fe31:4a0e/64
+ lo          65536       up                                      loopback  IP Address: 127.0.0.1/8
  lo                                                                        IP Address: ::1/128
+ swp1s0      9216 10G    up cluster01                e0b         swp
.
.
.
+ swp15      9216 100G    up sw2                      swp15       swp
+ swp16      9216 100G    up sw2                      swp16       swp
----
. Baixe a imagem do Cumulux Linux 5.11.0:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<ip-to-webserver>_/path/to/cumulus-linux-5.11.0-mlx-amd64.bin*
[sudo] password for cumulus:
Fetching installer: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.11.0-mlx-amd64.bin
Downloading URL: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.11.0-mlx-amd64.bin
######################################################################### 100.0%
Success: HTTP download complete.
EFI variables are not supported on this system
Warning: SecureBoot is not available.
Image is signed.
.
.
.
Staging installer image...done.
WARNING:
WARNING: Activating staged installer requested.
WARNING: This action will wipe out all system data.
WARNING: Make sure to back up your data.
WARNING:
Are you sure (y/N)? *y*
Activating staged installer...done.
Reboot required to take effect.
----
. Reinicie o switch:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. Alterar a senha:
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password:
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
Linux cumulus 5.11.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)

ZTP in progress. To disable, do 'ztp -d'
----
. Verifique a versão do Cumulus Linux: `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational    applied
-------------- ----------------
hostname       cumulus cumulus
build          Cumulus Linux 5.11.0
uptime         14:07:08
timezone       Etc/UTC
----
. Alterar o nome do host:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv config apply*
Warning: The following files have been changed since the last save, and they WILL be overwritten.
- /etc/nsswitch.conf
- /etc/synced/synced.conf
.
.
----
. Saia da sessão e entre novamente no switch para ver o nome atualizado do switch no prompt:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *exit*
logout

Debian GNU/Linux 10 cumulus ttyS0

cumulus login: *cumulus*
Password:
Last login: Tue Dec 15 21:43:13 UTC 2020 on ttyS0
Linux cumulus 5.11.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)


ZTP in progress. To disable, do 'ztp -d'

cumulus@sw1:mgmt:~$
----
. Defina o endereço IP:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv unset interface eth0 ip address dhcp*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip address 10.231.80.206/22*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip gateway 10.231.80.1*
cumulus@sw1:mgmt:~$ *nv config apply*
applied [rev_id: 2]
cumulus@sw1:mgmt:~$ *ip route show vrf mgmt*
default via 10.231.80.1 dev eth0 proto kernel
unreachable default metric 4278198272
10.231.80.0/22 dev eth0 proto kernel scope link src 10.231.80.206
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----


--
====
.O que vem a seguir?
Após atualizar sua versão do Cumulus Linux, você poderálink:install-rcf-sn2100-cluster.html["Instalar ou atualizar o script RCF"] .
