---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-storage/components-9336c-storage.html 
keywords: shared storage cluster switch 
summary: A partir do ONTAP 9.9.1, você pode usar switches Cisco Nexus 9336C-FX2 para combinar funcionalidades de armazenamento e cluster em um cenário de switch compartilhado. 
---
= Componentes e números de peça para switches de armazenamento Cisco Nexus 9336C-FX2 e 9336C-FX2-T
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para instalação e manutenção dos switches de armazenamento Cisco Nexus 9336C-FX2 e 9336C-FX2-T, certifique-se de consultar a lista de componentes e números de peça.

A tabela a seguir lista o número da peça e a descrição dos switches de armazenamento 9336C-FX2 e 9336C-FX2-T, ventiladores e fontes de alimentação:

[cols="1,2"]
|===
| Número da peça | Descrição 


 a| 
X190200-CS-PE
 a| 
Chave seletora de cluster, N9336C 36Pt PTSX 10/25/40/100G



 a| 
X190200-CS-PI
 a| 
Cluster Switch, N9336C 36Pt PSIN 10/25/40/100G



 a| 
X190212-CS-PE
 a| 
Chave seletora de cluster, N9336C 12Pt (9336C-FX2-T) PTSX 10/25/40/100G



 a| 
X190212-CS-PI
 a| 
Chave seletora de cluster, N9336C 12Pt (9336C-FX2-T) PSIN 10/25/40/100G



 a| 
SW-N9K-FX2-24P-UPG
 a| 
SW, Licença Cisco 9336CFX2 POD de 24 portas



 a| 
X190210-FE-PE
 a| 
N9K-9336C, FTE, PTSX, 36PT 10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C, FTE, PSIN, 36PT 10/25/40/100GQSFP28



 a| 
X190002
 a| 
Kit de acessórios X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
Fonte de alimentação N9K-9336C AC 1100W - Fluxo de ar de exaustão lateral



 a| 
X-NXA-PAC-1100W-PI2
 a| 
Fonte de alimentação N9K-9336C AC 1100W - Fluxo de ar de entrada pelo lado da porta



 a| 
X-NXA-FAN-65CFM-PE
 a| 
N9K-9336C 65 CFM, fluxo de ar de exaustão do lado esquerdo



 a| 
X-NXA-FAN-65CFM-PI
 a| 
N9K-9336C 65 CFM, fluxo de ar de admissão pelo lado esquerdo

|===


== Licenças Cisco Smart somente para portas 9336C-FX2-T

Para ativar mais de 12 portas no seu switch de armazenamento Cisco Nexus 9336C-FX-T, você precisa adquirir uma licença Cisco Smart.  As licenças Cisco Smart são gerenciadas por meio de contas Cisco Smart.

. Crie uma nova conta Smart, se necessário. Ver https://id.cisco.com/signin/register["Crie uma nova conta Smart"^] para mais detalhes.
. Solicitar acesso a uma conta Smart existente. Ver https://id.cisco.com/oauth2/default/v1/authorize?response_type=code&scope=openid%20profile%20address%20offline_access%20cci_coimemberOf%20email&client_id=cae-okta-web-gslb-01&state=s2wvKDiBja__7ylXonWrq8w-FAA&redirect_uri=https%3A%2F%2Frpfa.cloudapps.cisco.com%2Fcb%2Fsso&nonce=qO6s3cZE5ZdhC8UKMEfgE6fbu3mvDJ8PTw5jYOp6z30["Solicitar acesso a uma conta Smart existente"^] para mais detalhes.



NOTE: Após adquirir sua licença Smart, instale o RCF apropriado para habilitar e configurar todas as 36 portas disponíveis para uso.

.O que vem a seguir
Após confirmar os componentes e os números de peça, você pode revisar o link:required-documentation-9336c-storage.html["documentação necessária"].
