---
permalink: switch-cisco-9336c-fx2-storage/configure-switch-overview-9336c-storage.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Visão geral da instalação e configuração para switches de armazenamento Cisco Nexus 9336C-FX2 
---
= Visão geral da instalação e configuração para switches de armazenamento Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O switch Cisco Nexus 9336C-FX2 faz parte da plataforma Cisco Nexus 9000 e pode ser instalado em um gabinete de sistema NetApp. O Nexus 9336C-FX2 é um switch Ethernet que permite alternar dados entre controladores e compartimentos de disco.



== Visão geral da configuração inicial

Para configurar inicialmente um switch Cisco Nexus 9336C-FX2 em sistemas que executam o ONTAP, siga estas etapas:

. link:setup-worksheet-9336c-storage.html["Folha de cálculo de cablagem completa"].
+
A Planilha de exemplo de cabeamento fornece exemplos de atribuições de portas recomendadas dos switches para os controladores. A Planilha em branco fornece um modelo que você pode usar na configuração do cluster.

. link:install-9336c-storage.html["Instale o interrutor"].
+
Configure o hardware do switch.

. link:setup-switch-9336c-storage.html["Configure o interrutor"].
+
Configure o switch de armazenamento Cisco Nexus 9336C-FX2.

. link:install-switch-and-passthrough-panel-9336c-storage.html["Instale o interrutor em um gabinete NetApp"].
+
Dependendo de sua configuração, você pode instalar o switch Cisco Nexus 9336C-FX2 e o painel pass-through em um gabinete NetApp com os suportes padrão que estão incluídos com o switch.

. link:install-nxos-overview-9336c-storage.html["Prepare-se para instalar ou atualizar NX-os e RCF"].
+
Siga os procedimentos preliminares em preparação para a instalação do software Cisco NX-os e arquivos de configuração de referência (RCFs).

. link:install-nxos-software-9336c-storage.html["Instale ou atualize o software NX-os"].
+
Instale ou atualize o software NX-os no switch de armazenamento Nexus 9336C-FX2.

. link:install-rcf-software-9336c-storage.html["Instale ou atualize o arquivo de configuração do RCF"].
+
Instale ou atualize o RCF depois de configurar o switch Nexus 9336C-FX2 pela primeira vez. Você também pode usar este procedimento para atualizar sua versão RCF.





== Informações adicionais

Antes de iniciar a instalação ou manutenção, certifique-se de rever o seguinte:

* link:configure-reqs-9336c-storage.html["Requisitos de configuração"]
* link:components-9336c-storage.html["Componentes e números de peça"]
* link:required-documentation-9336c-storage.html["Documentação necessária"]
* link:smart-call-9336c-storage.html["Requisitos para Smart Call Home"]

