---
permalink: switch-cisco-9336c-fx2-storage/configure-software-overview-9336c-storage.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Visão geral da configuração de software para switches de storage Cisco Nexus 9336C-FX2 
---
= Fluxo de trabalho de instalação de software para switches de storage Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar e configurar o software para um switch de storage Cisco Nexus 9336C-FX2, siga estas etapas:

. link:install-nxos-overview-9336c-storage.html["Prepare-se para instalar ou atualizar NX-os e RCF"].
+
O software Cisco NX-os e os arquivos de configuração de referência (RCFs) devem ser instalados nos switches de armazenamento Cisco Nexus 9336C-FX2.

. link:install-nxos-software-9336c-storage.html["Instale ou atualize o software NX-os"].
+
Baixe e instale ou atualize o software NX-os no switch de armazenamento Cisco Nexus 9336C-FX2.

. link:install-rcf-software-9336c-storage.html["Instale ou atualize o arquivo de configuração do RCF"].
+
Instale ou atualize o RCF depois de configurar o switch de armazenamento Cisco Nexus 9336C-FX2 pela primeira vez. Você também pode usar este procedimento para atualizar sua versão RCF.


