---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-storage/configure-reqs-9336c-storage.html 
keywords: shared storage cluster switch 
summary: Revise os requisitos de versão do ONTAP e NX-OS e as configurações compatíveis para os switches de storage Cisco Nexus 9336C-FX2 e 9336C-FX2-T antes da instalação. 
---
= Analise os requisitos de configuração para os switches de storage Cisco Nexus 9336C-FX2 e 9336C-FX2-T
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Revise os requisitos de versão do ONTAP e do NX-OS e as configurações suportadas para os switches de storage Cisco Nexus 9336C-FX2 e 9336C-FX2-T antes da instalação ou atualização.



[[configuration-requirements]]
== Requisitos de configuração

Para a configuração, você precisa da quantidade e do tipo adequados de cabos e conectores de cabos para seus switches.

Dependendo do tipo de switch que você estiver configurando inicialmente, será necessário conectar-se à porta de console do switch com o cabo de console incluído; você também precisará fornecer informações específicas da rede.



[[network-requirements]]
== Requisitos de rede

Você precisa das seguintes informações de rede para todas as configurações de switch.

* Sub-rede IP para tráfego de rede de gerenciamento
* Nomes de host e endereços IP para cada um dos controladores do sistema de armazenamento e todos os switches aplicáveis
* A maioria dos controladores de sistema de armazenamento são gerenciados por meio da interface e0M, conectando-se à porta de serviço Ethernet (ícone de chave inglesa). Nos sistemas AFF A800 e AFF A700s , a interface e0M utiliza uma porta Ethernet dedicada.
* Consulte o link:https://hwu.netapp.com["Hardware Universe"^] para obter as informações mais recentes.


Para obter mais informações sobre a configuração inicial do seu switch, consulte o seguinte: link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Guia de Instalação e Atualização do Cisco Nexus 9336C-FX2"].

.O que vem a seguir
Após analisar os requisitos de configuração, você poderá confirmar sua solicitação. link:components-9336c-storage.html["componentes e números de peças"].
