---
permalink: switch-cisco-9336c-fx2/index.html 
sidebar: sidebar 
keywords: cisco, switch, cisco 9336 switch 
summary: 'Interrutores Cisco 9336-FX2"' 
---
= Visão geral e requisitos: Switches Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalação e manutenção do switch Cisco Nexus 9336C-FX2, certifique-se de revisar os requisitos de configuração e os requisitos de documentação.

Se você quiser criar clusters do ONTAP com mais de dois nós, precisará de dois switches de rede de cluster compatíveis. Você pode usar switches de gerenciamento adicionais, que são opcionais.

Você pode instalar o switch Cisco Nexus 9336C-FX2 (X190200/X190210) em um gabinete de sistema NetApp ou gabinete de terceiros com os suportes padrão que estão incluídos com o switch.



== Componentes do interrutor

A tabela a seguir lista o número de peça e a descrição do interrutor 9336C-FX2, ventiladores e fontes de alimentação:

[cols="1,2"]
|===
| Número de peça | Descrição 


 a| 
X190200-CS-PE
 a| 
N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190200-CS-PI
 a| 
N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PE
 a| 
N9K-9336C, FTE, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C, FTE, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190002
 a| 
Kit de acessórios X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
N9K-9336CA AC 1100W PSU - fluxo de ar do escape lateral da porta



 a| 
X-NXA-PAC-1100W-PI2
 a| 
N9K-9336CA AC 1100W PSU - fluxo de ar de entrada lateral da porta



 a| 
X-NXA-FAN-65CFM-PE
 a| 
N9K-9336C 65CFM, fluxo de ar do escape lateral da porta



 a| 
X-NXA-FAN-65CFM-PI
 a| 
N9K-9336C 65CFM, fluxo de ar de admissão do lado da porta

|===


== Requisitos de configuração

Para configurar o cluster, é necessário o número e o tipo apropriados de cabos e conetores de cabos para os switches. Dependendo do tipo de switch que você está configurando inicialmente, você precisa se conetar à porta do console do switch com o cabo de console incluído; você também precisa fornecer informações específicas de rede.



== Requisitos de rede

Você precisa das seguintes informações de rede para todas as configurações de switch:

* Sub-rede IP para o tráfego de rede de gerenciamento
* Nomes de host e endereços IP para cada um dos controladores do sistema de storage e todos os switches aplicáveis
* A maioria dos controladores do sistema de storage é gerenciada por meio da interface e0M, conetando-se à porta de serviço Ethernet (ícone de chave inglesa). Nos sistemas AFF A800 e AFF A700, a interface e0M utiliza uma porta Ethernet dedicada.


Consulte a https://hwu.netapp.com["Hardware Universe"^] para obter informações mais recentes.



== Requisitos para Smart Call Home

Smart Call Home monitora os componentes de hardware e software em sua rede, para gerar uma notificação baseada em e-mail sobre as condições críticas do sistema. Quando ocorre um evento no seu dispositivo, o Smart Call Home emite um alerta para todos os destinatários configurados no seu perfil de destino.

Você deve configurar um switch de rede de cluster para se comunicar usando e-mail com o sistema Smart Call Home. Opcionalmente, você pode configurar seu switch de rede de cluster para aproveitar o recurso de suporte de chamada inteligente incorporado do Cisco.

Antes de poder utilizar a funcionalidade Smart Call Home, tem de estar ciente das seguintes considerações:

* Um servidor de e-mail deve estar no lugar.
* O switch deve ter conetividade IP com o servidor de e-mail.
* É necessário configurar o nome do contacto (contacto do servidor SNMP), o número de telefone e as informações do endereço da rua. Isso é necessário para determinar a origem das mensagens recebidas.
* Um ID de CCO deve ser associado a um contrato de serviço Cisco SMARTnet apropriado para a sua empresa.
* O Serviço SMARTnet da Cisco deve estar em vigor para que o dispositivo seja registrado.


O http://www.cisco.com/c/en/us/products/switches/index.html["Site de suporte da Cisco"^] contém informações sobre os comandos para configurar Smart Call Home.



== Requisitos de documentação

Você precisa de documentação específica de switch e controlador para configurar seus switches Cisco 9336-FX2 e cluster ONTAP.



=== Documentação do switch

Para configurar os switches Cisco Nexus 9336C-FX2, você precisa da seguinte documentação na https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Suporte para switches Cisco Nexus 9000 Series"^] página:

[cols="1,2"]
|===
| Título do documento | Descrição 


 a| 
_Guia de Instalação de hardware da Série Nexus 9000_
 a| 
Fornece informações detalhadas sobre os requisitos do local, detalhes do hardware do switch e opções de instalação.



 a| 
_Guias de configuração do software de comutador da série Cisco Nexus 9000_ (escolha o guia para a versão NX-os instalada em seus switches)
 a| 
Fornece informações de configuração inicial do switch que você precisa antes de configurar o switch para operação ONTAP.



 a| 
_Guia de atualização e downgrade do software NX-os da série Cisco Nexus 9000_ (escolha o guia para a versão NX-os instalada em seus switches)
 a| 
Fornece informações sobre como fazer downgrade do switch para o software de switch suportado pelo ONTAP, se necessário.



 a| 
_Cisco Nexus 9000 Series NX-os Guia de Referência de comando_
 a| 
Fornece links para as várias referências de comando fornecidas pelo Cisco.



 a| 
_Cisco Nexus 9000 MIBs Referência_
 a| 
Descreve os arquivos MIB (Management Information base) para os switches Nexus 9000.



 a| 
_Nexus 9000 Series NX-os System Message Reference_
 a| 
Descreve as mensagens do sistema para os switches da série Cisco Nexus 9000, aqueles que são informativos e outros que podem ajudar a diagnosticar problemas com links, hardware interno ou software do sistema.



 a| 
_Notas de lançamento do Cisco Nexus 9000 Series NX-os (escolha as notas para a versão NX-os instalada em seus switches)_
 a| 
Descreve os recursos, bugs e limitações do Cisco Nexus 9000 Series.



 a| 
Conformidade regulamentar e informações de segurança para a série Cisco Nexus 9000
 a| 
Fornece informações legais, de conformidade, segurança e conformidade de agências internacionais para os switches da série Nexus 9000.

|===


=== Documentação de sistemas ONTAP

Para configurar um sistema ONTAP, você precisa dos seguintes documentos para a sua versão do sistema operacional a partir do https://docs.netapp.com/ontap-9/index.jsp["Centro de Documentação do ONTAP 9"^].

[cols="1,2"]
|===
| Nome | Descrição 


 a| 
_Instruções de instalação e configuração específicas do controlador_
 a| 
Descreve como instalar hardware NetApp.



 a| 
Documentação do ONTAP
 a| 
Fornece informações detalhadas sobre todos os aspetos das versões do ONTAP.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fornece informações de compatibilidade e configuração de hardware NetApp.

|===


=== Kit de trilho e documentação do gabinete

Para instalar um switch Cisco 9336-FX2 em um gabinete NetApp, consulte a documentação de hardware a seguir.

[cols="1,2"]
|===
| Nome | Descrição 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Armário do sistema 42U, guia profundo"^]
 a| 
Descreve as FRUs associadas ao gabinete do sistema 42U e fornece instruções de manutenção e substituição da FRU.



 a| 
link:install-switch-and-passthrough-panel.html["Instale um switch Cisco 9336-FX2 em um gabinete NetApp"^]
 a| 
Descreve como instalar um switch Cisco Nexus 9336C-FX2 em um gabinete NetApp de quatro colunas.

|===