---
permalink: switch-cisco-9336c-fx2-storage/install-nxos-overview-9336c-storage.html 
sidebar: sidebar 
keywords: cisco, nx-os, software, reference, configuration, file, rcf, install, fx2, cluster, switch, install nx-os software and rcfs on cisco nexus 9336-fx2 cluster switches - cisco nexus 9336x-fx2 
summary: 'O software Cisco NX-OS e os arquivos de configuração de referência \(RCFs\) devem ser instalados nos switches de cluster Cisco Nexus 9336C-FX2.' 
---
= Prepare-se para instalar ou atualizar o software NX-OS e o RCF.
:allow-uri-read: 


[role="lead"]
Antes de instalar o software NX-OS e o Arquivo de Configuração de Referência (RCF), siga este procedimento.

.Sobre os exemplos
Os exemplos neste procedimento utilizam a seguinte nomenclatura de interruptor e nó:

* Os nomes dos dois switches Cisco são s1 e s2.
* Os nomes dos nós são cluster1-01 e cluster1-02.


.Sobre esta tarefa
O procedimento requer o uso de comandos ONTAP e comandos dos switches Cisco Nexus série 9000; os comandos ONTAP são usados ​​a menos que indicado de outra forma.

.Passos
. Se AutoSupport estiver ativado, suprima a criação automática de casos enviando uma mensagem AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=xh`
+
onde x representa a duração do período de manutenção em horas.

+

NOTE: A mensagem do AutoSupport notifica o suporte técnico sobre essa tarefa de manutenção, de forma que a criação automática de chamados seja suprimida durante o período de manutenção.

. Altere o nível de privilégio para avançado, digitando *y* quando solicitado a continuar:
+
[source, cli]
----
set -privilege advanced
----
+
O prompt avançado(`*>` ) aparece.

. Exibir quantas interfaces estão configuradas em cada nó para cada switch:
+
[source, cli]
----
network device-discovery show -protocol lldp
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/lldp
            e5a    s1                        Eth1/2            N9K-C9336C
            e3b    s2                        Eth1/2            N9K-C9336C
cluster1-01/lldp
            e5a    s1                        Eth1/1            N9K-C9336C
            e3b    s2                        Eth1/1            N9K-C9336C
.
.
----
====
. Verifique o status administrativo ou operacional de cada porta de storage do nó e de cada porta de storage shelf.
+
.. Exiba os atributos da porta de storage do nó:
+
[source, cli]
----
storage port show
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -

.
.
----
====
.. Exiba os atributos da porta da prateleira de storage:
+
[source, cli]
----
storage shelf port show
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verifique se o monitoramento de integridade do switch (CSHM) está ativado para o switch para que os switches sejam monitorados:
+
[source, cli]
----
system switch ethernet show
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N9K-C9336C-FX2
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====




.O que vem a seguir?
Após preparar a instalação do software NX-OS e do RCF, você pode link:install-nxos-software-9336c-storage.html["instalar ou atualizar o software NX-OS"].
