---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Caso ainda não possua as informações de configuração e a documentação necessárias, você precisa reuni-las antes de configurar seu cluster e os switches da rede de gerenciamento. 
---
= Instalar os switches de armazenamento 9336C-FX2 e 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para instalar os switches de armazenamento Cisco Nexus 9336C-FX2 e 9336C-FX2-T.

.Antes de começar
Certifique-se de ter o seguinte:

* Acesso a um servidor HTTP, FTP ou TFTP no local de instalação para baixar as versões aplicáveis do NX-OS e do arquivo de configuração de referência (RCF).
* Versão aplicável do NX-OS, baixada de https://software.cisco.com/download/home["Download do software Cisco"^] página.
* Licenças aplicáveis, informações de rede e configuração, e cabos.
* Concluídolink:setup-worksheet-9336c-storage.html["Folhas de exercícios de cabeamento"] .
* Os RCFs aplicáveis ​​para rede de cluster e rede de gerenciamento da NetApp foram baixados do site de suporte da NetApp em http://mysupport.netapp.com/["meusuporte.netapp.com"^] .  Todos os switches de rede de cluster e de gerenciamento da Cisco são entregues com a configuração padrão de fábrica da Cisco . Esses switches também têm a versão atual do software NX-OS, mas não têm os RCFs carregados.
* Documentação necessária para o interruptor. Verlink:required-documentation-9336c-storage.html["Documentação necessária"] para mais informações.


.Passos
. Instale os switches e controladores da rede de cluster e da rede de gerenciamento no rack.
+
[cols="1,2"]
|===
| Se você estiver instalando seu... | Então... 


 a| 
Cisco Nexus 9336C-FX2 em um gabinete de sistema NetApp
 a| 
Verlink:install-switch-and-passthrough-panel-9336c-storage.html["Instalar switch em rack NetApp"] Para obter instruções sobre como instalar o switch em um gabinete NetApp .



 a| 
Equipamentos em um rack de telecomunicações
 a| 
Consulte os procedimentos fornecidos nos guias de instalação de hardware do switch e nas instruções de instalação e configuração da NetApp .

|===
. Conecte os switches da rede do cluster e da rede de gerenciamento aos controladores usando as planilhas de cabeamento preenchidas.
. Ligue os switches e controladores da rede do cluster e da rede de gerenciamento.


.O que vem a seguir?
Opcionalmente, você pode link:install-switch-and-passthrough-panel-9336c-storage.html["instalar um switch Cisco Nexus 9336C-FX2 em um gabinete NetApp"]. Caso contrário, acesse link:setup-switch-9336c-storage.html["configurar o switch"].
