---
permalink: switch-cisco-9336c-fx2-storage/install-upgrade-rcf-overview-9336c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2 
summary: Você pode instalar o RCF após configurar o switch Nexus 9336C-FX2 pela primeira vez. Você também pode usar este procedimento para atualizar sua versão do RCF. 
---
= Instale ou atualize a visão geral do ficheiro de configuração de referência (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você instala o Arquivo de Configuração de Referência (RCF) após configurar o switch de armazenamento Nexus 9336C-FX2 pela primeira vez. Você atualiza sua versão RCF quando tem uma versão existente do arquivo RCF instalada no seu switch.

Consulte o artigo da base de dados de Conhecimento link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração em um switch de interconexão Cisco, mantendo a conetividade remota"^]para obter mais informações ao instalar ou atualizar o RCF.

.Configurações RCF disponíveis
A tabela a seguir descreve os RCFs disponíveis para diferentes configurações. Escolha o RCF aplicável à sua configuração.

Para obter detalhes específicos de uso de porta e VLAN, consulte a seção banner e notas importantes no RCF.

[cols="1,2"]
|===
| Nome RCF | Descrição 


 a| 
2-Cluster-HA-Breakout
 a| 
É compatível com dois clusters de ONTAP com pelo menos oito nós, incluindo nós que usam portas de cluster compartilhado.



 a| 
4-Cluster-HA-Breakout
 a| 
Dá suporte a quatro clusters ONTAP com pelo menos quatro nós, incluindo nós que usam portas de cluster compartilhado de alta disponibilidade.



 a| 
1-cluster-HA
 a| 
Todas as portas são configuradas para 40/100GbE. Suporta tráfego compartilhado de cluster/HA em portas. Necessário para sistemas AFF A320, AFF A250 e FAS500f. Além disso, todas as portas podem ser usadas como portas de cluster dedicadas.



 a| 
1-Cluster-HA-Breakout
 a| 
As portas são configuradas para conexões de 4x10GbE, conexões de 4x25GbE (RCF 1,6 em switches 100GbE) e 40/100GbE. Dá suporte ao tráfego compartilhado de cluster/HA em portas para nós que usam portas compartilhadas de cluster/HA: Sistemas AFF A320, AFF A250 e FAS500f. Além disso, todas as portas podem ser usadas como portas de cluster dedicadas.



 a| 
Cluster-HA-Storage
 a| 
As portas estão configuradas para 40/100GbE para Cluster+HA, 4x10GbE breakout para Cluster e 4x25GbE breakout para Cluster+HA, e 100GbE para cada par de armazenamento HA.



 a| 
Cluster
 a| 
Duas versões do RCF com diferentes alocações de portas 4x10GbE (breakout) e portas 40/100GbE.  Todos os nós FAS e AFF são suportados, exceto os sistemas AFF A320, AFF A250 e FAS500f .



 a| 
Armazenamento
 a| 
Todas as portas são configuradas para 100GbE conexões de storage NVMe.

|===
.Documentação sugerida
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco"^]
+
Consulte a tabela de compatibilidade de switch para ver as versões ONTAP e RCF suportadas no site de suporte da NetApp. Note que pode haver dependências de comando entre a sintaxe de comando no RCF e a sintaxe encontrada em versões específicas do NX-os.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Switches Cisco Nexus 9000 Series"^]
+
Consulte os guias de software e atualização apropriados disponíveis no site da Cisco para obter a documentação completa sobre os procedimentos de atualização e downgrade do switch Cisco.



.Sobre os exemplos
Os exemplos deste procedimento utilizam a seguinte nomenclatura de switch e nó:

* Os nomes dos dois switches Cisco são CS1 e CS2.
* Os nomes dos nós são node1-01, node1-02, node1-03 e node1-04.
* Os nomes do LIF do cluster são node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 e node1-04_clus2.
* O `cluster1::*>` prompt indica o nome do cluster.


Veja o https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para verificar as portas corretas na sua plataforma.


NOTE: As saídas de comando podem variar dependendo de diferentes versões do ONTAP.

.Comandos utilizados
O procedimento requer o uso de comandos ONTAP e comandos Cisco Nexus 9000 Series switches; os comandos ONTAP são usados, a menos que indicado de outra forma.

.O que se segue?
Após revisar o procedimento de instalação ou atualização do RCF, você podelink:install-rcf-software-9336c-storage.html["instalar o RCF"] oulink:upgrade-rcf-software-9336c-storage.html["atualize seu RCF"] Conforme necessário.
