---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: Se você ainda não tiver as informações e a documentação de configuração necessárias, precisará coletar essas informações antes de configurar o cluster e os switches de rede de gerenciamento. 
---
= Instale o interrutor de armazenamento 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para instalar o switch de storage Cisco Nexus 9336C-FX2.

.O que você vai precisar
* Acesso a um servidor HTTP, FTP ou TFTP no site de instalação para baixar as versões de NX-os e arquivo de configuração de referência (RCF) aplicáveis.
* Versão NX-os aplicável, transferida a partir da https://software.cisco.com/download/home["Transferência do software Cisco"^] página.
* Licenças aplicáveis, informações de rede e configuração e cabos.
* link:setup-worksheet-9336c-storage.html["fichas de trabalho de cablagem"]Concluído .
* RCFs de rede de cluster e rede de gerenciamento NetApp aplicáveis baixados do site de suporte da NetApp em http://mysupport.netapp.com/["mysupport.NetApp.com"^]. Todos os switches de rede e rede de gerenciamento de cluster Cisco chegam com a configuração padrão de fábrica do Cisco. Esses switches também têm a versão atual do software NX-os, mas não têm os RCFs carregados.
* Documentação necessária do interrutor. Consulte link:required-documentation-9336c-storage.html["Documentação necessária"] para obter mais informações.


.Passos
. Coloque em rack os switches e controladores de rede de gerenciamento e rede de cluster.
+
[cols="1,2"]
|===
| Se você está instalando o seu... | Então... 


 a| 
Cisco Nexus 9336C-FX2 em um gabinete de sistema NetApp
 a| 
Consulte link:install-switch-and-passthrough-panel-9336c-storage.html["Instale o interrutor no gabinete do NetApp"] para obter instruções sobre como instalar o switch em um gabinete NetApp.



 a| 
Equipamento em um rack Telco
 a| 
Consulte os procedimentos fornecidos nos guias de instalação do hardware do switch e nas instruções de instalação e configuração do NetApp.

|===
. Faça o cabeamento dos switches de rede e rede de gerenciamento do cluster para os controladores usando as planilhas de cabeamento concluídas.
. Ligue a rede do cluster e os controladores e switches de rede de gerenciamento.


.O que se segue?
Vá para link:setup-switch-9336c-storage.html["Configurar o switch de storage Cisco Nexus 9336C-FX2"].
