---
permalink: switch-cisco-9336c-fx2-storage/install-rcf-software-9336c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches, storage 
summary: Você pode instalar o RCF depois de configurar o switch de armazenamento Nexus 9336C-FX2 pela primeira vez. Você também pode usar este procedimento para atualizar sua versão RCF. 
---
= Instale ou atualize o ficheiro de configuração de referência
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você instala o arquivo de configuração de referência (RCF) após configurar os switches de armazenamento Nexus 9336C-FX2 e 9336C-FX2-T pela primeira vez.

Consulte o artigo da base de dados de Conhecimento link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração em um switch de interconexão Cisco, mantendo a conetividade remota"^]para obter mais informações ao instalar o RCF.

.Antes de começar
Verifique as seguintes instalações e conexões:

* Uma ligação de consola ao interrutor. A conexão do console é opcional se você tiver acesso remoto ao switch.
* O switch CS1 e o switch CS2 são ativados e a configuração inicial do switch está concluída (o endereço IP de gerenciamento e o SSH estão configurados).
* A versão NX-os pretendida foi instalada.
* As portas do cluster de nós do ONTAP não estão conetadas.




== Passo 1: Instale o RCF nos interrutores

. Faça login no switch CS1 usando SSH ou usando um console serial.
. Copie o RCF para o flash de inicialização do switch CS1 usando um dos seguintes protocolos de transferência: FTP, TFTP, SFTP ou SCP.
+
Para obter mais informações sobre comandos Cisco, consulte o guia apropriado no https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Referência de comando Cisco Nexus 9000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
Este exemplo mostra TFTP sendo usado para copiar um RCF para o flash de inicialização no switch CS1:

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *Nexus_9336C_RCF_v1.6-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Aplique o RCF baixado anteriormente ao flash de inicialização.
+
Para obter mais informações sobre comandos Cisco, consulte o guia apropriado no https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Referência de comando Cisco Nexus 9000 Series NX-os"^].

+
.Mostrar exemplo
[%collapsible]
====
Este exemplo mostra o RCF `Nexus_9336C_RCF_v1.6-Storage.txt` a ser instalado no interrutor CS1:

[listing]
----
cs1# copy Nexus_9336C_RCF_v1.6-Storage.txt running-config echo-commands
----
====
. Examine a saída do banner a partir do `show banner motd` comando. Deve ler e seguir estas instruções para garantir a configuração e funcionamento corretos do interrutor.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch    : Nexus N9K-C9336C-FX2
* Filename  : Nexus_9336C_RCF_v1.6-Storage.txt
* Date      : 10-23-2020
* Version   : v1.6
*
* Port Usage : Storage configuration
* Ports  1-36: 100GbE Controller and Shelf Storage Ports
******************************************************************************
----
====
. Verifique se o RCF é a versão mais recente correta:
+
`show running-config`

+
Quando verificar a saída para verificar se tem o RCF correto, certifique-se de que as seguintes informações estão corretas:

+
** O banner RCF
** As configurações de nó e porta
** Personalizações
+
A saída varia de acordo com a configuração do seu site. Verifique as configurações da porta e consulte as notas de versão para ver se há alterações específicas ao RCF que você instalou.



. Registre quaisquer adições personalizadas entre o atual `running-config` arquivo e o arquivo RCF em uso.
. Depois de verificar se as versões RCF e as configurações do switch estão corretas, copie o `running-config` arquivo para o `startup-config` arquivo.
+
[listing]
----
cs1# copy running-config startup-config [########################################] 100% Copy complete
----
. Salve os detalhes básicos da configuração em `write_erase.cfg` arquivo no bootflash.
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

. Para RCF versão 1.12 e posteriores, execute os seguintes comandos:
+
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1280" >> bootflash:write_erase.cfg`

+
Veja o artigo da Base de Conhecimentolink:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração em um switch de interconexão Cisco, mantendo a conetividade remota"^] para mais detalhes.

. Verifique se o `write_erase.cfg` o arquivo é preenchido conforme o esperado:
+
`show file bootflash:write_erase.cfg`

. Emitir o `write erase` comando para apagar a configuração salva atual:
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copie a configuração básica salva anteriormente na configuração de inicialização.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. Interrutor de reinicialização CS1.
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Repita os passos 1 a 13 no switch cs2.
. Conecte as portas do cluster de todos os nós do cluster ONTAP aos switches CS1 e CS2.




== Etapa 2: Verifique as conexões do interrutor

. Verifique se as portas do switch conetadas às portas do cluster estão *up*.
+
`show interface brief`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
mgmt0  --           up     _<mgmt ip address>_                       1000    1500
Eth1/11         1       eth  trunk  up      none                     100G(D) --
Eth1/12         1       eth  trunk  up      none                     100G(D) --
Eth1/13         1       eth  trunk  up      none                     100G(D) --
Eth1/14         1       eth  trunk  up      none                     100G(D) --
Eth1/15         1       eth  trunk  up      none                     100G(D) --
Eth1/16         1       eth  trunk  up      none                     100G(D) --
Eth1/17         1       eth  trunk  up      none                     100G(D) --
Eth1/18         1       eth  trunk  up      none                     100G(D) --
Eth1/23         1       eth  trunk  up      none                     100G(D) --
Eth1/24         1       eth  trunk  up      none                     100G(D) --
Eth1/25         1       eth  trunk  up      none                     100G(D) --
Eth1/26         1       eth  trunk  up      none                     100G(D) --
Eth1/27         1       eth  trunk  up      none                     100G(D) --
Eth1/28         1       eth  trunk  up      none                     100G(D) --
Eth1/29         1       eth  trunk  up      none                     100G(D) --
Eth1/30         1       eth  trunk  up      none                     100G(D) --
----
====
. Verifique se os nós de cluster estão em suas VLANs de cluster corretas usando os seguintes comandos:
+
`show vlan brief`

+
`show interface trunk`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show vlan brief*

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po999
30   VLAN0030                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19, Eth1/20
                                                Eth1/21, Eth1/22, Eth1/23
                                                Eth1/24, Eth1/25, Eth1/26
                                                Eth1/27, Eth1/28, Eth1/29
                                                Eth1/30, Eth1/31, Eth1/32
                                                Eth1/33, Eth1/34, Eth1/35
                                                Eth1/36

cs1# *show interface trunk*

-----------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
-----------------------------------------------------
Eth1/1        1       trunking      --
Eth1/2        1       trunking      --
Eth1/3        1       trunking      --
Eth1/4        1       trunking      --
Eth1/5        1       trunking      --
Eth1/6        1       trunking      --
Eth1/7        1       trunking      --
Eth1/8        1       trunking      --
Eth1/9        1       trunking      --
Eth1/10       1       trunking      --
Eth1/11       1       trunking      --
Eth1/12       1       trunking      --
Eth1/13       1       trunking      --
Eth1/14       1       trunking      --
Eth1/15       1       trunking      --
Eth1/16       1       trunking      --
Eth1/17       1       trunking      --
Eth1/18       1       trunking      --
Eth1/19       1       trunking      --
Eth1/20       1       trunking      --
Eth1/21       1       trunking      --
Eth1/22       1       trunking      --
Eth1/23       1       trunking      --
Eth1/24       1       trunking      --
Eth1/25       1       trunking      --
Eth1/26       1       trunking      --
Eth1/27       1       trunking      --
Eth1/28       1       trunking      --
Eth1/29       1       trunking      --
Eth1/30       1       trunking      --
Eth1/31       1       trunking      --
Eth1/32       1       trunking      --
Eth1/33       1       trunking      --
Eth1/34       1       trunking      --
Eth1/35       1       trunking      --
Eth1/36       1       trunking      --

--------------------------------------------------------------------------------
Port          Vlans Allowed on Trunk
--------------------------------------------------------------------------------
Eth1/1        30
Eth1/2        30
Eth1/3        30
Eth1/4        30
Eth1/5        30
Eth1/6        30
Eth1/7        30
Eth1/8        30
Eth1/9        30
Eth1/10       30
Eth1/11       30
Eth1/12       30
Eth1/13       30
Eth1/14       30
Eth1/15       30
Eth1/16       30
Eth1/17       30
Eth1/18       30
Eth1/19       30
Eth1/20       30
Eth1/21       30
Eth1/22       30
Eth1/23       30
Eth1/24       30
Eth1/25       30
Eth1/26       30
Eth1/27       30
Eth1/28       30
Eth1/29       30
Eth1/30       30
Eth1/31       30
Eth1/32       30
Eth1/33       30
Eth1/34       30
Eth1/35       30
Eth1/36       30

--------------------------------------------------------------------------------
Port          Vlans Err-disabled on Trunk
--------------------------------------------------------------------------------
Eth1/1        none
Eth1/2        none
Eth1/3        none
Eth1/4        none
Eth1/5        none
Eth1/6        none
Eth1/7        none
Eth1/8        none
Eth1/9        none
Eth1/10       none
Eth1/11       none
Eth1/12       none
Eth1/13       none
Eth1/14       none
Eth1/15       none
Eth1/16       none
Eth1/17       none
Eth1/18       none
Eth1/19       none
Eth1/20       none
Eth1/21       none
Eth1/22       none
Eth1/23       none
Eth1/24       none
Eth1/25       none
Eth1/26       none
Eth1/27       none
Eth1/28       none
Eth1/29       none
Eth1/30       none
Eth1/31       none
Eth1/32       none
Eth1/33       none
Eth1/34       none
Eth1/35       none
Eth1/36       none

--------------------------------------------------------------------------------
Port          STP Forwarding
--------------------------------------------------------------------------------
Eth1/1        none
Eth1/2        none
Eth1/3        none
Eth1/4        none
Eth1/5        none
Eth1/6        none
Eth1/7        none
Eth1/8        none
Eth1/9        none
Eth1/10       none
Eth1/11       30
Eth1/12       30
Eth1/13       30
Eth1/14       30
Eth1/15       30
Eth1/16       30
Eth1/17       30
Eth1/18       30
Eth1/19       none
Eth1/20       none
Eth1/21       none
Eth1/22       none
Eth1/23       30
Eth1/24       30
Eth1/25       30
Eth1/26       30
Eth1/27       30
Eth1/28       30
Eth1/29       30
Eth1/30       30
Eth1/31       none
Eth1/32       none
Eth1/33       none
Eth1/34       none
Eth1/35       none
Eth1/36       none

--------------------------------------------------------------------------------
Port          Vlans in spanning tree forwarding state and not pruned
--------------------------------------------------------------------------------
Eth1/1        Feature VTP is not enabled
none
Eth1/2        Feature VTP is not enabled
none
Eth1/3        Feature VTP is not enabled
none
Eth1/4        Feature VTP is not enabled
none
Eth1/5        Feature VTP is not enabled
none
Eth1/6        Feature VTP is not enabled
none
Eth1/7        Feature VTP is not enabled
none
Eth1/8        Feature VTP is not enabled
none
Eth1/9        Feature VTP is not enabled
none
Eth1/10       Feature VTP is not enabled
none
Eth1/11       Feature VTP is not enabled
30
Eth1/12       Feature VTP is not enabled
30
Eth1/13       Feature VTP is not enabled
30
Eth1/14       Feature VTP is not enabled
30
Eth1/15       Feature VTP is not enabled
30
Eth1/16       Feature VTP is not enabled
30
Eth1/17       Feature VTP is not enabled
30
Eth1/18       Feature VTP is not enabled
30
Eth1/19       Feature VTP is not enabled
none
Eth1/20       Feature VTP is not enabled
none
Eth1/21       Feature VTP is not enabled
none
Eth1/22       Feature VTP is not enabled
none
Eth1/23       Feature VTP is not enabled
30
Eth1/24       Feature VTP is not enabled
30
Eth1/25       Feature VTP is not enabled
30
Eth1/26       Feature VTP is not enabled
30
Eth1/27       Feature VTP is not enabled
30
Eth1/28       Feature VTP is not enabled
30
Eth1/29       Feature VTP is not enabled
30
Eth1/30       Feature VTP is not enabled
30
Eth1/31       Feature VTP is not enabled
none
Eth1/32       Feature VTP is not enabled
none
Eth1/33       Feature VTP is not enabled
none
Eth1/34       Feature VTP is not enabled
none
Eth1/35       Feature VTP is not enabled
none
Eth1/36       Feature VTP is not enabled
none
----
====
+

NOTE: Para obter detalhes específicos de uso de porta e VLAN, consulte a seção banner e notas importantes no RCF.





== Passo 3: Configure o cluster do ONTAP

A NetApp recomenda que você use o Gerenciador de sistemas para configurar novos clusters.

O System Manager fornece um fluxo de trabalho simples e fácil para configuração e configuração de cluster, incluindo a atribuição de um endereço IP de gerenciamento de nós, a inicialização do cluster, a criação de um nível local, a configuração de protocolos e o provisionamento de armazenamento inicial.

Aceda a https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Configure o ONTAP em um novo cluster com o Gerenciador do sistema"] para obter instruções de configuração.

.O que se segue?
Depois de instalar ou atualizar seu RCF, vocêlink:configure-ssh-keys.html["verificar a configuração SSH"]
