---
permalink: switch-cisco-9336c-fx2-storage/install-upgrade-rcf-overview-9336c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2 
summary: 'Instale ou atualize o arquivo de configuração (RCF) nos switches de armazenamento Cisco Nexus 9336C-FX2 e 9336C-FX2-T após a configuração inicial ou ao atualizar um RCF existente.' 
---
= Instale ou atualize o RCF nos switches de armazenamento Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Instale o arquivo de configuração (RCF) nos switches de armazenamento Cisco Nexus 9336C-FX2 e 9336C-FX2-T após a configuração inicial ou atualize sua versão do RCF quando uma versão mais recente estiver disponível.

Consulte o artigo da Knowledge Base link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração de um switch de interconexão Cisco mantendo a conectividade remota"^] para obter mais informações ao instalar ou atualizar seu RCF.

.Configuração RCF disponível
Storage - (Storage RCF 1._xx_) é a configuração RCF disponível onde todas as portas estão configuradas para conexões de storage NVMe de 100GbE.

.Documentação sugerida
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet da Cisco"^]
+
Consulte a tabela de compatibilidade de switches para obter informações sobre as versões ONTAP e RCF suportadas no site de suporte da NetApp .  Note que pode haver dependências entre a sintaxe de comandos no RCF e a sintaxe encontrada em versões específicas do NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Switches Cisco Nexus série 9000"^]
+
Consulte os guias de software e atualização apropriados disponíveis no site da Cisco para obter a documentação completa sobre os procedimentos de atualização e downgrade dos switches Cisco .



.Sobre os exemplos
Os exemplos neste procedimento utilizam a seguinte nomenclatura de interruptor e nó:

* Os nomes dos dois switches Cisco são s1 e s2.
* Os nomes dos nós são cluster1-01 e cluster1-02.


Consulte o link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para verificar as portas corretas em sua plataforma.


NOTE: Os resultados dos comandos podem variar dependendo das diferentes versões do ONTAP.

.Comandos utilizados
O procedimento requer o uso de comandos ONTAP e comandos dos switches Cisco Nexus série 9000; os comandos ONTAP são usados ​​a menos que indicado de outra forma.

.O que vem a seguir?
Após revisar o procedimento de instalação ou atualização do RCF, você podelink:install-rcf-software-9336c-storage.html["instalar o RCF"] oulink:upgrade-rcf-software-9336c-storage.html["atualize seu RCF"] Conforme necessário.
