---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: 'A substituição de um switch Nexus 9336C-FX2 com defeito em uma rede de cluster é um procedimento não disruptivo \(NDU\).' 
---
= Substituir switches de armazenamento Cisco Nexus 9336C-FX2 e 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode substituir switches Nexus 9336C-FX2 e 9336C-FX2-T defeituosos em uma rede de cluster. Este é um procedimento não disruptivo.

.Antes de começar
Antes de instalar o software NX-OS e os RCFs nos switches de armazenamento Cisco Nexus 9336C-FX2 e 9336C-FX2-T, certifique-se de que:

* Seu sistema pode suportar switches de armazenamento Cisco Nexus 9336C-FX2 e 9336C-FX2-T.
* Você consultou a tabela de compatibilidade de switches na página de switches Ethernet da Cisco para obter informações sobre as versões suportadas do ONTAP, NX-OS e RCF.
* Você consultou os guias de software e atualização apropriados disponíveis no site da Cisco .
* Você baixou os RCFs aplicáveis.
* A configuração de rede existente apresenta as seguintes características:
+
** A página de switches Ethernet da Cisco contém as versões mais recentes do RCF e do NX-OS para seus switches.
** A conectividade de gerenciamento deve existir em ambos os switches.


* O switch Cisco Nexus 9336C-FX2 de substituição possui as seguintes características:
+
** A conectividade da rede de gerenciamento está funcional.
** O acesso ao console para o interruptor de substituição já está instalado.
** A imagem apropriada do sistema operacional RCF e NX-OS é carregada no switch.
** A configuração inicial do switch está concluída.




.Sobre esta tarefa
Este procedimento substitui o segundo switch de storage Nexus 9336C-FX2 s2 pelo novo switch 9336C-FX ns2. Os dois nós são cluster1-01 e cluster1-02.

Passos para concluir:

* Confirme se o switch a ser substituído é s2.
* Desconecte os cabos do switch s2.
* Reconecte os cabos ao switch ns2.
* Verifique todas as configurações do dispositivo no switch ns2.
+

NOTE: Pode haver dependências entre a sintaxe de comandos nas versões RCF e NX-OS.



.Passos
. Se o AutoSupport estiver ativado neste cluster, suprima a criação automática de casos invocando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ representa a duração da janela de manutenção em horas.

. Verifique o status de integridade das portas do nó de storage para garantir que há conexão com o switch de storage s1:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
cluster1-02
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
.
.
----
====
. Verifique se o switch de storage s1 está disponível:
+
`network device-discovery show`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
cluster1-01/cdp
           e5a   s1                        Ethernet1/1 NX9336C
           e4a   cluster1-02               e4a         AFF-A700
           e4e   cluster1-02               e4e         AFF-A700
cluster1-01/lldp
           e5a   s1                        Ethernet1/1 -
           e4a   cluster1-02               e4a         -
           e4e   cluster1-02               e4e         -
cluster1-02/cdp
           e3b   s1                        Ethernet1/2 NX9336C
           e4a   cluster1-01               e4a         AFF-A700
           e4e   cluster1-01               e4e         AFF-A700
cluster1-02/lldp
           e3b   s1                        Ethernet1/2 -
           e4a   cluster1-01               e4a         -
           e4e   cluster1-01               e4e         -
.
.
----
====
. Comande o espetáculo `lldp neighbors` Execute o comando no switch em funcionamento para confirmar que você consegue visualizar ambos os nós e todas as prateleiras:
+
`show lldp neighbors`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
cluster1-01      Eth1/1       121          S             e5a
cluster1-02      Eth1/2       121          S             e5a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. Verifique as portas das prateleiras de armazenamento no sistema de storage:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   s1
3.20    1   -             -
3.20    2   Ethernet1/6   s1
3.20    3   -             -
3.30    0   Ethernet1/7   s1
3.20    1   -             -
3.30    2   Ethernet1/8   s1
3.20    3   -             -
.
.
----
====
. Remova todos os cabos conectados ao switch de storage s2.
. Reconecte todos os cabos ao switch de substituição ns2.
. Verifique novamente o estado de integridade das portas do nó de armazenamento:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
cluster1-02
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
.
.
----
====
. Verifique se ambos os interruptores estão disponíveis:
+
`network device-discovery show`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
cluster1-01/cdp
          e3a  s1                         Ethernet1/1 NX9336C
          e4a  cluster1-02                e4a         AFF-A700
          e4e  cluster1-02                e4e         AFF-A700
          e7b  ns2                       Ethernet1/1 NX9336C
cluster1-01/lldp
          e3a  s1                         Ethernet1/1 -
          e4a  cluster1-02                e4a         -
          e4e  cluster1-02                e4e         -
          e7b  ns2                        Ethernet1/1 -
cluster1-02/cdp
          e3a  s1                         Ethernet1/2 NX9336C
          e4a  cluster1-01                e4a         AFF-A700
          e4e  cluster1-01                e4e         AFF-A700
          e7b  ns2                        Ethernet1/2 NX9336C
cluster1-02/lldp
          e3a  s1                         Ethernet1/2 -
          e4a  cluster1-01                e4a         -
          e4e  cluster1-01                e4e         -
          e7b  ns2                        Ethernet1/2 -
.
.
----
====
. Verifique as portas das prateleiras no sistema de armazenamento:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     s1
3.20    1     Ethernet1/5     ns2
3.20    2     Ethernet1/6     s1
3.20    3     Ethernet1/6     ns2
3.30    0     Ethernet1/7     s1
3.20    1     Ethernet1/7     ns2
3.30    2     Ethernet1/8     s1
3.20    3     Ethernet1/8     ns2
storage::*>
----
====
. Se você desativou a criação automática de casos, reative-a enviando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que vem a seguir?
Depois de substituir os interruptores, você pode link:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"].
