---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-storage/required-documentation-9336c-storage.html 
keywords: shared storage cluster switch 
summary: Para a instalação e manutenção do switch Cisco Nexus 9336C-FX2, verifique a documentação específica do switch e do controlador para configurar os switches Cisco 9336-FX2 e o cluster ONTAP. 
---
= Requisitos de documentação para switches de storage Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Para a instalação e manutenção do switch Cisco Nexus 9336C-FX2, verifique a documentação específica do switch e do controlador para configurar os switches Cisco 9336-FX2 e o cluster ONTAP.



== Documentação do switch

Para configurar os switches Cisco Nexus 9336C-FX2, você precisa da seguinte documentação na https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Suporte para switches Cisco Nexus 9000 Series"^] página:

[cols="1,2"]
|===
| Título do documento | Descrição 


 a| 
_Guia de Instalação de hardware da Série Nexus 9000_
 a| 
Fornece informações detalhadas sobre os requisitos do local, detalhes do hardware do switch e opções de instalação.



 a| 
_Guias de configuração do software de comutador da série Cisco Nexus 9000_ (escolha o guia para a versão NX-os instalada em seus switches)
 a| 
Fornece informações de configuração inicial do switch que você precisa antes de configurar o switch para operação ONTAP.



 a| 
_Guia de atualização e downgrade do software NX-os da série Cisco Nexus 9000_ (escolha o guia para a versão NX-os instalada em seus switches)
 a| 
Fornece informações sobre como fazer downgrade do switch para o software de switch suportado pelo ONTAP, se necessário.



 a| 
_Cisco Nexus 9000 Series NX-os Guia de Referência de comando_
 a| 
Fornece links para as várias referências de comando fornecidas pelo Cisco.



 a| 
_Cisco Nexus 9000 MIBs Referência_
 a| 
Descreve os arquivos MIB (Management Information base) para os switches Nexus 9000.



 a| 
_Nexus 9000 Series NX-os System Message Reference_
 a| 
Descreve as mensagens do sistema para os switches da série Cisco Nexus 9000, aqueles que são informativos e outros que podem ajudar a diagnosticar problemas com links, hardware interno ou software do sistema.



 a| 
_Notas de lançamento do Cisco Nexus 9000 Series NX-os (escolha as notas para a versão NX-os instalada em seus switches)_
 a| 
Descreve os recursos, bugs e limitações do Cisco Nexus 9000 Series.



 a| 
Conformidade regulamentar e informações de segurança para a série Cisco Nexus 9000
 a| 
Fornece informações legais, de conformidade, segurança e conformidade de agências internacionais para os switches da série Nexus 9000.

|===


== Documentação de sistemas ONTAP

Para configurar um sistema ONTAP, você precisa dos seguintes documentos para a sua versão do sistema operacional a partir do https://docs.netapp.com/ontap-9/index.jsp["Centro de Documentação do ONTAP 9"^].

[cols="1,2"]
|===
| Nome | Descrição 


 a| 
_Instruções de instalação e configuração específicas do controlador_
 a| 
Descreve como instalar hardware NetApp.



 a| 
Documentação do ONTAP
 a| 
Fornece informações detalhadas sobre todos os aspetos das versões do ONTAP.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fornece informações de compatibilidade e configuração de hardware NetApp.

|===


== Kit de trilho e documentação do gabinete

Para instalar um switch Cisco 9336-FX2 em um gabinete NetApp, consulte a documentação de hardware a seguir.

[cols="1,2"]
|===
| Nome | Descrição 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Armário do sistema 42U, guia profundo"^]
 a| 
Descreve as FRUs associadas ao gabinete do sistema 42U e fornece instruções de manutenção e substituição da FRU.



 a| 
link:install-switch-and-passthrough-panel-9336c-storage.html["Instale um switch Cisco 9336-FX2 em um gabinete NetApp"^]
 a| 
Descreve como instalar um switch Cisco Nexus 9336C-FX2 em um gabinete NetApp de quatro colunas.

|===