---
permalink: switch-cisco-9336c-fx2-storage/setup-worksheet-9336c-storage.html 
sidebar: sidebar 
keywords: document, support, platform, complete, blank, cabling, worksheet, guide, cisco, nexus, cisco nexus 9336c-fx2 cabling worksheet - cisco nexus 9336-fx2 
summary: Se você deseja documentar as plataformas suportadas, deve preencher a planilha de cabeamento em branco usando a planilha de cabeamento de exemplo preenchida como guia. 
---
= Preencha a planilha de cabeamento do Cisco Nexus 9336C-FX2 ou 9336C-FX2-T.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você deseja documentar as plataformas suportadas, baixe o PDF desta página e preencha a planilha de cabeamento.

A planilha de cabeamento de exemplo fornece exemplos de atribuições de portas recomendadas dos switches aos controladores.  A planilha em branco fornece um modelo que você pode usar para configurar seu cluster.

* <<Folha de exercícios de cabeamento de amostra 9336C-FX2>>
* <<Folha de trabalho de cabeamento em branco 9336C-FX2>>
* <<Folha de exemplo de cabeamento 9336C-FX2-T (12 portas)>>
* <<Folha de trabalho de cabeamento em branco 9336C-FX2-T (12 portas)>>




== Folha de exercícios de cabeamento de amostra 9336C-FX2

A definição da porta de exemplo em cada par de switches é a seguinte:

[cols="1,3,1,3"]
|===
2+| Chave seletora de cluster A 2+| Chave seletora de cluster B 


| Porta de comutação | Utilização de nós e portas | Porta de comutação | Utilização de nós e portas 


 a| 
1
 a| 
Nó 1 com 4 conexões 100GbE
 a| 
1
 a| 
Nó 1 com 4 conexões 100GbE



 a| 
2
 a| 
Nó 2 com 4 conexões 100GbE
 a| 
2
 a| 
Nó 2 com 4 conexões 100GbE



 a| 
3
 a| 
Nó 3 com 4 conexões 100GbE
 a| 
3
 a| 
Nó 3 com 4 conexões 100GbE



 a| 
4
 a| 
Nó 4x100GbE
 a| 
4
 a| 
Nó 4x100GbE



 a| 
5
 a| 
Nó 5 com 4 conexões 100GbE
 a| 
5
 a| 
Nó 5 com 4 conexões 100GbE



 a| 
6
 a| 
Nó 6 com 4 conexões 100GbE
 a| 
6
 a| 
Nó 6 com 4 conexões 100GbE



 a| 
7
 a| 
Nó 7 com 4 conexões 100GbE
 a| 
7
 a| 
Nó 7 com 4 conexões 100GbE



 a| 
8
 a| 
Nó 8 com 4 conexões 100GbE
 a| 
8
 a| 
Nó 8 com 4 conexões 100GbE



 a| 
9
 a| 
Nó 9 com 4 conexões 100GbE
 a| 
9
 a| 
Nó 9 com 4 conexões 100GbE



 a| 
10
 a| 
Nó 10 com 4 conexões 100GbE
 a| 
10
 a| 
Nó 10 com 4 conexões 100GbE



 a| 
11
 a| 
Nó 11 com 4 conexões 100GbE
 a| 
11
 a| 
Nó 11 com 4 conexões 100GbE



 a| 
12
 a| 
Nó 12 com 4 conexões 100GbE
 a| 
12
 a| 
Nó 12 com 4 conexões 100GbE



 a| 
13
 a| 
Nó 13 com 4 conexões 100GbE
 a| 
13
 a| 
Nó 13 com 4 conexões 100GbE



 a| 
14
 a| 
Nó 14 com 4 conexões 100GbE
 a| 
14
 a| 
Nó 14 com 4 conexões 100GbE



 a| 
15
 a| 
Nó 15 com 4 conexões 100GbE
 a| 
15
 a| 
Nó 15 com 4 conexões 100GbE



 a| 
16
 a| 
Nó 16 com 4 conexões 100GbE
 a| 
16
 a| 
Nó 16 com 4 conexões 100GbE



 a| 
17
 a| 
Nó 17 com 4 conexões 100GbE
 a| 
17
 a| 
Nó 17 com 4 conexões 100GbE



 a| 
18
 a| 
Nó 18 com 4 conexões 100GbE
 a| 
18
 a| 
Nó 18 com 4 conexões 100GbE



 a| 
19
 a| 
Nó 19 com 4 conexões 100GbE
 a| 
19
 a| 
Nó 19 com 4 conexões 100GbE



 a| 
20
 a| 
Nó 20 com 4 portas 100GbE
 a| 
20
 a| 
Nó 20 com 4 portas 100GbE



 a| 
21
 a| 
Nó 21 com 4 conexões 100GbE
 a| 
21
 a| 
Nó 21 com 4 conexões 100GbE



 a| 
22
 a| 
Nó 22 com 4 conexões 100GbE
 a| 
22
 a| 
Nó 22 com 4 conexões 100GbE



 a| 
23
 a| 
Nó 23 com 4 conexões 100GbE
 a| 
23
 a| 
Nó 23 com 4 conexões 100GbE



 a| 
24
 a| 
Nó 24 com 4 conexões 100GbE
 a| 
24
 a| 
Nó 24 com 4 conexões 100GbE



 a| 
25
 a| 
Nó 25 com 4 conexões 100GbE
 a| 
25
 a| 
Nó 25 com 4 conexões 100GbE



 a| 
26
 a| 
Nó 26 com 4 conexões 100GbE
 a| 
26
 a| 
Nó 26 com 4 conexões 100GbE



 a| 
27
 a| 
Nó 27 com 4 conexões 100GbE
 a| 
27
 a| 
Nó 27 com 4 conexões 100GbE



 a| 
28
 a| 
Nó 28 com 4 conexões 100GbE
 a| 
28
 a| 
Nó 28 com 4 conexões 100GbE



 a| 
29
 a| 
Nó 29 com 4 conexões 100GbE
 a| 
29
 a| 
Nó 29 com 4 conexões 100GbE



 a| 
30
 a| 
Nó 30 com 4 portas 100GbE
 a| 
30
 a| 
Nó 30 com 4 portas 100GbE



 a| 
31
 a| 
Nó 31 com 4 conexões 100GbE
 a| 
31
 a| 
Nó 31 com 4 conexões 100GbE



 a| 
32
 a| 
Nó 32 com 4 portas 100GbE
 a| 
32
 a| 
Nó 32 com 4 portas 100GbE



 a| 
33
 a| 
Nó 33 com 4 conexões 100GbE
 a| 
33
 a| 
Nó 33 com 4 conexões 100GbE



 a| 
30
 a| 
Nó 30 com 4 portas 100GbE
 a| 
30
 a| 
Nó 33 com 4 conexões 100GbE



 a| 
34
 a| 
Nó 34 com 4 conexões 100GbE
 a| 
34
 a| 
Nó 34 com 4 conexões 100GbE



 a| 
35
 a| 
Nó 35 com 4 conexões 100GbE
 a| 
35
 a| 
Nó 35 com 4 conexões 100GbE



 a| 
36
 a| 
Nó 36 com 4 conexões 100GbE
 a| 
36
 a| 
Nó 36 com 4 conexões 100GbE

|===


== Folha de trabalho de cabeamento em branco 9336C-FX2

Você pode usar a planilha de cabeamento em branco para documentar as plataformas que são suportadas como nós em um cluster.  A seção _Conexões de cluster suportadas_ do https://hwu.netapp.com["Hardware Universe"^] Define as portas do cluster utilizadas pela plataforma.

[cols="5%, 45%, 5%, 45%"]
|===
2+| Chave seletora de cluster A 2+| Chave seletora de cluster B 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11
 a| 
 a| 
11
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16
 a| 
 a| 
16
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22
 a| 
 a| 
22
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25
 a| 
 a| 
25
 a| 



 a| 
26
 a| 
 a| 
26
 a| 



 a| 
27
 a| 
 a| 
27
 a| 



 a| 
28
 a| 
 a| 
28
 a| 



 a| 
29
 a| 
 a| 
29
 a| 



 a| 
30
 a| 
 a| 
30
 a| 



 a| 
31
 a| 
 a| 
31
 a| 



 a| 
32
 a| 
 a| 
32
 a| 



 a| 
33
 a| 
 a| 
33
 a| 



 a| 
34
 a| 
 a| 
34
 a| 



 a| 
35
 a| 
 a| 
35
 a| 



 a| 
36
 a| 
 a| 
36
 a| 

|===


== Folha de exemplo de cabeamento 9336C-FX2-T (12 portas)

A definição da porta de exemplo em cada par de switches é a seguinte:

[cols="1,3,1,3"]
|===
2+| Chave seletora de cluster A 2+| Chave seletora de cluster B 


| Porta de comutação | Utilização de nós e portas | Porta de comutação | Utilização de nós e portas 


 a| 
1
 a| 
Nó 1 com 4 conexões 100GbE
 a| 
1
 a| 
Nó 1 com 4 conexões 100GbE



 a| 
2
 a| 
Nó 2 com 4 conexões 100GbE
 a| 
2
 a| 
Nó 2 com 4 conexões 100GbE



 a| 
3
 a| 
Nó 3 com 4 conexões 100GbE
 a| 
3
 a| 
Nó 3 com 4 conexões 100GbE



 a| 
4
 a| 
Nó 4x100GbE
 a| 
4
 a| 
Nó 4x100GbE



 a| 
5
 a| 
Nó 5 com 4 conexões 100GbE
 a| 
5
 a| 
Nó 5 com 4 conexões 100GbE



 a| 
6
 a| 
Nó 6 com 4 conexões 100GbE
 a| 
6
 a| 
Nó 6 com 4 conexões 100GbE



 a| 
7
 a| 
Nó 7 com 4 conexões 100GbE
 a| 
7
 a| 
Nó 7 com 4 conexões 100GbE



 a| 
8
 a| 
Nó 8 com 4 conexões 100GbE
 a| 
8
 a| 
Nó 8 com 4 conexões 100GbE



 a| 
9
 a| 
Nó 9 com 4 conexões 100GbE
 a| 
9
 a| 
Nó 9 com 4 conexões 100GbE



 a| 
10
 a| 
Nó 10 com 4 conexões 100GbE
 a| 
10
 a| 
Nó 10 com 4 conexões 100GbE



 a| 
11 a 36
 a| 
Requer licença
 a| 
11 a 36
 a| 
Requer licença

|===


== Folha de trabalho de cabeamento em branco 9336C-FX2-T (12 portas)

Você pode usar a planilha de cabeamento em branco para documentar as plataformas que são suportadas como nós em um cluster.

[cols="1, 1, 1, 1"]
|===
2+| Chave seletora de cluster A 2+| Chave seletora de cluster B 


 a| 
1
 a| 
 a| 
1
 a| 



 a| 
2
 a| 
 a| 
2
 a| 



 a| 
3
 a| 
 a| 
3
 a| 



 a| 
4
 a| 
 a| 
4
 a| 



 a| 
5
 a| 
 a| 
5
 a| 



 a| 
6
 a| 
 a| 
6
 a| 



 a| 
7
 a| 
 a| 
7
 a| 



 a| 
8
 a| 
 a| 
8
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11 a 36
 a| 
Requer licença
 a| 
11 a 36
 a| 
Requer licença

|===
Veja o https://hwu.netapp.com/Switch/Index["Hardware Universe"] Para obter mais informações sobre portas de switch.

.O que vem a seguir
Depois de concluir suas planilhas de cabeamento, você pode link:install-9336c-storage.html["instalar o interruptor"].
