---
permalink: switch-cisco-9808/configure-install-upgrade-nxos-overview-9808.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9808 
summary: Você pode instalar ou atualizar o NX-OS nos switches Nexus 9808 para sistemas AFX 2K. 
---
= Visão geral da instalação ou atualização do NX-OS - Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode instalar ou atualizar o NX-OS nos switches Cisco Nexus 9808 para sistemas AFX 2K.


NOTE: A instalação ou atualização do NX-OS é independente da instalação ou atualização do arquivo de configuração de referência (RCF). Se você estiver instalando ou atualizando tanto o NX-OS quanto o RCF, recomenda-se instalar ou atualizar o NX-OS primeiro.

* link:configure-install-nxos-9808.html["Instale o NX-OS"]
+
Você instala o NX-OS nos switches como parte de uma nova instalação do sistema AFX 2K, uma substituição do módulo supervisor ou uma redefinição do switch para as configurações padrão de fábrica.

* link:configure-upgrade-nxos-9808.html["Atualize o NX-OS"]
+
Você atualiza o NX-OS nos switches para oferecer suporte a novo hardware ou a uma nova versão do ONTAP no seu sistema AFX 2K.


