---
permalink: switch-cisco-9808/configure-install-upgrade-rcf-overview-9808.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9808 
summary: Instale ou atualize o RCF nos switches Cisco Nexus 9808 para instalações do sistema AFX 2K, substituições de módulos supervisores ou para oferecer suporte a novo hardware ou versões do ONTAP. 
---
= Saiba mais sobre como instalar ou atualizar o RCF no switch Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Instale ou atualize o arquivo de configuração (RCF) nos switches Cisco Nexus 9808. Instale um novo RCF para instalações do sistema AFX 2K ou substituições do módulo supervisor, ou atualize um RCF existente para oferecer suporte a novo hardware ou versões do ONTAP.


NOTE: A instalação ou atualização do RCF é independente da instalação ou atualização do NX-OS. Se você estiver instalando ou atualizando tanto o NX-OS quanto o RCF, recomenda-se instalar ou atualizar o NX-OS primeiro.



[[understand-the-supported-rcf-versions]]
=== Entenda as versões RCF suportadas

A versão do ONTAP em execução no seu sistema AFX e a versão do NX-OS nos seus switches Cisco Nexus 9808 determinam as versões de RCF suportadas pelos seus switches. As versões de RCF possuem configurações de velocidade de porta predefinidas que determinam quantas portas do switch estão em modo breakout (4x100GbE) e em modo não-breakout.

[NOTE]
====
Para obter a lista atual de versões RCF suportadas, consulte link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco NetApp"^].

As informações sobre as portas do switch também podem ser encontradas no link:https://hwu.netapp.com["Hardware Universe da NetApp"^].

====

NOTE: Para obter detalhes específicos sobre o uso de portas e VLANs, consulte a seção de banner e notas importantes no seu RCF. Consulte link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco NetApp"^] para obter mais informações.

Por exemplo, a tabela a seguir mostra os grupos predefinidos de portas do switch, suas velocidades de porta e utilização com base na versão 10.1 do RCF.

[cols="1,2"]
|===
| Grupos de portas de switch | Velocidades e uso das portas 


 a| 
Ethernet1/1 para Ethernet1/18
 a| 
Modo 400GbE para conexões intracluster, HA e de prateleira de armazenamento



 a| 
Ethernet1/19 para Ethernet1/35
 a| 
Modo 4x100GbE para conexões intracluster, HA e armazenamento



 a| 
Ethernet1/36
 a| 
Conexões ISL intracluster de 400GbE

|===


[[change-port-speed-configuration]]
=== Alterar a configuração de velocidade da porta

Para switches com RCF 10.1 e versões posteriores, você pode alterar a configuração de velocidade da porta para ajustar o número de portas do switch no modo breakout (4x100GbE) e no modo não-breakout (400GbE) quando precisar acomodar uma configuração de velocidade de porta diferente para o seu sistema AFX. Quaisquer modificações de porta feitas são aplicadas por placa de linha atualmente em uso.

Você realiza essa alteração como parte do procedimento de instalação ou atualização do RCF. Os procedimentos contêm etapas que direcionam você para esta página.

Você insere os comandos em ambos os switches.

[cols="1,2"]
|===
| Alterar a velocidade das portas | Passos 


 a| 
Alterar portas não breakout para portas breakout
 a| 
. Entre no modo de configuração na CLI.
. Modifique as velocidades das portas e os modos de breakout nos switches:
+
Para designar portas de breakout, use o comando  `interface breakout module`.

+
Por exemplo, para designar as portas 19-22 no modo 400GbE como portas de breakout (4x100GbE), utilize o seguinte:

+
`interface breakout module 1 port 19-22 map 100g-4x`

. Modifique a lista de portas com as novas portas que precisam usar o perfil de porta para a velocidade de porta desejada.
+
Por exemplo, para modificar a lista de portas com as novas portas, 19-22, para o perfil de porta de velocidade 100G, use o seguinte:

+
`interface e1/19/1-4, e1/20/1-4, e1/21/1-4, e1/22/1-4`

. Configure manualmente as portas breakout do switch (4x100GbE) para 100GbE. Se você não configurar manualmente a velocidade, as portas não serão ativadas e ficarão em estado desabilitado por erro.
+
`speed 100000`

+
`no negotiate auto`





 a| 
Retornar portas de breakout para portas não-breakout
 a| 
. Entre no modo de configuração na CLI.
. Para retornar as portas de breakout para portas não-breakout, use o comando  `no interface breakout` no modo de configuração.
+
Por exemplo, para retornar as portas 19-22 ao modo 400GbE, use o seguinte:

+
`no interface breakout module 1 port 19-22`



|===


[[suggested-documentation]]
=== Documentação sugerida

Antes de instalar ou atualizar o RCF em seus switches, recomenda-se que você revise a seguinte documentação:

* Consulte o artigo da Knowledge Base da NetApp link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração de um switch de interconexão Cisco mantendo a conectividade remota"^] para obter mais informações ao instalar ou atualizar seu RCF.
* Consulte o  https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe da NetApp"^] para verificar as portas corretas em sua plataforma.
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco (NSS)"^]
+
Consulte a tabela de compatibilidade de switches para obter informações sobre as versões ONTAP e RCF suportadas no site de suporte da NetApp .  Note que pode haver dependências entre a sintaxe de comandos no RCF e a sintaxe encontrada em versões específicas do NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Switches Cisco Nexus série 9000"^]
+
Consulte os guias de software e atualização apropriados disponíveis no site da Cisco para obter a documentação completa sobre os procedimentos de atualização e downgrade dos switches Cisco .



.O que vem a seguir?
Após revisar a visão geral de instalação ou atualização do RCF, você link:configure-install-rcf-9808.html["instalar o RCF"] ou link:configure-upgrade-rcf-9808.html["atualizar RCF"] conforme necessário.
