---
permalink: switch-cisco-9808/configure-verify-ssh-9808.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9808 
summary: 'Verifique se o SSH está habilitado nos switches Cisco Nexus 9808 para suportar o monitor de integridade do switch de rede Ethernet (CSHM) e a coleta de logs.' 
---
= Verifique o SSH para coleta de logs no switch Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifique se o SSH está habilitado nos switches Cisco Nexus 9808 para suportar os recursos de monitor de integridade do switch Ethernet (CSHM) e coleta de logs.

.Antes de começar
Você precisa estar conectado ao switch usando o console serial.

.Passos
. Verifique se o SSH está ativado:
+
[listing, subs="+quotes"]
----
(switch) *show ssh server*
ssh version 2 is enabled
----
. Verifique se as chaves SSH estão ativadas:
+
`show ssh key`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ssh key*

**************************************
rsa Keys generated:Wed May 14 18:49:37 2025

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCndfdJesautdCwk5Mk/7pKOFl0IeShc9uBtj74F52vbjyf1FHOCXX7Xf3Vopxs6L1hbzgCpFLo9E7pZBd3I+1AoLyQULtR3svzNieGY8mlWZGLtpKf/P2fDCd8JVJaejrwQhm49WUPiC6ziEqBDMOGhJpD2e9++umyDdr6
NbmK8Q==


bitcount:1024
fingerprint:
SHA256:QtNU+Qq2I4ZfYwEfMEB1+z8w7xaKTlantTdsjLBx+OU
**************************************
could not retrieve dsa key information
**************************************
ecdsa Keys generated:Wed May 14 18:50:56 2025


ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAAYnv17T+JlGmH8rg81xiOow0mPmkbkIG0o7h9EchixO3i3KjgQr8AwqkRHNTcQC3lRnizhJFUeMGCwuQTurziRCwE6fAOkWa2MRyXA1DYRKKXjVEOnW9+MvinMipHQ0cCc
YSExhh7j4HvWHIuYv8RmD7e3rmDQFlyyiLwdmpGfas2yaw==


bitcount:521
fingerprint:
SHA256:7cpZ5NGnIq5Iamw67ke+9o4qG9D3xxmGPauVl4X5934
**************************************

(switch)# *show feature | include scpServer*
scpServer              1          enabled
(switch)# *show feature | include ssh*
sshServer              1          enabled
(switch)#
----
====


.O que vem a seguir?
* Depois de verificar se o SSH está habilitado para coleta de logs, você link:../switch-cshm/cshm-overview.html["configurar monitor de integridade do switch Ethernet"].
* Depois de configurar o monitoramento de integridade do switch Ethernet, se você quiser aproveitar o recurso de suporte Smart Call Home da Cisco, você link:configure-smart-call-9808.html["configurar Smart Call Home"].
* Se você configurou seu switch como parte de uma nova instalação do sistema AFX 2K, você deve link:install-complete-afx-setup-9808.html["Conclua a configuração do sistema AFX"].

