---
permalink: switch-cisco-9808/configure-install-nxos-9808.html 
sidebar: sidebar 
keywords: procedure, install, nx-os, software, nexus, cluster, switch, install the nx-os software - cisco nexus 9808 
summary: Instale o NX-OS em switches Cisco Nexus 9808 para novas instalações do sistema AFX 2K, substituições de módulos supervisores ou redefinições para o padrão de fábrica. 
---
= Instale o NX-OS no switch Cisco Nexus 9808
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Instale o NX-OS em switches Cisco Nexus 9808 para novas instalações do sistema AFX 2K, substituições de módulos supervisores ou ao redefinir um switch para as configurações padrão de fábrica.

.Antes de começar
* O(s) switch(es) deve(m) estar ligado(s) e você deve ter concluído o link:configure-complete-initial-setup-9808.html["Conclua a configuração inicial do switch"] procedimento.
* Se você estiver instalando o NX-OS no(s) switch(es) como parte de uma nova instalação do sistema AFX ou substituição do módulo supervisor, verifique se a versão do NX-OS em seu(s) switch(es) é a versão atual suportada pela NetApp.
+
** Se seus switches tiverem a versão atual compatível com a NetApp, você não precisa instalar o NX-OS. Você precisa instalar o arquivo de configuração de referência (RCF). Comece com o link:configure-install-upgrade-rcf-overview-9808.html["Instalar ou atualizar a visão geral do RCF"].
** Se o(s) seu(s) switch(es) não tiverem a versão compatível com a NetApp atual, continue com este procedimento para instalar o NX-OS.


* Se você estiver instalando o NX-OS em um switch como parte de uma substituição de switch ou de uma redefinição de switch para as configurações padrão de fábrica, verifique se seu cluster está totalmente funcional, ou seja, se não há erros nos logs ou problemas semelhantes.
* Se você estiver instalando o NX-OS como parte de uma nova instalação do sistema AFX, poderá ignorar este requisito, pois os controladores do seu sistema AFX não estão ligados neste ponto da instalação e configuração do sistema AFX.


.Sobre esta tarefa
* A versão do ONTAP em execução no seu sistema AFX determina as versões do NX-OS compatíveis com seus switches.
+
** Para switches em um sistema AFX 2K, é compatível executar ONTAP 9.19.1GA ou posterior e NX-OS 10.6(3) ou posterior.
+
Para obter a lista atual de versões NX-OS suportadas, consulte link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco NetApp"^].



* Este procedimento requer apenas o uso de comandos dos switches da série Cisco Nexus 9000.
* Os exemplos neste procedimento referem-se ao primeiro switch como cs1 e ao segundo switch como cs2.
* Se você instalou switches como parte de uma nova instalação do sistema AFX 2K, instale o NX-OS no primeiro switch (cs1) e depois repita os passos para o segundo switch (cs2) usando este procedimento.




[[step-1-prepare-to-install-the-nx-os]]
== Etapa 1: Prepare-se para instalar o NX-OS

Prepare-se para instalar o NX-OS no(s) switch(es) certificando-se de que você tem acesso a um servidor com a versão compatível do NX-OS, faça o download do NX-OS, conecte-se à rede de gerenciamento para a transferência de arquivos e, em seguida, verifique a conectividade com o servidor.

.Passos
. Você precisa ter acesso a um servidor HTTP, SFTP, FTP ou TFTP. O acesso a um desses servidores permite que você baixe uma versão compatível do NX-OS.
. Faça o download da versão correta do NX-OS e da imagem EPLD para o(s) switch(es) na  https://software.cisco.com/download/home["Download do software Cisco"^] página.
. Conecte o switch à rede de gerenciamento (para a transferência de arquivos).
. Verifique a conectividade com o servidor que hospeda o NX-OS usando o comando  `ping`.
+
`ping <IP address>`

+
.Mostrar exemplo
[%collapsible]
====
Este exemplo verifica se o switch consegue alcançar o servidor no endereço IP 172.19.2.1:

[listing, subs="+quotes"]
----
cs1# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====




[[step-2-install-the-nx-os-and-epld-image]]
== Etapa 2: instale o NX-OS e a imagem EPLD

Você instala a imagem NX-OS e EPLD no primeiro switch (cs1) instalando e verificando as versões das imagens NX-OS e EPLD e, em seguida, repete essas etapas no segundo switch (cs2) se estiver instalando o NX-OS como parte de uma nova instalação do sistema AFX.

. Copie a imagem do NX-OS e do EPLD para o primeiro switch.
+
`copy <protocol>: bootflash: vrf management`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo utiliza sftp.

[listing, subs="+quotes"]
----
cs1# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos64-s1.10.6.3.F.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> *progress*
  Progress meter enabled
sftp> *get code/nxos64-s1.10.6.3.F.bin /bootflash/nxos64-s1.10.6.3.F.bin*
/code/nxos64-s1.10.6.3.F.bin  100% 1261MB   9.3MB/s   02:15
sftp> *exit*
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. Verifique a versão do NX-OS em execução:
+
`show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.5(3)(F) [Feature Release]
  Host NXOS: version 10.5(3)(F)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-s1.10.5.3.F.bin
  NXOS compile time:  02/27/2026 12:00:00 [03/14/2026 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9808 Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs1
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Mar 5 15:55:08 2026
  Reason: Reset Requested by CLI command reload
  System version: 10.5(3)(F)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. Instale a imagem NX-OS e EPLD.
+
A instalação do arquivo de imagem faz com que ele seja carregado sempre que o switch for reiniciado.

+
`install all nxos bootflash:nxos.<image_file>.bin`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo usa a versão 10.6(3)(F) do NX-OS.

[listing, subs="+quotes"]
----
cs1# *install all nxos bootflash:nxos64-s1.10.6.3.F.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos64-s1.10.6.3.F.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos64-s1.10.6.3.F.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos64-s1.10.6.3.F.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  Bootable  Impact          Install-type  Reason
------  --------  --------------- ------------  ---------
  1     yes       Disruptive      Reset         Default upgrade is not hitless



Images will be upgraded according to following table:

Module   Image    Running-Version(pri:alt)                 New-Version         Upg-Required
------- --------- ---------------------------------------- ------------------- ------------
  1      nxos     10.5(3)(F)                               10.6(3)(F)          Yes
  1      bios     xx.xx.:xx.xx                             xxx                 No


Switch will be reloaded for disruptive upgrade.

Do you want to continue with the installation (y/n)? [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS

Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. Verifique a nova versão do NX-OS após o switch ter sido reinicializado:
+
`show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.6(3)(F) [Feature Release]
  Host NXOS: version 10.6(3)(F)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-s1.10.6.3.F.bin
  NXOS compile time:  05/30/2026 12:00:00 [06/14/2026 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9808 Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs1
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun 5 15:55:08 2026
  Reason: Reset Requested by CLI command reload
  System version: 10.6(3)(F)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. Verifique se a nova versão do EPLD foi carregada com sucesso:
+
`show install epld status`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo usa a versão EPLD 10.6(3)(F).

[listing, subs="+quotes"]
----
cs1# *show install epld status*

1) Module 2 upgraded on Mon May  4 09:17:08 2026 (631239  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Fri Apr 24 19:49:50 2026

Status: EPLD Upgrade was Successful

EPLD                             Curr Ver       Old Ver
-------------------------------------------------------
MI FPGA                         0x10014         0x1000b
IO FPGA                         0x10033         0x10006

2) Module 27 upgraded on Wed Apr  1 15:03:13 2026 (193093  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Mon Mar 16 03:28:47 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
IO FPGA                         0x1002d         0x10020

3) Module 28 upgraded on Wed Apr  1 14:59:53 2026 (843907  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Mon Mar 16 03:28:47 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
IO FPGA                         0x1002d         0x10020

4) Module 27 upgraded on Fri Mar 27 21:55:55 2026 (132290  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

5) Module 27 upgraded on Fri Mar 27 21:50:16 2026 (  4899  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

6) Module 27 upgraded on Fri Mar 27 21:44:36 2026 (775397  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

7) Module 27 upgraded on Fri Mar 27 21:38:58 2026 (330582  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

8) Module 27 upgraded on Fri Mar 27 21:33:19 2026 (112679  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

9) Module 27 upgraded on Fri Mar 27 21:27:41 2026 (957182  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

10) Module 27 upgraded on Fri Mar 27 21:22:03 2026 ( 90303  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

11) Module 1 upgraded on Fri Mar 27 21:16:24 2026 (240369  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
MI FPGA                         0x10014         0x1000b
IO FPGA                         0x10033         0x10006
cs1#
----
====
. Se você estiver instalando o NX-OS como parte de uma nova instalação do sistema AFX, repita estes passos para instalar a imagem do NX-OS e do EPLD no switch cs2.


.O que vem a seguir?
Depois de instalar o NX-OS em seus switches, você instala o RCF começando com o link:configure-install-upgrade-rcf-overview-9808.html["Instalar ou atualizar a visão geral do RCF"].
