---
sidebar: sidebar 
permalink: switch-cisco-9808/reference-documentation-9808.html 
keywords: shared storage cluster switch 
summary: Para a instalação e configuração do switch Cisco Nexus 9808 como parte de um novo sistema AFX 2K ou para manutenção de switches existentes, você pode consultar a documentação aplicável do switch Cisco e a documentação dos sistemas NetApp. 
---
= Documentação de referência Cisco Nexus 9808
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para a instalação e configuração do switch Cisco Nexus 9808 como parte de um novo sistema AFX 2K ou para manutenção de switches existentes, você pode consultar a documentação aplicável do switch Cisco e a documentação dos sistemas NetApp.


NOTE: Para obter instruções passo a passo sobre como instalar e configurar seus switches como parte de um novo sistema AFX 2K, consulte o link:install-configure-switches-in-afx-workflow-9808.html["Instalar e configurar switches em um fluxo de trabalho de sistema AFX"].



[[cisco-switch-documentation]]
== Documentação do switch Cisco

Para instalar e configurar seus switches Cisco Nexus 9808 como parte de um novo sistema AFX 2K, você pode consultar os seguintes documentos da Cisco para se familiarizar com as notas de versão do switch, informações de segurança, opções de instalação, configuração inicial do software e referências de comandos.

Após instalar e configurar seus switches, você pode consultar os documentos aplicáveis da Cisco para realizar a manutenção dos seus switches.

Todos esses documentos estão disponíveis na link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Suporte para switches Cisco Nexus série 9000"^] página.

[cols="1,2,3"]
|===
| Tipo de tarefa | Título do documento Cisco | Descrição 


 a| 
Instalar e configurar
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html["Notas de versão do NX-OS para a série Cisco Nexus 9000"^](Selecione as notas referentes à versão do NX-OS instalada em seus switches)
 a| 
Descreve as funcionalidades, os erros e as limitações da série Cisco Nexus 9000.



 a| 
Instalar e configurar
 a| 
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch["Informações sobre conformidade regulamentar e segurança para a série Cisco Nexus 9000"^]
 a| 
Fornece informações sobre conformidade com agências internacionais, segurança e regulamentações para os switches da série Nexus 9000.



 a| 
Instalar e configurar
 a| 
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/hw/9800/9808/nx-os/cisco-nexus-9808-nx-os-mode-switch-hardware-installation-guide/m-8000-modular-overview-ph2.html?linkclickid=aisrch["Cisco Nexus 9808 NX-OS Mode Switch Guia de Instalação de Hardware"^]
 a| 
Fornece informações detalhadas sobre os requisitos do local, detalhes do hardware do switch e opções de instalação.



 a| 
Instalar e configurar
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html["Guias de configuração de software para switches Cisco Nexus série 9000"^](escolha o guia para a versão do NX-OS instalada em seus switches)
 a| 
Fornece as informações iniciais de configuração do switch necessárias antes de configurá-lo para operação com ONTAP .



 a| 
Instalar, configurar e manter
 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Guia de Comandos do Cisco Nexus Série 9000 NX-OS"^]
 a| 
Fornece links para as diversas referências de comandos disponibilizadas pela Cisco.



 a| 
Instalar e configurar
 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/upgrade/cisco-nexus-9000-nx-os-software-upgrade-downgrade-guide-101x.html["Guia de atualização e downgrade do software NX-OS da série Cisco Nexus 9000"^](escolha o guia para a versão do NX-OS instalada em seus switches)
 a| 
Fornece informações sobre como fazer o downgrade do software do switch para uma versão compatível com ONTAP , se necessário.



 a| 
Manter
 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-system-message-guides-list.html["Referência de mensagens do sistema Cisco Nexus 9000 Series NX-OS"^]
 a| 
Descreve as mensagens do sistema para switches da série Cisco Nexus 9000, incluindo as informativas e outras que podem ajudar a diagnosticar problemas com links, hardware interno ou software do sistema.

|===


[[netapp-systems-documentation]]
== NetApp systems documentação

Para instalar e configurar seus switches Cisco Nexus 9808 como parte de um novo sistema AFX 2K, você pode consultar os seguintes documentos e recursos de sistema da NetApp para se familiarizar com os sistemas AFX, as versões do ONTAP compatíveis, as configurações de hardware compatíveis e os requisitos de instalação do sistema.

[cols="1,2,3"]
|===
| Tipo de tarefa | Título do documento ONTAP | Descrição 


 a| 
Instalar e configurar
 a| 
link:https://docs.netapp.com/us-en/ontap-afx/index.html["Documentação dos sistemas AFX"^]
 a| 
Descreve como instalar o hardware da NetApp .



 a| 
Instalar e configurar
 a| 
link:https://docs.netapp.com/us-en/ontap-family/["Documentação do ONTAP"^]
 a| 
Fornece informações detalhadas sobre todos os aspectos das versões do ONTAP .



 a| 
Instalar e configurar
 a| 
link:https://hwu.netapp.com["Hardware Universe da NetApp"^]
 a| 
Fornece informações sobre configuração e compatibilidade de hardware da NetApp .



 a| 
Instalar e configurar
 a| 
link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Que informações adicionais preciso para instalar meu equipamento que não está no HWU?"^]
 a| 
Fornece mais informações sobre os requisitos de instalação do sistema de storage.

|===