---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/components-9336c-shared.html 
keywords: shared storage cluster switch 
summary: Identifique os componentes e os números de peça dos switches compartilhados Cisco Nexus 9336C-FX2 para dar suporte à instalação e à manutenção contínua. 
---
= Analise os componentes e os números de peça dos switches compartilhados Cisco Nexus 9336C-FX2.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Identifique os componentes e os números de peça dos switches compartilhados Cisco Nexus 9336C-FX2 para dar suporte à instalação e à manutenção contínua.

A tabela a seguir lista o número da peça e a descrição do switch 9336C-FX2, dos ventiladores e das fontes de alimentação:

|===
| Número da peça | Descrição 


| X190200-CS-PE | N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28 


| X190200-CS-PI | N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28 


| X190002 | Kit de acessórios X190001/X190003 


| X-NXA-PAC-1100W-PE2 | Fonte de alimentação N9K-9336C AC 1100W - Fluxo de ar de exaustão lateral 


| X-NXA-PAC-1100W-PI2 | Fonte de alimentação N9K-9336C AC 1100W - Fluxo de ar de entrada pelo lado da porta 


| X-NXA-FAN-65CFM-PE | N9K-9336C 65 CFM, fluxo de ar de exaustão do lado esquerdo 


| X-NXA-FAN-65CFM-PI | N9K-9336C 65 CFM, fluxo de ar de admissão pelo lado esquerdo 
|===
.O que vem a seguir
Após confirmar os componentes e os números de peça, você pode revisar o link:required-documentation-9336c-shared.html["documentação necessária"].
