---
permalink: switch-cisco-9336c-fx2-shared/configure-switch-overview-9336c-shared.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Visão geral da instalação e configuração para switches compartilhados Cisco Nexus 9336C-FX2 
---
= Visão geral da instalação e configuração para switches compartilhados Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O switch compartilhado Cisco Nexus 9336C-FX2 faz parte da plataforma Cisco Nexus 9000 e pode ser instalado em um gabinete de sistema NetApp. Os switches compartilhados permitem combinar a funcionalidade de cluster e armazenamento em uma configuração de switch compartilhado, suportando o uso de arquivos de configuração de referência de cluster e armazenamento compartilhados.



== Visão geral da configuração inicial

Para configurar inicialmente um switch Cisco Nexus 9336C-FX2 em sistemas que executam o ONTAP, siga estas etapas:

. link:cable-9336c-shared.html["Folha de cálculo de cablagem completa"].
. link:install-9336c-shared.html["Instale o interrutor"].
. link:setup-and-configure-9336c-shared.html["Configure o interrutor"].
. link:install-switch-and-passthrough-panel-9336c-shared.html["Instale o interrutor em um gabinete NetApp"].
. link:prepare-nxos-rcf-9336c-shared.html["Prepare-se para instalar o NX-os e o RCF"].
. link:install-nxos-software-9336c-shared.html["Instale o software NX-os"].
. link:install-nxos-rcf-9336c-shared.html["Instale o arquivo de configuração do RCF"].
. link:configure-ssh.html["Ativar SSH"].




== Informações adicionais

Antes de iniciar a instalação ou manutenção, certifique-se de rever o seguinte:

* link:configure-reqs-9336c-shared.html["Requisitos de configuração"]
* link:components-9336c-shared.html["Componentes e números de peça"]
* link:required-documentation-9336c-shared.html["Documentação necessária"]

