---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/install-9336c-shared.html 
keywords:  
summary:  
---
= Instalar switches compartilhados Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Siga estas instruções para configurar os switches compartilhados Cisco Nexus 9336C-FX2.

.Antes de começar
Certifique-se de ter o seguinte:

* Documentação obrigatória do switch compartilhado, documentação do controlador e documentação do ONTAP .  Verlink:required-documentation-9336c-shared.html["Requisitos de documentação para switches compartilhados Cisco Nexus 9336C-FX2"] e https://docs.netapp.com/us-en/ontap/index.html["Documentação do NetApp ONTAP"^] .
* Licenças aplicáveis, informações de rede e configuração, e cabos.
* Planilhas de cabeamento concluídas. Verlink:cable-9336c-shared.html["Preencha a planilha de cabeamento do Cisco Nexus 9336C-FX2."] .  Para obter mais informações sobre cabeamento, consulte o https://hwu.netapp.com["Hardware Universe"] .


.Passos
. Instale os switches, controladores e gavetas de armazenamento NVMe NS224 no rack.
+
Veja olink:../switch-cisco-9336c-fx2/install-switch-and-passthrough-panel-9336c-cluster.html["Instruções de instalação"] Para aprender como instalar o switch em um gabinete NetApp .

. Ligue os switches, controladores e gavetas de armazenamento NVMe NS224.


.O que vem a seguir?
Opcionalmente, você pode link:install-switch-and-passthrough-panel-9336c-shared.html["instalar um switch Cisco Nexus 9336C-FX2 em um gabinete NetApp"]. Caso contrário, acesse link:setup-and-configure-9336c-shared.html["Configure o interruptor"].
