---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/install-9336c-shared.html 
keywords:  
summary:  
---
= Instalar switches compartilhados Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Siga estas instruções para configurar os switches compartilhados Cisco Nexus 9336C-FX2.

.Antes de começar
Certifique-se de ter o seguinte:

* Documentação necessária do switch compartilhado, documentação do controlador e documentação do ONTAP. Consulte link:required-documentation-9336c-shared.html["Requisitos de documentação para switches compartilhados Cisco Nexus 9336C-FX2"] e  https://docs.netapp.com/us-en/ontap/index.html["Documentação do NetApp ONTAP"^].
* Licenças aplicáveis, informações de rede e configuração, e cabos.
* Planilhas de cabeamento preenchidas. Consulte link:cable-9336c-shared.html["Preencha a planilha de cabeamento do Cisco Nexus 9336C-FX2."]. Para mais informações sobre cabeamento, consulte o link:https://hwu.netapp.com["Hardware Universe"^].


.Passos
. Instale os switches, controladores e gavetas de armazenamento NVMe NS224 no rack.
+
Consulte link:../switch-cisco-9336c-fx2/install-switch-and-passthrough-panel-9336c-cluster.html["Instruções de instalação"] para saber como instalar o switch em um gabinete NetApp.

. Ligue os switches, controladores e gavetas de armazenamento NVMe NS224.


.O que vem a seguir?
Opcionalmente, você pode link:install-switch-and-passthrough-panel-9336c-shared.html["instalar um switch Cisco Nexus 9336C-FX2 em um gabinete NetApp"]. Caso contrário, acesse link:setup-and-configure-9336c-shared.html["Configure o interruptor"].
