---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= Migrar de uma configuração comutada com storage com conexão direta
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode migrar de uma configuração comutada com armazenamento de conexão direta adicionando dois novos switches compartilhados.

.Interrutores suportados
Os seguintes switches são suportados:

* Nexus 9336C-FX2
* Nexus 3232C


As versões ONTAP e NX-os suportadas neste procedimento estão na página switches Ethernet Cisco.  https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco"]Consulte .

.Portas de ligação
Os switches usam as seguintes portas para se conetar a nós:

* Nexus 9336C-FX2P:
+
** Portas 1- 3: Portas intra-cluster do modo de fuga (4x10G), int E1/1/1-4, E1/2/3-4, E1/1/1-4
** Portas 4- 6: Portas intra-cluster/HA do modo de fuga (4x25G), int E1/4/1-4, E1/5/1-4, E1/6/1-4
** Portas 7-34: Portas 40/100GbE intra-cluster/HA, int E1/7-34


* Nexus 3232CP:
+
** Portas 1-30: 10/40/100 GbE


* Os switches usam as seguintes portas ISL (Inter-Switch Link):
+
** Portas int E1/35-36: Nexus 9336C-FX2
** Portas E1/31-32: Nexus 3232C




O https://hwu.netapp.com["Hardware Universe"] contém informações sobre o cabeamento suportado para todos os switches de cluster.

.O que você vai precisar
* Certifique-se de que concluiu as seguintes tarefas:
+
** Configurou algumas das portas nos switches Nexus 9336C-FX2 para serem executadas a 100 GbE.
** Conectividade de 100 GbE planejada, migrada e documentada de nós para os switches Nexus 9336C-FX2.
** Migração de outros switches de cluster Cisco sem interrupções de um cluster ONTAP para switches de rede Cisco Nexus 9336C-FX2.


* A rede de switch existente está corretamente configurada e funcionando.
* Todas as portas estão no estado *up* para garantir operações ininterruptas.
* Os switches Nexus 9336C-FX2 são configurados e operando sob a versão adequada do NX-os instalado e o arquivo de configuração de referência (RCF) aplicado.
* A configuração de rede existente tem o seguinte:
+
** Um cluster NetApp redundante e totalmente funcional usando ambos os switches Cisco mais antigos.
** Conetividade de gerenciamento e acesso ao console aos switches Cisco mais antigos e aos novos switches.
** Todas as LIFs de cluster no estado *up* com os LIFs de cluster estão em suas portas residenciais.
** Portas ISL ativadas e cabeadas entre os outros switches Cisco e entre os novos switches.




.Sobre os exemplos
Os exemplos deste procedimento utilizam a seguinte nomenclatura de switch e nó:

* Os switches de cluster Cisco Nexus 3232C existentes são _C1_ e _C2_.
* Os novos switches Nexus 9336C-FX2 são _SH1_ e _SH2_.
* Os nós são _node1_ e _node2_.
* Os LIFs de cluster são _node1_clus1_ e _node1_clus2_ no nó 1 e _node2_clus1_ e _node2_clus2_ no nó 2 respetivamente.
* O interrutor C2 é substituído primeiro pelo interrutor SH2 e, em seguida, o interrutor C1 é substituído pelo interrutor SH1.


.Passos
. Se o AutoSupport estiver ativado neste cluster, suprimir a criação automática de casos invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
Onde x é a duração da janela de manutenção em horas.

. Verifique o status administrativo e operacional de cada porta de cluster.
. Verifique se todas as portas do cluster estão ativas com um status de integridade:
+
`network port show –role cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[step4]]Verifique se todas as interfaces de cluster (LIFs) estão na porta inicial:
+
`network interface show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[step5]]Verifique se o cluster exibe informações para ambos os switches do cluster:
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[step6]]Desativar reversão automática nos LIFs do cluster.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[step7]]desligue o interrutor C2.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[step8]]Verifique se as LIFs de cluster migraram para as portas hospedadas no switch de cluster SH1:
+
`network interface show -role cluster`

+
Isso pode levar alguns segundos.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[step9]]substitua o interrutor C2 pelo novo interrutor SH2 e volte a ligar o novo interrutor.
. Verifique se as portas estão em backup no SH2. *Nota* que os LIFs ainda estão no interrutor C1.
. Desligue o interrutor C1.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[step12]]Verifique se as LIFs de cluster migraram para as portas hospedadas no switch de cluster SH2. Isso pode levar alguns segundos.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[step13]]substitua o interrutor C1 pelo novo interrutor SH1 e volte a ligar o novo interrutor.
. Verifique se as portas estão em backup no SH1. *Nota* que os LIFs ainda estão no interrutor C2.
. Ativar a reversão automática nos LIFs do cluster:
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[step16]]Verifique se o cluster está saudável:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====

