---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html 
keywords:  
summary:  
---
= Migre de um cluster sem switch para armazenamento conectado diretamente.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode migrar de um cluster sem switches com armazenamento conectado diretamente adicionando dois novos switches compartilhados.

O procedimento a ser utilizado depende de você ter duas portas de rede de cluster dedicadas em cada controlador ou uma única porta de cluster em cada controlador.  O processo documentado funciona para todos os nós que utilizam portas ópticas ou Twinax, mas não é suportado neste switch se os nós estiverem utilizando portas RJ45 10Gb BASE-T integradas para as portas de rede do cluster.

A maioria dos sistemas requer duas portas de rede dedicadas para clusters em cada controlador. Ver https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet da Cisco"] para mais informações.

Se você tiver um ambiente de cluster sem switch de dois nós existente, poderá migrar para um ambiente de cluster com switch de dois nós usando switches Cisco Nexus 9336C-FX2 para permitir o dimensionamento além de dois nós no cluster.



== Requisitos de revisão

Assegure-se de que:

* Para a configuração sem switch de dois nós:
+
** A configuração sem switch de dois nós está configurada corretamente e funcionando.
** Os nós estão executando o ONTAP 9.8 ou posterior.
** Todas as portas do cluster estão no estado *ativo*.
** Todas as interfaces lógicas do cluster (LIFs) estão no estado *ativo* e em suas portas *principais*.


* Para a configuração do switch Cisco Nexus 9336C-FX2:
+
** Ambos os switches possuem conectividade de rede de gerenciamento.
** É possível acessar os switches do cluster através do console.
** As conexões nó a nó e switch a switch do Nexus 9336C-FX2 usam cabos Twinax ou de fibra.
** A NetApp https://hwu.netapp.com["Hardware Universe"] Contém mais informações sobre cabeamento.
** Os cabos Inter-Switch Link (ISL) são conectados às portas 1/35 e 1/36 em ambos os switches 9336C-FX2.


* A personalização inicial dos switches 9336C-FX2 foi concluída.  Para que:
+
** Os switches 9336C-FX2 estão executando a versão mais recente do software.
** Os arquivos de configuração de referência (RCFs) foram aplicados aos switches.
** Qualquer personalização do site, como SMTP, SNMP e SSH, é configurada nos novos switches.






== Migre os switches

.Sobre os exemplos
Os exemplos neste procedimento utilizam a seguinte nomenclatura de comutador de cluster e nó:

* Os nomes dos switches 9336C-FX2 são _cs1_ e _cs2_.
* Os nomes dos SVMs do cluster são _node1_ e _node2_.
* Os nomes dos LIFs são _node1_clus1_ e _node1_clus2_ no nó 1, e _node2_clus1_ e _node2_clus2_ no nó 2, respectivamente.
* O prompt cluster1::*> indica o nome do cluster.
* As portas de cluster utilizadas neste procedimento são _e3a_ e _e3b_, conforme o controlador AFF A400 .  O https://hwu.netapp.com["Hardware Universe"] Contém as informações mais recentes sobre as portas de cluster reais para suas plataformas.




=== Etapa 1: Migrar de um cluster sem switch com conexão direta

. Se o AutoSupport estiver ativado neste cluster, suprima a criação automática de casos invocando uma mensagem do AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=xh` .
+
onde x representa a duração do período de manutenção em horas.




NOTE: A mensagem do AutoSupport notifica o suporte técnico sobre essa tarefa de manutenção, de forma que a criação automática de chamados seja suprimida durante o período de manutenção.

. [[passo 2]]Altere o nível de privilégio para avançado, digitando "y" quando solicitado a continuar:
+
`set -privilege advanced`

+
A mensagem avançada (*>) é exibida.

. Desative todas as portas voltadas para os nós (exceto as portas ISL) nos dois novos switches do cluster, cs1 e cs2.  Você não deve desativar as portas ISL.
+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas voltadas para o nó, de 1 a 34, estão desativadas no switch cs1:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *shutdown*
----
====


. [[passo 4]]Verifique se o ISL e as portas físicas no ISL entre os dois switches 9336C-FX2 cs1 e cs2 estão ativos nas portas 1/35 e 1/36:
+
`show port-channel summary`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas ISL estão ativas no switch cs1:

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
O exemplo a seguir mostra que as portas ISL estão ativas no switch cs2:

[listing, subs="+quotes"]
----
       cs2# *show port-channel summary*
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====


. [[passo 5]]Exibir a lista de dispositivos vizinhos:
+
`show cdp neighbors`

+
Este comando fornece informações sobre os dispositivos que estão conectados ao sistema.

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir lista os dispositivos vizinhos no switch cs1:

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
O exemplo a seguir lista os dispositivos vizinhos no switch cs2:

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====


. [[passo 6]]Verifique se todas as portas do cluster estão ativas:
+
`network port show - ipspace Cluster`

+
Cada porta deve exibir "Link ativo" e "Saudável" no status de integridade.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
====


. [[passo 7]]Verifique se todas as LIFs do cluster estão ativas e operacionais:
+
`network interface show - vserver Cluster`

+
Cada LIF de cluster deve exibir verdadeiro para `Is Home` e ter um status Admin/Operador de ativo/ativo.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
====


. [[passo 8]]Verifique se a reversão automática está ativada em todas as LIFs do cluster:
+
`network interface show - vserver Cluster -fields auto-revert`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
====


. [[passo 9]]Desconecte o cabo da porta de cluster e3a no nó 1 e, em seguida, conecte e3a à porta 1 no switch de cluster cs1, usando o cabeamento apropriado compatível com os switches 9336C-FX2.
+
A NetApp https://hwu.netapp.com["Hardware Universe"] Contém mais informações sobre cabeamento.

. Desconecte o cabo da porta do cluster e3a no nó 2 e, em seguida, conecte e3a à porta 2 no switch do cluster cs1, usando o cabeamento apropriado suportado pelos switches 9336C-FX2.
. Habilite todas as portas voltadas para os nós no switch de cluster cs1.
+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas 1/1 a 1/34 estão habilitadas no switch cs1:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *no shutdown*
----
====


. [[passo12]]Verifique se todos os LIFs do cluster estão *ativos*, operacionais e exibidos como verdadeiros para `Is Home` :
+
`network interface show - vserver Cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todas as LIFs estão *ativas* no nó 1 e no nó 2 e que `Is Home` Os resultados são *verdadeiros*:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
====


. [[passo13]]Exibir informações sobre o estado dos nós no cluster:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir exibe informações sobre a integridade e a elegibilidade dos nós no cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====


. [[passo14]]Desconecte o cabo da porta de cluster e3b no nó1 e, em seguida, conecte e3b à porta 1 no switch de cluster cs2, usando o cabeamento apropriado compatível com os switches 9336C-FX2.
. Desconecte o cabo da porta do cluster e3b no nó 2 e, em seguida, conecte e3b à porta 2 no switch do cluster cs2, usando o cabeamento apropriado suportado pelos switches 9336C-FX2.
. Habilite todas as portas voltadas para os nós no switch de cluster cs2.
+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas 1/1 a 1/34 estão habilitadas no switch cs2:

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-34*
cs2(config-if-range)# *no shutdown*
----
====


. [[passo 17]]Verifique se todas as portas do cluster estão ativas:
+
`network port show - ipspace Cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todas as portas do cluster estão ativas no nó 1 e no nó 2:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
====


. [[passo18]]Verifique se todas as interfaces exibem verdadeiro para `Is Home` :
+
`network interface show - vserver Cluster`

+

NOTE: Isso pode levar alguns minutos para ser concluído.

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todas as LIFs estão *ativas* no nó 1 e no nó 2 e que `Is Home` Os resultados são verdadeiros:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
====


. [[passo19]]Verifique se ambos os nós têm uma conexão com cada switch:
+
`show cdp neighbors`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra os resultados apropriados para ambas as opções:

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step20]]Exiba informações sobre os dispositivos de rede descobertos em seu cluster:
+
`network device-discovery show -protocol cdp`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
====


. [[passo 21]]Verifique se a configuração de armazenamento do par HA 1 (e do par HA 2) está correta e sem erros:
+
`system switch ethernet show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====


. [[passo22]]Verifique se as configurações estão desativadas:
+
`network options switchless-cluster show`

+

NOTE: A conclusão do comando pode levar alguns minutos.  Aguarde o anúncio de que o tempo de vida de 3 minutos está prestes a expirar.

+
O `false` O resultado no exemplo a seguir mostra que as configurações estão desativadas:

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====


. [[passo 23]]Verifique o status dos membros do nó no cluster:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra informações sobre a saúde e a elegibilidade dos nós no cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Verifique a conectividade das interfaces do cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e posterior
--
Você pode usar o `network interface check cluster-connectivity` Comando para iniciar uma verificação de acessibilidade para conectividade do cluster e, em seguida, exibir os detalhes:

`network interface check cluster-connectivity start`e `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Aguarde alguns segundos antes de executar o `show` comando para exibir os detalhes.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas as versões do ONTAP
--
Para todas as versões do ONTAP , você também pode usar o `cluster ping-cluster -node <name>` comando para verificar a conectividade:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[passo25]] Altere o nível de privilégio de volta para administrador:
+
`set -privilege admin`





=== Passo 2: Configure o interruptor compartilhado

Os exemplos neste procedimento utilizam a seguinte nomenclatura de interruptor e nó:

* Os nomes dos dois switches compartilhados são _sh1_ e _sh2_.
* Os nós são _node1_ e _node2_.



NOTE: O procedimento requer o uso de comandos ONTAP e comandos dos switches Cisco Nexus série 9000; os comandos ONTAP são usados, a menos que indicado de outra forma.

. Verifique se a configuração de armazenamento do par HA 1 (e do par HA 2) está correta e sem erros:
+
`system switch ethernet show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Verifique se as portas do nó de armazenamento estão íntegras e operacionais:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
====


. [[passo 3]]Mova o par HA 1, portas do caminho A do NSM224 para o intervalo de portas sh1 11-22.
. Instale um cabo do par HA 1, nó 1, caminho A para o intervalo de portas 11-22 do sh1.  Por exemplo, o caminho de uma porta de armazenamento em um AFF A400 é e0c.
. Instale um cabo do par HA 1, nó 2, caminho A para o intervalo de portas 11-22 do sh1.
. Verifique se as portas do nó estão íntegras e operacionais:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Verifique se não há problemas com os switches de armazenamento ou com a fiação do cluster:
+
`system health alert show -instance`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. Mova as portas do caminho B do par HA 1 do NSM224 para o intervalo de portas 11-22 do sh2.
. Instale um cabo do par HA 1, nó 1, caminho B para o intervalo de portas 11-22 do sh2.  Por exemplo, a porta de armazenamento do caminho B em um AFF A400 é e5b.
. Instale um cabo do par HA 1, nó 2, caminho B para o intervalo de portas 11-22 do sh2.
. Verifique se as portas do nó estão íntegras e operacionais:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Verifique se a configuração de armazenamento do par HA 1 está correta e sem erros:
+
`system switch ethernet show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Reconfigure as portas de armazenamento secundário (controlador) não utilizadas no par HA 1, alterando-as de armazenamento para rede.  Se mais de um NS224 estiver conectado diretamente, haverá portas que precisarão ser reconfiguradas.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage port modify –node [node name] –port [port name] –mode network
----
====
+
Para colocar portas de armazenamento em um domínio de broadcast:

+
** `network port broadcast-domain create`(para criar um novo domínio, se necessário)
** `network port broadcast-domain add-ports`(para adicionar portas a um domínio existente)


. Se você desativou a criação automática de casos, reative-a enviando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que vem a seguir?
Depois de migrar seus switches, você pode link:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"].
