---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= Migre de uma configuração comutada para armazenamento conectado diretamente.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode migrar de uma configuração comutada com armazenamento conectado diretamente adicionando dois novos switches compartilhados.

.Interruptores suportados
Os seguintes interruptores são suportados:

* Nexus 9336C-FX2
* Nexus 3232C


As versões do ONTAP e do NX-OS suportadas neste procedimento estão na página de switches Ethernet da Cisco . Ver https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet da Cisco"] .

.Portas de conexão
Os switches utilizam as seguintes portas para se conectar aos nós:

* Nexus 9336C-FX2:
+
** Portas 1-3: Modo Breakout (4x10G) Portas Intra-Cluster, int e1/1/1-4, e1/2/1-4, e1/3/1-4
** Portas 4-6: Modo breakout (4x25G) Portas intra-cluster/HA, int e1/4/1-4, e1/5/1-4, e1/6/1-4
** Portas 7-34: Portas 40/100GbE Intra-Cluster/HA, int e1/7-34


* Nexus 3232C:
+
** Portas 1-30: 10/40/100 GbE


* Os switches utilizam as seguintes portas de Interconexão entre Switches (ISL):
+
** Portas int e1/35-36: Nexus 9336C-FX2
** Portas e1/31-32: Nexus 3232C




O https://hwu.netapp.com["Hardware Universe"] Contém informações sobre a cablagem suportada para todos os switches de cluster.

.O que você vai precisar
* Certifique-se de ter concluído as seguintes tarefas:
+
** Configurei algumas portas nos switches Nexus 9336C-FX2 para funcionarem em 100 GbE.
** Planejamos, migramos e documentamos a conectividade de 100 GbE dos nós para os switches Nexus 9336C-FX2.
** Migrei, sem interrupções, outros switches de cluster Cisco de um cluster ONTAP para switches de rede Cisco Nexus 9336C-FX2.


* A rede de switches existente está configurada corretamente e funcionando.
* Todas as portas estão em estado *ativo* para garantir operações sem interrupções.
* Os switches Nexus 9336C-FX2 estão configurados e operando com a versão correta do NX-OS instalada e o arquivo de configuração de referência (RCF) aplicado.
* A configuração de rede existente apresenta as seguintes características:
+
** Um cluster NetApp redundante e totalmente funcional, utilizando switches Cisco mais antigos.
** Conectividade de gerenciamento e acesso ao console tanto para os switches Cisco mais antigos quanto para os novos.
** Todas as LIFs do cluster estão no estado *ativo* e conectadas às suas portas de origem.
** As portas ISL foram habilitadas e conectadas por cabos entre os outros switches Cisco e entre os novos switches.




.Sobre os exemplos
Os exemplos neste procedimento utilizam a seguinte nomenclatura de interruptor e nó:

* Os switches de cluster Cisco Nexus 3232C existentes são _c1_ e _c2_.
* Os novos switches Nexus 9336C-FX2 são _sh1_ e _sh2_.
* Os nós são _node1_ e _node2_.
* Os LIFs do cluster são _node1_clus1_ e _node1_clus2_ no nó 1, e _node2_clus1_ e _node2_clus2_ no nó 2, respectivamente.
* O interruptor c2 é substituído primeiro pelo interruptor sh2 e, em seguida, o interruptor c1 é substituído pelo interruptor sh1.


.Passos
. Se o AutoSupport estiver ativado neste cluster, suprima a criação automática de casos invocando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
Onde x representa a duração do período de manutenção em horas.

. Verifique o status administrativo e operacional de cada porta do cluster.
. Verifique se todas as portas do cluster estão ativas e com status íntegro:
+
`network port show –role cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[passo 4]]Verifique se todas as interfaces de cluster (LIFs) estão na porta principal:
+
`network interface show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[passo 5]]Verifique se o cluster exibe informações para ambos os switches do cluster:
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[passo 6]]Desative a reversão automática nos LIFs do cluster.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[passo 7]]Desligue o interruptor c2.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[passo 8]]Verifique se as LIFs do cluster migraram para as portas hospedadas no switch de cluster sh1:
+
`network interface show -role cluster`

+
Isso pode levar alguns segundos.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[passo 9]]Substitua o interruptor c2 pelo novo interruptor sh2 e reconecte os cabos do novo interruptor.
. Verifique se as portas estão novamente ativas no sh2.  *Observação*: os LIFs ainda estão no switch c1.
. Desligue o interruptor c1.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[passo12]]Verifique se as LIFs do cluster migraram para as portas hospedadas no switch de cluster sh2. Isso pode levar alguns segundos.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[passo13]]Substitua o interruptor c1 pelo novo interruptor sh1 e reconecte os cabos do novo interruptor.
. Verifique se as portas estão novamente ativas no sh1.  *Observação*: os LIFs ainda estão no switch c2.
. Ativar reversão automática nos LIFs do cluster:
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[passo16]]Verifique se o cluster está íntegro:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====


.O que vem a seguir?
Depois de migrar seus switches, você pode link:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"].
