---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html 
keywords:  
summary:  
---
= Migre de um cluster sem switch com storage de conexão direta
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
É possível migrar de um cluster sem switch com armazenamento de conexão direta adicionando dois novos switches compartilhados.

O procedimento usado depende se você tem duas portas de rede de cluster dedicadas em cada controlador ou uma única porta de cluster em cada controlador. O processo documentado funciona para todos os nós que usam portas óticas ou Twinax, mas não é suportado neste switch se os nós estiverem usando portas integradas 10Gb BASE-T RJ45 para as portas de cluster-rede.

A maioria dos sistemas requer duas portas de rede de cluster dedicadas em cada controlador. Consulte https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco"] para obter mais informações.

Se você tiver um ambiente de cluster sem switch de dois nós existente, poderá migrar para um ambiente de cluster comutado de dois nós usando os switches Cisco Nexus 9336C-FX2 para permitir que você escale além de dois nós no cluster.



== Rever os requisitos

Certifique-se de que:

* Para a configuração sem switch de dois nós:
+
** A configuração sem switch de dois nós está corretamente configurada e funcionando.
** Os nós estão executando o ONTAP 9.8 e posterior.
** Todas as portas de cluster estão no estado *up*.
** Todas as interfaces lógicas de cluster (LIFs) estão no estado *up* e em suas portas *home*.


* Para a configuração do switch Cisco Nexus 9336C-FX2:
+
** Ambos os switches têm conetividade de rede de gerenciamento.
** Existe acesso à consola aos interrutores do cluster.
** As conexões de switch de nó para nó Nexus 9336C-FX2 e switch para switch usam cabos Twinax ou fibra.
** O NetApp https://hwu.netapp.com["Hardware Universe"] contém mais informações sobre cabeamento.
** Os cabos ISL (Inter-Switch Link) são conetados às portas 1/35 e 1/36 em ambos os switches 9336C-FX2.


* A personalização inicial dos switches 9336C-FX2 está concluída. Para que:
+
** Os switches 9336C-FX2 estão executando a versão mais recente do software
** Os ficheiros de configuração de referência (RCFs) foram aplicados aos comutadores
** Qualquer personalização de site, como SMTP, SNMP e SSH, é configurada nos novos switches.






== Migrar os switches

.Sobre os exemplos
Os exemplos deste procedimento utilizam a seguinte nomenclatura de nó e switch de cluster:

* Os nomes dos switches 9336C-FX2 são _CS1_ e _CS2_.
* Os nomes dos SVMs do cluster são _node1_ e _node2_.
* Os nomes dos LIFs são _node1_clus1_ e _node1_clus2_ no nó 1 e _node2_clus1_ e _node2_clus2_ no nó 2 respetivamente.
* O prompt cluster1::*> indica o nome do cluster.
* As portas de cluster usadas neste procedimento são _E3A_ e _e3b_, de acordo com o controlador AFF A400. O https://hwu.netapp.com["Hardware Universe"] contém as informações mais recentes sobre as portas de cluster reais para as suas plataformas.




=== Etapa 1: Migre de um cluster sem switch com conexão direta

. Se o AutoSupport estiver ativado neste cluster, suprimir a criação automática de casos invocando uma mensagem AutoSupport:  `system node autosupport invoke -node * -type all -message MAINT=xh`.
+
onde x é a duração da janela de manutenção em horas.




NOTE: A mensagem AutoSupport notifica o suporte técnico desta tarefa de manutenção para que a criação automática de casos seja suprimida durante a janela de manutenção.

. [[step2]]altere o nível de privilégio para avançado, inserindo y quando solicitado a continuar:
+
`set -privilege advanced`

+
É apresentado o aviso avançado (*>).

. Desative todas as portas voltadas para o nó (não portas ISL) nos novos switches de cluster CS1 e CS2. Não deve desativar as portas ISL.
+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas 1 a 34 voltadas para o nó estão desativadas no switch CS1:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *shutdown*
----
====


. [[step4]]Verifique se o ISL e as portas físicas no ISL entre os dois switches 9336C-FX2 CS1 e CS2 estão acima nas portas 1/35 e 1/36:
+
`show port-channel summary`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas ISL estão acima no interrutor CS1:

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
O exemplo a seguir mostra que as portas ISL estão acima no interrutor CS2:

[listing, subs="+quotes"]
----
       cs2# *show port-channel summary*
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====


. [[step5]]apresenta a lista de dispositivos vizinhos:
+
`show cdp neighbors`

+
Este comando fornece informações sobre os dispositivos que estão conetados ao sistema.

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir lista os dispositivos vizinhos no switch CS1:

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
O exemplo a seguir lista os dispositivos vizinhos no switch CS2:

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====


. [[step6]]Verifique se todas as portas de cluster estão ativas:
+
`network port show - ipspace Cluster`

+
Cada porta deve ser exibida para Link e Healthy for Health Status.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
====


. [[step7]]Verifique se todas as LIFs de cluster estão ativas e operacionais:
+
`network interface show - vserver Cluster`

+
Cada LIF de cluster deve exibir True para `Is Home` e ter um Admin de Status/Oper de up/up.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
====


. [[step8]]Verifique se a reversão automática está ativada em todas as LIFs do cluster:
+
`network interface show - vserver Cluster -fields auto-revert`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
====


. [[step9]]Desconete o cabo da porta do cluster E3A no node1 e conete o E3A à porta 1 no switch do cluster CS1, usando o cabeamento apropriado suportado pelos switches 9336C-FX2.
+
O NetApp https://hwu.netapp.com["Hardware Universe"] contém mais informações sobre cabeamento.

. Desconete o cabo da porta de cluster E3A no node2 e conete o E3A à porta 2 no switch de cluster CS1, usando o cabeamento apropriado suportado pelos switches 9336C-FX2.
. Habilite todas as portas voltadas para o nó no switch de cluster CS1.
+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas 1/1 a 1/34 estão ativadas no switch CS1:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *no shutdown*
----
====


. [[step12]]Verifique se todas as LIFs de cluster são *up*, operacionais e exibidas como True para `Is Home`:
+
`network interface show - vserver Cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todos os LIFs são *up* em node1 e node2 e que `Is Home` os resultados são *true*:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
====


. [[step13]]exibe informações sobre o status dos nós no cluster:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir exibe informações sobre a integridade e a elegibilidade dos nós no cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====


. [[step14]]Desconete o cabo da porta do cluster e3b no node1 e conete o e3b à porta 1 no switch do cluster CS2, usando o cabeamento apropriado suportado pelos switches 9336C-FX2.
. Desconete o cabo da porta de cluster e3b no node2 e conete o e3b à porta 2 no switch de cluster CS2, usando o cabeamento apropriado suportado pelos switches 9336C-FX2.
. Habilite todas as portas voltadas para o nó no switch de cluster CS2.
+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas 1/1 a 1/34 estão ativadas no switch CS2:

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-34*
cs2(config-if-range)# *no shutdown*
----
====


. [[step17]]Verifique se todas as portas de cluster estão ativas:
+
`network port show - ipspace Cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todas as portas do cluster estão em node1 e node2:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
====


. [[step18]]Verifique se todas as interfaces são exibidas verdadeiras para `Is Home`:
+
`network interface show - vserver Cluster`

+

NOTE: Isso pode levar vários minutos para ser concluído.

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todos os LIFs são *up* em node1 e node2 e que `Is Home` os resultados são verdadeiros:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
====


. [[step19]]Verifique se ambos os nós têm uma conexão para cada switch:
+
`show cdp neighbors`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra os resultados apropriados para ambos os switches:

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step20]]Mostre informações sobre os dispositivos de rede descobertos em seu cluster:
+
`network device-discovery show -protocol cdp`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
====


. [[step21]]Verifique se a configuração de armazenamento do par HA 1 (e par HA 2) está correta e livre de erros:
+
`system switch ethernet show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====


. [[step22]]Verifique se as configurações estão desativadas:
+
`network options switchless-cluster show`

+

NOTE: Pode demorar vários minutos para o comando ser concluído. Aguarde até que o anúncio "3 minutos de duração expire".

+
A `false` saída no exemplo a seguir mostra que as configurações estão desativadas:

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====


. [[step23]]Verifique o status dos membros do nó no cluster:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra informações sobre a integridade e a elegibilidade dos nós no cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Verifique a conectividade das interfaces de cluster remotas:


[role="tabbed-block"]
====
.ONTAP 9.9,1 e posterior
--
Você pode usar o `network interface check cluster-connectivity` comando para iniciar uma verificação de acessibilidade para conetividade de cluster e, em seguida, exibir os detalhes:

`network interface check cluster-connectivity start` e `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* espere alguns segundos antes de executar o `show` comando para exibir os detalhes.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todos os lançamentos do ONTAP
--
Para todas as versões do ONTAP, você também pode usar o `cluster ping-cluster -node <name>` comando para verificar a conetividade:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step25]] altere o nível de privilégio de volta para admin:
+
`set -privilege admin`





=== Passo 2: Configure o switch compartilhado

Os exemplos deste procedimento utilizam a seguinte nomenclatura de switch e nó:

* Os nomes dos dois switches compartilhados são _SH1_ e _SH2_.
* Os nós são _node1_ e _node2_.



NOTE: O procedimento requer o uso de comandos ONTAP e comandos Cisco Nexus 9000 Series switches, os comandos ONTAP são usados, a menos que indicado de outra forma.

. Verifique se a configuração de armazenamento do par HA 1 (e par HA 2) está correta e sem erros:
+
`system switch ethernet show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Verifique se as portas do nó de storage estão íntegras e operacionais:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
====


. [[step3]]mova as portas do par HA 1, NSM224 caminho A para o intervalo de portas SH1 11-22.
. Instale um cabo do par HA 1, node1, caminho A até o intervalo de portas SH1 11-22. Por exemplo, o caminho Que uma porta de armazenamento em um AFF A400 é e0c.
. Instale um cabo do par HA 1, node2, caminho A até o intervalo de portas SH1 11-22.
. Verifique se as portas dos nós estão íntegras e operacionais:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Verifique se não há problemas de cabeamento ou switch de storage no cluster:
+
`system health alert show -instance`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. Mova o par de HA 1 portas de caminho B NSM224 para o intervalo de portas SH2 11-22.
. Instale um cabo do par HA 1, node1, caminho B para o intervalo de portas SH2 11-22. Por exemplo, a porta de armazenamento de caminho B em um AFF A400 é e5b.
. Instale um cabo do par HA 1, node2, caminho B para o intervalo de portas SH2 11-22.
. Verifique se as portas dos nós estão íntegras e operacionais:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. Verifique se a configuração de armazenamento do par HA 1 está correta e sem erros:
+
`system switch ethernet show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. Reconfigure as portas de storage secundário não utilizadas (controladora) no par de HA 1 do storage à rede. Se mais de um NS224 foi conetado diretamente, haverá portas que devem ser reconfiguradas.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage port modify –node [node name] –port [port name] –mode network
----
====
+
Para colocar portas de armazenamento em um domínio de broadcast:

+
** `network port broadcast-domain create` (para criar um novo domínio, se necessário)
** `network port broadcast-domain add-ports` (para adicionar portas a um domínio existente)


. Se você suprimiu a criação automática de casos, reative-a invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que se segue?
link:../switch-cshm/config-overview.html["Configurar o monitoramento de integridade do switch"].
