---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/setup-and-configure-9336c-shared.html 
keywords:  
summary:  
---
= Configurar switches compartilhados Cisco Nexus 9336C-FX2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Siga estas instruções para configurar os switches compartilhados Cisco Nexus 9336C-FX2.

.Antes de começar
Certifique-se de ter o seguinte:

* Documentação obrigatória do switch compartilhado, documentação do controlador e documentação do ONTAP .  Verlink:required-documentation-9336c-shared.html["Requisitos de documentação para switches compartilhados Cisco Nexus 9336C-FX2"] e https://docs.netapp.com/us-en/ontap/index.html["Documentação do NetApp ONTAP"^] .
* Licenças aplicáveis, informações de rede e configuração, e cabos.
* Planilhas de cabeamento concluídas. Verlink:cable-9336c-shared.html["Preencha a planilha de cabeamento do Cisco Nexus 9336C-FX2."] .  Para obter mais informações sobre cabeamento, consulte o https://hwu.netapp.com["Hardware Universe"] .


.Passos
. [[passo 3]]Realize uma configuração inicial dos switches.
+
Para a configuração, você precisa da quantidade e do tipo adequados de cabos e conectores de cabos para seus switches.

+
Dependendo do tipo de switch que você estiver configurando inicialmente, será necessário conectar-se à porta de console do switch com o cabo de console incluído; você também precisará fornecer informações específicas da rede.

. Ligue o interruptor.
+
Ao ligar o switch pela primeira vez, forneça as respostas adequadas às seguintes perguntas de configuração inicial.

+
A política de segurança do seu site define as respostas e os serviços a serem ativados.

+
.. Cancelar o provisionamento automático e continuar com a configuração normal?  (sim/não)
+
Responda com *sim*.  A opção padrão é não.

.. Deseja implementar um padrão de senhas seguras?  (sim/não)
+
Responda com *sim*.  A opção padrão é sim.

.. Digite a senha de administrador.
+
A senha padrão é admin; você deve criar uma nova senha forte.

+
Uma senha fraca pode ser rejeitada.

.. Deseja acessar a caixa de diálogo de configuração básica?  (sim/não)
+
Responda com *sim* na configuração inicial do switch.

.. Criar outra conta de login?  (sim/não)
+
Sua resposta depende das políticas do seu site em relação a administradores alternativos.  A opção padrão é não.

.. Configurar string de comunidade SNMP somente leitura?  (sim/não)
+
Responda com *não*.  A opção padrão é não.

.. Configurar string de comunidade SNMP de leitura e gravação?  (sim/não)
+
Responda com *não*.  A opção padrão é não.

.. Digite o nome do interruptor.
+
O nome do interruptor está limitado a 63 caracteres alfanuméricos.

.. Continuar com a configuração de gerenciamento fora de banda (mgmt0)?  (sim/não)
+
Responda com *sim* (a opção padrão) quando solicitado.  No prompt "Endereço IPv4 mgmt0:", digite seu endereço IP: ip_address

.. Configurar o gateway padrão?  (sim/não)
+
Responda com *sim*.  No prompt "Endereço IPv4 do gateway padrão:", insira o seu gateway padrão.

.. Configurar opções avançadas de IP?  (sim/não)
+
Responda com *não*.  A opção padrão é não.

.. Habilitar o serviço Telnet?  (sim/não)
+
Responda com *não*.  A opção padrão é não.

.. Habilitar o serviço SSH?  (sim/não)
+
Responda com *sim*.  A opção padrão é sim.

+

NOTE: Recomenda-se o uso de SSH ao utilizar o Ethernet Switch Health Monitor (CSHM) devido aos seus recursos de coleta de logs.  O SSHv2 também é recomendado para maior segurança.

.. [[passo14]]Digite o tipo de chave SSH que deseja gerar (dsa/rsa/rsa1).  O padrão é rsa.
.. Insira o número de bits da chave (1024-2048).
.. Configurar o servidor NTP?  (sim/não)
+
Responda com *não*.  A opção padrão é não.

.. Configurar a camada de interface padrão (L3/L2):
+
Responda com *L2*.  O padrão é L2.

.. Configurar o estado padrão da interface da porta do switch (desligado/não desligado):
+
Responda com *noshut*.  O padrão é noshut.

.. Configurar perfil do sistema CoPP (estrito/moderado/tolerante/denso):
+
Responda com *rigoroso*.  O padrão é estrito.

.. Deseja editar a configuração?  (sim/não)
+
Você deverá ver a nova configuração neste ponto.  Revise e faça as alterações necessárias na configuração que você acabou de inserir.  Responda com "não" quando solicitado, caso esteja satisfeito com a configuração.  Responda com *sim* se desejar editar suas configurações.

.. Usar esta configuração e salvá-la?  (sim/não)
+
Responda com *sim* para salvar a configuração.  Isso atualiza automaticamente as imagens do Kickstart e do sistema.



. Verifique as opções de configuração selecionadas na tela que aparece ao final da configuração e certifique-se de salvar as alterações.
+

NOTE: Se você não salvar a configuração nesta etapa, nenhuma das alterações terá efeito na próxima vez que você reiniciar o switch.

. Verifique a versão nos switches de rede do cluster e, se necessário, baixe a versão do software compatível com a NetApp para os switches a partir do https://software.cisco.com/download/home["Download do software Cisco"^] página.


.O que vem a seguir?
Depois de configurar seus switches, você pode link:prepare-nxos-rcf-9336c-shared.html["prepare-se para instalar o NX-OS e o RCF"].
