---
permalink: switch-cisco-9364d-gx2a/configure-verify-ssh-9364d.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9364d-gx2a 
summary: 'Verifique se o SSH está habilitado nos switches Cisco Nexus 9364D-GX2A para suportar o monitor de integridade do switch Ethernet (CSHM) e a coleta de logs.' 
---
= Verifique o SSH para coleta de logs no switch Cisco Nexus 9364D-GX2A
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifique se o SSH está habilitado nos switches Cisco Nexus 9364D-GX2A para suportar os recursos de monitor de integridade do switch Ethernet (CSHM) e coleta de logs.

.Antes de começar
Você precisa estar conectado ao switch usando o console serial.

.Passos
. Verifique se o SSH está ativado:
+
[listing, subs="+quotes"]
----
(switch) *show ssh server*
ssh version 2 is enabled
----
. Verifique se as chaves SSH estão ativadas:
+
`show ssh key`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ssh key*

rsa Keys generated:Thu May 15 15:09:55 2025

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDCQJPZk7OGhg0j1t0NWKylnI8R8zDpuMpU6KKAjPOCShTFpibeYQqxOPTCAKACkut8dduZmc3bY9DIOle0cKYQ8PgS2mG9ovQ0RJ56RUNhVNPdJuhXM4ckHoiVJxIAbHkbcw8rzawbkT6cNBUiZY3MrOMh0e0CnMRhh9we
MOo/vQ==


bitcount:1024
fingerprint:
SHA256:TMUXFgyRC3EcIZEVbQ/P0elDByBCJizPJ1XKMkIXfPI
**************************************
could not retrieve dsa key information
**************************************
ecdsa Keys generated:Thu May 15 15:12:09 2025


ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBADquZcNSDA/eLAaItXyxVZxsSJSE3u4et9B6+RLq162zTe/3A6JTCyBrkfrMhQt9QMQ7XrMqJGxLSinXhyUClBxwQD/ZbkZueZHiFuYg5hKN97wUYvts+EwpG2mSVonxKKp
atmtgu48BqKfZTc4LZYL5vgdh5uuktJ0Z8mYHt3xKPXsvw==


bitcount:521
fingerprint:
SHA256:K8LDx6L7sJjLFn8iubUhjt66uk8TYmXwnQKWVD04C1o
**************************************

(switch)# *show feature | include scpServer*
scpServer              1          enabled
(switch)# *show feature | include ssh*
sshServer              1          enabled
(switch)#
----
====


.O que vem a seguir?
* Depois de verificar se o SSH está habilitado para coleta de logs, você link:../switch-cshm/cshm-overview.html["configurar monitor de integridade do switch Ethernet"].
+
** Depois de configurar o monitoramento de integridade do switch Ethernet, se você quiser aproveitar o recurso de suporte Smart Call Home da Cisco, você link:configure-smart-call-9364d.html["configurar Smart Call Home"].


* Se você configurou seu switch como parte de uma nova instalação do AFX 1K ou AFX 2K, você deve link:install-complete-afx-setup-9364d.html["Conclua a configuração do sistema AFX"].

