---
permalink: switch-cisco-9364d-gx2a/install-upgrade-rcf-overview-cluster.html 
sidebar: sidebar 
keywords: install, upgarde, cluster, switch, cisco 9364d-gx2a 
summary: Você pode instalar o RCF depois de configurar o switch Nexus 9364d-gx2a pela primeira vez. Você também pode usar este procedimento para atualizar seu RCF. 
---
= Visão geral da instalação ou atualização do Arquivo de Configuração de Referência (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você instala o arquivo de configuração de referência (RCF) após configurar o switch Nexus 9364D-GX2A pela primeira vez. Você atualiza sua versão RCF quando tem uma versão existente do arquivo RCF instalada no seu switch.

Consulte o artigo da Base de Conhecimento.link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração de um switch de interconexão Cisco mantendo a conectividade remota"^] Para obter mais informações ao instalar ou atualizar seu RCF.

.Configuração RCF disponível
* *Cluster-HA-Storage* - Suporta tráfego de cluster/HA/armazenamento compartilhado em portas (NX9364D-GX2A-RCF-v10.0-Shared.txt).


Para obter detalhes específicos sobre o uso de portas e VLANs, consulte a seção de avisos e notas importantes no seu RCF.

.Documentação sugerida
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco (NSS)"^]
+
Consulte a tabela de compatibilidade de switches para obter informações sobre as versões ONTAP e RCF suportadas no site de suporte da NetApp .  Note que pode haver dependências entre a sintaxe de comandos no RCF e a sintaxe encontrada em versões específicas do NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-guides-list.html["Switches Cisco Nexus 3=Série 9000"^]
+
Consulte os guias de software e atualização apropriados disponíveis no site da Cisco para obter a documentação completa sobre os procedimentos de atualização e downgrade dos switches Cisco .



.Sobre os exemplos
Os exemplos neste procedimento utilizam a seguinte nomenclatura de interruptor e nó:

* Os nomes dos dois switches Cisco são cs1 e cs2.
* Os nomes dos nós são node1-01, node1-02, node1-03 e node1-04.
* Os nomes do LIF do cluster são node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 e node1-04_clus2.
* O `cluster1::*>` O prompt indica o nome do cluster.


Veja o https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] Para verificar as portas de cluster corretas em suas plataformas.


NOTE: Os resultados dos comandos podem variar dependendo das diferentes versões do ONTAP.

.Comandos utilizados
O procedimento requer o uso de comandos ONTAP e comandos dos switches Cisco Nexus série 9000; os comandos ONTAP são usados ​​a menos que indicado de outra forma.

.O que vem a seguir?
Depois de revisar o procedimento de instalação do RCF ou atualização do RCF, vocêlink:install-rcf-software-9364d-cluster.html["instalar o RCF"] oulink:upgrade-rcf-software-9364d-cluster.html["atualize seu RCF"] conforme necessário.
