---
permalink: switch-cisco-9364d-gx2a/install-upgrade-rcf-overview-cluster.html 
sidebar: sidebar 
keywords: install, upgarde, cluster, switch, cisco 9364d-gx2a 
summary: Você pode instalar o RCF depois de configurar o switch Nexus 9364d-gx2a pela primeira vez.  Você também pode usar este procedimento para atualizar seu RCF. 
---
= Instale ou atualize a visão geral do ficheiro de configuração de referência (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você instala o arquivo de configuração de referência (RCF) após configurar o switch Nexus 9364D-GX2A pela primeira vez. Você atualiza sua versão RCF quando tem uma versão existente do arquivo RCF instalada no seu switch.

Consulte o artigo da base de dados de Conhecimento link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração em um switch de interconexão Cisco, mantendo a conetividade remota"^]para obter mais informações ao instalar ou atualizar o RCF.

.Configuração RCF disponível
* *Cluster-HA-Storage* - Suporta tráfego de cluster/HA/armazenamento compartilhado em portas (NX9364D-GX2A-RCF-v10.0-Shared.txt).


Para obter detalhes específicos de uso de porta e VLAN, consulte a seção banner e notas importantes no RCF.

.Documentação sugerida
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco (NSS)"^]
+
Consulte a tabela de compatibilidade de switch para ver as versões ONTAP e RCF suportadas no site de suporte da NetApp. Note que pode haver dependências de comando entre a sintaxe de comando no RCF e a sintaxe encontrada em versões específicas do NX-os.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-guides-list.html["Switches Cisco Nexus 3=Série 9000"^]
+
Consulte os guias de software e atualização apropriados disponíveis no site da Cisco para obter a documentação completa sobre os procedimentos de atualização e downgrade do switch Cisco.



.Sobre os exemplos
Os exemplos deste procedimento utilizam a seguinte nomenclatura de switch e nó:

* Os nomes dos dois switches Cisco são CS1 e CS2.
* Os nomes dos nós são node1-01, node1-02, node1-03 e node1-04.
* Os nomes do LIF do cluster são node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 e node1-04_clus2.
* O `cluster1::*>` prompt indica o nome do cluster.


Veja o https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para verificar as portas de cluster corretas em suas plataformas.


NOTE: As saídas de comando podem variar dependendo de diferentes versões do ONTAP.

.Comandos utilizados
O procedimento requer o uso de comandos ONTAP e comandos Cisco Nexus 9000 Series switches; os comandos ONTAP são usados, a menos que indicado de outra forma.

.O que se segue?
Depois de revisar o procedimento de instalação do RCF ou atualização do RCF, vocêlink:install-rcf-software-9364d-cluster.html["instalar o RCF"] oulink:upgrade-rcf-software-9364d-cluster.html["atualize seu RCF"] conforme necessário.
