---
sidebar: sidebar 
permalink: switch-cisco-9364d-gx2a/reference-documentation-9364d.html 
keywords: shared storage cluster switch 
summary: Revise a documentação do switch Cisco e dos sistemas NetApp para instalação e manutenção do switch Cisco Nexus 9364D-GX2A nos sistemas AFX 1K e AFX 2K. 
---
= Consulte a documentação de referência do switch Cisco Nexus 9364D-GX2A
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Revise a documentação aplicável do switch Cisco e a documentação dos sistemas NetApp para instalação, configuração e manutenção do switch Cisco Nexus 9364D-GX2A nos sistemas AFX 1K e AFX 2K.



[[switch-documentation]]
== Documentação do Switch

Para configurar os switches Cisco Nexus 9364D-GX2A, você precisa da seguinte documentação de link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Suporte para switches Cisco Nexus série 9000"^].

[cols="1,2"]
|===
| Título do documento | Descrição 


 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9364d-gx2a/cisco-nexus-9364d-gx2a-nx-os-mode-switch-hardware-installation-guide.html["Guia de instalação de hardware do switch Cisco Nexus 9364D-GX2A NX-OS Mode"^]
 a| 
Fornece informações detalhadas sobre os requisitos do local, detalhes do hardware do switch e opções de instalação.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-and-configuration-guides-list.html["Guias de configuração de software para switches Cisco Nexus série 9000"^](escolha o guia para a versão do NX-OS instalada em seus switches)
 a| 
Fornece as informações iniciais de configuração do switch necessárias antes de configurá-lo para operação com ONTAP .



 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/upgrade/cisco-nexus-9000-nx-os-software-upgrade-downgrade-guide-101x.html["Guia de atualização e downgrade do software NX-OS da série Cisco Nexus 9000"^](escolha o guia para a versão do NX-OS instalada em seus switches)
 a| 
Fornece informações sobre como fazer o downgrade do software do switch para uma versão compatível com ONTAP , se necessário.



 a| 
link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/102x/command-reference/config/b_n9k_config_commands_1021.html["Guia de Comandos do Cisco Nexus Série 9000 NX-OS"^]
 a| 
Fornece links para as diversas referências de comandos disponibilizadas pela Cisco.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-system-message-guides-list.html["Referência de mensagens do sistema Cisco Nexus 9000 Series NX-OS"^]
 a| 
Descreve as mensagens do sistema para switches da série Cisco Nexus 9000, incluindo as informativas e outras que podem ajudar a diagnosticar problemas com links, hardware interno ou software do sistema.



 a| 
link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-release-notes-list.html["Notas de versão do NX-OS para a série Cisco Nexus 9000"^](Selecione as notas referentes à versão do NX-OS instalada em seus switches)
 a| 
Descreve as funcionalidades, os erros e as limitações da série Cisco Nexus 9000.



 a| 
link:https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/hw/regulatory/compliance/RCSI.html?dtid=osscdc000283&linkclickid=srch["Informações sobre conformidade regulamentar e segurança para a série Cisco Nexus 9000"^]
 a| 
Fornece informações sobre conformidade com agências internacionais, segurança e regulamentações para os switches da série Nexus 9000.

|===


[[ontap-systems-documentation]]
== Documentação dos sistemas ONTAP

Para configurar um sistema ONTAP, você precisa dos seguintes documentos para a sua versão do sistema operacional.

[cols="1,2"]
|===
| Nome | Descrição 


 a| 
link:https://docs.netapp.com/us-en/ontap-afx/index.html["Documentação dos sistemas AFX"^]
 a| 
Descreve como instalar o hardware da NetApp .



 a| 
link:https://docs.netapp.com/us-en/ontap-family/["Documentação do ONTAP"^]
 a| 
Fornece informações detalhadas sobre todos os aspectos das versões do ONTAP .



 a| 
link:https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fornece informações sobre configuração e compatibilidade de hardware da NetApp .

|===