= Crie uma entrada de interruptor para que o ONTAP possa monitorá-la.
:allow-uri-read: 




== Crie uma entrada de interruptor para que o ONTAP possa monitorá-la.

Use o `system switch ethernet create` Comando para configurar e ativar manualmente o monitoramento de um switch Ethernet específico.  Isso é útil caso o ONTAP não adicione o switch automaticamente ou se você o removeu anteriormente e deseja adicioná-lo novamente.

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
Um exemplo típico é adicionar um switch chamado [DeviceName], com endereço IP 1.2.3.4 e credenciais SNMPv2c definidas como *cshm1!*.  Usar `-type storage-network` em vez de `-type cluster-network` Se você estiver configurando um switch de armazenamento.



== Desative o monitoramento sem excluir o interruptor.

Se você deseja pausar ou interromper o monitoramento de um determinado switch, mas ainda mantê-lo para monitoramento futuro, modifique-o. `is-monitoring-enabled-admim` parâmetro em vez de excluí-lo.

Por exemplo:

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
Isso permite preservar os detalhes e a configuração do switch sem gerar novos alertas ou redescobertas.



== Remova um interruptor que você não precisa mais.

Usar `system switch ethernet delete` Para excluir um interruptor que foi desconectado ou não é mais necessário:

[source, cli]
----
system switch ethernet delete -device DeviceName
----
Por padrão, este comando só terá sucesso se o ONTAP não detectar o switch por meio de CDP ou LLDP.  Para remover um interruptor detectado, use o `-force` parâmetro:

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
Quando `-force` Se o ONTAP o detectar novamente, ele poderá ser adicionado novamente de forma automática.
