= Novo suporte para interruptor
:allow-uri-read: 




== Novo suporte para interruptor

[cols="25h,~,~"]
|===
| Interruptores | Descrição | Disponível a partir de 


 a| 
Switch Cisco de 32 portas 400GbE (X190300-CS-PI e X190300-PE)
 a| 
Suporte para switch Cisco 9332D-GX2B Intra-Cluster/HA/Armazenamento.
 a| 
ONTAP 9.17.1



 a| 
Switch Cisco de 64 portas 400GbE (X190310-CS-PI)
 a| 
Suporte para switch Cisco 9364D-GX2A Intra-Cluster/HA/Armazenamento.
 a| 
ONTAP 9.17.1



 a| 
Switch de cluster e armazenamento Cisco Nexus 9336C-FX2-T de 12 portas 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI)
 a| 
Suporta configurações de cluster 10/25/40/100GbE e configurações de armazenamento 100GbE (armazenamento conectado ao switch).
 a| 
ONTAP 9.10.1



 a| 
Switch de cluster e armazenamento Cisco Nexus 9336C-FX2-T de 12 portas 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI)
 a| 
Suporta configurações de cluster 10/25/40/100GbE e configurações de armazenamento 100GbE (armazenamento conectado ao switch).
 a| 
ONTAP 9.10.1



 a| 
Switch NVIDIA de 16 portas 100GbE (X190006-PE e X190006-PI)
 a| 
Suporte para switch de interconexão de cluster NVIDIA SN2100 e switch de armazenamento, incluindo suporte para configurações de IP MetroCluster .
 a| 
ONTAP 9.10.1



 a| 
Switch Cisco de 36 portas 100GbE (X190200-CS-PE e X190200-CS-PI)
 a| 
Suporta infraestrutura compartilhada (cluster, alta disponibilidade e armazenamento conectado ao switch) no mesmo par de switches Cisco Nexus 9336C-FX2, incluindo suporte para configurações IP MetroCluster .
 a| 
ONTAP 9.9.1



 a| 
Switch Cisco de 36 portas 100GbE (X190200-CS-PE e X190200-CS-PI), (X190210-FE-PE e X190210-FE-PI)
 a| 
O switch de interconexão de cluster e switch de armazenamento Cisco Nexus 9336C-FX2 oferece suporte para sistemas de armazenamento AFF e ASA , bem como para conectividade de dados de front-end.
 a| 
ONTAP 9.8



 a| 
Switch Broadcom BES-53248 (X190005 e X190005R)
 a| 
O switch de interconexão de cluster Broadcom BES-53248 oferece suporte a controladores AFF/ FAS com portas 10/25GbE e 40/100GbE.
 a| 
ONTAP 9.8



 a| 
Switch Cisco de 36 portas 100GbE (X190200) e switch Cisco de 32 portas 100GbE (X190100 e X190100R)
 a| 
O switch de armazenamento Cisco Nexus 3232C oferece suporte para conectar os sistemas de armazenamento AFF e ASA com gavetas de unidades NVMe NS224:

* AFF A800/ AFF ASA A800
* AFF A700/ AFF ASA A700
* AFF A400/ AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8

|===