= Novo suporte do interrutor
:allow-uri-read: 




== Novo suporte do interrutor

[cols="25h,~,~"]
|===
| Interrutores | Descrição | Disponível a partir do início 


 a| 
Switch Cisco de 32 portas 400GbE (X190300-CS-PI e X190300-PE)
 a| 
Suporte para switch Cisco 9332D-GX2B Intra-Cluster/HA/Armazenamento.
 a| 
ONTAP 9.17.1



 a| 
Switch Cisco de 64 portas 400GbE (X190310-CS-PI)
 a| 
Suporte para switch Cisco 9364D-GX2A Intra-Cluster/HA/Armazenamento.
 a| 
ONTAP 9.17.1



 a| 
Switch de cluster e armazenamento Cisco Nexus 9336C-FX2-T de 12 portas 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI)
 a| 
Suporta configurações de cluster de 10/25/40/100 GbE e configurações de armazenamento de 100 GbE (armazenamento conectado ao switch).
 a| 
ONTAP 9.10,1



 a| 
Switch de cluster e armazenamento Cisco Nexus 9336C-FX2-T de 12 portas 10/25/40/100GbE (X190212-CS-PE e X190212-CS-PI)
 a| 
Suporta configurações de cluster de 10/25/40/100 GbE e configurações de armazenamento de 100 GbE (armazenamento conectado ao switch).
 a| 
ONTAP 9.10,1



 a| 
Switch NVIDIA de 16 portas 100GbE (X190006-PE e X190006-PI)
 a| 
Suporte a switch de interconexão de cluster e switch de storage NVIDIA SN2100, incluindo suporte para configurações IP MetroCluster.
 a| 
ONTAP 9.10,1



 a| 
Switch Cisco de 36 portas 100GbE (X190200-CS-PE e X190200-CS-PI)
 a| 
Dá suporte a uma infraestrutura compartilhada (cluster, HA e storage conectado a switch) no mesmo par de switches Cisco Nexus 9336C-FX2, incluindo suporte para configurações IP MetroCluster.
 a| 
ONTAP 9.9,1



 a| 
Switch de 36 portas 100GbE Cisco (X190200-CS-PE e X190200-CS-PI), (X190210-FE-PE e X190210-FE-PI)
 a| 
Switch de interconexão de cluster Cisco Nexus 9336C-FX2X compatível com switch de storage e switch de storage para sistemas de storage AFF e ASA, bem como para conectividade de dados de front-end.
 a| 
ONTAP 9,8



 a| 
Switch Broadcom BES-53248 (X190005 e X190005R)
 a| 
Suporte para switch de interconexão de cluster BES-53248 Broadcom para controladores AFF/FAS com portas 10/25GbE e 40/100GbE.
 a| 
ONTAP 9,8



 a| 
Switch Cisco de 36 portas 100GbE (X190200) e switch Cisco de 32 portas 100GbE (X190100 e X190100R)
 a| 
Suporte ao switch de storage Cisco Nexus 3232C para conectar compartimentos de unidade NVMe NS224 sistemas de storage AFF e ASA:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9,8

|===