---
permalink: switch-cisco-9332d-gx2b/configure-verify-ssh-9332d.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9332d-gx2b 
summary: 'Se você estiver configurando seus switches como parte de uma nova instalação do sistema AFX 1K ou AFX 2K, uma substituição de switch ou uma redefinição para as configurações padrão de fábrica, e desejar usar o Cluster Switch Health Monitor (CSHM) e os recursos de coleta de logs, você deve verificar se o SSH e as chaves SSH estão habilitados nos switches.' 
---
= Verifique o SSH para coleta de logs - Cisco Nexus 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver configurando seus switches como parte de uma nova instalação do sistema AFX 1K ou AFX 2K, uma substituição de switch ou uma redefinição para as configurações padrão de fábrica, para usar o recurso de coleta de logs do monitor de integridade do switch Ethernet (CSHM), você deve verificar se o SSH está habilitado nos switches.

.Antes de começar
Você precisa estar conectado ao switch usando o console serial.

.Passos
. Verifique se o SSH está ativado:
+
[listing, subs="+quotes"]
----
(switch) *show ssh server*
ssh version 2 is enabled
----
. Verifique se as chaves SSH estão ativadas:
+
`show ssh key`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ssh key*

**************************************
rsa Keys generated:Wed May 14 18:49:37 2025

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCndfdJesautdCwk5Mk/7pKOFl0IeShc9uBtj74F52vbjyf1FHOCXX7Xf3Vopxs6L1hbzgCpFLo9E7pZBd3I+1AoLyQULtR3svzNieGY8mlWZGLtpKf/P2fDCd8JVJaejrwQhm49WUPiC6ziEqBDMOGhJpD2e9++umyDdr6
NbmK8Q==


bitcount:1024
fingerprint:
SHA256:QtNU+Qq2I4ZfYwEfMEB1+z8w7xaKTlantTdsjLBx+OU
**************************************
could not retrieve dsa key information
**************************************
ecdsa Keys generated:Wed May 14 18:50:56 2025


ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAAYnv17T+JlGmH8rg81xiOow0mPmkbkIG0o7h9EchixO3i3KjgQr8AwqkRHNTcQC3lRnizhJFUeMGCwuQTurziRCwE6fAOkWa2MRyXA1DYRKKXjVEOnW9+MvinMipHQ0cCc
YSExhh7j4HvWHIuYv8RmD7e3rmDQFlyyiLwdmpGfas2yaw==


bitcount:521
fingerprint:
SHA256:7cpZ5NGnIq5Iamw67ke+9o4qG9D3xxmGPauVl4X5934
**************************************

(switch)# *show feature | include scpServer*
scpServer              1          enabled
(switch)# *show feature | include ssh*
sshServer              1          enabled
(switch)#
----
====


.O que vem a seguir?
* Depois de verificar se o SSH está habilitado para coleta de logs, você link:../switch-cshm/cshm-overview.html["configurar monitor de integridade do switch Ethernet"].
+
** Depois de configurar o monitoramento de integridade do switch Ethernet, se você quiser aproveitar o recurso de suporte Smart Call Home da Cisco, você link:configure-smart-call-9332d.html["configurar Smart Call Home"].


* Se você configurou seu switch como parte de uma nova instalação do AFX 1K ou AFX 2K, você deve link:install-complete-afx-setup-9332d.html["Conclua a configuração do sistema AFX"].

