---
permalink: switch-cisco-9332d-gx2b/configure-install-upgrade-rcf-overview-9332d.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9332d-gx2b 
summary: Instale ou atualize o RCF nos switches Cisco Nexus 9332D-GX2B para instalações dos sistemas AFX 1K e AFX 2K, substituição de switches ou para oferecer suporte a novo hardware ou versões do ONTAP. 
---
= Saiba como instalar ou atualizar o RCF no switch Cisco Nexus 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Instale ou atualize o arquivo de configuração (RCF) nos switches Cisco Nexus 9332D-GX2B. Instale um novo RCF para instalações de sistema AFX 1K ou AFX 2K ou substituição de switch, ou atualize um RCF existente para oferecer suporte a novo hardware ou versões do ONTAP.


NOTE: A instalação ou atualização do RCF é independente da instalação ou atualização do NX-OS. Se você estiver instalando ou atualizando tanto o NX-OS quanto o RCF, recomenda-se instalar ou atualizar o NX-OS primeiro.



[[understand-the-supported-rcf-versions]]
=== Entenda as versões RCF suportadas

A versão do ONTAP em execução no seu sistema AFX e a versão do NX-OS nos seus switches determinam as versões de RCF suportadas pelos seus switches. As versões de RCF possuem configurações de velocidade de porta predefinidas que determinam quantas portas do switch estão no modo breakout (4x100GbE) e no modo não-breakout.

[NOTE]
====
Para obter a lista atual de versões RCF suportadas, consulte a link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco NetApp"^] página.

As informações sobre as portas do switch também podem ser encontradas na https://hwu.netapp.com["Hardware Universe da NetApp"^].

====
* Se você possui um sistema AFX 1K, o RCF 10.0 e versões posteriores são compatíveis.
* Se você possui um sistema AFX 2K, o RCF 10.1 e versões posteriores são compatíveis.
* O RCF 10.0 possui um único arquivo e suporta switches compartilhados, `Cluster-HA-Storage AFX RCF_10.0`.
+
Por exemplo, a tabela a seguir mostra os agrupamentos predefinidos das portas do switch, suas velocidades de porta e o uso para este arquivo RCF.

+
[cols="1,2"]
|===
| Grupos de portas de switch | Velocidades e uso das portas 


 a| 
Ethernet1/1/1-4 para Ethernet1/30/1-4
 a| 
Modo 4x100GbE para conexões de cluster, HA e armazenamento



 a| 
Ethernet 1/31, Ethernet 1/32
 a| 
400GbE ISL

|===
* O RCF 10.1 possui arquivos diferentes para diferentes casos de uso nos sistemas AFX 1K e AFX 2K. Dependendo de como você planeja usar os switches na configuração do seu sistema AFX 1K ou AFX 2K (compartilhado, somente storage ou apenas cluster e HA), você escolhe o arquivo RCF aplicável.
+
Por exemplo, se você estiver usando seus switches como switches compartilhados em um sistema AFX 2K, você usa o arquivo RCF apropriado para esse caso de uso. O arquivo RCF apropriado pode ter um nome semelhante a  `RCF-v10.1-NX9332D-GX2B-CL1-ST1-100GBR15-400G15.txt`. A tabela a seguir mostra os grupos predefinidos de portas do switch, suas velocidades de porta e o uso para este arquivo RCF.

+
[cols="1,2"]
|===
| Grupos de portas de switch | Velocidades e uso das portas 


 a| 
Ethernet1/1/1-4 para Ethernet1/15/1-4
 a| 
Modo 4x100GbE para conexões intra-cluster, HA e de prateleira de storage



 a| 
Ethernet1/16 para Ethernet1/30
 a| 
Modo 400GbE para conexões intracluster, HA e de storage



 a| 
Ethernet 1/31, Ethernet 1/32
 a| 
Conexões ISL intracluster de 400GbE

|===
+
[NOTE]
====
Você pode alterar os grupos predefinidos para ajustar o número de portas do switch no modo breakout (4x100GbE) e 400GbE quando precisar acomodar uma configuração de velocidade de porta diferente para o seu sistema AFX.

Você fará isso mais tarde, como parte do procedimento de instalação ou atualização do RCF.

====




[[change-port-speed-configuration]]
=== Alterar a configuração de velocidade da porta

Para switches com RCF 10.1 e versões posteriores, você pode alterar a configuração de velocidade da porta para ajustar o número de portas do switch no modo breakout (4x100GbE) e no modo não-breakout (400GbE) quando precisar acomodar uma configuração de velocidade de porta diferente para o seu sistema AFX.

Você realiza essa alteração como parte do procedimento de instalação ou atualização do RCF. Os procedimentos contêm etapas que direcionam você para esta página.

Você insere os comandos em ambos os switches.

[cols="1,2"]
|===
| Alterar a velocidade das portas | Passos 


 a| 
Alterar portas não breakout para portas breakout
 a| 
. Entre no modo de configuração na CLI.
. Modifique as velocidades das portas e os modos de breakout nos switches:
+
Para designar portas de breakout, use o comando  `interface breakout module`.

+
Por exemplo, para designar as portas 15 a 19 no modo 400GbE como portas breakout (4x100GbE), use o seguinte:

+
`interface breakout module 1 port 15-19 map 100g-4x`

. Modifique a lista de portas com as novas portas que precisam usar o perfil de porta para a velocidade de porta desejada.
+
Por exemplo, para modificar a lista de portas com as novas portas, 15-19, para o perfil de porta de velocidade 100G, use o seguinte:

+
`interface e1/15/1-4, e1/16/1-4, e1/17/1-4, e1/18/1-4, e1/19/1-4`

. Configure manualmente as portas breakout do switch (4x100GbE) para 100GbE. Se você não configurar manualmente a velocidade, as portas não serão ativadas e ficarão em estado desabilitado por erro.
+
`speed 100000`

+
`no negotiate auto`





 a| 
Retornar portas de breakout para portas não-breakout
 a| 
. Entre no modo de configuração na CLI.
. Para retornar as portas de breakout para portas não-breakout, use o comando  `no interface breakout` no modo de configuração.
+
Por exemplo, para retornar as portas 15-19 ao modo 400GbE, use o seguinte:

+
`no interface breakout module 1 port 15-19`



|===


[[suggested-documentation]]
=== Documentação sugerida

Antes de instalar ou atualizar o RCF em seus switches, recomenda-se que você revise a seguinte documentação:

* Consulte o artigo da Knowledge Base da NetApp link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração de um switch de interconexão Cisco mantendo a conectividade remota"^] para obter mais informações ao instalar ou atualizar seu RCF.
* Consulte o  https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para verificar as portas corretas em sua plataforma.
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco (NSS)"^]
+
Consulte a tabela de compatibilidade de switches para obter informações sobre as versões ONTAP e RCF suportadas no site de suporte da NetApp .  Note que pode haver dependências entre a sintaxe de comandos no RCF e a sintaxe encontrada em versões específicas do NX-OS.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Switches Cisco Nexus série 9000"^]
+
Consulte os guias de software e atualização apropriados disponíveis no site da Cisco para obter a documentação completa sobre os procedimentos de atualização e downgrade dos switches Cisco .



.O que vem a seguir?
Após revisar a visão geral de instalação ou atualização do RCF, você link:configure-install-rcf-9332d.html["instalar o RCF"] ou link:configure-upgrade-rcf-9332d.html["atualizar RCF"] conforme necessário.
