---
permalink: switch-cisco-9332d-gx2b/migrate-to-2n-switched-9332d-cluster.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched 9332D-GX2B cluster environment,switchless cluster environments,9332D-GX2B switches 
summary: Se você tiver um ambiente de cluster sem switch de dois nós existente, poderá migrar para um ambiente de cluster com switch de dois nós usando switches Cisco Nexus 9332D-GX2B para permitir o dimensionamento além de dois nós no cluster. 
---
= Migrar para um cluster comutado de dois nós
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você tiver um ambiente de cluster _sem switch_ de dois nós existente, poderá migrar para um ambiente de cluster _com switch_ de dois nós usando switches Cisco Nexus 9332D-GX2B.

O processo de migração funciona para todos os nós que utilizam portas ópticas ou Twinax, mas não é suportado neste switch se os nós estiverem utilizando portas RJ45 10Gb BASE-T integradas para as portas de rede do cluster.



== Requisitos de revisão

.O que você vai precisar
* Para a configuração sem switch de dois nós:
+
** A configuração sem switch de dois nós está configurada corretamente e funcionando.
** Todas as portas do cluster estão no estado *ativo*.
** Todas as interfaces lógicas do cluster (LIFs) estão no estado *ativo* e em suas portas de origem.
** Ver https://hwu.netapp.com["Hardware Universe"^] Para todas as versões ONTAP suportadas.


* Para a configuração do switch Cisco Nexus 9332D-GX2B:
+
** Ambos os switches possuem conectividade de rede de gerenciamento.
** É possível acessar os switches do cluster através do console.
** As conexões nó a nó e switch a switch do Nexus 9332D-GX2B usam cabos Twinax ou de fibra.
+
Ver https://hwu.netapp.com["Hardware Universe"^] Para obter mais informações sobre cabeamento.



* Os cabos Inter-Switch Link (ISL) são conectados às portas 1/35 e 1/36 em ambos os switches 9332D-GX2B.
* A personalização inicial dos dois switches 9332D-GX2B foi concluída, de modo que:
+
** Os switches 9332D-GX2B estão executando a versão mais recente do software.
** Os arquivos de configuração de referência (RCFs) são aplicados aos switches.  Qualquer personalização do site, como SMTP, SNMP e SSH, é configurada nos novos switches.




.Sobre os exemplos
Os exemplos neste procedimento utilizam a seguinte nomenclatura de comutador de cluster e nó:

* Os nomes dos switches 9332D-GX2B2 são cs1 e cs2.
* Os nomes dos SVMs do cluster são node1 e node2.
* Os nomes dos LIFs são node1_clus1 e node1_clus2 no nó 1, e node2_clus1 e node2_clus2 no nó 2, respectivamente.
* O `cluster1::*>` O prompt indica o nome do cluster.
* As portas do cluster utilizadas neste procedimento são e0a e e0b.


Ver https://hwu.netapp.com["Hardware Universe"^] Para obter informações sobre as portas de cluster para suas plataformas.



== Migre os switches



=== Etapa 1: Prepare-se para a migração

. Se o AutoSupport estiver ativado neste cluster, suprima a criação automática de casos invocando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
onde x representa a duração do período de manutenção em horas.

+

NOTE: A mensagem do AutoSupport notifica o suporte técnico sobre essa tarefa de manutenção, de forma que a criação automática de chamados seja suprimida durante o período de manutenção.

. Altere o nível de privilégio para avançado, inserindo `y` Quando solicitado a continuar:
+
`set -privilege advanced`

+
O prompt avançado(`*>` ) aparece.





=== Etapa 2: Configurar portas e cabos

. Desative todas as portas voltadas para os nós (exceto as portas ISL) nos dois novos switches do cluster, cs1 e cs2.
+
Não desative as portas ISL.

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas voltadas para o nó, de 1 a 34, estão desativadas no switch cs1:

[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs1(config-if-range)# shutdown
----
====
. Verifique se o ISL e as portas físicas no ISL entre os dois switches 9332D-GX2B cs1 e cs2 estão ativos nas portas 1/35 e 1/36:
+
`show port-channel summary`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas ISL estão ativas no switch cs1:

[listing]
----
cs1# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
O exemplo a seguir mostra que as portas ISL estão ativas no switch cs2:

[listing]
----
(cs2)# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====
. Exibir a lista de dispositivos vizinhos:
+
`show cdp neighbors`

+
Este comando fornece informações sobre os dispositivos que estão conectados ao sistema.

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir lista os dispositivos vizinhos no switch cs1:

[listing]
----
cs1# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
O exemplo a seguir lista os dispositivos vizinhos no switch cs2:

[listing]
----
cs2# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====
. Verifique se todas as portas do cluster estão ativas:
+
`network port show -ipspace Cluster`

+
Cada porta deve aparecer para cima. `Link` e saudável para `Health Status` .

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
====
. Verifique se todas as LIFs do cluster estão ativas e operacionais:
+
`network interface show -vserver Cluster`

+
Cada LIF de cluster deve exibir `true` para `Is Home` e tenha um `Status Admin/Oper` de cima/para cima.

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -vserver Cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. Verifique se a reversão automática está ativada em todas as LIFs do cluster:
+
`network interface show -vserver Cluster -fields auto-revert`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====
. Desconecte o cabo da porta do cluster e0a no nó 1 e, em seguida, conecte e0a à porta 1 no switch do cluster cs1, usando o cabeamento apropriado suportado pelos switches 9332D-GX2B.
+
O https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - Switches"^] Contém mais informações sobre cabeamento.

+
https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - Switches"^]

. Desconecte o cabo da porta do cluster e0a no nó 2 e, em seguida, conecte e0a à porta 2 no switch do cluster cs1, usando o cabeamento apropriado suportado pelos switches 9332D-GX2B.
. Habilite todas as portas voltadas para os nós no switch de cluster cs1.
+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas 1/1 a 1/34 estão habilitadas no switch cs1:

[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs1(config-if-range)# no shutdown
----
====
. Verifique se todas as LIFs do cluster estão ativas, operacionais e exibidas como `true` para `Is Home` :
+
`network interface show -vserver Cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todas as LIFs estão ativas no nó 1 e no nó 2 e que `Is Home` Os resultados são verdadeiros:

[listing]
----
cluster1::*> network interface show -vserver Cluster

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true

4 entries were displayed.
----
====
. Exibir informações sobre o estado dos nós no cluster:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir exibe informações sobre a integridade e a elegibilidade dos nós no cluster:

[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. Desconecte o cabo da porta do cluster e0b no nó 1 e, em seguida, conecte e0b à porta 1 no switch do cluster cs2, usando o cabeamento apropriado suportado pelos switches 9332D-GX2B.
. Desconecte o cabo da porta do cluster e0b no nó 2 e, em seguida, conecte e0b à porta 2 no switch do cluster cs2, usando o cabeamento apropriado suportado pelos switches 9332D-GX2B.
. Habilite todas as portas voltadas para os nós no switch de cluster cs2.
+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas 1/1 a 1/34 estão habilitadas no switch cs2:

[listing]
----
cs2# config
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs2(config-if-range)# no shutdown
----
====
. Verifique se todas as portas do cluster estão ativas:
+
`network port show -ipspace Cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todas as portas do cluster estão ativas no nó 1 e no nó 2:

[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
====




=== Etapa 3: Verifique a configuração

. Verifique se todas as interfaces exibem verdadeiro para `Is Home` :
+
`network interface show -vserver Cluster`

+

NOTE: Isso pode levar alguns minutos para ser concluído.

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que todas as LIFs estão ativas no nó 1 e no nó 2 e que `Is Home` Os resultados são verdadeiros:

[listing]
----
cluster1::*> network interface show -vserver Cluster

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true

4 entries were displayed.
----
====
. Verifique se ambos os nós possuem uma conexão com cada switch:
+
`show cdp neighbors`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra os resultados apropriados para ambas as opções:

[listing]
----
(cs1)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           FAS2980       e0a
node2              Eth1/2         133    H           FAS2980       e0a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 4

(cs2)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           FAS2980       e0b
node2              Eth1/2         133    H           FAS2980       e0b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 4
----
====
. Exibir informações sobre os dispositivos de rede descobertos em seu cluster:
+
`network device-discovery show -protocol cdp`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C9336C
            e0b    cs2                       0/2               N9K-C9336C
node1      /cdp
            e0a    cs1                       0/1               N9K-C9336C
            e0b    cs2                       0/1               N9K-C9336C

4 entries were displayed.
----
====
. Verifique se as configurações estão desativadas:
+
`network options switchless-cluster show`

+

NOTE: A conclusão do comando pode levar alguns minutos.  Aguarde o anúncio de que o tempo de vida de 3 minutos está prestes a expirar.

+
.Mostrar exemplo
[%collapsible]
====
O resultado incorreto no exemplo a seguir mostra que as configurações estão desativadas:

[listing]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: false
----
====
. Verifique o status dos nós membros do cluster:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra informações sobre a saúde e a elegibilidade dos nós no cluster:

[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Verifique a conectividade das interfaces do cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e posterior
--
Você pode usar o `network interface check cluster-connectivity` Comando para iniciar uma verificação de acessibilidade para conectividade do cluster e, em seguida, exibir os detalhes:

`network interface check cluster-connectivity start`e `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Aguarde alguns segundos antes de executar o `show` comando para exibir os detalhes.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas as versões do ONTAP
--
Para todas as versões do ONTAP , você também pode usar o `cluster ping-cluster -node <name>` comando para verificar a conectividade:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[passo 7]] Altere o nível de privilégio de volta para administrador:
+
`set -privilege admin`

. Se você desativou a criação automática de casos, reative-a enviando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que vem a seguir?
link:../switch-cshm/config-overview.html["Configure o monitoramento de integridade do switch."].
