---
permalink: switch-cisco-9332d-gx2b/replace-9332d-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9332d-gx2b cluster switch - cisco nexus 9332d-gx2b 
summary: 'A substituição de um switch Nexus 9332D-GX2B com defeito em uma rede de cluster é um procedimento não disruptivo \(NDU\).' 
---
= Substituir um switch Cisco Nexus 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estas etapas para substituir um switch Nexus 9332D-GX2B com defeito em uma rede compartilhada. Este é um procedimento não disruptivo (NDU).



== Rever os requisitos

Antes de efetuar a substituição do interrutor, certifique-se de que:

* Você verificou o número de série do switch para garantir que o switch correto seja substituído.
* No cluster existente e na infra-estrutura de rede:
+
** O cluster existente é verificado como completamente funcional, com pelo menos um switch de cluster totalmente conetado.
** Todas as portas do cluster estão ativas.
** Todas as interfaces lógicas de cluster (LIFs) estão ativas e em suas portas domésticas.
** O ONTAP `cluster ping-cluster -node <node-name>` O comando deve indicar que a conectividade básica e a comunicação maior que PMTU são bem-sucedidas em todos os caminhos.


* No switch de substituição Nexus 9332D-GX2B:
+
** A conetividade de rede de gerenciamento no switch de substituição está funcional.
** O acesso do console ao interrutor de substituição está no lugar.
** As conexões do nó são as portas 1/1 a 1/30.
** Todas as portas Inter-Switch Link (ISL) estão desabilitadas nas portas 1/31 e 1/32.
** O arquivo de configuração de referência desejado (RCF) e o interrutor de imagem do sistema operacional NX-os são carregados no switch.
** A personalização inicial do switch está concluída, conforme detalhado emlink:setup-switch-9332d-cluster.html["Configurar o switch de cluster 9332D-GX2B"] .
+
Quaisquer personalizações de sites anteriores, como STP, SNMP e SSH, são copiadas para o novo switch.



* Você executou o comando para migrar um LIF de cluster do nó onde o LIF de cluster está hospedado.




== Ativar o registo da consola

O NetApp recomenda fortemente que você ative o log do console nos dispositivos que você está usando e execute as seguintes ações ao substituir o switch:

* Deixe o AutoSupport ativado durante a manutenção.
* Acione um AutoSupport de manutenção antes e depois da manutenção para desativar a criação de casos durante a manutenção. Consulte este artigo da base de dados de Conhecimento https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: Como suprimir a criação automática de casos durante as janelas de manutenção programada"^] para obter mais detalhes.
* Ativar o registo de sessão para quaisquer sessões CLI. Para obter instruções sobre como ativar o registo de sessão, consulte a secção "saída de sessão de registo" neste artigo da base de dados de conhecimento https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Como configurar o PuTTY para uma conetividade ideal aos sistemas ONTAP"^] .




== Substitua o interrutor

.Sobre os exemplos
Os exemplos deste procedimento utilizam a seguinte nomenclatura de switch e nó:

* Os nomes dos switches Nexus 9332D-GX2B existentes são cs1 e cs2.
* O nome do novo switch Nexus 9332D-GX2B é newcs2.
* Os nomes dos nós são node1-01, node1-02, node1-03 e node1-04.
* Os nomes do cluster LIF são node1-01_clus1 e node1-01_clus2 para node1-01, node1-02_clus1 e node1-02_clus2 para node1-02, node1-03_clus1 e node1-03_clus2 para node1-03 e node1-04_clus1 e node1-04_clus2 para node1-04.
* O prompt para alterações em todos os nós de cluster é cluster1::*>


.Sobre esta tarefa
O procedimento a seguir é baseado na seguinte topologia de rede de cluster:

.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.


cluster1::*> *network interface show -vserver Cluster*
            Logical    Status     Network            Current     Current   Is
Vserver     Interface  Admin/Oper Address/Mask       Node        Port      Home
----------- ---------- ---------- ------------------ ----------- --------- ----
Cluster
            node1-01_clus1 up/up  169.254.36.44/16    node1-01    e7a      true
            node1-01_clus2 up/up  169.254.7.5/16      node1-01    e7b      true
            node1-02_clus1 up/up  169.254.197.206/16  node1-02    e7a      true
            node1-02_clus2 up/up  169.254.195.186/16  node1-02    e7b      true
            node1-03_clus1 up/up  169.254.192.49/16   node1-03    e7a      true
            node1-03_clus2 up/up  169.254.182.76/16   node1-03    e7b      true
            node1-04_clus1 up/up  169.254.59.49/16    node1-04    e7a      true
            node1-04_clus2 up/up  169.254.62.244/16   node1-04    e7b      true

8 entries were displayed.

cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e11a   cs1(FLMXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e11b   cs2(FDOXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e1a    cs1(FLMXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            e1b    cs2(FDOXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B
            e7b    cs2(FDOXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B

cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Device-ID          Local Intrfce  Hldtme Capability  Platform         Port ID
cs2(FDOXXXXXXXX)    Eth1/31        179    R S I s   N9K-C9364D-GX2A   Eth1/63
cs2(FDOXXXXXXXX)    Eth1/32        179    R S I s   N9K-C9364D-GX2A   Eth1/64
node1-01            Eth1/4/1       123    H         AFX-1K            e1a
node1-01            Eth1/4/2       123    H         AFX-1K            e7a
node1-01            Eth1/4/3       123    H         AFX-1K            e10a
node1-01            Eth1/4/4       123    H         AFX-1K            e11a
node1-02            Eth1/9/1       138    H         AFX-1K            e1a
node1-02            Eth1/9/2       138    H         AFX-1K            e7a
node1-02            Eth1/9/3       138    H         AFX-1K            e10a
node1-02            Eth1/9/4       138    H         AFX-1K            e11a
node1-03            Eth1/15/1      138    H         AFX-1K            e1a
node1-03            Eth1/15/2      138    H         AFX-1K            e7a
node1-03            Eth1/15/3      138    H         AFX-1K            e10a
node1-03            Eth1/15/4      138    H         AFX-1K            e11a
node1-04            Eth1/16/1      173    H         AFX-1K            e1a
node1-04            Eth1/16/2      173    H         AFX-1K            e7a
node1-04            Eth1/16/3      173    H         AFX-1K            e10a
node1-04            Eth1/16/4      173    H         AFX-1K            e11a

Total entries displayed: 18

cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Device-ID          Local Intrfce  Hldtme Capability  Platform         Port ID
cs1(FLMXXXXXXXX)    Eth1/31        179    R S I s   N9K-C9364D-GX2A   Eth1/63
cs1(FLMXXXXXXXX)    Eth1/32        179    R S I s   N9K-C9364D-GX2A   Eth1/64
node1-01            Eth1/4/1       123    H         AFX-1K            e1a
node1-01            Eth1/4/2       123    H         AFX-1K            e7a
node1-01            Eth1/4/3       123    H         AFX-1K            e10a
node1-01            Eth1/4/4       123    H         AFX-1K            e11a
node1-02            Eth1/9/1       138    H         AFX-1K            e1a
node1-02            Eth1/9/2       138    H         AFX-1K            e7a
node1-02            Eth1/9/3       138    H         AFX-1K            e10a
node1-02            Eth1/9/4       138    H         AFX-1K            e11a
node1-03            Eth1/15/1      138    H         AFX-1K            e1a
node1-03            Eth1/15/2      138    H         AFX-1K            e7a
node1-03            Eth1/15/3      138    H         AFX-1K            e10a
node1-03            Eth1/15/4      138    H         AFX-1K            e11a
node1-04            Eth1/16/1      173    H         AFX-1K            e1a
node1-04            Eth1/16/2      173    H         AFX-1K            e7a
node1-04            Eth1/16/3      173    H         AFX-1K            e10a
node1-04            Eth1/16/4      173    H         AFX-1K            e11a

Total entries displayed: 18
----
====


=== Passo 1: Prepare-se para a substituição

. Se o AutoSupport estiver ativado neste cluster, suprimir a criação automática de casos invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
onde x é a duração da janela de manutenção em horas.

+

NOTE: A mensagem AutoSupport notifica o suporte técnico desta tarefa de manutenção para que a criação automática de casos seja suprimida durante a janela de manutenção.

. Instale o RCF e a imagem apropriados no interrutor, newcs2, e faça os preparativos necessários para o local.
+
Se necessário, verifique, baixe e instale as versões apropriadas do software RCF e NX-os para o novo switch. Se tiver verificado que o novo switch está corretamente configurado e não precisa de atualizações para o software RCF e NX-os, avance para o passo 2.

+
.. Vá para a página _NetApp Cluster and Management Network switches Referência Configuração do arquivo Descrição_ no site de suporte da NetApp.
.. Clique no link para a _Cluster Network and Management Network Compatibility Matrix_ e observe a versão necessária do software do switch.
.. Clique na seta de volta do navegador para retornar à página Descrição, clique em *CONTINUAR*, aceite o contrato de licença e vá para a página Download.
.. Siga as etapas na página Download para baixar os arquivos RCF e NX-os corretos para a versão do software ONTAP que você está instalando.


. No novo switch, efetue login como administrador e desligue todas as portas que serão conectadas às interfaces do cluster de nós (portas 1/1 a 1/30).
+
Se o interrutor que está a substituir não estiver funcional e estiver desligado, avance para o passo 4. As LIFs nos nós de cluster já devem ter falhado para a outra porta de cluster para cada nó.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
newcs2# *config*
newcs2(config)# *interface e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7/1-4,e1/8/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/9/1-4,e1/10/1-4,e1/11/1-4,e1/12/1-4,e1/13/1-4,e1/14/1-4,e1/15/1-4,e1/16/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/17/1-4,e1/18/1-4,e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-44,e1/23/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/24/1-,e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-44*
newcs2(config-if-range)# *shutdown*
newcs2(config-if-range)# exit
newcs2(config)# exit
----
====
. Verifique se todas as LIFs do cluster têm a reversão automática ativada:
+
[source, cli]
----
network interface show -vserver Cluster -fields auto-revert
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

             Logical
Vserver      Interface        Auto-revert
------------ ---------------- -------------
Cluster      node1-01_clus1   true
Cluster      node1-02_clus2   true
Cluster      node1-03_clus1   true
Cluster      node1-04_clus2   true

4 entries were displayed.
----
====
. Verifique a conectividade das interfaces de cluster remotas:
+
.. Você pode usar o `network interface check cluster-connectivity show` comando para exibir os detalhes de uma verificação de acessibilidade para conectividade de cluster:
+
[source, cli]
----
network interface check cluster-connectivity show
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                     Source          Destination     Packet
Node      Date                       LIF             LIF             Loss
--------- -------------------------- --------------- --------------- -----------
node1-01
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
====
.. Alternativamente, você também pode usar o `cluster ping-cluster -node <node-name>` comando para verificar a conectividade:
+
`cluster ping-cluster -node <node-name>`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====






=== Etapa 2: Configurar cabos e portas

. Desligue as portas ISL Eth1/31 e Eth1/32 no switch Nexus 9332D-GX2B cs1.
+
[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/31-32*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# exit
cs1(config)# exit
----
. Remova todos os cabos do switch Nexus 9332D-GX2B cs2 e conecte-os às mesmas portas no switch 9332D-GX2B newcs2.
. Abra as portas ISLs Eth1/31 e Eth1/32 entre os switches cs1 e newcs2 e, em seguida, verifique o status da operação do canal da porta.
+
Port-Channel deve indicar Po1(SU) e Member Ports deve indicar Eth1/31(P) e Eth1/32(P).

+
.Mostrar exemplo
[%collapsible]
====
Este exemplo habilita as portas ISL Eth1/31 e Eth1/32 e exibe o resumo do canal de porta no switch cs1:

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *int e1/31-32*
cs1(config-if-range)# *no shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
cs1#
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
999   Po999(SD)   Eth      NONE      --
----
====
. Verifique se a porta e7b está ativa em todos os nós:
+
[source, cli]
----
network port show ipspace Cluster
----
+
.Mostrar exemplo
[%collapsible]
====
A saída deve ser semelhante ao seguinte:

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.
----
====
. No mesmo nó usado na etapa anterior, reverta o LIF do cluster associado à porta na etapa anterior usando o comando de reversão da interface de rede.
+
.Mostrar exemplo
[%collapsible]
====
Neste exemplo, o LIF node1-01_clus2 no node1-01 é revertido com sucesso se o valor Home for verdadeiro e a porta for e7b.

Os comandos a seguir retornam LIF `node1-01_clus2` sobre `node1-01` para o porto de origem `e7a` e exibe informações sobre os LIFs em ambos os nós.  A ativação do primeiro nó será bem-sucedida se a coluna Is Home for verdadeira para ambas as interfaces do cluster e elas mostrarem as atribuições de porta corretas, neste exemplo `e7a` e `e7b` no nó1-01.

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical        Status     Network            Current    Current Is
Vserver   Interface      Admin/Oper Address/Mask       Node       Port    Home
--------- -------------- ---------- ------------------ ---------- ------- -----
Cluster
          node1-01_clus1  up/up     169.254.209.69/16  node1-01   e7a     true
          node1-01_clus2  up/up     169.254.49.125/16  node1-01   e7b     true
          node1-02_clus1  up/up     169.254.47.194/16  node1-02   e7b     true
          node1-02_clus2  up/up     169.254.19.183/16  node1-02   e7a     false
          .
          .
          .
----
====
. Exibir informações sobre os nós em um cluster:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
Este exemplo mostra que a integridade do nó para node1 e node2 neste cluster é verdadeira:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node           Health  Eligibility
-------------- ------- ------------
node1-01       false   true
node1-02       true    true
node1-03       true    true
node1-04       true    true
----
====
. Verifique se todas as portas de cluster físico estão ativas:
+
[source, cli]
----
network port show ipspace Cluster
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false
.
.
.
----
====
. Verifique a conectividade das interfaces de cluster remotas:
+
.. Você pode usar o `network interface check cluster-connectivity` comando para exibir os detalhes de uma verificação de acessibilidade para conectividade de cluster:
+
[source, cli]
----
network interface check cluster-connectivity start
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                     Source          Destination     Packet
Node      Date                       LIF             LIF             Loss
--------- -------------------------- --------------- --------------- -----------
node1-01
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
====
.. Alternativamente, você também pode usar o `cluster ping-cluster -node <node-name>` comando para verificar a conectividade:
+
`cluster ping-cluster -node <node-name>`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====






=== Etapa 3: Verifique a configuração

. Verifique a integridade de todas as portas no cluster.
+
.. *Portas de cluster*
+
... Verifique se as portas do cluster estão ativas e íntegras em todos os nós do cluster:
+
[source, cli]
----
network port show ipspace Cluster
----
+
[source, cli]
----
network interface show -vserver Cluster
----
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
[source, cli]
----
show cdp neighbors
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*
Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.

cluster1::*> *network interface show -vserver Cluster*

          Logical       Status     Network            Current    Current Is
Vserver   Interface     Admin/Oper Address/Mask       Node       Port    Home
--------- ------------- ---------- ------------------ ---------- ------- ----
Cluster
          node1-01_clus1  up/up    169.254.209.69/16  node1-01   e7a     true
          node1-01_clus2  up/up    169.254.49.125/16  node1-01   e7b     true
          node1-02_clus1  up/up    169.254.47.194/16  node1-02   e7b     true
          node1-02_clus2  up/up    169.254.19.183/16  node1-02   e7a     true
          node1-03_clus1  up/up    169.254.209.69/16  node1-03   e7a     true
          node1-03_clus2  up/up    169.254.49.125/16  node1-03   e7b     true
          node1-04_clus1  up/up    169.254.47.194/16  node1-04   e7b     true
          node1-04_clus2  up/up    169.254.19.183/16  node1-04   e7a     false

8 entries were displayed.

cluster1::> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/16/3    N9K-C9332D-GX2B
            e11a   cs1(FLMXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e11b   cs2(FDOXXXXXXXX)          Ethernet1/16/4    N9K-C9332D-GX2B
            e1a    cs1(FLMXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            e1b    cs2(FDOXXXXXXXX)          Ethernet1/16/1    N9K-C9332D-GX2B
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B
            e7b    cs2(FDOXXXXXXXX)          Ethernet1/16/2    N9K-C9332D-GX2B
.
.
.

cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce  Hldtme Capability  Platform          Port ID
newcs2(FDOXXXXXXXX)   Eth1/31        179    R S I s     N9K-C9364D-GX2A   Eth1/63
newcs2(FDOXXXXXXXX)   Eth1/32        179    R S I s     N9K-C9364D-GX2A   Eth1/64
node1-01              Eth1/4/1       123    H           AFX-1K            e1a
node1-01              Eth1/4/2       123    H           AFX-1K            e7a
node1-01              Eth1/4/3       123    H           AFX-1K            e10a
node1-01              Eth1/4/4       123    H           AFX-1K            e11a
node1-02              Eth1/9/1       138    H           AFX-1K            e1a
node1-02              Eth1/9/2       138    H           AFX-1K            e7a
node1-02              Eth1/9/3       138    H           AFX-1K            e10a
node1-02              Eth1/9/4       138    H           AFX-1K            e11a
node1-03              Eth1/15/1      138    H           AFX-1K            e1a
node1-03              Eth1/15/2      138    H           AFX-1K            e7a
node1-03              Eth1/15/3      138    H           AFX-1K            e10a
node1-03              Eth1/15/4      138    H           AFX-1K            e11a
node1-04              Eth1/16/1      173    H           AFX-1K            e1a
node1-04              Eth1/16/2      173    H           AFX-1K            e7a
node1-04              Eth1/16/3      173    H           AFX-1K            e10a
node1-04              Eth1/16/4      173    H           AFX-1K            e11a

Total entries displayed: 18


newcs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform          Port ID
cs1(FDOXXXXXXXX)   Eth1/31        179    R S I s     N9K-C9364D-GX2A   Eth1/63
cs1(FDOXXXXXXXX)   Eth1/32        179    R S I s     N9K-C9364D-GX2A   Eth1/64
node1-01           Eth1/4/1       123    H           AFX-1K            e1a
node1-01           Eth1/4/2       123    H           AFX-1K            e7a
node1-01           Eth1/4/3       123    H           AFX-1K            e10a
node1-01           Eth1/4/4       123    H           AFX-1K            e11a
node1-02           Eth1/9/1       138    H           AFX-1K            e1a
node1-02           Eth1/9/2       138    H           AFX-1K            e7a
node1-02           Eth1/9/3       138    H           AFX-1K            e10a
node1-02           Eth1/9/4       138    H           AFX-1K            e11a
node1-03           Eth1/15/1      138    H           AFX-1K            e1a
node1-03           Eth1/15/2      138    H           AFX-1K            e7a
node1-03           Eth1/15/3      138    H           AFX-1K            e10a
node1-03           Eth1/15/4      138    H           AFX-1K            e11a
node1-04           Eth1/16/1      173    H           AFX-1K            e1a
node1-04           Eth1/16/2      173    H           AFX-1K            e7a
node1-04           Eth1/16/3      173    H           AFX-1K            e10a
node1-04           Eth1/16/4      173    H           AFX-1K            e11a

Total entries displayed: 18
----
====


.. *Portas HA*
+
... Verifique se todas as portas HA estão ativas e com status íntegro:
+
`ha interconnect status show -node <node-name>`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====


.. *Portas de armazenamento*
+
... Verifique se todas as portas de armazenamento estão ativas e com status íntegro:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-02
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-03
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
node1-04
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
16 entries were displayed.
----
====


.. *Portas de prateleira de armazenamento*
+
... Verifique se todas as portas da prateleira de armazenamento estão ativas e com status íntegro:
+
[source, cli]
----
storage shelf port show
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false

16 entries were displayed.
----
====
... Verifique o status da conexão de todas as portas da prateleira de armazenamento:
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 CX9332D-cs1
1.1   1  connected       Ethernet1/15/1 CX9364D-cs1
1.1   2  connected       Ethernet1/17/2 CX9332D-cs1
1.1   3  connected       Ethernet1/15/2 CX9364D-cs1
1.1   4  connected       Ethernet1/17/3 CX9332D-cs1
1.1   5  connected       Ethernet1/15/3 CX9364D-cs1
1.1   6  connected       Ethernet1/17/4 CX9332D-cs1
1.1   7  connected       Ethernet1/15/4 CX9364D-cs1
1.1   8  connected       Ethernet1/19/1 CX9332D-cs1
1.1   9  connected       Ethernet1/17/1 CX9364D-cs1
1.1   10 connected       Ethernet1/19/2 CX9332D-cs1
1.1   11 connected       Ethernet1/17/2 CX9364D-cs1
1.1   12 connected       Ethernet1/19/3 CX9332D-cs1
1.1   13 connected       Ethernet1/17/3 CX9364D-cs1
1.1   14 connected       Ethernet1/19/4 CX9332D-cs1
1.1   15 connected       Ethernet1/17/4 CX9364D-cs1

16 entries were displayed.
----
====




. Se você suprimiu a criação automática de casos, reative-a invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que se segue?
Depois de substituir seus interruptores, vocêlink:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"] .
