---
permalink: switch-cisco-9332d-gx2b/setup-switch-9332d-cluster.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9332d-gx2b 
summary: Siga este procedimento para configurar o switch Cisco Nexus 9332D-GX2B. 
---
= Configurar o switch 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para configurar o switch Cisco Nexus 9332D-GX2B.

.Antes de começar
Certifique-se de ter:

* Ligue seus interruptores.
* Acesso a um servidor HTTP, FTP ou TFTP no local de instalação para baixar as versões aplicáveis do NX-OS e do Arquivo de Configuração de Referência (RCF).
* Versão aplicável do NX-OS, baixada de https://software.cisco.com/download/home["Download do software Cisco"^] página.


[IMPORTANT]
====
* O NX-OS 10.4.2 é a única versão suportada para switches Cisco Nexus 9332D-GX2B em um cluster ONTAP .
* Não atualize ou faça downgrade da sua versão do NX-OS para uma versão não suportada; somente a 10.4.2 é suportada atualmente.


====
* Licenças aplicáveis, informações de rede e configuração, e cabos.
* Os RCFs aplicáveis ​​para redes compartilhadas e redes de gerenciamento da NetApp podem ser baixados do site de suporte da NetApp em http://mysupport.netapp.com/["meusuporte.netapp.com"^] . Todos os switches de rede compartilhada e de gerenciamento da Cisco vêm com a configuração padrão de fábrica da Cisco . Esses switches também têm a versão atual do software NX-OS, mas não têm os RCFs carregados.
* link:required-documentation-9332d-cluster.html["Documentação necessária sobre switches e ONTAP"].


.Passos
. Execute uma configuração inicial dos switches de rede compartilhados.
+
Ao ligar o switch pela primeira vez, responda às seguintes perguntas de configuração inicial, conforme necessário.  A política de segurança do seu site define as respostas e os serviços a serem ativados.

+
[cols="1,2"]
|===
| Incitar | Resposta 


 a| 
Cancelar o provisionamento automático e continuar com a configuração normal?  (sim/não)
 a| 
Responda com *sim*.  A opção padrão é não.



 a| 
Deseja implementar um padrão de senhas seguras?  (sim/não)
 a| 
Responda com *sim*.  A opção padrão é sim.



 a| 
Digite a senha de administrador.
 a| 
A senha padrão é "`admin`"; você deve criar uma nova senha forte.  Uma senha fraca pode ser rejeitada.



 a| 
Deseja acessar a caixa de diálogo de configuração básica?  (sim/não)
 a| 
Responda com *sim* na configuração inicial do switch.



 a| 
Criar outra conta de login?  (sim/não)
 a| 
Sua resposta depende das políticas do seu site em relação a administradores alternativos.  A opção padrão é *não*.



 a| 
Configurar string de comunidade SNMP somente leitura?  (sim/não)
 a| 
Responda com *não*.  A opção padrão é não.



 a| 
Configurar string de comunidade SNMP de leitura e gravação?  (sim/não)
 a| 
Responda com *não*.  A opção padrão é não.



 a| 
Digite o nome do interruptor.
 a| 
Digite o nome do interruptor, que está limitado a 63 caracteres alfanuméricos.



 a| 
Continuar com a configuração de gerenciamento fora de banda (mgmt0)?  (sim/não)
 a| 
Responda com *sim* (a opção padrão) quando solicitado.  No prompt "mgmt0 IPv4 address:", digite seu endereço IP: ip_address.



 a| 
Configurar o gateway padrão?  (sim/não)
 a| 
Responda com *sim*.  No prompt "Endereço IPv4 do gateway padrão:", insira o seu gateway padrão.



 a| 
Configurar opções avançadas de IP?  (sim/não)
 a| 
Responda com *não*.  A opção padrão é não.



 a| 
Habilitar o serviço Telnet?  (sim/não)
 a| 
Responda com *não*.  A opção padrão é não.



 a| 
O serviço SSH está ativado?  (sim/não)
 a| 
Responda com *sim*.  A opção padrão é sim.


NOTE: Recomenda-se o uso de SSH ao utilizar o Ethernet Switch Health Monitor (CSHM) devido aos seus recursos de coleta de logs.  O SSHv2 também é recomendado para maior segurança.



 a| 
Digite o tipo de chave SSH que deseja gerar (dsa/rsa/rsa1).
 a| 
O padrão é *rsa*.



 a| 
Insira o número de bits da chave (1024-2048).
 a| 
Insira o número de bits da chave, de 1024 a 2048.



 a| 
Configurar o servidor NTP?  (sim/não)
 a| 
Responda com *não*.  A opção padrão é não.



 a| 
Configurar camada de interface padrão (L3/L2)
 a| 
Responda com *L2*.  O padrão é L2.



 a| 
Configurar o estado padrão da interface da porta do switch (desligado/não desligado)
 a| 
Responda com *noshut*.  O padrão é noshut.



 a| 
Configurar perfil do sistema CoPP (estrito/moderado/tolerante/denso)
 a| 
Responda com *rigoroso*.  O padrão é estrito.



 a| 
Deseja editar a configuração?  (sim/não)
 a| 
Você deverá ver a nova configuração neste ponto.  Revise e faça as alterações necessárias na configuração que você acabou de inserir.  Responda com *não* quando solicitado, caso esteja satisfeito com a configuração.  Responda com *sim* se desejar editar suas configurações.



 a| 
Usar esta configuração e salvá-la?  (sim/não)
 a| 
Responda com *sim* para salvar a configuração.  Isso atualiza automaticamente as imagens do Kickstart e do sistema.


NOTE: Se você não salvar a configuração nesta etapa, nenhuma das alterações terá efeito na próxima vez que você reiniciar o switch.

|===
. Verifique as opções de configuração selecionadas na tela que aparece ao final da configuração e certifique-se de salvar as alterações.
. Verifique a versão nos switches de rede compartilhados e, se necessário, baixe a versão do software compatível com a NetApp para os switches a partir do site da NetApp. https://software.cisco.com/download/home["Download do software Cisco"^] página.


.O que vem a seguir?
Depois de configurar seus switches, você link:install-nxos-overview-9332d-cluster.html["prepare-se para instalar o software NX-OS e RCF"].
