---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Visão geral da configuração de software para switches de cluster Cisco Nexus 9336C-FX2 
---
= Fluxo de trabalho de instalação de software para switches de cluster Cisco Nexus 9336C-FX2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar e configurar o software para um switch Cisco Nexus 9336C-FX2 e para instalar ou atualizar o arquivo de configuração de referência (RCF), siga estas etapas:

. link:install-nxos-overview-9336c-cluster.html["Prepare-se para instalar o software NX-os e o RCF"].
+
O software Cisco NX-os e os arquivos de configuração de referência (RCFs) devem ser instalados nos switches de cluster Cisco Nexus 9336C-FX2.

. link:install-nxos-software-9336c-cluster.html["Instale ou atualize o software NX-os"].
+
Baixe e instale ou atualize o software NX-os no switch de cluster Cisco Nexus 9336C-FX2.

. link:install-nxos-rcf-9336c-cluster.html["Instale ou atualize o RCF"].
+
Instale ou atualize o RCF depois de configurar o switch Cisco Nexus 9336C-FX2 pela primeira vez. Você também pode usar este procedimento para atualizar sua versão RCF.

. link:configure-ssh-keys.html["Gerar chaves SSH"].
+
Se você usar os recursos do Monitor de integridade do comutador Ethernet (CSHM) e da coleção de logs, gere chaves SSH nos switches.


