---
permalink: switch-cisco-9336c-fx2/migrate-cn1610-9336c-cluster.html 
sidebar: sidebar 
keywords: migrate cluster Cisco Nexus 9336C-FX2 cluster switches cn1610 
summary: Você pode migrar switches de cluster NetApp CN1610 de um cluster ONTAP para switches de rede de cluster Cisco Nexus 9336C-FX2 sem interrupções. 
---
= Migrar de switches de cluster NetApp CN1610 para switches de cluster Cisco 9336C-FX2 e 9336C-FX2-T
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode migrar switches de cluster NetApp CN1610 para um cluster ONTAP para switches de cluster Cisco 9336C-FX2 e 9336C-FX2-T. Este é um procedimento não disruptivo.



== Requisitos de revisão

Você deve estar ciente de determinadas informações de configuração, conexões de porta e requisitos de cabeamento ao substituir switches de cluster NetApp CN1610 por switches de cluster Cisco 9336C-FX2 e 9336C-FX2-T. Você também deve verificar o número de série do switch para garantir que o switch correto seja migrado.

.Interruptores suportados
Os seguintes switches de cluster são suportados:

* NetApp CN1610
* Cisco 9336C-FX2
* Cisco 9336C-FX2-T


Para obter detalhes sobre as portas suportadas e suas configurações, consulte o https://hwu.netapp.com/["Hardware Universe"^] .

.O que você vai precisar
Verifique se sua configuração atende aos seguintes requisitos:

* O cluster existente está configurado corretamente e funcionando.
* Todas as portas do cluster estão no estado *ativo* para garantir operações sem interrupções.
* Os switches de cluster Cisco 9336C-FX2 e 9336C-FX2-T estão configurados e operando sob a versão correta do NX-OS instalada com o arquivo de configuração de referência (RCF) aplicado.
* A configuração de rede do cluster existente apresenta as seguintes características:
+
** Um cluster NetApp redundante e totalmente funcional, utilizando switches NetApp CN1610.
** Conectividade de gerenciamento e acesso ao console tanto para os switches NetApp CN1610 quanto para os novos switches.
** Todas as LIFs do cluster estão ativas e conectadas às suas portas de origem.


* Algumas portas são configuradas nos switches Cisco 9336C-FX2 e 9336C-FX2-T para operar em 40GbE ou 100GbE.
* Você planejou, migrou e documentou a conectividade de 40 GbE e 100 GbE dos nós para os switches de cluster Cisco 9336C-FX2 e 9336C-FX2-T.




== Migre os switches

.Sobre os exemplos
Os exemplos neste procedimento utilizam a seguinte nomenclatura de interruptor e nó:

* Os switches de cluster CN1610 existentes são _C1_ e _C2_.
* Os novos interruptores de cluster 9336C-FX2 são _cs1_ e _cs2_.
* Os nós são _node1_ e _node2_.
* Os LIFs do cluster são _node1_clus1_ e _node1_clus2_ no nó 1, e _node2_clus1_ e _node2_clus2_ no nó 2, respectivamente.
* O `cluster1::*>` O prompt indica o nome do cluster.
* As portas de cluster usadas neste procedimento são _e3a_ e _e3b_.


.Sobre esta tarefa
Este procedimento abrange o seguinte cenário:

* O interruptor C2 é substituído primeiro pelo interruptor cs2.
+
** Desative as portas dos nós do cluster.  Todas as portas devem ser desligadas simultaneamente para evitar instabilidade no cluster.
+
*** Todas as LIFs do cluster fazem failover para o novo switch cs2.


** Em seguida, o cabeamento entre os nós e o C2 é desconectado do C2 e reconectado ao cs2.


* O interruptor C1 é substituído pelo interruptor cs1.
+
** Desative as portas dos nós do cluster.  Todas as portas devem ser desligadas simultaneamente para evitar instabilidade no cluster.
+
*** Todas as LIFs do cluster fazem failover para o novo switch cs1.


** Em seguida, o cabeamento entre os nós e C1 é desconectado de C1 e reconectado a cs1.





NOTE: Nenhum link operacional entre switches (ISL) é necessário durante este procedimento. Isso ocorre porque as alterações na versão do RCF podem afetar a conectividade ISL temporariamente. Para garantir a operação ininterrupta do cluster, o procedimento a seguir transfere todas as LIFs do cluster para o switch parceiro operacional enquanto executa as etapas no switch de destino.



=== Etapa 1: Prepare-se para a migração

. Se o AutoSupport estiver ativado neste cluster, suprima a criação automática de casos invocando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
onde _x_ é a duração da janela de manutenção em horas.

. Altere o nível de privilégio para avançado, digitando *y* quando solicitado a continuar:
+
`set -privilege advanced`

+
A mensagem avançada (*>) é exibida.

. Desative a reversão automática nos LIFs do cluster.
+
Ao desativar a reversão automática para este procedimento, as LIFs do cluster não retornarão automaticamente à sua porta original.  Eles permanecem no porto atual enquanto ele continuar funcionando.

+
`network interface modify -vserver Cluster -lif * -auto-revert false`





=== Etapa 2: Configurar portas e cabos

. Determine o status administrativo ou operacional de cada interface de cluster.
+
Cada porta deve aparecer para cima. `Link` e `healthy` para `Health Status` .

+
.. Exibir os atributos da porta de rede:
+
`network port show -ipspace Cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
.. Exibir informações sobre os LIFs e seus respectivos nós de origem:
+
`network interface show -vserver Cluster`

+
Cada LIF deve exibir `up/up` para `Status Admin/Oper` e `true` para `Is Home` .

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current     Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node        Port    Home
----------- -----------  ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2       e3b     true

----
====


. As portas do cluster em cada nó são conectadas aos switches de cluster existentes da seguinte maneira (da perspectiva dos nós), utilizando o comando:
+
`network device-discovery show -protocol`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e3a    C1 (6a:ad:4f:98:3b:3f)    0/1               -
            e3b    C2 (6a:ad:4f:98:4c:a4)    0/1               -
node2      /cdp
            e3a    C1 (6a:ad:4f:98:3b:3f)    0/2               -
            e3b    C2 (6a:ad:4f:98:4c:a4)    0/2               -
----
====
. As portas e switches do cluster estão conectados da seguinte forma (do ponto de vista dos switches) usando o comando:
+
`show cdp neighbors`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
C1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1        124    H           AFF-A400         e3a
node2                 Eth1/2        124    H           AFF-A400         e3a
C2                    0/13          179    S I s       CN1610           0/13
C2                    0/14          175    S I s       CN1610           0/14
C2                    0/15          179    S I s       CN1610           0/15
C2                    0/16          175    S I s       CN1610           0/16

C2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 Eth1/1        124    H           AFF-A400         e3b
node2                 Eth1/2        124    H           AFF-A400         e3b
C1                    0/13          175    S I s       CN1610           0/13
C1                    0/14          175    S I s       CN1610           0/14
C1                    0/15          175    S I s       CN1610           0/15
C1                    0/16          175    S I s       CN1610           0/16
----
====
. Verifique a conectividade das interfaces do cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e posterior
--
Você pode usar o `network interface check cluster-connectivity` Comando para iniciar uma verificação de acessibilidade para conectividade do cluster e, em seguida, exibir os detalhes:

`network interface check cluster-connectivity start`e `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Aguarde alguns segundos antes de executar o `show` comando para exibir os detalhes.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas as versões do ONTAP
--
Para todas as versões do ONTAP , você também pode usar o `cluster ping-cluster -node <name>` comando para verificar a conectividade:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e3a
Cluster node1_clus2 169.254.49.125 node1     e3b
Cluster node2_clus1 169.254.47.194 node2     e3a
Cluster node2_clus2 169.254.19.183 node2     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[passo 5]] No switch C2, desligue as portas conectadas às portas do cluster dos nós para realizar o failover das LIFs do cluster.
+

CAUTION: Não tente migrar manualmente os LIFs do cluster.

+
[listing, subs="+quotes"]
----
(C2)# *configure*
(C2)(Config)# *interface 0/1-0/12*
(C2)(Interface 0/1-0/12)# *shutdown*
(C2)(Interface 0/1-0/12)# *exit*
(C2)(Config)# *exit*
----
. Mova as portas do cluster de nós do antigo switch C2 para o novo switch cs2, usando o cabeamento apropriado suportado pelo Cisco 9336C-FX2 e 9336C-FX2-T.
. Exibir os atributos da porta de rede:
+
`network port show -ipspace Cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. As portas do cluster em cada nó agora estão conectadas aos switches do cluster da seguinte maneira, da perspectiva dos nós:
+
`network device-discovery show -protocol`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e3a    C1  (6a:ad:4f:98:3b:3f)   0/1               CN1610
            e3b    cs2 (b8:ce:f6:19:1a:7e)   Ethernet1/1/1     N9K-C9336C-FX2
node2      /cdp
            e3a    C1  (6a:ad:4f:98:3b:3f)   0/2               CN1610
            e3b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2     N9K-C9336C-FX2
----
====
. No switch cs2, verifique se todas as portas do cluster de nós estão ativas:
+
`network interface show -vserver Cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current     Current Is
Vserver     Interfac     Admin/Oper Address/Mask       Node        Port    Home
----------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.3.4/16     node1       e0b     false
            node1_clus2  up/up      169.254.3.5/16     node1       e0b     true
            node2_clus1  up/up      169.254.3.8/16     node2       e0b     false
            node2_clus2  up/up      169.254.3.9/16     node2       e0b     true
----
====
. No switch C1, desligue as portas conectadas às portas do cluster dos nós para realizar o failover das LIFs do cluster.
+
[listing, subs="+quotes"]
----
(C1)# *configure*
(C1)(Config)# *interface 0/1-0/12*
(C1)(Interface 0/1-0/12)# *shutdown*
(C1)(Interface 0/1-0/12)# *exit*
(C1)(Config)# *exit*
----
. Mova as portas do cluster de nós do antigo switch C1 para o novo switch cs1, usando o cabeamento apropriado suportado pelo Cisco 9336C-FX2 e 9336C-FX2-T.
. Verifique a configuração final do cluster:
+
`network port show -ipspace Cluster`

+
Cada porta deve exibir `up` para `Link` e `healthy` para `Health Status` .

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. As portas do cluster em cada nó agora estão conectadas aos switches do cluster da seguinte maneira, da perspectiva dos nós:
+
`network device-discovery show -protocol`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /cdp
            e3a    cs1 (b8:ce:f6:19:1a:7e)   Ethernet1/1/1   N9K-C9336C-FX2
            e3b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2
node2      /cdp
            e3a    cs1 (b8:ce:f6:19:1a:7e)   Ethernet1/1/1   N9K-C9336C-FX2
            e3b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2
----
====
. Nos switches cs1 e cs2, verifique se todas as portas do cluster de nós estão ativas:
+
`network port show -ipspace Cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. Verifique se ambos os nós possuem uma conexão com cada switch:
+
`network device-discovery show -protocol`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra os resultados apropriados para ambas as opções:

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  --------------
node1      /cdp
            e0a    cs1 (b8:ce:f6:19:1b:42)   Ethernet1/1/1   N9K-C9336C-FX2
            e0b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2

node2      /cdp
            e0a    cs1 (b8:ce:f6:19:1b:42)   Ethernet1/1/1   N9K-C9336C-FX2
            e0b    cs2 (b8:ce:f6:19:1b:96)   Ethernet1/1/2   N9K-C9336C-FX2
----
====




=== Etapa 3: Verifique a configuração

. Ativar reversão automática nos LIFs do cluster:
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. Verifique se todas as LIFs da rede do cluster estão de volta às suas portas de origem:
+
`network interface show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. Altere o nível de privilégio de volta para administrador:
+
`set -privilege admin`

. Se você desativou a criação automática de casos, reative-a enviando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que vem a seguir?
Depois de migrar seus switches, você pode link:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"].
