---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2/required-documentation-9336c-cluster.html 
keywords: shared storage cluster switch 
summary: Para a instalação e manutenção do switch Cisco Nexus 9336C-FX2, certifique-se de consultar a documentação específica do switch e do controlador para configurar seus switches Cisco 9336-FX2 e o cluster ONTAP . 
---
= Requisitos de documentação para switches Cisco Nexus 9336C-FX2 e 9336C-FX2-T
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para instalação e manutenção dos switches Cisco Nexus 9336C-FX2 e 9336C-FX2-T, revise a documentação específica do switch e do controlador para configurar seus switches Cisco 9336-FX2 e o cluster ONTAP .



== Documentação do Switch

Para configurar os switches Cisco Nexus 9336C-FX2 e 9336C-FX2-T, você precisa da seguinte documentação: https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Suporte para switches Cisco Nexus série 9000"^] página:

[cols="1,2"]
|===
| Título do documento | Descrição 


 a| 
_Guia de Instalação de Hardware da Série Nexus 9000_
 a| 
Fornece informações detalhadas sobre os requisitos do local, detalhes do hardware do switch e opções de instalação.



 a| 
_Guias de Configuração de Software para Switches Cisco Nexus Série 9000_ (escolha o guia correspondente à versão do NX-OS instalada em seus switches)
 a| 
Fornece as informações iniciais de configuração do switch necessárias antes de configurá-lo para operação com ONTAP .



 a| 
Guia de atualização e downgrade do software NX-OS da série Cisco Nexus 9000 (escolha o guia correspondente à versão do NX-OS instalada em seus switches)
 a| 
Fornece informações sobre como fazer o downgrade do software do switch para uma versão compatível com ONTAP , se necessário.



 a| 
_Índice principal de referência de comandos do Cisco Nexus 9000 Series NX-OS_
 a| 
Fornece links para as diversas referências de comandos disponibilizadas pela Cisco.



 a| 
_Referência de MIBs do Cisco Nexus 9000_
 a| 
Descreve os arquivos da Base de Informações de Gerenciamento (MIB) para os switches Nexus 9000.



 a| 
_Referência de mensagens do sistema NX-OS da série Nexus 9000_
 a| 
Descreve as mensagens do sistema para switches da série Cisco Nexus 9000, incluindo as informativas e outras que podem ajudar a diagnosticar problemas com links, hardware interno ou software do sistema.



 a| 
_Notas de versão do NX-OS para a série Cisco Nexus 9000 (selecione as notas referentes à versão do NX-OS instalada em seus switches)_
 a| 
Descreve as funcionalidades, os erros e as limitações da série Cisco Nexus 9000.



 a| 
Informações sobre conformidade regulamentar e segurança para a série Cisco Nexus 9000
 a| 
Fornece informações sobre conformidade com agências internacionais, segurança e regulamentações para os switches da série Nexus 9000.

|===


== Documentação dos sistemas ONTAP

Para configurar um sistema ONTAP , você precisa dos seguintes documentos para a sua versão do sistema operacional. https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^] .

[cols="1,2"]
|===
| Nome | Descrição 


 a| 
Instruções de instalação e configuração específicas do controlador
 a| 
Descreve como instalar o hardware da NetApp .



 a| 
Documentação do ONTAP
 a| 
Fornece informações detalhadas sobre todos os aspectos das versões do ONTAP .



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fornece informações sobre configuração e compatibilidade de hardware da NetApp .

|===


== Kit de trilhos e documentação do gabinete

Para instalar um switch Cisco 9336-FX2 em um gabinete NetApp , consulte a seguinte documentação de hardware.

[cols="1,2"]
|===
| Nome | Descrição 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Gabinete de sistema 42U, guia profundo"^]
 a| 
Descreve as FRUs (Unidades Substituíveis em Campo) associadas ao gabinete do sistema 42U e fornece instruções de manutenção e substituição de FRUs.



 a| 
link:install-switch-and-passthrough-panel-9336c-cluster.html["Instale um switch Cisco 9336-FX2 em um gabinete NetApp."^]
 a| 
Descreve como instalar os switches Cisco Nexus 9336C-FX2 e 9336C-FX2-T em um gabinete NetApp de quatro postes.

|===