---
permalink: switch-cisco-9336c-fx2/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, nexus, ontap, install the cluster switch health monitor (csm) configuration file for 92300yc switches - cisco nexus 9336c-fx2' 
summary: Você pode usar este procedimento para instalar o arquivo de configuração aplicável para o monitoramento de integridade do switch de cluster dos switches de cluster Nexus 92300YC. 
---
= Instale o ficheiro de configuração do Monitor de integridade do interrutor do cluster (SHM)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para instalar o arquivo de configuração aplicável para o monitoramento de integridade do switch de cluster (SHM) dos switches de cluster Nexus 9336C-FX2.

.O que você vai precisar
Antes de configurar o SHM para os switches de cluster 9336C-FX2, certifique-se de que o cluster ONTAP está ativo e em execução.


NOTE: Você também deve habilitar o SSH para usar todos os recursos disponíveis no SHM.

.Passos
. Transfira o ficheiro zip de configuração do cluster SHM com base na versão de lançamento do ONTAP correspondente. Este arquivo está disponível na https://mysupport.netapp.com/NOW/cgi-bin/software/["Download do software NetApp"^] página.
+
.. Na página de download de software, selecione *Switch Health Monitor Configuration Files*
.. Selecione Plataforma *ONTAP* e selecione *Go!*
.. Na página Switch Health Monitor Configuration Files for ONTAP, selecione *View & Download*
.. Na página de Configuração do Monitor de integridade do comutador para ONTAP > Descrição, selecione *Download* para o modelo de switch de cluster aplicável, por exemplo: *Cisco Nexus 9336C-FX2*
.. Na página Contrato de Licença de Usuário final, selecione *aceitar*
.. Na página Switch Health Monitor Configuration Files for ONTAP > Download, selecione o arquivo de configuração aplicável, por exemplo, *Cisco_Nexus_9336C-FX2.zip*


. Carregue o ficheiro zip aplicável para o servidor Web interno onde o endereço IP é X.X.X.
+
Para um endereço IP de servidor web interno de 192.168.2.20 e assumindo que existe um diretório /usr/download, você pode fazer upload do seu arquivo zip para o seu servidor web usando scp:

+
[listing]
----
% scp Cisco_Nexus_9336C-FX2.zip admin@192.168.2.20:/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. Aceda à definição do modo avançado a partir de um dos sistemas ONTAP no cluster:
+
`set-privilege advanced`

+
[listing]
----
cluster1::> set -privilege advanced
----
. Executar o comando de configuração do monitor de integridade do comutador `system cluster-switch configure-health-monitor -node * -package-url X.X.X.X/location_to_download_zip_file` :
+
[listing]
----
cluster1::> system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. Verifique se a saída do comando contém a cadeia de texto "pacote baixado processado com sucesso". Se ocorrer um erro, contacte o suporte da NetApp.
. Execute o comando `system cluster-switch show` no sistema ONTAP e certifique-se de que os switches de cluster são descobertos com o campo monitorado definido como "verdadeiro".
+
[listing]
----
cluster1::> system cluster-switch show
----
+

NOTE: Se, a qualquer momento, você reverter para uma versão anterior do ONTAP, precisará instalar o arquivo de configuração SHM novamente para ativar o SHM de switches de cluster 9336C-FX2.


