---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: O modelo base de switch de cluster BES-53248 é licenciado para portas 16 10GbE ou 25GbE e duas portas 100GbE. Novas portas podem ser adicionadas comprando mais licenças. 
---
= Instalar licenças para switches de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O modelo base de switch de cluster BES-53248 é licenciado para portas 16 10GbE ou 25GbE e duas portas 100GbE. Você pode adicionar novas portas comprando mais licenças.



== Reveja as licenças disponíveis

As seguintes licenças estão disponíveis para uso no switch de cluster BES-53248:

[cols="1,2,3"]
|===
| Tipo de licença | Detalhes da licença | Versão de firmware suportada 


 a| 
SW-BES-53248A2-8P-2P
 a| 
Chave de licença Broadcom 8PT-10G25G e 2PT-40G100G, X190005/R
 a| 
EFOS 3.4.4.6 e posterior



 a| 
SW-BES-53248A2-8P-1025G
 a| 
Chave de licença Broadcom 8 porta 10G25G, X190005/R
 a| 
EFOS 3.4.4.6 e posterior



 a| 
SW-BES53248A2-6P-40-100G
 a| 
Chave de licença Broadcom 6 porta 40G100G, X190005/R
 a| 
EFOS 3.4.4.6 e posterior

|===


== Licenças legadas

A tabela a seguir lista as licenças legadas que estavam disponíveis para uso no switch de cluster BES-53248:

[cols="1,2,3"]
|===
| Tipo de licença | Detalhes da licença | Versão de firmware suportada 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Chave de licença Broadcom 8P 10-25,2P40-100, X190005/R
 a| 
EFOS 3.4.3.3 e posterior



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Chave de licença Broadcom 16P 10-25,4P40-100, X190005/R
 a| 
EFOS 3.4.3.3 e posterior



 a| 
SW-BES-53248A1-G1-24P-LIC
 a| 
Chave de licença Broadcom 24P 10-25,6P40-100, X190005/R
 a| 
EFOS 3.4.3.3 e posterior



 a| 
SW-BES54248-40-100G-LIC
 a| 
Chave de licença Broadcom 6Port 40G100G, X190005/R
 a| 
EFOS 3.4.4.6 e posterior



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
Chave de licença Broadcom 8Port 10G25G, X190005/R
 a| 
EFOS 3.4.4.6 e posterior



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
Chave de licença Broadcom 16Port 10G25G, X190005/R
 a| 
EFOS 3.4.4.6 e posterior



 a| 
SW-BES53248-24P-1025G-LIC
 a| 
Chave de licença Broadcom 24Port 10G25G, X190005/R
 a| 
EFOS 3.4.4.6 e posterior

|===

NOTE: Não é necessária uma licença para a configuração base.



== Instalar ficheiros de licença

Siga estas etapas para instalar licenças para switches de cluster BES-53248.

.Passos
. Conete o switch de cluster à rede de gerenciamento.
. Use o `ping` comando para verificar a conetividade com o servidor que hospeda EFOS, licenças e o arquivo RCF.
+
.Mostrar exemplo
[%collapsible]
====
Este exemplo verifica se o switch está conetado ao servidor no endereço IP 172.19.2.1:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Verifique a utilização atual da licença no interrutor CS2:
+
`show license`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. Instale o ficheiro de licença.
+
Repita esta etapa para carregar mais licenças e usar diferentes números de índice de chave.

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir usa SFTP para copiar um arquivo de licença para um índice de chave 1.

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. Exiba todas as informações atuais da licença e observe o status da licença antes que o switch CS2 seja reinicializado:
+
`show license`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. Exibir todas as portas licenciadas:
+
`show port all | exclude Detach`

+
As portas dos arquivos de licença adicionais não são exibidas até que o switch seja reinicializado.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. Reinicie o switch:
+
`reload`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. Verifique se a nova licença está ativa e observe que a licença foi aplicada:
+
`show license`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. Verifique se todas as novas portas estão disponíveis:
+
`show port all | exclude Detach`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: Ao instalar licenças adicionais, você deve configurar as novas interfaces manualmente. Não volte a aplicar um RCF a um interrutor de produção em funcionamento existente.



== Solucionar problemas de instalação

Quando surgirem problemas ao instalar uma licença, execute os seguintes comandos de depuração antes de executar o `copy` comando novamente.

Depurar comandos para usar: `debug transfer` E. `debug license`

.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
Quando você executa o `copy` comando com `debug transfer` as opções e `debug license` ativadas, a saída do log é retornada.

.Mostrar exemplo
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
Verifique o seguinte na saída de depuração:

* Verifique se o número de série corresponde: `Serial number QTFCU38290012 matched.`
* Verifique se o modelo do interrutor corresponde: `Model BES-53248 matched.`
* Verifique se o índice de licença especificado não foi usado anteriormente. Quando um índice de licença já é usado, o seguinte erro é retornado: `License file /mnt/download//license.dat.1 already exists.`
* Uma licença de porta não é uma licença de recurso. Portanto, a seguinte declaração é esperada: `Feature not found in license file with index = 1.`


Use o `copy` comando para fazer backup de licenças de porta para o servidor:

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: Se você precisar fazer o downgrade do software do switch da versão 3,4.4,6, as licenças serão removidas. Este é o comportamento esperado.

Você deve instalar uma licença mais antiga apropriada antes de reverter para uma versão mais antiga do software.



== Ative portas recém-licenciadas

Para ativar portas recém-licenciadas, você precisa editar a versão mais recente do RCF e descomentar os detalhes da porta aplicável.

A licença padrão ativa as portas 0/1 a 0/16 e 0/55 a 0/56 enquanto as portas recém-licenciadas estarão entre as portas 0/17 a 0/54, dependendo do tipo e do número de licenças disponíveis. Por exemplo, para ativar a licença SW-BES54248-40-100g-LIC, você deve descomentar a seguinte seção no RCF:

.Mostrar exemplo
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: Para portas de alta velocidade entre 0/49 e 0/54 inclusive, descomente cada porta, mas apenas descomente uma linha *speed* no RCF para cada uma dessas portas, seja: *Speed 100g full-duplex* ou *speed 40G full-duplex* como mostrado no exemplo. Para portas de baixa velocidade entre 0/17 e 0/48 inclusive, descomente toda a seção de 8 portas quando uma licença apropriada tiver sido ativada.

.O que se segue?
link:configure-install-rcf.html["Instalar o ficheiro de configuração de referência (RCF)"] ou link:upgrade-rcf.html["Atualize o RCF"].
