---
permalink: switch-bes-53248/configure-ssh.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, bes, enable ssh on bes-53248 cluster switches - bes-53248 switches 
summary: 'O SSH é um requisito ao usar o Cluster Switch Health Monitor (CSHM) e os recursos de coleta de logs. Para habilitar o SSH nos switches de cluster BES-53248, primeiro você gera as chaves SSH e depois habilita o SSH.' 
---
= Habilite o SSH nos switches de cluster BES-53248.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando o Monitor de Saúde do Switch Ethernet (CSHM) e os recursos de coleta de logs, será necessário gerar as chaves SSH e, em seguida, habilitar o SSH nos switches do cluster.

.Passos
. Verifique se o SSH está desativado:
+
`show ip ssh`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Disabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Disabled
SCP server Administrative Mode: ............... Disabled
----
====
+
** Se o SSH não estiver desativado, desative-o da seguinte forma:
+
`no ip ssh server enable`

+
`no ip scp server enable`

+
[NOTE]
====
*** Para EFOS 3.12 e posteriores, o acesso ao console é necessário, pois as sessões SSH ativas são perdidas quando o SSH é desabilitado.
*** Para EFOS 3.11 e versões anteriores, as sessões SSH atuais são mantidas abertas após a desativação do servidor SSH.


====
+

WARNING: Certifique-se de desativar o SSH antes de modificar as chaves; caso contrário, um aviso será exibido no switch.



. No modo de configuração, gere as chaves SSH:
+
`crypto key generate`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *config*

(switch) (Config)# *crypto key generate rsa*

Do you want to overwrite the existing RSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate dsa*

Do you want to overwrite the existing DSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate ecdsa 521*

Do you want to overwrite the existing ECDSA keys? (y/n): *y*
----
====
. No modo de configuração, defina a autorização AAA para coleta de logs ONTAP :
+
`aaa authorization commands "noCmdAuthList" none`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) (Config)# *aaa authorization commands "noCmdAuthList" none*
(switch) (Config)# *exit*
----
====
. Reative o SSH/SCP.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *ip ssh server enable*
(switch)# *ip scp server enable*
(switch)# *ip ssh pubkey-auth*
----
====
. Salve essas alterações no startup-config:
+
`write memory`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Criptografe as chaves SSH (somente para o modo FIPS):
+

CAUTION: No modo FIPS, as chaves precisam ser criptografadas com uma senha para garantir a segurança.  Na ausência de uma chave criptografada, o aplicativo não consegue ser iniciado.  As chaves são criadas e criptografadas usando os seguintes comandos:

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) *configure*
(switch) (Config)# *crypto key encrypt write rsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *crypto key encrypt write dsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch)(Config)# *crypto key encrypt write ecdsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *end*
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Reinicie o switch:
+
`reload`

. Verifique se o SSH está ativado:
+
`show ip ssh`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Enabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Enabled
SCP server Administrative Mode: ............... Enabled
----
====


.O que vem a seguir?
Depois de habilitar o SSH, você pode link:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"].
