---
permalink: switch-bes-53248/configure-reqs-bes53248.html 
sidebar: sidebar 
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches 
summary: Você pode usar a tabela de atribuição de portas do switch de cluster BES-53248 como guia para configurar seu cluster. 
---
= Requisitos de configuração para switches de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalação e manutenção do switch BES-53248, certifique-se de revisar os requisitos de suporte e configuração do EFOS e do ONTAP .



== Suporte para EFOS e ONTAP

Veja o https://hwu.netapp.com/Switch/Index["Hardware Universe da NetApp"^] e https://mysupport.netapp.com/site/info/broadcom-cluster-switch["matriz de compatibilidade de switches Broadcom"^] Para informações sobre compatibilidade do EFOS e do ONTAP com os switches BES-53248.  O suporte para EFOS e ONTAP pode variar de acordo com o tipo específico de máquina do switch BES-53248.  Para obter detalhes sobre todos os tipos de máquinas de comutação BES-52348, consultelink:components-bes53248.html["Componentes e números de peça para os interruptores do cluster BES-53248"] .



== Requisitos de configuração

Para configurar um cluster, você precisa da quantidade e do tipo adequados de cabos e conectores de cabos para os switches do cluster.  Dependendo do tipo de switch de cluster que você estiver configurando inicialmente, será necessário conectar-se à porta de console do switch com o cabo de console incluído.



=== Atribuições de portas de comutadores de cluster

Você pode usar a tabela de atribuições de portas do switch de cluster BES-53248, compatível com a Broadcom, como um guia para configurar seu cluster.

[cols="1,2"]
|===
| Portas de comutação | Utilização de portas 


 a| 
01-16
 a| 
Nós de porta de cluster 10/25GbE, configuração básica



 a| 
17-48
 a| 
Nós de cluster com portas 10/25GbE, com licenças.



 a| 
49-54
 a| 
Nós de cluster com portas 40/100GbE, com licenças, adicionados da direita para a esquerda.



 a| 
55-56
 a| 
Portas de link entre switches (ISL) de cluster 100GbE, configuração básica

|===
Veja o https://hwu.netapp.com/Switch/Index["Hardware Universe"] Para obter mais informações sobre portas de switch.



=== Restrição de velocidade do grupo de portos

* Nos switches de cluster BES-53248, as 48 portas 10/25GbE (SFP28/SFP+) são combinadas em 12 grupos de 4 portas, da seguinte forma: Portas 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44 e 45-48.
* A velocidade da porta SFP28/SFP+ deve ser a mesma (10GbE ou 25GbE) em todas as portas do grupo de 4 portas.




=== Requisitos adicionais

* Se você adquirir licenças adicionais, consultelink:configure-licenses.html["Ativar portas recém-licenciadas"] Para obter detalhes sobre como ativá-los.
* Se o SSH estiver ativo, você deverá reativá-lo manualmente após executar o comando. `erase startup-config` e reiniciando o switch.


.O que vem a seguir
Após analisar os requisitos de configuração, você poderá confirmar sua solicitação. link:components-bes53248.html["componentes e números de peças"].
