---
permalink: switch-bes-53248/configure-install-initial.html 
sidebar: sidebar 
keywords: switches initial setup,initial setup,efos download 
summary: Pode utilizar este procedimento para efetuar a instalação inicial do comutador de cluster BES-53248. 
---
= Configure o switch do cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estas etapas para executar uma configuração inicial do switch do cluster BES-53248.

.Antes de começar
* O hardware está instalado, conforme descrito em link:install-hardware-bes53248.html["Instale o hardware"].
* Você revisou o seguinte:
+
** link:configure-reqs-bes53248.html["Requisitos de configuração"]
** link:components-bes53248.html["Componentes e números de peça"]
** link:required-documentation-bes53248.html["Requisitos de documentação"]




.Sobre os exemplos
Os exemplos nos procedimentos de configuração usam a seguinte nomenclatura de switch e nó:

* Os nomes dos switches NetApp são `cs1` e `cs2`. A atualização começa no segundo switch, _CS2._
* Os nomes de LIF do cluster são `node1_clus1` e `node1_clus2` para node1 `node2_clus1` e e `node2_clus2` node2.
* O nome do IPspace é Cluster.
* O `cluster1::>` prompt indica o nome do cluster.
* As portas de cluster em cada nó são nomeadas e `e0a` `e0b`. Consulte a https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^] para obter as portas de cluster reais suportadas na sua plataforma.
* Os ISLs (links interswitches) suportados para os switches NetApp são as portas 0/55 e 0/56.
* As conexões de nó suportadas para os switches NetApp são as portas 0/1 a 0/16 com licenciamento padrão.
* Os exemplos usam dois nós, mas você pode ter até 24 nós em um cluster.


.Passos
. Conete a porta serial a um host ou porta serial.
. Conete a porta de gerenciamento (a porta chave RJ-45 no lado esquerdo do switch) à mesma rede onde o servidor TFTP está localizado.
. No console, defina as configurações de série do lado do host:
+
** 115200 baud
** 8 bits de dados
** 1 bit de paragem
** paridade: nenhuma
** controle de fluxo: nenhum


. Faça login no switch como `admin` e pressione *Enter* quando for solicitada uma senha. O nome padrão do switch é *routing*. No prompt, digite `enable`. Isso lhe dá acesso ao modo EXEC privilegiado para configuração de switch.
+
[listing, subs="+quotes"]
----
User: *admin*
Password:
(Routing)> *enable*
Password:
(Routing)#
----
. Altere o nome do switch para *CS2*.
+
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
(cs2)#
----
. Para definir um endereço de gerenciamento IPv4 ou IPv6 estático para a porta de serviço do switch:


[role="tabbed-block"]
====
.IPv4
--
A porta de serviço está definida para usar DHCP por padrão. O endereço IP, a máscara de sub-rede e o endereço de gateway padrão são atribuídos automaticamente.

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip <ip-address> <netmask> <gateway>*
----
--
.IPv6
--
A porta de serviço está definida para usar DHCP por padrão. O endereço IP, a máscara de sub-rede e o endereço de gateway padrão são atribuídos automaticamente.

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ipv6 <address>*
(cs2)# *serviceport ipv6 <gateway>*
----
--
====
. [[step7]]Verifique os resultados usando o comando:
+
`show serviceport`

+
[listing, subs="+quotes"]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
. Configure o domínio e o servidor de nomes:
+
[source, cli]
----
ip domain name <domain_name>
ip name server <server_name>
----
+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ip domain name company.com*
(cs2)(Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2)(Config)# *exit*
(cs2)#
----
. Configure o servidor NTP.


[role="tabbed-block"]
====
.EFOS 3.10.0.3 e posterior
--
Configure o fuso horário e a sincronização de horário (NTP):

[source, cli]
----
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 e anteriores
--
Configure o fuso horário e a sincronização de horário (SNTP):

[source, cli]
----
sntp client mode <client_mode>
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *sntp client mode unicast*
(cs2)(Config)# *sntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step10]]Configure a hora manualmente se você não configurou um servidor NTP na etapa anterior.


[role="tabbed-block"]
====
.EFOS 3.10.0.3 e posterior
--
Configure a hora manualmente.

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 e anteriores
--
Configure a hora manualmente.

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *no sntp client mode*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step11]]Salve a configuração em execução na configuração de inicialização:
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----


.O que se segue?
link:configure-efos-software.html["Instale o software EFOS"]
