---
permalink: switch-bes-53248/configure-install-rcf.html 
sidebar: sidebar 
keywords: install rcf,setup rcf,rcf file 
summary: 'Você pode instalar o Arquivo de Configuração de Referência (RCF) após configurar o switch de cluster BES-53248 e aplicar as novas licenças.' 
---
= Instale o arquivo de configuração de referência (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode instalar o Arquivo de Configuração de Referência (RCF) após configurar o switch de cluster BES-53248 e aplicar as novas licenças.


CAUTION: Para o EFOS 3.12 e versões posteriores, siga os passos de instalação emlink:efos-install-rcf-license-file.html["Instale o arquivo de configuração de referência (RCF) e o arquivo de licença."] .



== Requisitos de revisão

.Antes de começar
Verifique se os seguintes itens estão em vigor:

* Um backup atual da configuração do switch.
* Um cluster totalmente funcional (sem erros nos logs ou problemas semelhantes).
* O arquivo RCF atual está disponível em https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Comutadores de cluster Broadcom"^] página.
* Uma configuração de inicialização no RCF que reflita as imagens de inicialização desejadas, necessária caso você esteja instalando apenas o EFOS e mantendo sua versão atual do RCF.  Se precisar alterar a configuração de inicialização para refletir as imagens de inicialização atuais, você deve fazê-lo antes de reaplicar o RCF para que a versão correta seja instanciada em reinicializações futuras.
* É necessária uma conexão de console com o switch ao instalar o RCF a partir de suas configurações padrão de fábrica.  Este requisito é opcional se você já utilizou o artigo da Base de Conhecimento. https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração de um switch de interconexão Broadcom mantendo a conectividade remota"^] Para limpar a configuração previamente.


.Documentação sugerida
Consulte a tabela de compatibilidade de switches para obter informações sobre as versões suportadas do ONTAP e do RCF.  Veja o https://mysupport.netapp.com/site/info/broadcom-cluster-switch["Download do software EFOS"^] página.  Note que pode haver dependências entre a sintaxe de comandos no RCF e a encontrada em versões do EFOS.



== Instale o arquivo de configuração.

.Sobre os exemplos
Os exemplos neste procedimento utilizam a seguinte nomenclatura de interruptor e nó:

* Os nomes dos dois switches BES-53248 são cs1 e cs2.
* Os nomes dos nós são cluster1-01, cluster1-02, cluster1-03 e cluster1-04.
* Os nomes do LIF do cluster são cluster1-01_clus1, cluster1-01_clus2, cluster1-02_clus1, cluster1-02_clus2, cluster1-03_clus1, cluster1-03_clus2, cluster1-04_clus1 e cluster1-04_clus2.
* O `cluster1::*>` O prompt indica o nome do cluster.
* Os exemplos neste procedimento utilizam quatro nós.  Esses nós utilizam duas portas de interconexão de cluster de 10GbE. `e0a` e `e0b` .  Veja o https://hwu.netapp.com/Home/Index["Hardware Universe"^] Para verificar as portas de cluster corretas em suas plataformas.



NOTE: Os resultados dos comandos podem variar dependendo das diferentes versões do ONTAP.

.Sobre esta tarefa
O procedimento requer o uso de comandos ONTAP e comandos de switch Broadcom; os comandos ONTAP são usados ​​a menos que indicado de outra forma.

Nenhum link operacional entre switches (ISL) é necessário durante este procedimento. Isso ocorre porque as alterações na versão do RCF podem afetar a conectividade ISL temporariamente. Para garantir a operação ininterrupta do cluster, o procedimento a seguir migra todas as LIFs do cluster para o switch parceiro operacional enquanto executa as etapas no switch de destino.


CAUTION: Antes de instalar uma nova versão de software de switch e RCFs, consulte o artigo da Base de Conhecimento. https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração de um switch de interconexão Broadcom mantendo a conectividade remota"^] .  Se precisar apagar completamente as configurações do switch, será necessário realizar a configuração básica novamente.  Você precisa estar conectado ao switch usando o console serial, pois a exclusão completa da configuração redefine a configuração da rede de gerenciamento.



== Passo 1: Prepare-se para a instalação

. Se o AutoSupport estiver ativado neste cluster, suprima a criação automática de casos invocando uma mensagem do AutoSupport :
+
[source, cli]
----
system node autosupport invoke -node * -type all -message MAINT=xh
----
+
onde _x_ é a duração da janela de manutenção em horas.

+

NOTE: A mensagem do AutoSupport notifica o suporte técnico sobre essa tarefa de manutenção, de forma que a criação automática de chamados seja suprimida durante o período de manutenção.

+
O comando a seguir suprime a criação automática de casos por duas horas:

+
[listing]
----
cluster1::*> system node autosupport invoke -node \* -type all -message MAINT=2h
----
. Altere o nível de privilégio para avançado, digitando *y* quando solicitado a continuar:
+
[source, cli]
----
set -privilege advanced
----
+
A mensagem avançada (*>) é exibida.

. Exibir as portas do cluster em cada nó que estão conectadas aos switches do cluster:
+
[source, cli]
----
network device-discovery show
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
cluster1-01/cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
cluster1-02/cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
cluster1-03/cdp
            e0a    cs1                       0/4               BES-53248
            e0b    cs2                       0/4               BES-53248
cluster1-04/cdp
            e0a    cs1                       0/3               BES-53248
            e0b    cs2                       0/3               BES-53248
cluster1::*>
----
====
. Verifique o status administrativo e operacional de cada porta do cluster.
+
.. Verifique se todas as portas do cluster estão ativas e com status íntegro:
+
[source, cli]
----
network port show -role cluster
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*

Node: cluster1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: cluster1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false
8 entries were displayed.

Node: cluster1-03

   Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
cluster1::*>
----
====
.. Verifique se todas as interfaces de cluster (LIFs) estão na porta principal:
+
[source, cli]
----
network interface show -role cluster
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network           Current      Current Is
Vserver     Interface          Admin/Oper Address/Mask      Node         Port    Home
----------- ------------------ ---------- ----------------- ------------ ------- ----
Cluster
            cluster1-01_clus1  up/up     169.254.3.4/23     cluster1-01  e0a     true
            cluster1-01_clus2  up/up     169.254.3.5/23     cluster1-01  e0b     true
            cluster1-02_clus1  up/up     169.254.3.8/23     cluster1-02  e0a     true
            cluster1-02_clus2  up/up     169.254.3.9/23     cluster1-02  e0b     true
            cluster1-03_clus1  up/up     169.254.1.3/23     cluster1-03  e0a     true
            cluster1-03_clus2  up/up     169.254.1.1/23     cluster1-03  e0b     true
            cluster1-04_clus1  up/up     169.254.1.6/23     cluster1-04  e0a     true
            cluster1-04_clus2  up/up     169.254.1.7/23     cluster1-04  e0b     true
----
====


. Verifique se o cluster exibe informações para ambos os switches do cluster.


[role="tabbed-block"]
====
.ONTAP 9.8 e posterior
--
A partir do ONTAP 9.8, utilize o comando:

[source, cli]
----
system switch ethernet show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
.ONTAP 9.7 e versões anteriores
--
Para ONTAP 9.7 e versões anteriores, utilize o comando:

[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
====
. [[passo 6]]Desative a reversão automática nos LIFs do cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----




== Etapa 2: Configurar portas

. No switch cs2, confirme a lista de portas que estão conectadas aos nós do cluster.
+
[source, cli]
----
show isdp neighbor
----
. No switch de cluster cs2, desligue as portas conectadas às portas de cluster dos nós.  Por exemplo, se as portas 0/1 a 0/16 estiverem conectadas a nós ONTAP :
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)#
----
. Verifique se as LIFs do cluster foram migradas para as portas hospedadas no switch de cluster cs1. Isso pode levar alguns segundos.
+
[source, cli]
----
network interface show -role cluster
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical           Status     Network            Current       Current Is
Vserver     Interface         Admin/Oper Address/Mask       Node          Port    Home
----------- ----------------- ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1 up/up      169.254.3.4/23     cluster1-01   e0a     true
            cluster1-01_clus2 up/up      169.254.3.5/23     cluster1-01   e0a     false
            cluster1-02_clus1 up/up      169.254.3.8/23     cluster1-02   e0a     true
            cluster1-02_clus2 up/up      169.254.3.9/23     cluster1-02   e0a     false
            cluster1-03_clus1 up/up      169.254.1.3/23     cluster1-03   e0a     true
            cluster1-03_clus2 up/up      169.254.1.1/23     cluster1-03   e0a     false
            cluster1-04_clus1 up/up      169.254.1.6/23     cluster1-04   e0a     true
            cluster1-04_clus2 up/up      169.254.1.7/23     cluster1-04   e0a     false
cluster1::*>
----
====
. Verifique se o cluster está íntegro:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
----
====
. Caso ainda não o tenha feito, salve a configuração atual do switch copiando a saída do seguinte comando para um arquivo de log:
+
[source, cli]
----
show running-config
----
. Limpe a configuração do switch CS2 e execute uma configuração básica.
+

CAUTION: Ao atualizar ou aplicar um novo RCF, você deve apagar as configurações do switch e realizar a configuração básica.  Você precisa estar conectado ao switch usando o console serial para apagar as configurações do switch.  Este requisito é opcional se você já utilizou o artigo da Base de Conhecimento. https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração de um switch de interconexão Broadcom mantendo a conectividade remota?"] Para limpar a configuração previamente.

+

NOTE: Limpar a configuração não exclui as licenças.

+
.. Acesse o switch via SSH.
+
Prossiga somente quando todas as LIFs do cluster tiverem sido removidas das portas do switch e o switch estiver preparado para ter a configuração apagada.

.. Entrar no modo privilegiado:
+
[listing]
----
(cs2)> enable
(cs2)#
----
.. Copie e cole os seguintes comandos para remover a configuração RCF anterior (dependendo da versão RCF anterior utilizada, alguns comandos podem gerar um erro se uma determinada configuração não estiver presente):
+
[source, cli]
----
clear config interface 0/1-0/56
y
clear config interface lag 1
y
configure
deleteport 1/1 all
no policy-map CLUSTER
no policy-map WRED_25G
no policy-map WRED_100G
no class-map CLUSTER
no class-map HA
no class-map RDMA
no classofservice dot1p-mapping
no random-detect queue-parms 0
no random-detect queue-parms 1
no random-detect queue-parms 2
no random-detect queue-parms 3
no random-detect queue-parms 4
no random-detect queue-parms 5
no random-detect queue-parms 6
no random-detect queue-parms 7
no cos-queue min-bandwidth
no cos-queue random-detect 0
no cos-queue random-detect 1
no cos-queue random-detect 2
no cos-queue random-detect 3
no cos-queue random-detect 4
no cos-queue random-detect 5
no cos-queue random-detect 6
no cos-queue random-detect 7
exit
vlan database
no vlan 17
no vlan 18
exit
----
.. Salve a configuração em execução na configuração de inicialização:
+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
.. Execute um reinício do switch:
+
[listing, subs="+quotes"]
----
(cs2)# *reload*

Are you sure you would like to reset the system? (y/n) *y*
----
.. Faça login novamente no switch usando SSH para concluir a instalação do RCF.


. Observe o seguinte:
+
.. Caso licenças de porta adicionais tenham sido instaladas no switch, você deverá modificar o RCF para configurar as portas licenciadas adicionais. Verlink:configure-licenses.html#activate-newly-licensed-ports["Ativar portas recém-licenciadas"] para mais detalhes.
.. Registre todas as personalizações feitas no RCF anterior e aplique-as ao novo RCF.  Por exemplo, configurar as velocidades das portas ou programar o modo FEC.




[role="tabbed-block"]
====
.EFOS versão 3.12.x e posterior
--
. Copie o RCF para o bootflash do switch cs2 usando um dos seguintes protocolos de transferência: HTTP, HTTPS, FTP, TFTP, SFTP ou SCP.
+
Este exemplo mostra o uso do SFTP para copiar um arquivo RCF para a memória flash de inicialização no switch cs2:



[listing, subs="+quotes"]
----
(cs2)# *copy tftp://172.19.2.1/BES-53248-RCF-v1.9-Cluster-HA.txt nvram:reference-config*
Remote Password:**
Mode........................................... TFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /
Filename....................................... BES-53248_RCF_v1.9-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... reference-config.scr
Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
TFTP Code transfer starting...
File transfer operation completed successfully.
----
. Verifique se o script foi baixado e salvo com o nome de arquivo que você definiu:
+
`script list`

+
[listing, subs="+quotes"]
----
(cs2)# *script list*

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
reference-config.scr                       2680         2024 05 31 21:54:22
2 configuration script(s) found.
2042 Kbytes free.
----
. Aplique o script ao interruptor:
+
`script apply`

+
[listing, subs="+quotes"]
----
(cs2)# *script apply reference-config.scr*

Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully.
Configuration Saved!

Configuration script 'reference-config.scr' applied.
----


--
.Todas as outras versões EFOS
--
. Copie o RCF para o bootflash do switch cs2 usando um dos seguintes protocolos de transferência: HTTP, HTTPS, FTP, TFTP, SFTP ou SCP.
+
Este exemplo mostra o uso do SFTP para copiar um arquivo RCF para a memória flash de inicialização no switch cs2:



[listing, subs="+quotes"]
----
(cs2)# *copy sftp://172.19.2.1/tmp/BES-53248_RCF_v1.9-Cluster-HA.txt
nvram:script BES-53248_RCF_v1.9-Cluster-HA.scr*
Remote Password:**
Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.9-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.9-Cluster-HA.scr
Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...
File transfer operation completed successfully.
----
. Verifique se o script foi baixado e salvo com o nome de arquivo que você definiu:
+
`script list`

+
[listing, subs="+quotes"]
----
(cs2)# *script list*

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.9-Cluster-HA.scr          2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
. Aplique o script ao interruptor:
+
`script apply`

+
[listing, subs="+quotes"]
----
(cs2)# *script apply BES-53248_RCF_v1.9-Cluster-HA.scr*

Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully.
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.9-Cluster-HA.scr' applied.
----


--
====
. Examine a saída do banner do `show clibanner` comando.  Você deve ler e seguir estas instruções para verificar a configuração e o funcionamento corretos do switch.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show clibanner*

Banner Message configured :
=========================
BES-53248 Reference Configuration File v1.9 for Cluster/HA/RDMA

Switch   : BES-53248
Filename : BES-53248-RCF-v1.9-Cluster.txt
Date     : 10-26-2022
Version  : v1.9
Port Usage:
Ports 01 - 16: 10/25GbE Cluster Node Ports, base config
Ports 17 - 48: 10/25GbE Cluster Node Ports, with licenses
Ports 49 - 54: 40/100GbE Cluster Node Ports, with licenses, added right to left
Ports 55 - 56: 100GbE Cluster ISL Ports, base config
NOTE:
- The 48 SFP28/SFP+ ports are organized into 4-port groups in terms of port
speed:
Ports 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44,
45-48
The port speed should be the same (10GbE or 25GbE) across all ports in a 4-port
group
- If additional licenses are purchased, follow the 'Additional Node Ports
activated with Licenses' section for instructions
- If SSH is active, it will have to be re-enabled manually after 'erase
startup-config'
command has been executed and the switch rebooted
----
====
. No switch, verifique se as portas licenciadas adicionais aparecem após a aplicação do RCF:
+
[source, cli]
----
show port all | exclude Detach
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ------------ ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
====
. Verifique no interruptor se as alterações foram aplicadas:
+
[source, cli]
----
show running-config
----
+
[listing, subs="+quotes"]
----
(cs2)# *show running-config*
----
. Salve a configuração em execução para que ela se torne a configuração de inicialização ao reiniciar o switch:
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
. Reinicie o switch e verifique se a configuração em execução está correta:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

Are you sure you would like to reset the system? (y/n) *y*

System will now restart!
----
. No switch de cluster cs2, ative as portas conectadas às portas de cluster dos nós.  Por exemplo, se as portas 0/1 a 0/16 estiverem conectadas a nós ONTAP :
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)#
----
. Verifique as portas no switch CS2:
+
[source, cli]
----
show interfaces status all | exclude Detach
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# show interfaces status all | exclude Detach

                                Link    Physical    Physical    Media       Flow
Port       Name                 State   Mode        Status      Type        Control     VLAN
---------  -------------------  ------  ----------  ----------  ----------  ----------  ------
.
.
.
0/16       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/17       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/18       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
0/19       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
.
.
.
0/50       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/51       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/52       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/53       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/54       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/55       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
0/56       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
----
====
. Verifique a integridade das portas do cluster.
+
.. Verifique se as portas e0b estão ativas e íntegras em todos os nós do cluster:
+
[source, cli]
----
network port show -role cluster
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*

Node: cluster1-01
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-02

                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-03
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: cluster1-04
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false
----
====
.. Verifique o estado de funcionamento do switch no cluster:
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-01/cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
cluster01-2/cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
cluster01-3/cdp
            e0a    cs1                       0/4               BES-53248
            e0b    cs2                       0/4               BES-53248
cluster1-04/cdp
            e0a    cs1                       0/3               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====


. Verifique se o cluster exibe informações para ambos os switches do cluster.


[role="tabbed-block"]
====
.ONTAP 9.8 e posterior
--
A partir do ONTAP 9.8, utilize o comando:

[source, cli]
----
system switch ethernet show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
.ONTAP 9.7 e versões anteriores
--
Para ONTAP 9.7 e versões anteriores, utilize o comando:

[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
====
. [[passo20]]No switch de cluster cs1, desligue as portas conectadas às portas de cluster dos nós.
+
O exemplo a seguir utiliza a saída de exemplo da interface:

+
[listing, subs="+quotes"]
----
(cs1)> *enable*
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *shutdown*
----
. Verifique se as LIFs do cluster foram migradas para as portas hospedadas no switch cs2. Isso pode levar alguns segundos.
+
[source, cli]
----
network interface show -role cluster
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network            Current            Current  Is
Vserver     Interface          Admin/Oper Address/Mask       Node               Port     Home
----------- ------------------ ---------- ------------------ ------------------ -------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01        e0a      false
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01        e0b      true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02        e0a      false
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02        e0b      true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03        e0a      false
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03        e0b      true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04        e0a      false
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04        e0b      true
cluster1::*>
----
====
. Verifique se o cluster está íntegro:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health   Eligibility   Epsilon
-------------------- -------- ------------- -------
cluster1-01          true     true          false
cluster1-02          true     true          false
cluster1-03          true     true          true
cluster1-04          true     true          false
----
====
. Repita os passos 4 a 19 no switch cs1.
. Ativar reversão automática nos LIFs do cluster:
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Reinicie o interruptor cs1.  Isso faz com que as LIFs do cluster voltem às suas portas originais.  Você pode ignorar os eventos de "portas do cluster inativas" relatados nos nós enquanto o switch reinicia.
+
[listing, subs="+quotes"]
----
(cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully.
Configuration Saved! System will now restart!
----




== Etapa 3: Verifique a configuração

. No switch cs1, verifique se as portas do switch conectadas às portas do cluster estão *ativas*:
+
[source, cli]
----
show interfaces status all | exclude Detach
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# show interfaces status all | exclude Detach

                                Link    Physical    Physical    Media       Flow
Port       Name                 State   Mode        Status      Type        Control     VLAN
---------  -------------------  ------  ----------  ----------  ----------  ----------  ------
.
.
.
0/16       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/17       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/18       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
0/19       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
.
.
.
0/50       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/51       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/52       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/53       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/54       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/55       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
0/56       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
----
====
. Verifique se o ISL entre os switches cs1 e cs2 está funcionando corretamente:
+
[source, cli]
----
show port-channel 1/1
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)
Mbr     Device/       Port      Port
Ports   Timeout       Speed     Active
------- ------------- --------- -------
0/55    actor/long    Auto      True
        partner/long
0/56    actor/long    Auto      True
        partner/long
----
====
. Verifique se as LIFs do cluster retornaram à sua porta original:
+
[source, cli]
----
network interface show -role cluster
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> network interface show -role cluster
            Logical            Status     Network            Current             Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node                Port    Home
----------- ------------------ ---------- ------------------ ------------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01         e0a     true
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01         e0b     true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02         e0a     true
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02         e0b     true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03         e0a     true
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03         e0b     true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04         e0a     true
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04         e0b     true
----
====
. Verifique se o cluster está íntegro:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
----
====
. Verifique a conectividade das interfaces do cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e posterior
--
Você pode usar o `network interface check cluster-connectivity` Comando para iniciar uma verificação de acessibilidade para conectividade do cluster e, em seguida, exibir os detalhes:

`network interface check cluster-connectivity start`e `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Aguarde alguns segundos antes de executar o `show` comando para exibir os detalhes.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source              Destination         Packet
Node   Date                       LIF                 LIF                 Loss
------ -------------------------- ------------------- ------------------- -------
cluster1-01
       3/5/2022 19:21:18 -06:00   cluster1-01_clus2   cluster01-02_clus1  none
       3/5/2022 19:21:20 -06:00   cluster1-01_clus2   cluster01-02_clus2  none

cluster1-02
       3/5/2022 19:21:18 -06:00   cluster1-02_clus2   cluster1-02_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-02_clus2   cluster1-02_clus2   none
----
--
.Todas as versões do ONTAP
--
Para todas as versões do ONTAP , você também pode usar o `cluster ping-cluster -node <name>` comando para verificar a conectividade:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is cluster1-03
Getting addresses from network interface table...
Cluster cluster1-03_clus1 169.254.1.3 cluster1-03 e0a
Cluster cluster1-03_clus2 169.254.1.1 cluster1-03 e0b
Cluster cluster1-04_clus1 169.254.1.6 cluster1-04 e0a
Cluster cluster1-04_clus2 169.254.1.7 cluster1-04 e0b
Cluster cluster1-01_clus1 169.254.3.4 cluster1-01 e0a
Cluster cluster1-01_clus2 169.254.3.5 cluster1-01 e0b
Cluster cluster1-02_clus1 169.254.3.8 cluster1-02 e0a
Cluster cluster1-02_clus2 169.254.3.9 cluster1-02 e0b
Local = 169.254.1.3 169.254.1.1
Remote = 169.254.1.6 169.254.1.7 169.254.3.4 169.254.3.5 169.254.3.8
169.254.3.9
Cluster Vserver Id = 4294967293
Ping status:
............
Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)
................................................
Detected 9000 byte MTU on 12 path(s):
  Local 169.254.1.3 to Remote 169.254.1.6
  Local 169.254.1.3 to Remote 169.254.1.7
  Local 169.254.1.3 to Remote 169.254.3.4
  Local 169.254.1.3 to Remote 169.254.3.5
  Local 169.254.1.3 to Remote 169.254.3.8
  Local 169.254.1.3 to Remote 169.254.3.9
  Local 169.254.1.1 to Remote 169.254.1.6
  Local 169.254.1.1 to Remote 169.254.1.7
  Local 169.254.1.1 to Remote 169.254.3.4
  Local 169.254.1.1 to Remote 169.254.3.5
  Local 169.254.1.1 to Remote 169.254.3.8
  Local 169.254.1.1 to Remote 169.254.3.9
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----
--
====
. Altere o nível de privilégio de volta para administrador:
+
[source, cli]
----
set -privilege admin
----
. Se você desativou a criação automática de casos, reative-a enviando uma mensagem do AutoSupport :
+
[source, cli]
----
system node autosupport invoke -node * -type all -message MAINT=END
----


.O que vem a seguir?
Após instalar o RCF, você pode link:configure-ssh.html["habilitar SSH"].
