---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 'Siga estes passos para instalar o software Ethernet Fabric OS (EFOS) no switch de cluster BES-53248.' 
---
= Instale o software EFOS.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estes passos para instalar o software Ethernet Fabric OS (EFOS) no switch de cluster BES-53248.

O software EFOS inclui um conjunto de recursos e protocolos de rede avançados para o desenvolvimento de sistemas de infraestrutura Ethernet e IP.  Essa arquitetura de software é adequada para qualquer dispositivo de organização de rede que utilize aplicações que exijam inspeção ou separação minuciosa de pacotes.



== Preparar para instalação

.Antes de começar
* Este procedimento é adequado apenas para novas instalações.
* Faça o download do software Broadcom EFOS aplicável aos switches do seu cluster a partir do site https://www.broadcom.com/support/bes-switch["Suporte para switches Ethernet Broadcom"^] site.
* Garanta olink:configure-install-initial.html["O comutador de cluster BES-53248 está configurado."] .




== Instale o software

Utilize um dos seguintes métodos para instalar o software EFOS:

* <<Método 1: Instalar o EFOS>>. Utilizado na maioria dos casos.
* <<Método 2: Instalar o EFOS no modo ONIE>>. Utilize esta opção se uma versão do EFOS for compatível com FIPS e a outra versão do EFOS não for compatível com FIPS.




=== Método 1: Instalar o EFOS

Siga os passos abaixo para instalar o software EFOS.

.Passos
. Faça login na porta de console serial do switch ou conecte-se via SSH.
. Use o `ping` Comando para verificar a conectividade com o servidor que hospeda o EFOS, as licenças e o arquivo RCF.
+
.Mostrar exemplo
[%collapsible]
====
Este exemplo verifica se o switch está conectado ao servidor no endereço IP 172.19.2.1:

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Faça o download do arquivo de imagem para o switch.
+
Consulte a tabela a seguir para obter informações sobre os protocolos de cópia suportados:

+
|===


| *Protocolo* | *Pré-requisito* 


 a| 
Protocolo de Transferência de Arquivos Trivial (TFTP)
 a| 
Nenhum



 a| 
Protocolo de Transferência de Arquivos SSH (SFTP)
 a| 
Seu pacote de software deve suportar gerenciamento seguro.



 a| 
FTP
 a| 
Senha necessária



 a| 
XMODEM
 a| 
Nenhum



 a| 
YMODEM
 a| 
Nenhum



 a| 
ZMODEM
 a| 
Nenhum



 a| 
Protocolo de Cópia Segura (SCP)
 a| 
Seu pacote de software deve suportar gerenciamento seguro.



 a| 
HTTP
 a| 
Transferências de arquivos baseadas em linha de comando são suportadas em plataformas selecionadas quando um utilitário WGET nativo estiver disponível.



 a| 
HTTPS
 a| 
Transferências de arquivos baseadas em linha de comando são suportadas em plataformas selecionadas quando um utilitário WGET nativo estiver disponível.

|===
+
Copiar o arquivo de imagem para a imagem ativa significa que, ao reiniciar, essa imagem estabelecerá a versão do EFOS em execução.  A imagem anterior permanece disponível como backup.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Exibir as imagens de inicialização para a configuração ativa e de backup:
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. Reinicie o switch:
+
`reload`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. Faça login novamente e verifique a nova versão do software EFOS:
+
`show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Conclua a instalação.  Siga estes cinco passos para reconfigurar o switch:
+
.. link:configure-licenses.html["Instalar licenças"]
.. link:configure-install-rcf.html["Instale o arquivo RCF"]
.. link:configure-ssh.html["Habilitar SSH"]
.. link:CSHM_log_collection.html["Ativar coleta de logs"]
.. link:CSHM_snmpv3.html["Configure o SNMPv3 para monitoramento."]


. Repita os passos de 1 a 7 no interruptor do parceiro.




=== Método 2: Instalar o EFOS no modo ONIE

Você pode executar os seguintes passos se uma versão do EFOS for compatível com FIPS e a outra versão do EFOS não for compatível com FIPS.  Esses passos podem ser usados para instalar a imagem EFOS 3.7.xx, compatível ou não com FIPS, a partir do ONIE, caso o switch não inicialize.

.Passos
. Conecte-se a um console que esteja conectado à porta serial do switch.
. Inicialize o switch no modo de instalação ONIE.
+
Durante a inicialização, selecione ONIE quando a mensagem aparecer.

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
Após selecionar *ONIE*, o interruptor carrega e apresenta várias opções.  Selecione *Instalar SO*.

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
O switch inicia no modo de instalação ONIE.

. Interrompa a descoberta ONIE e configure a interface Ethernet.
+
Quando a seguinte mensagem aparecer, pressione *Enter* para abrir o console ONIE:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: A detecção do ONIE continua e as mensagens são impressas no console.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configure a interface Ethernet da porta de gerenciamento do switch e adicione a rota usando `ifconfig eth0 <ipAddress> netmask <netmask> up` e `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Verifique se o servidor que hospeda o arquivo de instalação do ONIE está acessível:
+
`ping`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Instale o novo software do switch:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
O software é instalado e, em seguida, reinicia o switch.  Deixe o switch reiniciar normalmente na nova versão do EFOS.

. Faça login e verifique se o novo software do switch está instalado:
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. Conclua a instalação.  O switch reinicia sem nenhuma configuração aplicada e retorna às configurações de fábrica.  Siga estes seis passos para reconfigurar o switch:
+
.. link:configure-install-initial.html["Configurar interruptor"]
.. link:configure-licenses.html["Instalar licenças"]
.. link:configure-install-rcf.html["Instale o arquivo RCF"]
.. link:configure-ssh.html["Habilitar SSH"]
.. link:CSHM_log_collection.html["Ativar coleta de logs"]
.. link:CSHM_snmpv3.html["Configure o SNMPv3 para monitoramento."]


. Repita os passos de 1 a 8 no interruptor do parceiro.


.O que vem a seguir
Após instalar o software EFOS, você pode link:configure-licenses.html["Instale suas licenças"].
