---
permalink: switch-bes-53248/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: two-node switchless clusters, migrating to a two-node switched BES-53248 cluster environment,BES-53248 switches, migrating two-node switched clusters,2-node 
summary: Se você possui um cluster sem switches de dois nós, pode migrar, sem interrupções, para um cluster com switches de dois nós que inclua switches de cluster BES-53248 compatíveis com a Broadcom. 
---
= Migre para um ambiente de cluster NetApp comutado.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você já possui um ambiente de cluster de dois nós sem switches, pode migrar para um ambiente de cluster de dois nós com switches usando os switches de cluster BES-53248 compatíveis com a Broadcom, o que permite escalar o cluster para além de dois nós.

O processo de migração funciona para todas as portas de nós do cluster que utilizam portas ópticas ou Twinax, mas não é suportado neste switch se os nós estiverem utilizando portas RJ45 10GBASE-T integradas para as portas de rede do cluster.



== Requisitos de revisão

Analise os seguintes requisitos para o ambiente de cluster.

* Tenha em mente que a maioria dos sistemas requer duas portas de rede dedicadas para o cluster em cada controlador.
* Certifique-se de que o comutador de cluster BES-53248 esteja configurado conforme descrito emlink:replace-switch-reqs.html["Requisitos de substituição"] antes de iniciar este processo de migração.
* Para a configuração sem switch de dois nós, certifique-se de que:
+
** A configuração sem switch de dois nós está configurada corretamente e funcionando.
** Os nós estão executando o ONTAP 9.5P8 ou versões posteriores.  O suporte para portas de cluster 40/100 GbE começa com a versão 3.4.4.6 e posteriores do firmware EFOS.
** Todas as portas do cluster estão no estado *ativo*.
** Todas as interfaces lógicas do cluster (LIFs) estão no estado *ativo* e em suas portas de origem.


* Para a configuração do switch de cluster BES-53248 com suporte da Broadcom, certifique-se de que:
+
** O comutador de cluster BES-53248 está totalmente funcional em ambos os comutadores.
** Ambos os switches possuem conectividade de rede de gerenciamento.
** É possível acessar os switches do cluster através do console.
** As conexões entre nós e entre switches do BES-53248 utilizam cabos Twinax ou de fibra óptica.
+
O https://hwu.netapp.com/Home/Index["_Universo de Hardware da NetApp_"^] Contém informações sobre compatibilidade com ONTAP , firmware EFOS suportado e cabeamento para switches BES-53248.



* Os cabos Inter-Switch Link (ISL) são conectados às portas 0/55 e 0/56 em ambos os switches BES-53248.
* A personalização inicial de ambos os switches BES-53248 está concluída, de modo que:
+
** Os switches BES-53248 estão executando a versão mais recente do software.
** Os switches BES-53248 possuem licenças de porta opcionais instaladas, caso sejam adquiridas.
** Os arquivos de configuração de referência (RCFs) são aplicados aos switches.


* Qualquer personalização do site (SMTP, SNMP e SSH) é configurada nos novos switches.


.restrições de velocidade do grupo portuário
* As 48 portas 10/25GbE (SFP28/SFP+) são combinadas em 12 grupos de 4 portas, da seguinte forma: Portas 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44 e 45-48.
* A velocidade da porta SFP28/SFP+ deve ser a mesma (10GbE ou 25GbE) em todas as portas do grupo de 4 portas.
* Se as velocidades em um grupo de 4 portas forem diferentes, as portas do switch não funcionarão corretamente.




== Migrar para o ambiente de cluster

.Sobre os exemplos
Os exemplos neste procedimento utilizam a seguinte nomenclatura de comutador de cluster e nó:

* Os nomes dos switches BES-53248 são `cs1` e `cs2` .
* Os nomes dos SVMs do cluster são `node1` e `node2` .
* Os nomes dos LIFs são `node1_clus1` e `node1_clus2` no nó 1, e `node2_clus1` e `node2_clus2` no nó 2, respectivamente.
* O `cluster1::*>` O prompt indica o nome do cluster.
* As portas de cluster usadas neste procedimento são `e0a` e `e0b` .
+
O https://hwu.netapp.com/Home/Index["_Universo de Hardware da NetApp_"^] Contém as informações mais recentes sobre as portas de cluster reais para suas plataformas.





=== Etapa 1: Prepare-se para a migração

. Se o AutoSupport estiver ativado neste cluster, suprima a criação automática de casos invocando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
onde x representa a duração do período de manutenção em horas.

+

NOTE: A mensagem do AutoSupport notifica o suporte técnico sobre essa tarefa de manutenção, de forma que a criação automática de chamados seja suprimida durante o período de manutenção.

+
O comando a seguir suprime a criação automática de casos por duas horas:

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. Altere o nível de privilégio para avançado, digitando *y* quando solicitado a continuar:
+
`set -privilege advanced`

+
O prompt avançado(`*>` ) aparece.





=== Etapa 2: Configurar portas e cabos

. Desative todas as portas voltadas para o nó que estiverem ativadas (exceto as portas ISL) nos dois novos switches do cluster, cs1 *e* cs2.
+

NOTE: Você não deve desativar as portas ISL.

+
O exemplo a seguir mostra que as portas voltadas para o nó, de 1 a 16, estão desativadas no switch cs1:

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. Verifique se o ISL e as portas físicas no ISL entre os dois switches BES-53248, cs1 e cs2, estão ativos:
+
`show port-channel`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que as portas ISL estão ativas no switch cs1:

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
O exemplo a seguir mostra que as portas ISL estão ativas no switch cs2:

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. Exibir a lista de dispositivos vizinhos:
+
`show isdp neighbors`

+
Este comando fornece informações sobre os dispositivos que estão conectados ao sistema.

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir lista os dispositivos vizinhos no switch cs1:

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
O exemplo a seguir lista os dispositivos vizinhos no switch cs2:

[listing, subs="+quotes"]
----
(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
====
. Verifique se todas as portas do cluster estão ativas:
+
`network port show -ipspace Cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy
----
====
. Verifique se todas as LIFs do cluster estão ativas e operacionais:
+
`network interface show -vserver Cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. Desative a reversão automática nos LIFs do cluster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. Desconecte o cabo da porta do cluster e0a no nó 1 e, em seguida, conecte e0a à porta 1 no switch do cluster cs1, usando o cabeamento apropriado suportado pelos switches BES-53248.
+
O https://hwu.netapp.com/Home/Index["_Universo de Hardware da NetApp_"^] Contém mais informações sobre cabeamento.

. Desconecte o cabo da porta do cluster e0a no nó 2 e, em seguida, conecte e0a à porta 2 no switch do cluster cs1, usando o cabeamento apropriado suportado pelos switches BES-53248.
. Habilite todas as portas voltadas para os nós no switch de cluster cs1.
+
O exemplo a seguir mostra que as portas de 1 a 16 estão habilitadas no switch cs1:

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *no shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. Verifique se todas as portas do cluster estão ativas:
+
`network port show -ipspace Cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. Verifique se todas as LIFs do cluster estão ativas e operacionais:
+
`network interface show -vserver Cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     false
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     false
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true
----
====
. Exibir informações sobre o estado dos nós no cluster:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir exibe informações sobre a integridade e a elegibilidade dos nós no cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. Desconecte o cabo da porta do cluster e0b no nó 1 e, em seguida, conecte e0b à porta 1 no switch do cluster cs2, usando o cabeamento apropriado suportado pelos switches BES-53248.
. Desconecte o cabo da porta do cluster e0b no nó 2 e, em seguida, conecte e0b à porta 2 no switch do cluster cs2, usando o cabeamento apropriado suportado pelos switches BES-53248.
. Habilite todas as portas voltadas para os nós no switch de cluster cs2.
+
O exemplo a seguir mostra que as portas de 1 a 16 estão habilitadas no switch cs2:

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)# *exit*
----
. Verifique se todas as portas do cluster estão ativas:
+
`network port show -ipspace Cluster`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====




=== Etapa 3: Verifique a configuração

. Ative a reversão automática nos LIFs do cluster.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert true*
----
. Verifique se as LIFs do cluster retornaram às suas portas originais (isso pode levar um minuto):
+
`network interface show -vserver Cluster`

+
Se as LIFs do cluster não tiverem retornado à sua porta original, reverta-as manualmente:

+
`network interface revert -vserver Cluster -lif *`

. Verifique se todas as interfaces exibem `true` para `Is Home` :
+
`network interface show -vserver Cluster`

+

NOTE: Isso pode levar alguns minutos para ser concluído.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true
----
====
. Verifique se ambos os nós possuem uma conexão com cada switch:
+
`show isdp neighbors`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra os resultados apropriados para ambas as opções:

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform -- Port ID
-------------- ------------ --------- ------------ ----------- ----------
node1          0/1          175       H            FAS2750     e0a
node2          0/2          157       H            FAS2750     e0a
cs2            0/55         178       R            BES-53248   0/55
cs2            0/56         178       R            BES-53248   0/56


(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform    Port ID
-------------- ------------ --------- ------------ ----------- ------------
node1          0/1          137       H            FAS2750     e0b
node2          0/2          179       H            FAS2750     e0b
cs1            0/55         175       R            BES-53248   0/55
cs1            0/56         175       R            BES-53248   0/56
----
====
. Exibir informações sobre os dispositivos de rede descobertos em seu cluster:
+
`network device-discovery show -protocol cdp`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
====
. Verifique se as configurações estão desativadas:
+
`network options switchless-cluster show`

+

NOTE: A conclusão do comando pode levar alguns minutos.  Aguarde o anúncio de que o tempo de vida de 3 minutos está prestes a expirar.

+
O `false` O resultado no exemplo a seguir mostra que as configurações estão desativadas:

+
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
. Verifique o status dos nós membros do cluster:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra informações sobre a saúde e a elegibilidade dos nós no cluster:

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. Verifique a conectividade das interfaces do cluster remoto:


[role="tabbed-block"]
====
.ONTAP 9.9.1 e posterior
--
Você pode usar o `network interface check cluster-connectivity` Comando para iniciar uma verificação de acessibilidade para conectividade do cluster e, em seguida, exibir os detalhes:

`network interface check cluster-connectivity start`e `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*NOTA:* Aguarde alguns segundos antes de executar o `show` comando para exibir os detalhes.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.Todas as versões do ONTAP
--
Para todas as versões do ONTAP , você também pode usar o `cluster ping-cluster -node <name>` comando para verificar a conectividade:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[passo 9]]Altere o nível de privilégio de volta para administrador:
+
`set -privilege admin`

. Se você desativou a criação automática de casos, reative-a enviando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
+
Para obter mais informações, consulte: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["Artigo da Base de Conhecimento da NetApp : Como suprimir a criação automática de chamados durante janelas de manutenção programadas"^]



.O que vem a seguir?
Depois de migrar seus switches, você pode link:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"].
