---
permalink: switch-bes-53248/required-documentation-bes53248.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: Você precisa de documentação específica sobre os switches e controladores para configurar o seu modo Cluster. 
---
= Requisitos de documentação para switches de cluster BES-53248
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalação e manutenção do switch BES-53248, certifique-se de consultar a documentação específica do switch e do controlador.



== Documentação da Broadcom

Para configurar o switch de cluster BES-53248, você precisa dos seguintes documentos, disponíveis no site de suporte da Broadcom: https://www.broadcom.com/support/bes-switch["Linha de produtos de switches Ethernet da Broadcom"^]

[cols="1,2"]
|===
| Título do documento | Descrição 


 a| 
_Guia do Administrador EFOS v3.4.3_
 a| 
Fornece exemplos de como usar o switch BES-53248 em uma rede típica.



 a| 
_Referência de Comandos da CLI do EFOS v3.4.3_
 a| 
Descreve os comandos da interface de linha de comando (CLI) que você usa para visualizar e configurar o software BES-53248.



 a| 
_Guia de Introdução ao EFOS v3.4.3_
 a| 
Fornece informações detalhadas sobre o switch BES-53248.



 a| 
_Guia de Referência SNMP do EFOS v3.4.3_
 a| 
Fornece exemplos de como usar o switch BES-53248 em uma rede típica.



 a| 
_Parâmetros e valores de escala do EFOS v3.4.3_
 a| 
Descreve os parâmetros de escala padrão com os quais o software EFOS é fornecido e validado nas plataformas suportadas.



 a| 
_Especificações Funcionais do EFOS v3.4.3_
 a| 
Descreve as especificações do software EFOS nas plataformas suportadas.



 a| 
_Notas de lançamento do EFOS v3.4.3_
 a| 
Fornece informações específicas da versão do software BES-53248.



 a| 
_Matriz de compatibilidade de rede de cluster e rede de gerenciamento_
 a| 
Fornece informações sobre compatibilidade de rede.  A matriz está disponível no site de downloads do switch BES-53248 em https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["switches de cluster Broadcom"^] .

|===


== Documentação e artigos da base de conhecimento sobre sistemas ONTAP

Para configurar um sistema ONTAP , você precisa dos seguintes documentos do site de suporte da NetApp em http://mysupport.netapp.com/["meusuporte.netapp.com"^] ou o site da Base de Conhecimento (BC) em https://kb.netapp.com/["kb.netapp.com"^] .

[cols="1,2"]
|===
| Nome | Descrição 


 a| 
https://hwu.netapp.com/Home/Index["Hardware Universe da NetApp"^]
 a| 
Descreve os requisitos de energia e de instalação para todos os equipamentos NetApp , incluindo gabinetes de sistema, e fornece informações sobre os conectores e opções de cabos relevantes a serem usados, juntamente com seus respectivos números de peça.



 a| 
Instruções de instalação e configuração específicas do controlador
 a| 
Descreve como instalar o hardware da NetApp .



 a| 
ONTAP 9
 a| 
Fornece informações detalhadas sobre todos os aspectos da versão ONTAP 9.



 a| 
_Como adicionar licenças de porta adicionais para o switch BES-53248 compatível com Broadcom_
 a| 
Fornece informações detalhadas sobre como adicionar licenças de porta.  Vá para o https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["Artigo da Base de Conhecimento"^] .

|===