---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: 'Siga estas etapas para atualizar o software do sistema operacional de malha Ethernet (EFOS) no switch de cluster BES-53248.' 
---
= Atualize o software EFOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estes passos para atualizar o software EFOS no switch de cluster BES-53248.

O software EFOS inclui um conjunto de funcionalidades de rede avançadas e protocolos para o desenvolvimento de sistemas de infra-estrutura Ethernet e IP. Esta arquitetura de software é adequada para qualquer dispositivo organizacional de rede usando aplicativos que exigem inspeção ou separação de pacotes minuciosa.



== Prepare-se para a atualização

.Antes de começar
* Faça o download do software Broadcom EFOS aplicável para seus switches de cluster a partir https://www.broadcom.com/support/bes-switch["Suporte ao comutador Ethernet Broadcom"^] do site.
* Reveja as seguintes notas sobre as versões do EFOS.


[]
====
*Observe o seguinte:*

* Ao atualizar do EFOS 3,4.x.x para o EFOS 3,7.x.x ou posterior, o switch deve estar executando o EFOS 3.4.4.6 (ou versão 3,4.x.x posterior). Se você estiver executando uma versão antes disso, atualize o switch para EFOS 3.4.4.6 (ou versão posterior 3,4.x.x) primeiro, então atualize o switch para EFOS 3,7.x.x ou posterior.
* A configuração para o EFOS 3,4.x.x e 3,7.x.x ou posterior é diferente. Alterar a versão do EFOS de 3,4.x.x para 3,7.x.x ou posterior, ou vice-versa, requer que o switch seja redefinido para os padrões de fábrica e os arquivos RCF para que a versão do EFOS correspondente seja (re)aplicada. Este procedimento requer acesso através da porta do console serial.
* A partir da versão 3,7.x.x do EFOS ou posterior, uma versão não compatível com FIPS e compatível com FIPS está disponível. Diferentes etapas se aplicam ao passar de uma versão não compatível com FIPS para uma versão compatível com FIPS ou vice-versa. Alterar o EFOS de uma versão não compatível com FIPS para uma versão compatível com FIPS ou vice-versa redefinirá o switch para os padrões de fábrica. Este procedimento requer acesso através da porta do console serial.


====
|===


| *Procedimento* | *Versão atual do EFOS* | *Nova versão EFOS* | *Passos de alto nível* 


 a| 
Etapas para atualizar o EFOS entre duas versões (não) compatíveis com FIPS
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
Atualize a nova imagem EFOS usando <<Método 1: Atualizar o EFOS>>o . As informações de configuração e licença são mantidas.



 a| 
3.4.4.6 (ou posterior 3,4.x.x)
 a| 
3,7.x.x ou posterior não compatível com FIPS
 a| 
Atualize o EFOS <<Método 1: Atualizar o EFOS>>usando o . Redefina o switch para os padrões de fábrica e aplique o arquivo RCF para EFOS 3,7.x.x ou posterior.



.2+| 3,7.x.x ou posterior não compatível com FIPS  a| 
3.4.4.6 (ou posterior 3,4.x.x)
 a| 
Downgrade EFOS usando <<Método 1: Atualizar o EFOS>>. Redefina o switch para os padrões de fábrica e aplique o arquivo RCF para EFOS 3,4.x.x



 a| 
3,7.x.x ou posterior não compatível com FIPS
 a| 
Atualize a nova imagem EFOS usando <<Método 1: Atualizar o EFOS>>o . As informações de configuração e licença são mantidas.



 a| 
3,7.x.x ou posterior compatível com FIPS
 a| 
3,7.x.x ou posterior compatível com FIPS
 a| 
Atualize a nova imagem EFOS usando <<Método 1: Atualizar o EFOS>>o . As informações de configuração e licença são mantidas.



 a| 
Passos para atualizar para/a partir de uma versão EFOS compatível com FIPS
 a| 
Não compatível com FIPS
 a| 
Compatível com FIPS
 a| 
Atualização da imagem EFOS usando <<Método 2: Atualizar o EFOS usando a instalação do sistema operacional ONIE>>o . A configuração do switch e as informações da licença serão perdidas.



 a| 
Compatível com FIPS
 a| 
Não compatível com FIPS

|===
[IMPORTANT]
====
Para verificar se sua versão do EFOS é compatível com FIPS ou não compatível com FIPS, use o `show fips status` comando. Nos exemplos a seguir, *IP_switch_A1* está usando EFOS compatível com FIPS e *IP_switch_A2* está usando EFOS não compatível com FIPS.

* Switch IP_switch_A1 (EFOS compatível com FIPS):
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* Switch IP_switch_A2 (EFOS não compatível com FIPS):
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== Atualize o software

Use um dos seguintes métodos:

* <<Método 1: Atualizar o EFOS>>. Use para a maioria dos casos (consulte a tabela acima).
* <<Método 2: Atualizar o EFOS usando a instalação do sistema operacional ONIE>>. Use se uma versão do EFOS for compatível com FIPS e a outra versão do EFOS não for compatível com FIPS.



NOTE: Atualize o EFOS em um switch de cada vez para garantir a operação contínua da rede de cluster.



=== Método 1: Atualizar o EFOS

Execute os seguintes passos para atualizar o software EFOS.


IMPORTANT: Observe que depois de atualizar os switches de cluster BES-53248 do EFOS 3,3.x.x ou 3,4.x.x para o EFOS 3.7.0.4 ou 3,8.0,2, os ISLs (Inter-Switch Links) e os canais de porta estão marcados no estado *para baixo*. Este é o comportamento esperado e é seguro continuar com a atualização, a menos que você esteja tendo problemas com LIFs de reversão automática. Consulte o artigo da base de dados de Conhecimento: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["Falha na atualização do NDU do comutador de cluster BES-53248 para o EFOS 3.7.0.4 e posterior"^] Para obter mais detalhes.

.Passos
. Conete o switch de cluster BES-53248 à rede de gerenciamento.
. Use o `ping` comando para verificar a conetividade com o servidor que hospeda EFOS, licenças e o arquivo RCF.
+
Este exemplo verifica se o switch está conetado ao servidor no endereço IP 172.19.2.1:

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Desative a reversão automática nos LIFs do cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Apresentar as imagens de arranque para a configuração ativa e de cópia de segurança:
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6              3.7.0.4        3.7.0.4

----
====
. Transfira o ficheiro de imagem para o interrutor.
+
Copiar o arquivo de imagem para a imagem ativa significa que, quando você reiniciar, essa imagem estabelece a versão do EFOS em execução. A imagem anterior permanece disponível como cópia de segurança.

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk backup*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. Apresentar as imagens de arranque para a configuração ativa e de cópia de segurança:
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4    3.7.0.4             3.7.0.4       3.10.0.3
----
====
. Inicie o sistema a partir da configuração de cópia de segurança:
+
`boot system backup`

+
[listing, subs="+quotes"]
----
(cs2)# *boot system backup*
Activating image backup ..
----
. Apresentar as imagens de arranque para a configuração ativa e de cópia de segurança:
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1    3.10.0.3    3.10.0.3            3.10.0.3       3.11.0.2
----
====
. Salve a configuração em execução na configuração de inicialização:
+
`write memory`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.

Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. Reinicie o switch:
+
`reload`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. Inicie sessão novamente e verifique a nova versão do software EFOS:
+
`show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Repita os passos 5 a 11 no interrutor CS1.
. Ative a reversão automática nos LIFs do cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Verifique se os LIFs do cluster reverteram para sua porta inicial:
+
[source, cli]
----
network interface show -role Cluster
----
+
Para obter mais detalhes, link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Reverter um LIF para sua porta inicial"]consulte .





=== Método 2: Atualizar o EFOS usando a instalação do sistema operacional ONIE

Pode executar as seguintes etapas se uma versão do EFOS for compatível com FIPS e a outra versão do EFOS não for compatível com FIPS. Estas etapas podem ser usadas para atualizar a imagem EFOS 3,7.x.x não compatível com FIPS ou FIPS do ONIE se o switch não inicializar.


NOTE: Esta funcionalidade só está disponível para EFOS 3,7.x.x ou posterior não compatível com FIPS.


CAUTION: Se você atualizar o EFOS usando a instalação do ONIE os, a configuração será redefinida para os padrões de fábrica e as licenças serão excluídas. Você deve configurar o switch e instalar licenças e um RCF suportado para retornar o switch à operação normal.

.Passos
. Desative a reversão automática nos LIFs do cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Inicialize o switch no modo de instalação ONIE.
+
Durante o arranque, selecione ONIE quando vir o aviso:

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Depois de selecionar *ONIE*, o switch carrega e apresenta várias opções. Selecione *Instalar os*.

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
O switch inicializa no modo de instalação ONIE.

. Pare a descoberta ONIE e configure a interface Ethernet.
+
Quando a seguinte mensagem for exibida, pressione *Enter* para chamar o console ONIE:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: A descoberta ONIE continua e as mensagens são impressas no console.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configure a interface Ethernet e adicione a rota utilizando `ifconfig eth0 <ipAddress> netmask <netmask> up` e. `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Verifique se o servidor que hospeda o arquivo de instalação ONIE está acessível:
+
`ping`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Instale o novo software do interrutor:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
O software instala e, em seguida, reinicia o interrutor. Deixe o switch reiniciar normalmente para a nova versão do EFOS.

. Verifique se o novo software do switch está instalado:
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. Conclua a instalação. O switch reinicializa sem nenhuma configuração aplicada e redefine para os padrões de fábrica. Execute as seguintes etapas para reconfigurar o switch:
+
.. link:configure-licenses.html["Instalar licenças"]
.. link:configure-install-rcf.html["Instale o RCF"]
.. link:configure-ssh.html["Ativar SSH"]
.. link:CSHM_log_collection.html["Ativar a coleção de registos"]
.. link:CSHM_snmpv3.html["Configure o SNMPv3 para monitoramento"]


. Repita os passos 2 a 8 no interrutor CS1.
. Ative a reversão automática nos LIFs do cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Verifique se os LIFs do cluster reverteram para sua porta inicial:
+
[source, cli]
----
network interface show -role Cluster
----
+
Para obter mais detalhes, link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Reverter um LIF para sua porta inicial"]consulte .


