---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: 'Siga estes passos para atualizar o software Ethernet Fabric OS (EFOS) no switch de cluster BES-53248.' 
---
= Atualize o software EFOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estes passos para atualizar o software EFOS no switch de cluster BES-53248.

O software EFOS inclui um conjunto de recursos e protocolos de rede avançados para o desenvolvimento de sistemas de infraestrutura Ethernet e IP.  Essa arquitetura de software é adequada para qualquer dispositivo de organização de rede que utilize aplicações que exijam inspeção ou separação minuciosa de pacotes.



== Prepare-se para a atualização

.Antes de começar
* Faça o download do software Broadcom EFOS aplicável aos switches do seu cluster a partir do site https://www.broadcom.com/support/bes-switch["Suporte para switches Ethernet Broadcom"^] site.
* Consulte as seguintes notas referentes às versões do EFOS.


[]
====
*Observe o seguinte:*

* Ao atualizar do EFOS 3.4.xx para o EFOS 3.7.xx ou posterior, o switch deve estar executando o EFOS 3.4.4.6 (ou uma versão 3.4.xx posterior).  Se você estiver executando uma versão anterior a essa, atualize primeiro o switch para o EFOS 3.4.4.6 (ou uma versão 3.4.xx posterior) e, em seguida, atualize-o para o EFOS 3.7.xx ou posterior.
* A configuração para o EFOS 3.4.xx e para o 3.7.xx ou versões posteriores é diferente.  Alterar a versão do EFOS de 3.4.xx para 3.7.xx ou posterior, ou vice-versa, exige que o switch seja redefinido para as configurações de fábrica e que os arquivos RCF da versão correspondente do EFOS sejam (re)aplicados.  Este procedimento requer acesso através da porta de console serial.
* A partir da versão 3.7.xx ou posterior do EFOS, estão disponíveis uma versão não compatível com FIPS e uma versão compatível com FIPS.  Etapas diferentes se aplicam ao migrar de uma versão não compatível com FIPS para uma versão compatível com FIPS ou vice-versa.  Alterar o EFOS de uma versão não compatível com FIPS para uma versão compatível com FIPS, ou vice-versa, redefinirá o switch para as configurações de fábrica.  Este procedimento requer acesso através da porta de console serial.


====
|===


| *Procedimento* | *Versão atual do EFOS * | *Nova versão EFOS* | *Etapas de alto nível* 


 a| 
Passos para atualizar o EFOS entre duas versões (não) compatíveis com FIPS.
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
Atualize a nova imagem EFOS usando<<Método 1: Atualizar o EFOS>> .  As informações de configuração e licença são mantidas.



 a| 
3.4.4.6 (ou posterior 3.4.xx)
 a| 
3.7.xx ou posterior não compatível com FIPS
 a| 
Atualize o EFOS usando<<Método 1: Atualizar o EFOS>> .  Restaure as configurações de fábrica do switch e aplique o arquivo RCF para EFOS 3.7.xx ou posterior.



.2+| 3.7.xx ou posterior não compatível com FIPS  a| 
3.4.4.6 (ou posterior 3.4.xx)
 a| 
Rebaixar EFOS usando<<Método 1: Atualizar o EFOS>> .  Restaure as configurações de fábrica do switch e aplique o arquivo RCF para EFOS 3.4.xx.



 a| 
3.7.xx ou posterior não compatível com FIPS
 a| 
Atualize a nova imagem EFOS usando<<Método 1: Atualizar o EFOS>> .  As informações de configuração e licença são mantidas.



 a| 
Compatível com FIPS versão 3.7.xx ou posterior
 a| 
Compatível com FIPS versão 3.7.xx ou posterior
 a| 
Atualize a nova imagem EFOS usando<<Método 1: Atualizar o EFOS>> .  As informações de configuração e licença são mantidas.



 a| 
Etapas para atualizar para/de uma versão do EFOS compatível com FIPS
 a| 
Não compatível com FIPS
 a| 
Em conformidade com o FIPS
 a| 
Atualização da imagem EFOS usando<<Método 2: Atualizar o EFOS usando a instalação do ONIE OS>> .  As informações de configuração e licença do switch serão perdidas.



 a| 
Em conformidade com o FIPS
 a| 
Não compatível com FIPS

|===
[IMPORTANT]
====
Para verificar se a sua versão do EFOS é compatível ou não com o padrão FIPS, utilize o seguinte: `show fips status` comando.  Nos exemplos a seguir, *IP_switch_a1* está usando EFOS compatível com FIPS e *IP_switch_a2* está usando EFOS não compatível com FIPS.

* No switch IP_switch_a1 (EFOS compatível com FIPS):
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* No switch IP_switch_a2 (EFOS não compatível com FIPS):
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== Atualize o software

Utilize um dos seguintes métodos:

* <<Método 1: Atualizar o EFOS>>. Utilizar na maioria dos casos (ver tabela acima).
* <<Método 2: Atualizar o EFOS usando a instalação do ONIE OS>>. Utilize esta opção se uma versão do EFOS for compatível com FIPS e a outra versão do EFOS não for compatível com FIPS.



NOTE: Atualize o EFOS em um switch de cada vez para garantir a operação contínua da rede do cluster.



=== Método 1: Atualizar o EFOS

Siga os passos abaixo para atualizar o software EFOS.


IMPORTANT: Observe que, após a atualização dos switches de cluster BES-53248 do EFOS 3.3.xx ou 3.4.xx para o EFOS 3.7.0.4 ou 3.8.0.2, os links entre switches (ISLs) e os canais de porta são marcados como *Inativos*.  Este é o comportamento esperado e você pode prosseguir com a atualização sem problemas, a menos que esteja enfrentando dificuldades com a reversão automática das LIFs.  Consulte o artigo da Base de Conhecimento: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["O cluster switch NDU apresentou falha na atualização para o EFOS 3.7.0.4 e versões posteriores (BES-53248)."^] Para obter mais detalhes.

.Passos
. Conecte o switch de cluster BES-53248 à rede de gerenciamento.
. Use o `ping` Comando para verificar a conectividade com o servidor que hospeda o EFOS, as licenças e o arquivo RCF.
+
Este exemplo verifica se o switch está conectado ao servidor no endereço IP 172.19.2.1:

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. Desative a reversão automática nos LIFs do cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Exibir as imagens de inicialização para a configuração ativa e de backup:
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6              3.7.0.4        3.7.0.4

----
====
. Faça o download do arquivo de imagem para o switch.
+
Copiar o arquivo de imagem para a imagem de backup significa que, quando você reinicializar, essa imagem estabelecerá a versão do EFOS em execução, concluindo a atualização.

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk backup*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. Exibir as imagens de inicialização para a configuração ativa e de backup:
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4    3.10.0.3            3.7.0.4       3.10.0.3
----
====
. Inicialize o sistema a partir da configuração de backup:
+
`boot system backup`

+
[listing, subs="+quotes"]
----
(cs2)# *boot system backup*
Activating image backup ..
----
. Exibir as imagens de inicialização para a configuração ativa e de backup:
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1    3.10.0.3    3.10.0.3            3.10.0.3       3.10.0.3
----
====
. Salve a configuração em execução na configuração de inicialização:
+
`write memory`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.

Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. Reinicie o switch:
+
`reload`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. Faça login novamente e verifique a nova versão do software EFOS:
+
`show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. Repita os passos 5 a 11 no interruptor cs1.
. Ative a reversão automática nos LIFs do cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Verifique se as LIFs do cluster retornaram à sua porta original:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
Para obter mais detalhes, consultelink:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Reverter um LIF para sua porta de origem"] .





=== Método 2: Atualizar o EFOS usando a instalação do ONIE OS

Você pode executar os seguintes passos se uma versão do EFOS for compatível com FIPS e a outra versão do EFOS não for compatível com FIPS.  Esses passos podem ser usados para atualizar a imagem EFOS 3.7.xx, compatível ou não com FIPS, a partir do ONIE, caso o switch não inicialize.


NOTE: Essa funcionalidade está disponível apenas para EFOS 3.7.xx ou posterior não compatível com FIPS.


CAUTION: Se você atualizar o EFOS usando a instalação do ONIE OS, a configuração será redefinida para os padrões de fábrica e as licenças serão excluídas.  Você precisa configurar o switch, instalar as licenças e um RCF compatível para que o switch volte a operar normalmente.

.Passos
. Desative a reversão automática nos LIFs do cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. Inicialize o switch no modo de instalação ONIE.
+
Durante a inicialização, selecione ONIE quando a mensagem aparecer:

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
Após selecionar *ONIE*, o interruptor carrega e apresenta várias opções.  Selecione *Instalar SO*.

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
O switch inicia no modo de instalação ONIE.

. Interrompa a descoberta ONIE e configure a interface Ethernet.
+
Quando a seguinte mensagem aparecer, pressione *Enter* para abrir o console ONIE:

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: A detecção do ONIE continua e as mensagens são impressas no console.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Configure a interface Ethernet e adicione a rota usando `ifconfig eth0 <ipAddress> netmask <netmask> up` e `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Verifique se o servidor que hospeda o arquivo de instalação do ONIE está acessível:
+
`ping`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. Instale o novo software do switch:
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
O software é instalado e, em seguida, reinicia o switch.  Deixe o switch reiniciar normalmente na nova versão do EFOS.

. Verifique se o novo software do switch está instalado:
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. Conclua a instalação.  O switch reinicia sem nenhuma configuração aplicada e retorna às configurações de fábrica.  Siga os passos abaixo para reconfigurar o switch:
+
.. link:configure-licenses.html["Instalar licenças"]
.. link:configure-install-rcf.html["Instale o RCF"]
.. link:configure-ssh.html["Habilitar SSH"]
.. link:CSHM_log_collection.html["Ativar coleta de logs"]
.. link:CSHM_snmpv3.html["Configure o SNMPv3 para monitoramento."]


. Repita os passos 2 a 8 no interruptor cs1.
. Ative a reversão automática nos LIFs do cluster.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. Verifique se as LIFs do cluster retornaram à sua porta original:
+
[source, cli]
----
network interface show -vserver Cluster
----
+
Para obter mais detalhes, consultelink:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["Reverter um LIF para sua porta de origem"] .


