---
permalink: switch-cisco-3132q-v/cn1610-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Antes de configurar os switches Cisco Nexus 3132q-v, revise uma visão geral do processo e da nomenclatura. 
---
= Requisitos de migração
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Os switches Cisco Nexus 3132Q-V podem ser usados como switches de cluster no seu cluster AFF ou FAS . Os switches de cluster permitem que você crie clusters ONTAP com mais de dois nós.

[NOTE]
====
O procedimento requer o uso de comandos ONTAP e comandos dos switches Cisco Nexus série 3000; os comandos ONTAP são usados, a menos que indicado de outra forma.

====
Para mais informações, consulte:

* https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["Página de descrição dos NetApp CN1601 e CN1610"^]
* https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Página de descrição do switch Ethernet da Cisco"^]
* http://hwu.netapp.com["Hardware Universe"^]




== Requisitos CN1610

Os seguintes switches de cluster são suportados:

* NetApp CN1610
* Cisco Nexus 3132Q-V


Os switches de cluster suportam as seguintes conexões de nó:

* NetApp CN1610: portas 0/1 a 0/12 (10 GbE)
* Cisco Nexus 3132Q-V: portas e1/1-30 (40/100 GbE)


Os switches do cluster utilizam as seguintes portas de enlace entre switches (ISL):

* NetApp CN1610: portas 0/13 a 0/16 (10 GbE)
* Cisco Nexus 3132Q-V: portas e1/31-32 (40/100 GbE)
+
Olink:https://hwu.netapp.com/["Hardware Universe"^] Contém informações sobre a cablagem compatível com os switches Nexus 3132Q-V:

* Os nós com conexões de cluster de 10 GbE requerem cabos breakout de fibra óptica QSFP para SFP+ ou cabos breakout de cobre QSFP para SFP+.
* Nós com conexões de cluster 40/100 GbE requerem módulos ópticos QSFP/QSFP28 compatíveis com cabos de fibra óptica ou cabos de cobre QSFP/QSFP28 de conexão direta.


A cablagem ISL adequada é a seguinte:

* Início: Para CN1610 a CN1610 (SFP+ a SFP+), quatro cabos de fibra óptica ou cobre SFP+ de conexão direta.
* Provisório: Para CN1610 para Nexus 3132Q-V (conversor QSFP para quatro SFP+), um cabo de fibra óptica ou cobre com conversor QSFP para SFP+
* Final: Para conexão direta entre Nexus 3132Q-V e Nexus 3132Q-V (QSFP28 para QSFP28), utilize dois cabos de fibra óptica ou cobre QSFP28.


Os cabos twinax da NetApp não são compatíveis com os switches Cisco Nexus 3132Q-V.

Se a sua configuração atual do CN1610 utiliza cabos twinax da NetApp para conexões entre nós do cluster e switches ou conexões ISL, e você deseja continuar usando twinax em seu ambiente, será necessário adquirir cabos twinax da Cisco .  Alternativamente, você pode usar cabos de fibra óptica tanto para as conexões ISL quanto para as conexões entre os nós do cluster e os switches.

.Sobre os exemplos utilizados
Os exemplos neste procedimento descrevem a substituição de switches CN1610 por switches Cisco Nexus 3132Q-V.  Você pode usar esses passos (com algumas modificações) para outros switches Cisco mais antigos.

O procedimento também utiliza a seguinte nomenclatura de interruptores e nós:

* Os resultados dos comandos podem variar dependendo das diferentes versões do ONTAP.
* Os interruptores CN1610 a serem substituídos são *CL1* e *CL2*.
* Os switches Nexus 3132Q-V para substituir os switches CN1610 são *C1* e *C2*.
* *n1_clus1* é a primeira interface lógica de cluster (LIF) conectada ao switch de cluster 1 (CL1 ou C1) para o nó *n1*.
* *n1_clus2* é a primeira LIF de cluster conectada ao switch de cluster 2 (CL2 ou C2) para o nó *n1*.
* *n1_clus3* é a segunda LIF conectada ao switch de cluster 2 (CL2 ou C2) para o nó *n1*.
* *n1_clus4* é a segunda LIF conectada ao switch de cluster 1 (CL1 ou C1) para o nó *n1*.
* O número de portas 10 GbE e 40/100 GbE é definido nos arquivos de configuração de referência (RCFs) disponíveis no https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Download do arquivo de configuração de referência do switch de rede de cluster Cisco"^] página.
* Os nós são *n1*, *n2*, *n3* e *n4*.


Os exemplos neste procedimento utilizam quatro nós:

* Dois nós utilizam quatro portas de interconexão de cluster 10 GbE: *e0a*, *e0b*, *e0c* e *e0d*.
* Os outros dois nós usam duas portas de interconexão de cluster de 40 GbE: *e4a* e *e4e*.
+
Olink:https://hwu.netapp.com/["Hardware Universe"^] Lista as portas de cluster reais em suas plataformas.



.O que vem a seguir?
link:cn5596-prepare-to-migrate.html["Prepare-se para a migração"].
