---
permalink: switch-cisco-3132q-v/cn5596-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Antes de configurar os switches Cisco Nexus 3132q-v, revise uma visão geral do processo e da nomenclatura. 
---
= Requisitos de migração
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Os switches Cisco Nexus 3132Q-V podem ser usados como switches de cluster em seu cluster AFF ou FAS. Os switches de cluster permitem que você crie clusters do ONTAP com mais de dois nós.

[NOTE]
====
O procedimento requer o uso de comandos ONTAP e comandos Cisco Nexus 3000 Series switches; os comandos ONTAP são usados, a menos que indicado de outra forma.

====
Para obter mais informações, consulte:

* http://support.netapp.com/NOW/download/software/cm_switches/["Página de descrição do comutador Ethernet Cisco"^]
* http://hwu.netapp.com["Hardware Universe"^]




== Cisco Nexus 5596 requisitos

Os switches de cluster usam as seguintes portas para conexões com nós:

* Nexus 5596: Portas E1/1-40 (10 GbE)
* Nexus 3132Q-V: Portas E1/1-30 (10/40/100 GbE)


Os switches do cluster usam as seguintes portas ISL (Inter-Switch Link):

* Nexus 5596: Portas E1/41-48 (10 GbE)
* Nexus 3132Q-V: Portas E1/31-32 (40/100 GbE)


O link:https://hwu.netapp.com/["_Hardware Universe_"^] contém informações sobre cabeamento compatível com switches Nexus 3132Q-V:

* Os nós com conexões de cluster de 10 GbE exigem cabos de conexões de fibra ótica QSFP para SFP ou cabos de conexões de cobre QSFP para SFP.
* Os nós com conexões de cluster de 40/100 GbE exigem módulos óticos QSFP/QSFP28 com cabos de fibra ou cabos de conexão direta de cobre QSFP/QSFP28.


Os switches de cluster usam o cabeamento ISL apropriado:

* Início: Nexus 5596 (SFP para SFP)
+
** 8x cabos de conexão direta de fibra ou cobre SFP


* Interino: Nexus 5596 para Nexus 3132Q-V (QSFP para mais de 4xSFP break-out)
+
** 1x cabos de rutura de fibra QSFP para SFP ou de rutura de cobre


* Final: Nexus 3132Q-V para Nexus 3132Q-V (QSFP28 a QSFP28)
+
** 2x QSFP28 cabos de ligação direta de fibra ou cobre


* Nos switches Nexus 3132Q-V, você pode operar portas QSFP/QSFP28 nos modos 40/100 Gigabit Ethernet ou 4 x10 Gigabit Ethernet.
+
Por padrão, existem 32 portas no modo 40/100 Gigabit Ethernet. Essas 40 portas Gigabit Ethernet são numeradas em uma convenção de nomenclatura de 2 tuplos. Por exemplo, a segunda porta 40 Gigabit Ethernet é numerada como 1/2.

+
O processo de alteração da configuração de 40 Gigabit Ethernet para 10 Gigabit Ethernet é chamado _breakout_ e o processo de alteração da configuração de 10 Gigabit Ethernet para 40 Gigabit Ethernet é chamado _breakin_.

+
Quando você divide uma porta Ethernet de 40/100 Gigabit em 10 portas Gigabit Ethernet, as portas resultantes são numeradas usando uma convenção de nomenclatura de 3 tuplas. Por exemplo, as portas de saída da segunda porta 40/100 Gigabit Ethernet são numeradas como 1/2/1, 1/2/2, 1/2/4 e 1/2/3.

* No lado esquerdo dos switches Nexus 3132Q-V estão 2 portas SFP mais, chamadas 1/33 e 1/34.
* Você configurou algumas das portas nos switches Nexus 3132Q-V para serem executadas a 10 GbE ou 40/100 GbE.
+
[NOTE]
====
Você pode dividir as primeiras seis portas no modo 4x10 GbE usando o `interface breakout module 1 port 1-6 map 10g-4x` comando. Da mesma forma, você pode reagrupar as primeiras seis portas QSFP a partir da configuração de breakout usando o `no interface breakout module 1 port 1-6 map 10g-4x` comando.

====
* Você fez o Planejamento, a migração e leu a documentação necessária sobre a conectividade de 10 GbE e 40/100 GbE dos nós para os switches de cluster Nexus 3132Q-V.
* As versões ONTAP e NX-os suportadas neste procedimento estão no link:http://support.netapp.com/NOW/download/software/cm_switches/.html["Página de switches Ethernet Cisco"^].


.Sobre os exemplos usados
Os exemplos neste procedimento descrevem a substituição de switches Cisco Nexus 5596 por switches Cisco Nexus 3132Q-V. Pode utilizar estes passos (com modificações) para outras centrais Cisco mais antigas.

O procedimento também usa a seguinte nomenclatura de switch e nó:

* As saídas de comando podem variar dependendo de diferentes versões do ONTAP.
* Os switches Nexus 5596 a serem substituídos são *CL1* e *CL2*.
* Os switches Nexus 3132Q-V para substituir os switches Nexus 5596 são *C1* e *C2*.
* *n1_clus1* é a primeira interface lógica de cluster (LIF) conetada ao switch de cluster 1 (CL1 ou C1) para o nó *n1*.
* *n1_clus2* é o primeiro cluster LIF conetado ao switch de cluster 2 (CL2 ou C2) para o nó *n1*.
* *n1_clus3* é o segundo LIF conetado ao switch de cluster 2 (CL2 ou C2) para o nó *n1*.
* *n1_clus4* é o segundo LIF conetado ao switch de cluster 1 (CL1 ou C1) para o nó *n1*.
* O número de portas 10 GbE e 40/100 GbE é definido nos arquivos de configuração de referência (RCFs) disponíveis na https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Download do arquivo de configuração de referência do comutador de rede de cluster Cisco"^] página.
* Os nós são *n1*, *n2*, *n3* e *n4*.


Os exemplos neste procedimento usam quatro nós:

* Dois nós usam quatro portas de interconexão de cluster de 10 GbE: *e0a*, *e0b*, *e0c* e *e0d*.
* Os outros dois nós usam duas portas de interconexão de cluster de 40 GbE: *e4a* e *e4e*.
+
A link:https://hwu.netapp.com/["_Hardware Universe_"^] lista as portas de cluster reais em suas plataformas.



.Cenários abordados
Este procedimento abrange os seguintes cenários:

* O cluster começa com dois nós conectados e funcionando em dois switches de cluster Nexus 5596.
* O interrutor do cluster CL2 a ser substituído por C2 (passos 1 a 19):
+
** O tráfego em todas as portas de cluster e LIFs em todos os nós conectados ao CL2 é migrado para as primeiras portas de cluster e LIFs conetadas ao CL1.
** Desconete o cabeamento de todas as portas de cluster em todos os nós conectados ao CL2 e use o cabeamento de saída compatível para reconetar as portas ao novo switch de cluster C2.
** Desconete o cabeamento entre as portas ISL entre CL1 e CL2 e, em seguida, use o cabeamento de saída suportado para reconetar as portas de CL1 a C2.
** O tráfego em todas as portas de cluster e LIFs conetadas ao C2 em todos os nós é revertido.


* O interrutor do cluster CL2 a ser substituído por C2.
+
** O tráfego em todas as portas de cluster ou LIFs em todos os nós conectados ao CL1 é migrado para as segundas portas de cluster ou LIFs conetadas ao C2.
** Desconete o cabeamento de todas as portas de cluster em todos os nós conectados ao CL1 e reconete, usando o cabeamento de saída compatível, ao novo switch de cluster C1.
** Desconete o cabeamento entre as portas ISL entre CL1 e C2 e reconete usando o cabeamento suportado, de C1 a C2.
** O tráfego em todas as portas de cluster ou LIFs conetadas ao C1 em todos os nós é revertido.


* Dois nós de FAS9000 foram adicionados ao cluster com exemplos mostrando detalhes do cluster.


.O que se segue?
link:cn5596-prepare-to-migrate.html["Prepare-se para a migração"].
