---
permalink: switch-cisco-3132q-v/cn5596-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Antes de configurar os switches Cisco Nexus 3132q-v, revise uma visão geral do processo e da nomenclatura. 
---
= Requisitos de migração
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Os switches Cisco Nexus 3132Q-V podem ser usados como switches de cluster no seu cluster AFF ou FAS . Os switches de cluster permitem que você crie clusters ONTAP com mais de dois nós.

[NOTE]
====
O procedimento requer o uso de comandos ONTAP e comandos dos switches Cisco Nexus série 3000; os comandos ONTAP são usados, a menos que indicado de outra forma.

====
Para mais informações, consulte:

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== Requisitos do Cisco Nexus 5596

Os switches do cluster utilizam as seguintes portas para conexões com os nós:

* Nexus 5596: portas e1/1-40 (10 GbE)
* Nexus 3132Q-V: portas e1/1-30 (10/40/100 GbE)


Os switches do cluster utilizam as seguintes portas de Inter-Switch Link (ISL):

* Nexus 5596: portas e1/41-48 (10 GbE)
* Nexus 3132Q-V: portas e1/31-32 (40/100 GbE)


Olink:https://hwu.netapp.com/["_Universo do Hardware_"^] Contém informações sobre a cablagem compatível com os switches Nexus 3132Q-V:

* Os nós com conexões de cluster de 10 GbE requerem cabos breakout de fibra óptica QSFP para SFP+ ou cabos breakout de cobre QSFP para SFP+.
* Os nós com conexões de cluster 40/100 GbE requerem módulos ópticos QSFP/QSFP28 compatíveis com cabos de fibra óptica ou cabos de cobre QSFP/QSFP28 de conexão direta.


Os switches do cluster utilizam a cablagem ISL apropriada:

* Início: Nexus 5596 (SFP+ para SFP+)
+
** 8 cabos de conexão direta SFP+ em fibra óptica ou cobre


* Interino: Nexus 5596 para Nexus 3132Q-V (adaptador QSFP para 4xSFP+)
+
** 1 cabo breakout de fibra óptica ou de cobre QSFP para SFP+


* Versão final: Nexus 3132Q-V para Nexus 3132Q-V (QSFP28 para QSFP28)
+
** 2 cabos de fibra óptica ou cobre QSFP28 com conexão direta


* Nos switches Nexus 3132Q-V, você pode operar as portas QSFP/QSFP28 nos modos 40/100 Gigabit Ethernet ou 4 x10 Gigabit Ethernet.
+
Por padrão, existem 32 portas no modo Gigabit Ethernet 40/100.  Essas 40 portas Gigabit Ethernet são numeradas seguindo uma convenção de nomenclatura de 2 elementos.  Por exemplo, a segunda porta Ethernet de 40 Gigabits é numerada como 1/2.

+
O processo de alterar a configuração de Ethernet de 40 Gigabit para Ethernet de 10 Gigabit é chamado de _breakout_ e o processo de alterar a configuração de Ethernet de 10 Gigabit para Ethernet de 40 Gigabit é chamado de _breakin_.

+
Ao dividir uma porta Gigabit Ethernet de 40/100 em 10 portas Gigabit Ethernet, as portas resultantes são numeradas usando uma convenção de nomenclatura de 3 elementos.  Por exemplo, as portas de conexão da segunda porta Gigabit Ethernet 40/100 são numeradas como 1/2/1, 1/2/2, 1/2/3 e 1/2/4.

* No lado esquerdo dos switches Nexus 3132Q-V encontram-se duas portas SFP+, denominadas 1/33 e 1/34.
* Você configurou algumas portas nos switches Nexus 3132Q-V para operar em 10 GbE ou 40/100 GbE.
+
[NOTE]
====
Você pode configurar as seis primeiras portas para o modo 4x10 GbE usando o `interface breakout module 1 port 1-6 map 10g-4x` comando.  Da mesma forma, você pode reagrupar as seis primeiras portas QSFP+ da configuração de breakout usando o `no interface breakout module 1 port 1-6 map 10g-4x` comando.

====
* Você já realizou o planejamento, a migração e leu a documentação necessária sobre a conectividade de 10 GbE e 40/100 GbE dos nós para os switches de cluster Nexus 3132Q-V.
* As versões do ONTAP e do NX-OS suportadas neste procedimento são as seguintes:link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet da Cisco"^] .


.Sobre os exemplos utilizados
Os exemplos neste procedimento descrevem a substituição de switches Cisco Nexus 5596 por switches Cisco Nexus 3132Q-V.  Você pode usar esses passos (com algumas modificações) para outros switches Cisco mais antigos.

O procedimento também utiliza a seguinte nomenclatura de interruptores e nós:

* Os resultados dos comandos podem variar dependendo das diferentes versões do ONTAP.
* Os switches Nexus 5596 a serem substituídos são *CL1* e *CL2*.
* Os switches Nexus 3132Q-V para substituir os switches Nexus 5596 são *C1* e *C2*.
* *n1_clus1* é a primeira interface lógica de cluster (LIF) conectada ao switch de cluster 1 (CL1 ou C1) para o nó *n1*.
* *n1_clus2* é a primeira LIF de cluster conectada ao switch de cluster 2 (CL2 ou C2) para o nó *n1*.
* *n1_clus3* é a segunda LIF conectada ao switch de cluster 2 (CL2 ou C2) para o nó *n1*.
* *n1_clus4* é a segunda LIF conectada ao switch de cluster 1 (CL1 ou C1) para o nó *n1*.
* O número de portas 10 GbE e 40/100 GbE é definido nos arquivos de configuração de referência (RCFs) disponíveis emlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Download do arquivo de configuração de referência do switch de rede de cluster Cisco"^] .
* Os nós são *n1*, *n2*, *n3* e *n4*.


Os exemplos neste procedimento utilizam quatro nós:

* Dois nós utilizam quatro portas de interconexão de cluster 10 GbE: *e0a*, *e0b*, *e0c* e *e0d*.
* Os outros dois nós usam duas portas de interconexão de cluster de 40 GbE: *e4a* e *e4e*.
+
Olink:https://hwu.netapp.com/["_Universo do Hardware_"^] Lista as portas de cluster reais em suas plataformas.



.Cenários abordados
Este procedimento abrange os seguintes cenários:

* O cluster inicia com dois nós conectados e funcionando em dois switches de cluster Nexus 5596.
* O interruptor do cluster CL2 deve ser substituído por C2 (etapas 1 a 19):
+
** O tráfego em todas as portas do cluster e LIFs em todos os nós conectados ao CL2 é migrado para as primeiras portas do cluster e LIFs conectadas ao CL1.
** Desconecte os cabos de todas as portas do cluster em todos os nós conectados ao CL2 e, em seguida, use cabos de breakout compatíveis para reconectar as portas ao novo switch de cluster C2.
** Desconecte os cabos entre as portas ISL entre CL1 e CL2 e, em seguida, use cabos breakout compatíveis para reconectar as portas de CL1 a CL2.
** O tráfego em todas as portas do cluster e LIFs conectadas ao C2 em todos os nós foi revertido.


* O interruptor de cluster CL2 será substituído por C2.
+
** O tráfego em todas as portas de cluster ou LIFs em todos os nós conectados ao CL1 é migrado para as segundas portas de cluster ou LIFs conectadas ao C2.
** Desconecte os cabos de todas as portas do cluster em todos os nós conectados ao CL1 e reconecte-os, usando cabos breakout compatíveis, ao novo switch de cluster C1.
** Desconecte os cabos entre as portas ISL entre CL1 e C2 e reconecte-os usando cabos compatíveis, de C1 para C2.
** O tráfego em todas as portas do cluster ou LIFs conectadas ao C1 em todos os nós é revertido.


* Dois nós FAS9000 foram adicionados ao cluster, com exemplos mostrando detalhes do cluster.


.O que vem a seguir?
Após analisar os requisitos de migração, você podelink:cn5596-prepare-to-migrate.html["Prepare-se para migrar seus switches."] .
