---
permalink: switch-cisco-3132q-v/configure-reqs-3132q.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: Analise os requisitos de configuração dos switches de cluster Cisco Nexus 3132Q-V antes da instalação ou atualização. 
---
= Analise os requisitos de configuração para os switches de cluster Cisco Nexus 3132Q-V
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Analise os requisitos de configuração dos switches de cluster Cisco Nexus 3132Q-V antes da instalação ou atualização.



[[configuration-requirements]]
== Requisitos de configuração

Para configurar seu cluster, você precisa da quantidade e do tipo adequados de cabos e conectores para seus switches. Dependendo do tipo de switch que você estiver configurando inicialmente, você precisa se conectar à porta de console do switch com o cabo de console incluso; você também precisa fornecer informações específicas de rede.



[[network-requirements]]
== Requisitos de rede

Você precisa das seguintes informações de rede para todas as configurações de switch:

* Sub-rede IP para tráfego de rede de gerenciamento.
* Nomes de host e endereços IP para cada um dos controladores do sistema de storage e todos os switches aplicáveis.
* A maioria dos controladores de sistema de storage é gerenciada pela interface e0M ao se conectar à porta de serviço Ethernet (ícone de chave inglesa). Nos sistemas AFF A800 e AFF A700, a interface e0M utiliza uma porta Ethernet dedicada.


.Informações relacionadas
* Consulte o link:https://hwu.netapp.com["Hardware Universe"^] para obter as informações mais recentes.
* Consulte link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Que informações adicionais preciso para instalar meu equipamento que não está no HWU?"^] para obter mais informações sobre os requisitos de instalação do switch.


.O que vem a seguir
Após analisar os requisitos de configuração, você pode revisar o link:required-documentation-3132q.html["documentação necessária"].
