---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Antes de configurar os switches Cisco Nexus 3132q-v, revise uma visão geral do processo e da nomenclatura. 
---
= Requisitos de migração
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Se você tiver um cluster sem switch de dois nós, revise este procedimento para os requisitos aplicáveis para migrar para um cluster comutado de dois nós.

[NOTE]
====
O procedimento requer o uso de comandos ONTAP e comandos Cisco Nexus 3000 Series switches; os comandos ONTAP são usados, a menos que indicado de outra forma.

====
Para obter mais informações, consulte:

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 e CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switch Ethernet Cisco"^]
* link:http://hwu.netapp.com["Hardware Universe"^]


.Conexões de porta e nó
Certifique-se de entender os requisitos de cabeamento e conexões de nó e porta ao migrar para um cluster comutado de dois nós com os switches de cluster Cisco Nexus 3132Q-V.

* Os switches do cluster usam as portas ISL (Inter-Switch Link) E1/31-32.
* O link:https://hwu.netapp.com/["Hardware Universe"^] contém informações sobre cabeamento compatível com switches Nexus 3132Q-V:
+
** Os nós com conexões de cluster de 10 GbE exigem módulos óticos QSFP com cabos de fibra breakout ou cabos de rutura de cobre QSFP para SFP.
** Os nós com conexões de cluster de 40 GbE exigem módulos óticos QSFP/QSFP28 com cabos de fibra ou cabos de conexão direta de cobre QSFP/QSFP28.
** Os switches de cluster usam o cabeamento ISL apropriado: Cabos de conexão direta de fibra 2x QSFP28 ou cobre.


* No Nexus 3132Q-V, você pode operar portas QSFP como modos Ethernet de 40 GB ou Ethernet 4x10 GB.
+
Por padrão, existem 32 portas no modo Ethernet de 40 GB. Essas portas Ethernet de 40 GB são numeradas em uma convenção de nomenclatura de 2 tuplos. Por exemplo, a segunda porta Ethernet de 40 GB é numerada como 1/2. O processo de alteração da configuração de Ethernet de 40 GB para Ethernet de 10 GB é chamado _breakout_ e o processo de alteração da configuração de Ethernet de 10 GB para Ethernet de 40 GB é chamado _breakin_. Quando você divide uma porta Ethernet de 40 GB em portas Ethernet de 10 GB, as portas resultantes são numeradas usando uma convenção de nomenclatura de 3 tuplas. Por exemplo, as portas de saída da segunda porta Ethernet de 40 GB são numeradas como 1/2/1, 1/2/2, 1/2/4 e 1/2/3.

* No lado esquerdo do Nexus 3132Q-V está um conjunto de quatro portas SFP multiplexadas para a primeira porta QSFP.
+
Por padrão, o RCF é estruturado para usar a primeira porta QSFP.

+
Você pode ativar quatro portas SFP em vez de uma porta QSFP para Nexus 3132Q-V usando o `hardware profile front portmode sfp-plus` comando. Da mesma forma, você pode redefinir o Nexus 3132Q-V para usar uma porta QSFP em vez de quatro portas SFP usando o `hardware profile front portmode qsfp` comando.

* Certifique-se de que configurou algumas das portas no Nexus 3132Q-V para serem executadas a 10 GbE ou 40 GbE.
+
Você pode dividir as primeiras seis portas no modo 4x10 GbE usando o `interface breakout module 1 port 1-6 map 10g-4x` comando. Da mesma forma, você pode reagrupar as primeiras seis portas QSFP a partir da configuração de breakout usando o `no interface breakout module 1 port 1-6 map 10g-4x` comando.

* O número de portas de 10 GbE e 40 GbE é definido nos arquivos de configuração de referência (RCFs) disponíveis emlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Transferência do ficheiro de configuração de referência do comutador de rede de cluster da Cisco"^] .


.Antes de começar
* Configurações corretamente configuradas e funcionando.
* Nós executando o ONTAP 9.4 ou posterior.
* Todas as portas de cluster `up` no estado.
* O switch de cluster Cisco Nexus 3132Q-V é suportado.
* A configuração de rede de cluster existente tem:
+
** A infraestrutura de cluster do Nexus 3132 que é redundante e totalmente funcional em ambos os switches.
** As versões mais recentes do RCF e NX-os em seus switches.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Switches Ethernet Cisco"^]tem informações sobre as versões do ONTAP e do NX-OS suportadas neste procedimento.

** Conetividade de gerenciamento em ambos os switches.
** Acesso ao console a ambos os switches.
** Todas as interfaces lógicas de cluster (LIFs) no `up` estado sem serem migradas.
** Personalização inicial do switch.
** Todas as portas ISL ativadas e cabeadas.




Além disso, você precisa Planejar, migrar e ler a documentação necessária sobre a conectividade de 10 GbE e 40 GbE dos nós para os switches de cluster Nexus 3132Q-V.

.Sobre os exemplos usados
Os exemplos deste procedimento utilizam a seguinte nomenclatura de switch e nó:

* Switches de cluster Nexus 3132Q-V, C1 e C2.
* Os nós são n1 e n2.


[NOTE]
====
Os exemplos neste procedimento usam dois nós, cada um usando duas portas de interconexão de cluster de 40 GbE *e4a* e *e4e*. link:https://hwu.netapp.com/["Hardware Universe"^]O tem detalhes sobre as portas de cluster em suas plataformas.

====
Este procedimento abrange os seguintes cenários:

* *n1_clus1* é a primeira interface lógica de cluster (LIF) a ser conetada ao switch de cluster C1 para o nó *n1*.
* *n1_clus2* é o primeiro cluster LIF a ser conetado ao switch de cluster C2 para o nó *n1*.
* *n2_clus1* é o primeiro cluster LIF a ser conetado ao switch de cluster C1 para o nó *n2*.
* *n2_clus2* é o segundo LIF de cluster a ser conetado ao switch de cluster C2 para o nó *n2*.
* O número de portas de 10 GbE e 40 GbE é definido nos arquivos de configuração de referência (RCFs) disponíveis emlink:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Transferência do ficheiro de configuração de referência do comutador de rede de cluster da Cisco"^] .


[NOTE]
====
O procedimento requer o uso de comandos ONTAP e comandos Cisco Nexus 3000 Series switches; os comandos ONTAP são usados, a menos que indicado de outra forma.

====
* O cluster começa com dois nós conetados e funcionando em uma configuração de cluster sem switch de dois nós.
* A primeira porta de cluster é movida para C1.
* A segunda porta do cluster é movida para C2.
* A opção de cluster sem switch de dois nós está desativada.


.O que se segue?
link:migrate-switchless-prepare-to-migrate.html["Prepare-se para a migração"].
