---
permalink: switch-cisco-3132q-v/required-documentation-3132q.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: Analise a documentação necessária para instalar e manter os switches de cluster Cisco Nexus 3132Q-V. 
---
= Analise os requisitos de documentação para os switches de cluster Cisco Nexus 3132Q-V
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Analise a documentação do switch e do controlador necessária para configurar os switches de cluster Cisco Nexus 3132Q-V e configurá-los em um cluster ONTAP.



[[switch-documentation]]
== Documentação do Switch

Para configurar os switches Cisco Nexus 3132Q-V, você precisa da seguinte documentação de link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Suporte para switches Cisco Nexus 3000 Series"^].

[cols="1,2"]
|===
| Título do documento | Descrição 


 a| 
_Guia de Instalação de Hardware da Série Nexus 3000_
 a| 
Fornece informações detalhadas sobre os requisitos do local, detalhes do hardware do switch e opções de instalação.



 a| 
_Guias de Configuração de Software para Switches Cisco Nexus 3000 Series_ (escolha o guia correspondente à versão do NX-OS instalada em seus switches)
 a| 
Fornece as informações iniciais de configuração do switch necessárias antes de configurá-lo para operação com ONTAP .



 a| 
_Cisco Nexus 3000 Series NX-OS Software Upgrade and Downgrade Guide_ (escolha o guia correspondente à versão do NX-OS instalada em seus switches)
 a| 
Fornece informações sobre como fazer o downgrade do software do switch para uma versão compatível com ONTAP , se necessário.



 a| 
_Índice principal de referência de comandos do Cisco Nexus 3000 Series NX-OS_
 a| 
Fornece links para as diversas referências de comandos disponibilizadas pela Cisco.



 a| 
_Referência de MIBs do Cisco Nexus 3000_
 a| 
Descreve os arquivos da Base de Informações de Gerenciamento (MIB) para os switches Nexus 3000.



 a| 
_Referência de mensagens do sistema NX-OS da série Nexus 3000_
 a| 
Descreve as mensagens do sistema para switches Cisco Nexus 3000 Series, incluindo as informativas e outras que podem ajudar a diagnosticar problemas com links, hardware interno ou software do sistema.



 a| 
_Notas de versão do Cisco Nexus 3000 Series NX-OS (selecione as notas para a versão do NX-OS instalada em seus switches)_
 a| 
Descreve os recursos, bugs e limitações da Cisco Nexus 3000 Series.



 a| 
Informações regulamentares, de conformidade e de segurança para Cisco Nexus 6000, Cisco Nexus 5000 Series, Cisco Nexus 3000 Series e Cisco Nexus 2000 Series
 a| 
Fornece informações sobre conformidade com agências internacionais, segurança e informações estatutárias para os switches da série Nexus 3000.

|===


[[ontap-systems-documentation]]
== Documentação dos sistemas ONTAP

Para configurar um sistema ONTAP, você precisa dos seguintes documentos para a sua versão do sistema operacional.

[cols="1,2"]
|===
| Nome | Descrição 


 a| 
Instruções de instalação e configuração específicas do controlador
 a| 
Descreve como instalar o hardware da NetApp .



 a| 
link:https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^]
 a| 
Fornece informações detalhadas sobre todos os aspectos das versões do ONTAP .



 a| 
link:https://hwu.netapp.com["Hardware Universe"^]
 a| 
Fornece informações sobre configuração e compatibilidade de hardware da NetApp .

|===


[[rail-kit-and-cabinet-documentation]]
== Kit de trilhos e documentação do gabinete

Para instalar um switch Cisco 3132Q-V em um NetApp cabinet, consulte a seguinte documentação de hardware.

[cols="1,2"]
|===
| Nome | Descrição 


 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["Gabinete de sistema 42U, guia profundo"^]
 a| 
Descreve as FRUs (Unidades Substituíveis em Campo) associadas ao gabinete do sistema 42U e fornece instruções de manutenção e substituição de FRUs.



 a| 
link:install-cisco-nexus-3132qv.html["Instale o switch Cisco Nexus 3132Q-V em um gabinete NetApp"^]
 a| 
Descreve como instalar um switch Cisco Nexus 3132Q-V em um gabinete NetApp de quatro postes.

|===