---
permalink: switch-cisco-3132q-v/reset-switch-3132q-v.html 
sidebar: sidebar 
keywords: 3132Q-V reset switch to factory defaults, 3132Q-V2 switches configuration, efos 
summary: Redefina o switch de cluster Cisco Nexus 3132Q-V para as configurações de fábrica apagando a configuração atual do switch. 
---
= Redefina o switch de cluster Cisco Nexus 3132Q-V para as configurações de fábrica
:allow-uri-read: 


[role="lead"]
Redefina o switch de cluster Cisco Nexus 3132Q-V para os padrões de fábrica apagando a configuração atual do switch e restaurando-o para as configurações originais.

.Sobre esta tarefa
* Você precisa estar conectado ao switch usando o console serial.
* Esta tarefa redefine a configuração da rede de gerenciamento.


.Passos
. Apagar a configuração existente:
+
`write erase`

+
[listing, subs="+quotes"]
----
(cs2)# *write erase*

Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n) [n] *y*
----
. Recarregue o software do switch:
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

This command will reboot the system. (y/n)? [n] *y*
----
+
O sistema é reinicializado e entra no assistente de configuração. Durante a inicialização, se você receber o prompt “Abortar provisionamento automático e continuar com a configuração normal? (sim/não)[n]”, você deve responder *sim* para prosseguir.



.O que vem a seguir
Após reiniciar o interruptor, você pode link:install-overview-cisco-3132qv.html["reconfigurar"] configurá-lo de acordo com suas necessidades.
