---
permalink: switch-cisco-3232c-storage/install-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: 'Instale o arquivo de configuração (RCF) nos switches de storage Cisco Nexus 3232C após a configuração inicial.' 
---
= Instale o RCF nos switches de armazenamento Cisco Nexus 3232C.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Instale o arquivo de configuração (RCF) nos switches de storage Cisco Nexus 3232C após a configuração inicial. O RCF define as atribuições de porta e as configurações de rede necessárias para a operação da rede de storage.

.Antes de começar
Verifique as seguintes instalações e conexões:

* Um backup atual da configuração do switch.
* Um cluster totalmente funcional (sem erros nos logs ou problemas semelhantes).
* O RCF atual.
* Uma conexão de console com o switch, isso é necessário ao instalar o RCF.


.Sobre esta tarefa
O procedimento requer o uso de comandos ONTAP e comandos dos switches Cisco Nexus 3000 Series; comandos ONTAP são usados, a menos que indicado de outra forma.

Conclua o procedimento em link:prepare-install-cisco-nexus-3232c-storage.html["Prepare-se para instalar o NX-OS e o RCF."] e depois siga os passos abaixo.



[[step-1-install-the-rcf-on-the-switches]]
== Passo 1: Instale o RCF nos interruptores

. Faça login no switch s2 usando SSH ou usando um console serial.
. Copie o RCF para a bootflash do switch s2 usando um dos seguintes protocolos de transferência: FTP, TFTP, SFTP ou SCP. Para obter mais informações sobre os comandos da Cisco, consulte o guia apropriado em  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Referência de comandos do Cisco Nexus 3000 Series NX-OS"^].
+
.Mostrar exemplo
[%collapsible]
====
Este exemplo mostra o TFTP sendo usado para copiar um RCF para a bootflash no switch s2:

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Aplique o RCF previamente baixado à memória flash de inicialização.
+
Para obter mais informações sobre os comandos da Cisco, consulte o guia apropriado em  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Referência de comandos do Cisco Nexus 3000 Series NX-OS"^].

+
.Mostrar exemplo
[%collapsible]
====
Este exemplo mostra o arquivo RCF `NX9336C-FX2-RCF-v1.13-1-Storage.txt` sendo instalado no switch s2:

[listing, subs="+quotes"]
----
s2# *copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
====
+
[NOTE]
====
Certifique-se de ler atentamente as seções *Installation notes*, *Important Notes* e *banner* do seu RCF. Você deve ler e seguir essas instruções para verificar a configuração e o funcionamento corretos do switch.

====
. Examine a saída do comando  `show banner motd`. Você deve ler e seguir as instruções em *Notas Importantes* para garantir a configuração e o funcionamento corretos do switch.
. Verifique se o RCF é a versão mais recente correta:
+
`show running-config`

+
Ao verificar a saída para confirmar se você tem o RCF correto, certifique-se de que as seguintes informações estejam corretas:

+
** A bandeira da RCF
** Configurações de nó e porta
** Personalizações
+
O resultado varia de acordo com a configuração do seu site.  Verifique as configurações da porta e consulte as notas de versão para quaisquer alterações específicas do RCF que você instalou.



. Reaplique quaisquer personalizações anteriores à configuração do switch.
. Após verificar se as versões do RCF e as configurações do switch estão corretas, copie o `running-config` arquivo para o `startup-config` arquivo.
+
`s2# copy running-config startup-config [########################################] 100% Copy complete`

. Reinicializar o switch s2:
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Repita as etapas 1 a 8 no switch s1.
. Conecte as portas de storage dos nós e as portas dos shelves de storage de todos os nós no cluster ONTAP aos switches s1 e s2.




[[step-2-verify-the-switch-connections]]
== Passo 2: Verifique as conexões do interruptor

. Verifique se as portas do switch estão *up*.
+
`show interface brief`

. Verifique se as portas de storage do nó e as portas do shelf de storage estão nas VLANs corretas usando os seguintes comandos:
+
`show vlan brief`

+
`show interface trunk`





[[step-3-set-up-your-ontap-cluster]]
== Etapa 3: Configure seu cluster ONTAP

A NetApp recomenda que você utilize o System Manager para configurar novos clusters.

System Manager oferece um fluxo de trabalho simples e fácil para a configuração e instalação de clusters, incluindo a atribuição de um endereço IP de gerenciamento de nó, a inicialização do cluster, a criação de uma camada local, a configuração de protocolos e o provisionamento de armazenamento inicial.

Consulte  https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["Configurar o ONTAP em um novo cluster com o System Manager"] para obter instruções de configuração.

.O que vem a seguir?
Após instalar o RCF, você pode link:configure-ssh-keys.html["verificar a configuração SSH"].
