---
permalink: switch-cisco-3232c-storage/replace-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: É possível substituir um switch de armazenamento Cisco Nexus 3232C defeituoso sem interromper o funcionamento do sistema, executando uma sequência específica de tarefas. 
---
= Substitua um switch de armazenamento Cisco Nexus 3232C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estes passos para substituir um switch de armazenamento Cisco Nexus 3232C defeituoso. Este é um procedimento não disruptivo.



== Requisitos de revisão

A configuração de rede existente deve apresentar as seguintes características:

* A página de switches Ethernet da Cisco contém as versões mais recentes do RCF e do NX-OS para seus switches.
* A conectividade de gerenciamento deve existir em ambos os switches.
+
[NOTE]
====
Certifique-se de que todas as etapas de solução de problemas foram concluídas para confirmar se o seu switch precisa ser substituído.

====


O switch Cisco Nexus 3232C de substituição deve ter as seguintes características:

* A conectividade da rede de gerenciamento deve estar funcional.
* O acesso ao console do interruptor de substituição deve estar configurado corretamente.
* A imagem apropriada do sistema operacional RCF e NX-OS deve ser carregada no switch.
* A personalização inicial do interruptor deve estar concluída.




== Substitua o interruptor

Este procedimento substitui o segundo switch de storage Nexus 3232C s2 pelo novo switch 3232C ns2. Os dois nós são cluster1-01 e cluster1-02.



=== Passo 1: confirme se o switch a ser substituído é o s2

. Se o AutoSupport estiver ativado neste cluster, suprima a criação automática de casos invocando uma mensagem do AutoSupport :
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ representa a duração da janela de manutenção em horas.

+
[NOTE]
====
A mensagem do AutoSupport notifica o suporte técnico sobre essa tarefa de manutenção, de forma que a criação automática de chamados seja suprimida durante o período de manutenção.

====
. Verifique o status de integridade das portas do nó de storage para garantir que há conexão com o switch de storage s1:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
cluster1-01
                   e5a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
cluster1-02
                   e5a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
====
. Verifique se o switch de storage s1 está disponível:
+
`network device-discovery show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
cluster1-01/cdp
            e5a    s1                        Ethernet1/1       NX3232C
            e4a    cluster1-02                     e4a               AFF-A700
            e4e    cluster1-02                     e4e               AFF-A700
cluster1-01/lldp
            e5a    s1                        Ethernet1/1       -
            e4a    cluster1-02                     e4a               -
            e4e    cluster1-02                     e4e               -
cluster1-02/cdp
            e3a    s1                        Ethernet1/2       NX3232C
            e4a    cluster1-01                     e4a               AFF-A700
            e4e    cluster1-01                     e4e               AFF-A700
cluster1-02/lldp
            e3a    s1                        Ethernet1/2       -
            e4a    cluster1-01                     e4a               -
            e4e    cluster1-01                     e4e               -
.
.
----
====
. Execute o `show lldp neighbors` Execute o comando no switch em funcionamento para confirmar que você consegue visualizar ambos os nós e todas as prateleiras:
+
`show lldp neighbors`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
s1# *show lldp neighbors*
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
cluster1-01             Eth1/1          121        S           e5a
cluster1-02             Eth1/2          121        S           e5a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
====




=== Etapa 2: Configurar a cablagem

. [[cinco]]Verifique as portas das prateleiras no sistema de armazenamento:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  s1
3.20   1   -            -
3.20   2   Ethernet1/6  s1
3.20   3   -            -
3.30   0   Ethernet1/7  s1
3.20   1   -            -
3.30   2   Ethernet1/8  s1
3.20   3   -            -
----
====
. Remova todos os cabos conectados ao switch de storage s2.
. Reconecte todos os cabos ao switch de substituição ns2.




=== Etapa 3: verifique todas as configurações do dispositivo no switch ns2

. Verifique o estado de integridade das portas do nó de armazenamento:
+
`storage port show -port-type ENET`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
cluster1-01
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
cluster1-02
                   e5a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30

.
.
----
====
. Verifique se ambos os interruptores estão disponíveis:
+
`network device-discovery show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
cluster1-01/cdp
            e5a    s1                        Ethernet1/1       NX3232C
            e4a    cluster1-02               e4a               AFF-A700
            e4e    cluster1-02               e4e               AFF-A700
            e7b    ns2                       Ethernet1/1       NX3232C
cluster1-01/lldp
            e5a    s1                        Ethernet1/1       -
            e4a    cluster1-02               e4a               -
            e4e    cluster1-02               e4e               -
            e7b    ns2                       Ethernet1/1       -
cluster1-02/cdp
            e5a    s1                        Ethernet1/2       NX3232C
            e4a    cluster1-01               e4a               AFF-A700
            e4e    cluster1-01               e4e               AFF-A700
            e7b    ns2                       Ethernet1/2       NX3232C
cluster1-02/lldp
            e5a    s1                        Ethernet1/2       -
            e4a    cluster1-01               e4a               -
            e4e    cluster1-01               e4e               -
            e7b    ns2                       Ethernet1/2       -
.
.
----
====
. Verifique as portas das prateleiras no sistema de armazenamento:
+
`storage shelf port show -fields remote-device,remote-port`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 s1
3.20  1  Ethernet1/5 ns2
3.20  2  Ethernet1/6 s1
3.20  3  Ethernet1/6 ns2
3.30  0  Ethernet1/7 s1
3.20  1  Ethernet1/7 ns2
3.30  2  Ethernet1/8 s1
3.20  3  Ethernet1/8 ns2
.
.
----
====
. Se você desativou a criação automática de casos, reative-a enviando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que vem a seguir?
Depois de substituir o interruptor, você pode link:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"].
