---
permalink: switch-cisco-3232c-storage/upgrade-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: Você pode usar este procedimento para atualizar sua versão do RCF. 
---
= Atualize seu Arquivo de Configuração de Referência (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você atualiza a versão do RCF quando já possui uma versão do arquivo RCF instalada em seus switches operacionais.

.Antes de começar
Certifique-se de ter o seguinte:

* Um backup atual da configuração do switch.
* Um cluster totalmente funcional (sem erros nos logs ou problemas semelhantes).
* O RCF atual.
* Se você estiver atualizando a versão do seu RCF, precisará de uma configuração de inicialização no RCF que reflita as imagens de inicialização desejadas.
+
Se você precisar alterar a configuração de inicialização para refletir as imagens de inicialização atuais, deverá fazer isso antes de reaplicar o RCF para que a versão correta seja incluída em reinicializações futuras.




CAUTION: Antes de instalar uma nova versão de software do switch e os RCFs, você deve apagar as configurações do switch e realizar a configuração básica.  Você precisa estar conectado ao switch usando o console serial ou ter preservado as informações básicas de configuração antes de apagar as configurações do switch.



== Etapa 1: Prepare-se para a atualização

. Se o AutoSupport estiver ativado neste cluster, suprima a criação automática de casos invocando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
Onde _x_ representa a duração do período de manutenção em horas.

. Altere o nível de privilégio para avançado, digitando *y* quando solicitado a continuar:
+
`set -privilege advanced`

+
A mensagem avançada (*>) é exibida.

. Exiba as portas em cada nó que estão conectadas aos switches:
+
[source, cli]
----
network device-discovery show
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
cluster1-01/cdp
            e5a    s1                       Ethernet1/7     N3K-C3232C
            e3b    s2                       Ethernet1/7     N3K-C3232C
cluster1-02/cdp
            e5a    s1                       Ethernet1/8     N3K-C3232C
            e3b    s2                       Ethernet1/8     N3K-C3232C
.
.
----
====
. Verifique o status administrativo ou operacional de cada porta de storage do nó e de cada porta de storage shelf.
+
.. Verifique se todas as portas de storage do nó estão ativas e com status íntegro:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
cluster1-02
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
.
.
----
====
.. Verifique se todas as portas da prateleira de armazenamento estão ativas e com status íntegro:
+
[source, cli]
----
storage shelf port show
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verifique se os switches estão sendo monitorados.
+
[source, cli]
----
system switch ethernet show
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====






== Etapa 2: atualize o RCF

. Faça login no switch s2 usando SSH ou usando um console serial.
. Desligue as portas conectadas a todas as portas dos nós.
+
[listing, subs="+quotes"]
----
s2> *enable*
s2# *configure*
s2(config)# *interface e1/1-32*
s2(config-if-range)# *shutdown*
s2(config-if-range)# *exit*
s2(config)# *exit*
----
+

CAUTION: Certifique-se de desligar *todas* as portas conectadas para evitar problemas de conexão de rede. Consulte o artigo da Base de Conhecimento. https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["Nó fora do quorum durante a migração do LIF do cluster na atualização do sistema operacional."^] Para obter mais detalhes.

. Caso ainda não o tenha feito, salve uma cópia da configuração atual do switch copiando a saída do seguinte comando para um arquivo de texto:
+
`show running-config`

+
.. Registre quaisquer adições personalizadas entre o atual `running-config` e o arquivo RCF em uso (como uma configuração SNMP para sua organização).
.. Para NX-OS 10.2 e versões posteriores, use o `show diff running-config` comando para comparar com o arquivo RCF salvo na memória flash de inicialização. Caso contrário, utilize uma ferramenta de comparação ou de diferenças de terceiros.


. Salve os detalhes básicos de configuração em `write_erase.cfg` arquivo no bootflash.
+
[NOTE]
====
Certifique-se de configurar o seguinte:

** Nome de usuário e senha
** Endereço IP de gerenciamento
** Gateway padrão
** Nome do interruptor


====
+
`s2# show run | section "switchname" > bootflash:write_erase.cfg`

+
`s2# show run | section "hostname" >> bootflash:write_erase.cfg`

+
`s2# show run | i "username admin password" >> bootflash:write_erase.cfg`

+
`s2# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`s2# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
Consulte o artigo da Base de Conhecimento.link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["Como limpar a configuração de um switch de interconexão Cisco mantendo a conectividade remota"^] Para obter mais detalhes.

. Verifique se o `write_erase.cfg` O arquivo foi preenchido conforme o esperado:
+
`*show file bootflash:write_erase.cfg*`

. Emita o `write erase` comando para apagar a configuração salva atual:
+
`s2# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. Copie a configuração básica salva anteriormente para a configuração de inicialização.
+
`s2# *copy bootflash:write_erase.cfg startup-config*`

. Reinicie o switch:
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Após o endereço IP de gerenciamento estar acessível novamente, faça login no switch via SSH.
+
Você pode precisar atualizar as entradas do arquivo hosts relacionadas às chaves SSH.

. Copie o RCF para a bootflash do switch s2 usando um dos seguintes protocolos de transferência: FTP, TFTP, SFTP ou SCP.
+
Para obter mais informações sobre os comandos da Cisco, consulte o guia apropriado em  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html#CommandReferences["Documentação do Cisco Nexus 3000 Series NX-OS"^].

+
.Mostrar exemplo
[%collapsible]
====
Este exemplo mostra o TFTP sendo usado para copiar um RCF para a bootflash no switch s2:

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. Aplique o RCF previamente baixado à memória flash de inicialização.
+
Para obter mais informações sobre os comandos da Cisco, consulte o guia apropriado em  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Documentação da série Cisco Nexus 3000"^].

+
Este exemplo mostra o arquivo RCF `NX3232C-RCF-v1.13-1-Storage.txt` sendo instalado no switch s2:

+
[listing, subs="+quotes"]
----
s2# *copy NX3232C-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
+
[CAUTION]
====
Certifique-se de ler atentamente as seções *Notas de instalação*, *Notas importantes* e *banner* do seu RCF. Você deve ler e seguir estas instruções para garantir a configuração e operação corretas do switch.

====
. Verifique se o arquivo RCF é a versão mais recente correta:
+
`show running-config`

+
Ao verificar a saída para confirmar se você tem o RCF correto, certifique-se de que as seguintes informações estejam corretas:

+
** A bandeira da RCF
** Configurações de nó e porta
** Personalizações
+
O resultado varia de acordo com a configuração do seu site.  Verifique as configurações da porta e consulte as notas de versão para quaisquer alterações específicas do RCF que você instalou.



. Reaplique quaisquer personalizações anteriores à configuração do switch.
. Após verificar se as versões do RCF, as adições personalizadas e as configurações do switch estão corretas, copie o `running-config` arquivo para o `startup-config` arquivo.
+
Para obter mais informações sobre os comandos da Cisco, consulte o guia apropriado em  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Documentação da série Cisco Nexus 9000"^].

+
`s2# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. Reinicialize o switch s2. Você pode ignorar os alertas do "monitor de integridade do switch do cluster" e os eventos de "portas do cluster inativas" relatados nos nós enquanto o switch reinicializa.
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. Verifique o status administrativo ou operacional de cada porta de storage do nó e de cada porta de storage shelf.
+
.. Verifique se todas as portas de armazenamento estão ativas e com status íntegro:
+
[source, cli]
----
storage port show -port-type ENET
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
cluster1-02
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
.
.
----
====
.. Verifique se todas as portas da prateleira de armazenamento estão ativas e com status íntegro:
+
[source, cli]
----
storage shelf port show
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. Verifique se os switches estão sendo monitorados:
+
[source, cli]
----
system switch ethernet show
----
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch           Type               Address          Model
  ---------------- ------------------ ---------------- ---------------
  s1               storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2               storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====


. Repita as etapas de 1 a 16 no switch s1.




== Etapa 3: verifique a rede de storage

Conclua as seguintes etapas em cada switch de storage para verificar se a rede de storage está funcionando corretamente após a atualização do RCF.

. Verifique se as portas do switch estão *up*.
+
[source, cli]
----
show interface brief
----
. Verifique se as portas de storage do nó esperadas ainda estão conectadas:
+
[source, cli]
----
show cdp neighbors
----
. Verifique se as portas esperadas do compartimento de storage ainda estão conectadas:
+
[source, cli]
----
show lldp neighbors
----
. Verifique se as portas de storage do nó e as portas do shelf de storage estão nas VLANs corretas usando os seguintes comandos:
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----


.O que vem a seguir?
Após atualizar seu RCF, você podelink:configure-ssh-keys.html["verificar a configuração SSH"] .
