---
permalink: switch-netapp-cn1610/install-rcf-file.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: 'Ao instalar um arquivo de configuração de referência (RCF), você deve primeiro migrar as LIFs do cluster do switch cs2.  Após a instalação e validação do RCF, os LIFs podem ser migrados de volta.' 
---
= Instale um arquivo de configuração de referência em um switch CN1610.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para instalar um Arquivo de Configuração de Referência (RCF).

Antes de instalar um RCF, você deve primeiro migrar as LIFs do cluster do switch cs2.  Após a instalação e validação do RCF, os LIFs podem ser migrados de volta.



== Requisitos de revisão

.Antes de começar
Certifique-se de ter o seguinte:

* Um backup atual da configuração do switch.
* Um cluster totalmente funcional (sem erros nos logs e sem placas de interface de rede (NICs) defeituosas ou problemas semelhantes).
* Conexões de porta totalmente funcionais no switch de cluster.
* Todas as portas do cluster estão configuradas.
* Todas as interfaces lógicas do cluster (LIFs) estão configuradas.
* Um caminho de comunicação bem-sucedido: O ONTAP (privilégio: avançado) `cluster ping-cluster -node node1` O comando deve indicar que `larger than PMTU communication` Tem sucesso em todos os caminhos.
* Uma versão compatível do RCF e do ONTAP.
+
Certifique-se de consultar a tabela de compatibilidade de switches no http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Switches NetApp CN1601 e CN1610"^] Página com as versões RCF e ONTAP suportadas.





== Instale o RCF

O procedimento a seguir utiliza a sintaxe clusterizada do Data ONTAP 8.2.  Como resultado, o Vserver do cluster, os nomes LIF e a saída da CLI são diferentes daqueles presentes no Data ONTAP 8.3.

Pode haver dependências entre a sintaxe de comandos nas versões RCF e FASTPATH.


NOTE: Na versão 1.2 do RCF, o suporte para Telnet foi explicitamente desativado devido a preocupações de segurança.  Para evitar problemas de conectividade durante a instalação do RCF 1.2, verifique se o Secure Shell (SSH) está ativado.  O https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["Guia do Administrador do Switch NetApp CN1610"^] Possui mais informações sobre SSH.

.Sobre os exemplos
Os exemplos neste procedimento utilizam a seguinte nomenclatura de interruptor e nó:

* Os dois switches NetApp são o cs1 e o cs2.
* Os dois LIFs do cluster são clus1 e clus2.
* Os servidores virtuais são vs1 e vs2.
* O `cluster::*>` O prompt indica o nome do cluster.
* As portas do cluster em cada nó são denominadas e1a e e2a.
+
https://hwu.netapp.com/["Hardware Universe"^]Possui mais informações sobre as portas de cluster reais que são suportadas em sua plataforma.

* Os links entre switches (ISLs) suportados são as portas 0/13 a 0/16.
* As conexões de nó suportadas são as portas 0/1 a 0/12.
* Uma versão compatível de FASTPATH, RCF e ONTAP.
+
Certifique-se de consultar a tabela de compatibilidade de switches no http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Switches NetApp CN1601 e CN1610"^] Página com as versões suportadas de FASTPATH, RCF e ONTAP .





=== Etapa 1: Migrar cluster

. Salve as informações de configuração atuais do seu switch:
+
`write memory`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra a configuração atual do switch sendo salva na configuração de inicialização.(`startup-config` ) arquivo no switch cs2:

[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. No console de cada nó, migre o clus2 para a porta e1a:
+
`network interface migrate`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
====
. No console de cada nó, verifique se a migração ocorreu:
+
`network interface show -role cluster`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra que o clus2 migrou para a porta e1a em ambos os nós:

[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
====
. Desative a porta e2a em ambos os nós:
+
`network port modify`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra a porta e2a sendo desativada em ambos os nós:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Verifique se a porta e2a está desativada em ambos os nós:
+
`network port show`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
====
. Desligue as portas ISL no cs1, o switch NetApp ativo.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====




=== Etapa 2: Instalar o RCF

. Copie o RCF para o switch.
+

NOTE: Você deve definir o `.scr` A extensão deve fazer parte do nome do arquivo antes de executar o script.  Esta extensão é para o sistema operacional FASTPATH.

+
O switch validará o script automaticamente à medida que ele for baixado para o switch, e a saída será exibida no console.

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
====
. Verifique se o script foi baixado e salvo com o nome de arquivo que você definiu.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
====
. Valide o script.
+

NOTE: O script é validado durante o download para verificar se cada linha é uma linha de comando de switch válida.

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
====
. Aplique o script ao interruptor.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
====
. Verifique se as alterações foram implementadas no switch.
+
[listing]
----
(cs2) # show running-config
----
+
O exemplo exibe o `running-config` arquivo no interruptor.  Você deve comparar o arquivo com o RCF para verificar se os parâmetros que você definiu estão de acordo com o esperado.

. Salve as alterações.
. Defina o `running-config` arquivo para ser o padrão.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
====
. Reinicie o switch e verifique se o `running-config` O arquivo está correto.
+
Após a reinicialização, você deve fazer login e visualizar o `running-config` arquivo e, em seguida, procure a descrição da interface 3/64, que é o rótulo da versão do RCF.

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. Ative as portas ISL no cs1, o switch ativo.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
====
. Verifique se os ISLs estão operacionais:
+
`show port-channel 3/1`

+
O campo Link State deve indicar `Up` .

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Ative a porta de cluster e2a em ambos os nós:
+
`network port modify`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra a porta e2a sendo ativada no nó 1 e no nó 2:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====




=== Etapa 3: Validar a instalação

. Verifique se a porta e2a está ativa em ambos os nós:
+
`network port show -_role cluster_`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
====
. Em ambos os nós, reverta o clus2 associado à porta e2a:
+
`network interface revert`

+
A LIF pode reverter automaticamente, dependendo da sua versão do ONTAP.

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
. Verifique se o LIF agora está em casa.(`true` ) em ambos os nós:
+
`network interface show -_role cluster_`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. Veja o status dos membros do nó:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
====
. Copie o `running-config` arquivo para o `startup-config` salve o arquivo quando estiver satisfeito com as versões do software e as configurações do switch.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. Repita os passos anteriores para instalar o RCF no outro switch, cs1.


.O que vem a seguir?
link:../switch-cshm/config-overview.html["Configure o monitoramento de integridade do switch."]
