---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: Ao instalar o software FASTPATH ​​em seus switches NetApp , você deve iniciar a atualização pelo segundo switch, cs2. 
---
= Instale o software FASTPATH
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao instalar o software FASTPATH ​​em seus switches NetApp , você deve iniciar a atualização pelo segundo switch, _cs2_.



== Requisitos de revisão

.Antes de começar
Certifique-se de ter o seguinte:

* Um backup atual da configuração do switch.
* Um cluster totalmente funcional (sem erros nos logs e sem placas de interface de rede (NICs) defeituosas ou problemas semelhantes).
* Conexões de porta totalmente funcionais no switch de cluster.
* Todas as portas do cluster estão configuradas.
* Todas as interfaces lógicas do cluster (LIFs) devem estar configuradas (não devem ter sido migradas).
* Um caminho de comunicação bem-sucedido: O ONTAP (privilégio: avançado) `cluster ping-cluster -node node1` O comando deve indicar que `larger than PMTU communication` Tem sucesso em todos os caminhos.
* Uma versão compatível do FASTPATH ​​e do ONTAP.
+
Certifique-se de consultar a tabela de compatibilidade de switches no http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Switches NetApp CN1601 e CN1610"^] Página com as versões suportadas do FASTPATH ​​e do ONTAP .





== Instale o FASTPATH

O procedimento a seguir utiliza a sintaxe clusterizada do Data ONTAP 8.2.  Como resultado, o Vserver do cluster, os nomes LIF e a saída da CLI são diferentes daqueles presentes no Data ONTAP 8.3.

Pode haver dependências entre a sintaxe de comandos nas versões RCF e FASTPATH.

.Sobre os exemplos
Os exemplos neste procedimento utilizam a seguinte nomenclatura de interruptor e nó:

* Os dois switches NetApp são o cs1 e o cs2.
* Os dois LIFs do cluster são clus1 e clus2.
* Os servidores virtuais são vs1 e vs2.
* O `cluster::*>` O prompt indica o nome do cluster.
* As portas do cluster em cada nó são denominadas e1a e e2a.
+
https://hwu.netapp.com/["Hardware Universe"^]Possui mais informações sobre as portas de cluster reais que são suportadas em sua plataforma.

* Os links entre switches (ISLs) suportados são as portas 0/13 a 0/16.
* As conexões de nó suportadas são as portas 0/1 a 0/12.




=== Etapa 1: Migrar cluster

. Se o AutoSupport estiver ativado neste cluster, suprima a criação automática de casos invocando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ representa a duração da janela de manutenção em horas.

+

NOTE: A mensagem do AutoSupport notifica o suporte técnico sobre essa tarefa de manutenção, de forma que a criação automática de chamados seja suprimida durante o período de manutenção.

. Faça login no switch como administrador.  Não há senha por padrão.  No `(cs2) #` conforme solicitado, digite o `enable` comando.  Novamente, não há senha por padrão.  Isso lhe dá acesso ao modo EXEC privilegiado, que permite configurar a interface de rede.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. No console de cada nó, migre o clus2 para a porta e1a:
+
`network interface migrate`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. No console de cada nó, verifique se a migração ocorreu:
+
`network interface show`

+
O exemplo a seguir mostra que o clus2 migrou para a porta e1a em ambos os nós:

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== Etapa 2: Instale o software FASTPATH

. Desative a porta e2a do cluster em ambos os nós:
+
`network port modify`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra a porta e2a sendo desativada em ambos os nós:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Verifique se a porta e2a está desativada em ambos os nós:
+
`network port show`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. Desative as portas Inter-Switch Link (ISL) no cs1, o switch NetApp ativo:
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. Faça backup da imagem ativa atual no CS2.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. Faça o download do arquivo de imagem para o switch.
+
Copiar o arquivo de imagem para a imagem ativa significa que, ao reiniciar, essa imagem estabelece a versão do FASTPATH em execução.  A imagem anterior permanece disponível como backup.

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Verifique a versão em execução do software FASTPATH.
+
`show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. Visualize as imagens de inicialização para a configuração ativa e de backup.
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. Reinicie o switch.
+
`reload`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== Etapa 3: Validar a instalação

. Faça login novamente e verifique a nova versão do software FASTPATH.
+
`show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. Ative as portas ISL no cs1, o switch ativo.
+
`configure`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. Verifique se os ISLs estão operacionais:
+
`show port-channel 3/1`

+
O campo Link State deve indicar `Up` .

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Copie o `running-config` arquivo para o `startup-config` salve o arquivo quando estiver satisfeito com as versões do software e as configurações do switch.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. Ative a segunda porta do cluster, e2a, em cada nó:
+
`network port modify`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. Reverter clus2 associado à porta e2a:
+
`network interface revert`

+
A LIF pode reverter automaticamente, dependendo da sua versão do software ONTAP .

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. Verifique se o LIF agora está em casa.(`true` ) em ambos os nós:
+
`network interface show -_role cluster_`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. Veja o estado dos nós:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. Repita os passos anteriores para instalar o software FASTPATH no outro switch, cs1.
. Se você desativou a criação automática de casos, reative-a enviando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`


