---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: Quando você instala o software FASTPATH em seus switches NetApp, você deve começar a atualização com o segundo switch, CS2. 
---
= Instale o software FASTPATH
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você instala o software FASTPATH em seus switches NetApp, você deve começar a atualização com o segundo switch, _CS2_.



== Rever os requisitos

.O que você vai precisar
* Um backup atual da configuração do switch.
* Um cluster totalmente funcional (sem erros nos logs e sem placas de interface de rede de cluster (NICs) defeituosas ou problemas semelhantes).
* Conexões de porta totalmente funcionais no switch de cluster.
* Todas as portas do cluster configuradas.
* Todas as interfaces lógicas de cluster (LIFs) configuradas (não devem ter sido migradas).
* Um caminho de comunicação bem-sucedido: O comando ONTAP (privilégio: Avançado) `cluster ping-cluster -node node1` deve indicar que `larger than PMTU communication` é bem-sucedido em todos os caminhos.
* Uma versão suportada do FASTPATH e ONTAP.
+
Certifique-se de consultar a tabela de compatibilidade de switch na http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Switches NetApp CN1601 e CN1610"^] página para as versões FASTPATH e ONTAP suportadas.





== Instale o FASTPATH

O procedimento a seguir usa a sintaxe Clustered Data ONTAP 8.2. Como resultado, o SVM de cluster, os nomes de LIF e a saída de CLI são diferentes dos do Data ONTAP 8.3.

Pode haver dependências de comando entre sintaxe de comando nas versões RCF e FASTPATH.

.Sobre os exemplos
Os exemplos deste procedimento utilizam a seguinte nomenclatura de switch e nó:

* Os dois switches NetApp são CS1 e CS2.
* Os dois LIFs de cluster são clus1 e clus2.
* Os VServers são VS1 e VS2.
* O `cluster::*>` prompt indica o nome do cluster.
* As portas de cluster em cada nó são denominadas e1a e E2A.
+
https://hwu.netapp.com/["Hardware Universe"^] tem mais informações sobre as portas de cluster reais que são suportadas na sua plataforma.

* Os ISLs (Inter-Switch Links) suportados são as portas 0/13 a 0/16.
* As conexões de nós suportadas são as portas 0/1 a 0/12.




=== Etapa 1: Migrar cluster

. Se o AutoSupport estiver ativado neste cluster, suprimir a criação automática de casos invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ é a duração da janela de manutenção em horas.

+

NOTE: A mensagem AutoSupport notifica o suporte técnico desta tarefa de manutenção para que a criação automática de casos seja suprimida durante a janela de manutenção.

. Faça login no switch como admin. Por padrão, não há senha. No `(cs2) #` prompt, digite o `enable` comando. Novamente, não há senha por padrão. Isso lhe dá acesso ao modo EXEC privilegiado, que permite configurar a interface de rede.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. No console de cada nó, migre clus2 para a porta e1a:
+
`network interface migrate`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. No console de cada nó, verifique se a migração ocorreu:
+
`network interface show`

+
O exemplo a seguir mostra que o clus2 migrou para a porta e1a em ambos os nós:

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== Passo 2: Instale o software FASTPATH

. Encerre a porta E2A do cluster em ambos os nós:
+
`network port modify`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra a porta E2A sendo fechada em ambos os nós:

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. Verifique se a porta E2A está desligada em ambos os nós:
+
`network port show`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. Desligue as portas ISL (Inter-Switch Link) no CS1, o interrutor NetApp ativo:
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. Faça uma cópia de segurança da imagem ativa atual no CS2.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. Transfira o ficheiro de imagem para o interrutor.
+
Copiar o arquivo de imagem para a imagem ativa significa que, quando você reiniciar, essa imagem estabelece a versão FASTPATH em execução. A imagem anterior permanece disponível como cópia de segurança.

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. Verifique a versão em execução do software FASTPATH.
+
`show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. Visualize as imagens de arranque para a configuração ativa e de cópia de segurança.
+
`show bootvar`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. Reinicie o switch.
+
`reload`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== Passo 3: Valide a instalação

. Faça login novamente e verifique a nova versão do software FASTPATH.
+
`show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. Abra as portas ISL no CS1, o interrutor ativo.
+
`configure`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. Verifique se os ISLs estão operacionais:
+
`show port-channel 3/1`

+
O campo Estado da ligação deve `Up` indicar .

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. Copie o `running-config` arquivo para o `startup-config` arquivo quando estiver satisfeito com as versões de software e as configurações de switch.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. Ative a segunda porta do cluster, E2A, em cada nó:
+
`network port modify`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. Reverter clus2 associado à porta E2A:
+
`network interface revert`

+
O LIF pode reverter automaticamente, dependendo da sua versão do software ONTAP.

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. Verifique se o LIF está agora em (`true`casa ) em ambos os nós:
+
`network interface show -_role cluster_`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. Exibir o status dos nós:
+
`cluster show`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. Repita as etapas anteriores para instalar o software FASTPATH no outro switch, CS1.
. Se você suprimiu a criação automática de casos, reative-a invocando uma mensagem AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


