---
permalink: switch-netapp-cn1610/migrate-overview.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, netapp cn1610 
summary: Analise as opções de migração para passar de um cluster sem switch de dois nós para um cluster com switches usando os switches de cluster NetApp CN1610. 
---
= Analise as opções de migração para os switches de cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Analise as opções de migração para passar de um cluster sem switch de dois nós para um cluster com switch usando os switches de cluster NetApp CN1610. O procedimento depende de você ter duas portas de rede de cluster dedicadas ou uma única porta de cluster em cada controlador.

A maioria dos sistemas requer duas portas de rede dedicadas para cluster em cada controlador.

Os nós FAS22xx permitem uma única porta de cluster em cada controlador.

Existem duas opções de migração disponíveis:

* link:migrate-switched-netapp-cn1610.html["Migre de um cluster sem switch para um ambiente de cluster NetApp CN1610 com switches"]
* link:migrate-fas22xx-systems.html["Migrar de um cluster sem switch (sistemas FAS22xx com uma única conexão de rede de cluster)"]

