---
permalink: switch-netapp-cn1610/migrate-overview.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, netapp cn1610 
summary: Se você possui um cluster sem switch de dois nós, pode migrar, sem interrupções, para um cluster com switch de dois nós que inclua os switches de rede de cluster CN1610 da NetApp. 
---
= Opções de migração para um cluster comutado de dois nós com NetApp CN1610 switches de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você possui um cluster sem switch de dois nós, pode migrar, sem interrupções, para um cluster com switch de dois nós que inclua os switches de rede de cluster CN1610 da NetApp. O procedimento que você deve usar depende de você ter duas portas de rede de cluster dedicadas em cada controlador ou uma única porta de cluster em cada controlador.

A maioria dos sistemas requer duas portas de rede dedicadas para cluster em cada controlador.

Os nós FAS22xx permitem uma única porta de cluster em cada controlador.

Existem duas opções de migração disponíveis:

* link:migrate-switched-netapp-cn1610.html["Migre de um cluster sem switch para um ambiente de cluster NetApp CN1610 com switches"]
* link:migrate-fas22xx-systems.html["Migrar de um cluster sem switch (sistemas FAS22xx com uma única conexão de rede de cluster)"]

