---
permalink: switch-netapp-cn1610/prepare-install-fastpath-rcfs.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs, netapp cluster switch 
summary: 'Você deve instalar o software FASTPATH e os arquivos de configuração de referência (RCFs) em um switch de cluster NetApp CN1610.' 
---
= Prepare-se para instalar o software FASTPATH e os RCFs em um switch de cluster NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve instalar o software FASTPATH e os arquivos de configuração de referência (RCFs) em um switch de cluster NetApp CN1610.

.Antes de começar
* O cluster deve ser um cluster totalmente funcional.
* Não deve haver placas de interface de rede de cluster (NICs) defeituosas e todas as portas conetadas no switch de cluster devem estar funcionais.
* Todas as portas do cluster devem estar ativas.
* Todas as interfaces lógicas de cluster (LIFs) devem estar ativas e não devem ter sido migradas.
* O comando ONTAP (privilégio: Avançado) `cluster ping-cluster -node node1` deve indicar que `larger than PMTU communication` é bem-sucedido em todos os caminhos.
* Você deve consultar a tabela de compatibilidade de switch na http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["Switches NetApp CN1601 e CN1610"^] página para as versões FASTPATH, RCF e ONTAP suportadas.
+
Pode haver dependências de comando entre sintaxe de comando nas versões RCF e FASTPATH.




NOTE: No RCF versão 1,2, o suporte para Telnet foi explicitamente desativado devido a problemas de segurança. Para evitar problemas de conetividade durante a instalação do RCF 1,2, você deve verificar se o Secure Shell (SSH) está ativado. O https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["Guia do administrador do switch NetApp CN1610"^] tem mais informações sobre SSH.

.Sobre esta tarefa
Os exemplos deste procedimento utilizam a seguinte nomenclatura de switch e nó:

* Os procedimentos neste documento usam a sintaxe Clustered Data ONTAP 8.2. Como resultado, o SVM de cluster, os nomes de LIF e a saída de CLI serão diferentes dos do Data ONTAP 8.3.
* Os dois switches NetApp são CS1 e CS2.
* Os dois LIFs de cluster são clus1 e clus2.
* Os VServers são VS1 e VS2.
* O `cluster::*>` prompt indica o nome do cluster.
* As portas de cluster em cada nó são denominadas e1a e E2A.
+
O https://hwu.netapp.com/["Hardware Universe"^] tem mais informações sobre as portas de cluster reais que são suportadas na sua plataforma.

* Os ISLs (links interswitches) suportados para o switch de cluster NetApp são as portas 0/13 a 0/16.
* As conexões de nós compatíveis com o switch de cluster NetApp são as portas 0/1 a 0/12.


Este procedimento tem duas partes:

* link:task-install-fastpath-software.html["Instale o software FASTPATH"] Descreve como instalar o software FASTPATH.
* link:task-install-an-rcf-on-a-cn1610-switch.html["Instale um RCF num interrutor CN1610"] Descreve como instalar RCFs.

