---
permalink: switch-netapp-cn1610/required-documentation-cn1610.html 
sidebar: sidebar 
keywords: cn1610, switch, netapp 
summary: Para instalação e manutenção do switch NetApp CN1610, certifique-se de revisar toda a documentação recomendada. 
---
= Requisitos de documentação para switches NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para a instalação do switch NetApp CN1610, certifique-se de revisar toda a documentação recomendada.

[cols="1,2"]
|===
| Título do documento | Descrição 


 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117853["Guia de Instalação 1G"^]
 a| 
Uma visão geral dos recursos de hardware e software do switch CN1601 e do processo de instalação.



 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117824["Guia de Instalação 10G"^]
 a| 
Uma visão geral dos recursos de hardware e software do switch CN1610 e uma descrição dos recursos para instalar o switch e acessar a CLI.



 a| 
link:https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["Guia de instalação e configuração dos switches CN1601 e CN1610"^]
 a| 
Detalha como configurar o hardware e o software do switch para o seu ambiente de cluster.



 a| 
Guia do Administrador do Switch CN1601
 a| 
Fornece exemplos de como usar o switch CN1601 em uma rede típica.

* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117844["Guia do Administrador"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2811865["Guia do Administrador, Versão 1.1.x.x"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117874["Guia do Administrador, Versão 1.2.x.x"^]




 a| 
Referência de comandos da interface de linha de comando do switch de rede CN1610
 a| 
Fornece informações detalhadas sobre os comandos da interface de linha de comando (CLI) que você usa para configurar o software CN1601.

* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117834["Referência de comandos"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2811863["Referência de comandos, versão 1.1.x.x"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1117863["Guia de Comandos, Versão 1.2.x.x"^]


|===