---
permalink: switch-netapp-cn1610/switch-overview-cn1610.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs 
summary: Antes de configurar os switches NetApp CN1610, revise a visão geral do procedimento. 
---
= Visão geral da instalação e configuração dos switches NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O CN1610 é um switch de camada 2 gerenciável de alta largura de banda que fornece 16 portas Small Form-Factor Pluggable Plus (SFP+) de 10 Gigabits.

O switch inclui fontes de alimentação redundantes e bandejas de ventoinhas que suportam troca a quente para alta disponibilidade. Este switch de 1U pode ser instalado em um gabinete de sistema padrão de 19 polegadas e 42U da NetApp ou em um gabinete de terceiros.

O switch suporta gerenciamento local através da porta de console ou gerenciamento remoto usando Telnet ou SSH por meio de uma conexão de rede. O CN1610 inclui uma porta de gerenciamento dedicada de 1 Gigabit Ethernet RJ45 para gerenciamento fora de banda do switch. Você pode gerenciar o switch inserindo comandos na interface de linha de comando (CLI) ou usando um sistema de gerenciamento de rede (NMS) baseado em SNMP.
