---
permalink: switch-netapp-cn1610/switch-overview-cn1610.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs 
summary: Saiba mais sobre o switch de cluster NetApp CN1610 e seu papel na rede de cluster ONTAP. 
---
= Saiba mais sobre os switches de cluster NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O NetApp CN1610 é um switch de cluster de Camada 2 gerenciável de alta largura de banda que oferece 16 portas SFP+ de 10 Gigabits. Consulte esta página para saber mais sobre os recursos do switch e seu papel na rede de cluster ONTAP.

O switch inclui fontes de alimentação redundantes e bandejas de ventoinhas que suportam troca a quente para alta disponibilidade. Este switch de 1U pode ser instalado em um gabinete de sistema padrão de 19 polegadas e 42U da NetApp ou em um gabinete de terceiros.

O switch suporta gerenciamento local através da porta de console ou gerenciamento remoto usando Telnet ou SSH por meio de uma conexão de rede. O CN1610 inclui uma porta de gerenciamento dedicada de 1 Gigabit Ethernet RJ45 para gerenciamento fora de banda do switch. Você pode gerenciar o switch inserindo comandos na interface de linha de comando (CLI) ou usando um sistema de gerenciamento de rede (NMS) baseado em SNMP.
