---
permalink: switch-netapp-cn1610/switch-overview-cn1610.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs 
summary: Antes de configurar os interrutores NetApp CN1610, reveja a descrição geral do procedimento. 
---
= Visão geral da instalação e configuração dos switches NetApp CN1610
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O CN1610 é um switch de camada 2 gerenciado de alta largura de banda que fornece portas SFP (Small Form-factor Pluggable Plus) de 16 10 Gigabit.

O switch inclui fontes de alimentação redundantes e bandejas de ventiladores que suportam hot swap para alta disponibilidade. Este switch 1U pode ser instalado em um gabinete de sistema NetApp 42U padrão de 19 polegadas ou em um gabinete de terceiros.

O switch oferece suporte ao gerenciamento local por meio da porta do console ou do gerenciamento remoto usando Telnet ou SSH por meio de uma conexão de rede. O CN1610 inclui uma porta de gerenciamento dedicada Ethernet RJ45 de 1 Gigabit para gerenciamento de switch fora da banda. Você pode gerenciar o switch inserindo comandos na interface de linha de comando (CLI) ou usando um sistema de gerenciamento de rede baseado em SNMP (NMS).
