---
permalink: get-started/learn-switch-concept.html 
sidebar: sidebar 
keywords:  
summary: Aprenda sobre clusters, armazenamento e switches compartilhados. 
---
= Saiba mais sobre os switches do seu sistema ONTAP
:allow-uri-read: 


[role="lead"]
A NetApp oferece sistemas AFX, cluster, armazenamento e switches compartilhados que fornecem comunicações internas com a capacidade de mover dados e interfaces de rede pelo cluster sem interrupções.

Os switches de "front-end" fornecem conectividade ao armazenamento do host, enquanto os switches de cluster de "back-end" fornecem conexões entre dois ou mais controladores NetApp .


NOTE: Somente switches de back-end validados pela NetApp(encomendados à NetApp) são suportados.


CAUTION: Se você estiver atualizando seus switches, a NetApp recomenda que você conclua primeiro qualquer atualização de software do ONTAP e, em seguida, execute a atualização de software dos seus switches.



[[afx-systems-switches]]
== Interruptores de sistemas AFX

Os switches da AFX systems permitem criar switches de rede rápidos, eficientes em termos de energia e que economizam espaço. Seu tamanho reduzido e alta densidade de portas os tornam ideais para lidar com grandes redes. As portas suportam diferentes velocidades e podem ser divididas em várias conexões. Os switches da AFX systems suportados pela NetApp incluem:

* Cisco Nexus 9808
* Cisco Nexus 9332D-GX2B
* Cisco Nexus 9364D-GX2A




[[cluster-switches]]
== Comutadores de cluster

Os switches de cluster permitem que você crie clusters ONTAP com mais de dois nós. Os switches de cluster suportados pela NetApp incluem:

* Broadcom BES-53248
* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




[[storage-switches]]
== Interruptores de armazenamento

Os switches de armazenamento permitem rotear dados entre servidores e arrays de armazenamento em uma rede de área de armazenamento (SAN).  Os switches de armazenamento compatíveis com a NetApp incluem:

* Cisco Nexus 9336C-FX2
* NVIDIA SN2100




[[shared-switches]]
== Switches compartilhados

Os switches compartilhados permitem combinar a funcionalidade de cluster e armazenamento em uma configuração de switch compartilhado, suportando o uso de RCFs (Funções de Configuração de Cluster) compartilhadas para cluster e armazenamento.  O switch compartilhado compatível com a NetApp é:

* Cisco Nexus 9336C-FX2




[[end-of-availability-switches]]
== Interruptores de fim de disponibilidade

Para obter uma lista de switches que não estão mais disponíveis para compra, mas ainda são suportados, consulte link:../eoa/index.html["Interruptores de fim de disponibilidade"].
