---
permalink: switch-cisco-92300/components-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Se você deseja criar clusters ONTAP com mais de dois nós, precisará de dois switches de rede de cluster compatíveis.  Você pode usar interruptores de gerenciamento adicionais, que são opcionais. 
---
= Componentes e números de peça para switches Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para a instalação e manutenção do switch Cisco Nexus 92300YC, certifique-se de revisar todos os componentes e números de peça do switch. Consulte a link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para obter detalhes. Consulte link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["Que informações adicionais preciso para instalar meu equipamento que não está no HWU?"^] para obter mais informações sobre os requisitos de instalação do switch.

A tabela a seguir lista o número de peça e a descrição do switch 92300YC, dos ventiladores e das fontes de alimentação:

[cols="1,2"]
|===
| Número da peça | Descrição 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = exaustão do lado da porta)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = entrada de ar pelo lado das portas)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventilador, fluxo de ar de entrada pelo lado da porta Cisco N9K



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventilador, fluxo de ar de exaustão do lado da porta Cisco N9K



 a| 
X-NXA-PAC-650W-B
 a| 
Fonte de alimentação Cisco 650W - entrada pelo lado da porta



 a| 
X-NXA-PAC-650W-F
 a| 
Fonte de alimentação Cisco 650W - exaustão lateral da porta

|===
Detalhes do fluxo de ar do switch Cisco Nexus 92300YC:

* Fluxo de ar de exaustão do lado da porta (ar padrão) — o ar frio entra no chassi através dos módulos de ventoinha e fonte de alimentação no corredor frio e é expelido pela extremidade da porta do chassi no corredor quente. Fluxo de ar de exaustão do lado da porta com coloração azul.
* Fluxo de ar de entrada pelo lado da porta (ar reverso) — o ar frio entra no chassi pela extremidade da porta no corredor frio e é expelido pelos módulos de ventoinha e fonte de alimentação no corredor quente. Fluxo de ar de entrada pelo lado da porta com coloração bordô.


.O que vem a seguir
Depois de confirmar os componentes e os números de peça, você pode revisar o link:required-documentation-92300.html["documentação necessária"].
