---
permalink: switch-cisco-92300/components-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: Se você deseja criar clusters ONTAP com mais de dois nós, precisará de dois switches de rede de cluster compatíveis.  Você pode usar interruptores de gerenciamento adicionais, que são opcionais. 
---
= Componentes e números de peça para switches Cisco Nexus 92300YC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para a instalação e manutenção do switch Cisco Nexus 92300YC, certifique-se de revisar todos os componentes do switch e seus respectivos números de peça. Veja o https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] para mais detalhes.

A tabela a seguir lista o número da peça e a descrição do switch 92300YC, dos ventiladores e das fontes de alimentação:

[cols="1,2"]
|===
| Número da peça | Descrição 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX (PTSX = Exaustão do Lado da Porta)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN (PSIN = Entrada do Lado da Porta)



 a| 
X-NXA-FAN-35CFM-B
 a| 
Ventilador, entrada de ar lateral da porta Cisco N9K



 a| 
X-NXA-FAN-35CFM-F
 a| 
Ventilador, fluxo de ar de exaustão lateral da porta Cisco N9K



 a| 
X-NXA-PAC-650W-B
 a| 
Fonte de alimentação Cisco 650W - entrada lateral



 a| 
X-NXA-PAC-650W-F
 a| 
Fonte de alimentação Cisco 650W - exaustão lateral.

|===
Detalhes do fluxo de ar do switch Cisco Nexus 92300YC:

* Fluxo de ar de exaustão pelo lado esquerdo (ar padrão) -- O ar frio entra no chassi através dos módulos de ventoinha e fonte de alimentação no corredor frio e é expelido pela extremidade esquerda do chassi no corredor quente.  Fluxo de ar de exaustão do lado de bombordo com coloração azul.
* Fluxo de ar de entrada pelo lado esquerdo (ar reverso) -- O ar frio entra no chassi pela extremidade esquerda no corredor frio e é expelido através do ventilador e dos módulos de alimentação no corredor quente.  Fluxo de ar de admissão pelo lado esquerdo com coloração bordô.


.O que vem a seguir
Após confirmar os componentes e os números de peça, você pode revisar o link:required-documentation-92300.html["documentação necessária"].
