---
permalink: switch-cisco-92300/install-nxos-software.html 
sidebar: sidebar 
keywords: install nx-os,nx-os configure 
summary: Você pode usar este procedimento para instalar o software NX-os no switch Nexus 92300YC. 
---
= Instale o software NX-os
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para instalar o software NX-os no switch Nexus 92300YC.

NX-os é um sistema operacional de rede para a série Nexus de switches Ethernet e MDS série de switches de rede de área de armazenamento Fibre Channel (FC) fornecidos pela Cisco Systems.



== Rever os requisitos

.Portas e conexões de nós compatíveis
* Os ISLs (Inter-Switch Links) suportados para os switches Nexus 92300YC são as portas 1/65 e 1/66.
* As conexões de nós suportadas pelos switches Nexus 92300YC são as portas 1/1 a 1/66.


.Antes de começar
Certifique-se de que tem o seguinte:

* Software NetApp Cisco NX-os aplicável para os seus comutadores a partir do site de suporte da NetApp, disponível em http://mysupport.netapp.com/["mysupport.NetApp.com"]
* Um cluster totalmente funcional (sem erros nos logs ou problemas semelhantes).
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Página do switch Ethernet Cisco"^]. Consulte a tabela de compatibilidade do switch para ver as versões suportadas do ONTAP e NX-os.




== Instale o software

Os exemplos neste procedimento usam dois nós, mas você pode ter até 24 nós em um cluster.

.Sobre os exemplos
Os exemplos deste procedimento utilizam a seguinte nomenclatura de switch e nó:

* Os nomes dos switches Nexus 92300YC são `cs1` e `cs2`.
* O exemplo usado neste procedimento inicia a atualização no segundo switch, _*CS2*._
* Os nomes de LIF do cluster são `node1_clus1` e `node1_clus2` para node1 `node2_clus1` e e `node2_clus2` node2.
* O nome do IPspace é `Cluster`.
* O `cluster1::*>` prompt indica o nome do cluster.
* As portas de cluster em cada nó são nomeadas e `e0a` `e0b`.
+
Consulte a link:https://hwu.netapp.com/Home/Index["_Hardware Universe_"] para obter as portas de cluster reais suportadas na sua plataforma.



.Passos
. Conete o switch de cluster à rede de gerenciamento.
. Use o `ping` comando para verificar a conetividade com o servidor que hospeda o software NX-os e o RCF.
+
.Mostrar exemplo
[%collapsible]
====
Este exemplo verifica se o switch pode alcançar o servidor no endereço IP 172.19.2.1:

[listing, subs="+quotes"]
----
cs2# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. Copie o software NX-os e as imagens EPLD para o switch Nexus 92300YC.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.9.2.2.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.2.2.bin  /bootflash/nxos.9.2.2.bin
/code/nxos.9.2.2.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.


cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.9.2.2.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.2.2.img  /bootflash/n9000-epld.9.2.2.img
/code/n9000-epld.9.2.2.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. Verifique a versão em execução do software NX-os:
+
`show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2018, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 05.31
  NXOS: version 9.2(1)
  BIOS compile time:  05/17/2018
  NXOS image file is: bootflash:///nxos.9.2.1.bin
  NXOS compile time:  7/17/2018 16:00:00 [07/18/2018 00:21:19]


Hardware
  cisco Nexus9000 C92300YC Chassis
  Intel(R) Xeon(R) CPU D-1526 @ 1.80GHz with 16337884 kB of memory.
  Processor Board ID FDO220329V5

  Device name: cs2
  bootflash:  115805356 kB
Kernel uptime is 0 day(s), 4 hour(s), 23 minute(s), 11 second(s)

Last reset at 271444 usecs after Wed Apr 10 00:25:32 2019
  Reason: Reset Requested by CLI command reload
  System version: 9.2(1)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

cs2#
----
====
. Instale a imagem NX-os.
+
Instalar o arquivo de imagem faz com que ele seja carregado toda vez que o switch é reinicializado.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *install all nxos bootflash:nxos.9.2.2.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.2.2.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.2.2.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.2.2.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS



Compatibility check is done:
Module  bootable       Impact     Install-type  Reason
------  --------  --------------- ------------  ------
  1       yes      disruptive         reset     default upgrade is not hitless



Images will be upgraded according to following table:

Module   Image         Running-Version(pri:alt            New-Version         Upg-Required
------  --------  --------------------------------------  ------------------  ------------
  1       nxos                                  9.2(1)              9.2(2)         yes
  1       bios    v05.31(05/17/2018):v05.28(01/18/2018)   v05.33(09/08/2018)       yes


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] *y*


Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS
2019 Apr 10 04:59:35 cs2 %$ VDC-1 %$ %VMAN-2-ACTIVATION_STATE: Successfully deactivated virtual service 'guestshell+'

Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. Verifique a nova versão do software NX-os depois que o switch reiniciar:
+
`show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *show version*

Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2018, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 05.33
  NXOS: version 9.2(2)
  BIOS compile time:  09/08/2018
  NXOS image file is: bootflash:///nxos.9.2.2.bin
  NXOS compile time:  11/4/2018 21:00:00 [11/05/2018 06:11:06]


Hardware
  cisco Nexus9000 C92300YC Chassis
  Intel(R) Xeon(R) CPU D-1526 @ 1.80GHz with 16337884 kB of memory.
  Processor Board ID FDO220329V5

  Device name: cs2
  bootflash:  115805356 kB
  Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 52 second(s)

Last reset at 182004 usecs after Wed Apr 10 04:59:48 2019
  Reason: Reset due to upgrade
  System version: 9.2(1)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
----
====
. Atualize a imagem EPLD e reinicie o switch.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cs2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI FPGA                          0x7
IO FPGA                          0x17
MI FPGA2                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2

cs2# *install epld bootflash:n9000-epld.9.2.2.img module 1*
Compatibility check:
Module        Type         Upgradable        Impact   Reason
------  -----------------  ----------    ----------   ------
     1            SUP           Yes       disruptive  Module Upgradable

Retrieving EPLD versions.... Please wait.
Images will be upgraded according to following table:
Module  Type   EPLD              Running-Version   New-Version  Upg-Required
------  ----  -------------      ---------------   -----------  ------------
     1   SUP  MI FPGA                   0x07        0x07             No
     1   SUP  IO FPGA                   0x17        0x19            Yes
     1   SUP  MI FPGA2                  0x02        0x02             No
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] *y*

Proceeding to upgrade Modules.

Starting Module 1 EPLD Upgrade

Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sectors)
Module 1 EPLD upgrade is successful.
Module        Type  Upgrade-Result
------  ------------------  --------------
     1         SUP         Success


EPLDs upgraded.

Module 1 EPLD upgrade is successful.
----
====
. Após a reinicialização do switch, faça login novamente e verifique se a nova versão do EPLD foi carregada com sucesso.
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
cs2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI FPGA                          0x7
IO FPGA                          0x19
MI FPGA2                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2
GEM FPGA                         0x2
----
====


.O que se segue?
link:install-the-rcf-file.html["Instale o ficheiro de configuração de referência"]
