---
permalink: switch-cshm/config-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: 'O recurso de coleta de logs do monitor de integridade do switch Ethernet (CSHM) é usado para coletar logs de switches de cluster ou de rede de armazenamento no ONTAP.' 
---
= Configurar coleta de logs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O monitor de integridade do switch Ethernet (CSHM) é responsável por garantir o funcionamento adequado dos switches de rede do cluster e do armazenamento, além de coletar logs dos switches para fins de depuração.  Este procedimento orienta você no processo de configuração da coleta, solicitação de registros detalhados de *Suporte* e ativação da coleta horária de dados *Periódicos* coletados pelo AutoSupport.

*NOTA:* Se você ativar o modo FIPS, deverá concluir o seguinte:

[NOTE]
====
. Recrie as chaves SSH no switch seguindo as instruções do fornecedor.
. Regenerar chaves SSH no ONTAP usando `debug system regenerate-systemshell-key-pair`
. Execute novamente a rotina de configuração de coleta de logs usando o `system switch ethernet log setup-password` comando


====


== Antes de começar

* O usuário deve ter acesso ao interruptor. `show` comandos.  Caso essas opções não estejam disponíveis, crie um novo usuário e conceda as permissões necessárias a ele.
* O monitoramento de integridade do switch deve estar ativado.  Verifique isso certificando-se de que `Is Monitored:` O campo é definido como *verdadeiro* na saída do `system switch ethernet show` comando.
* Para coleta de logs com switches Broadcom e Cisco :
+
** O usuário local deve ter privilégios de administrador de rede.
** Um novo usuário deve ser criado no switch para cada configuração de cluster com a coleta de logs habilitada.  Esses switches não suportam múltiplas chaves SSH para o mesmo usuário.  Qualquer configuração adicional de coleta de logs realizada sobrescreverá quaisquer chaves SSH preexistentes do usuário.


* Para suporte à coleta de logs com switches NVIDIA , o _usuário_ responsável pela coleta de logs deve ter permissão para executar o comando. `cl-support` comando sem precisar fornecer uma senha.  Para permitir esse uso, execute o comando:
+
`echo '_<user>_ ALL = NOPASSWD: /usr/cumulus/bin/cl-support' | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/cumulus`





== Passos

[role="tabbed-block"]
====
.ONTAP 9.15.1 e posterior
--
. Para configurar a coleta de logs, execute o seguinte comando para cada switch.  Você será solicitado a inserir o nome do switch, o nome de usuário e a senha para a coleta de logs.
+
*NOTA:* Se responder *s* à solicitação de especificação do usuário, certifique-se de que o usuário tenha as permissões necessárias, conforme descrito em<<Antes de começar>> .

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Para CL 5.11.1, crie o usuário *cumulus* e responda *y* à seguinte mensagem: Deseja especificar um usuário diferente de admin para a coleta de logs?  {s|n}: *s*

. [[passo 2]]Ativar a coleta periódica de logs:
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -periodic-enabled true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs1*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log modify -device cs2 -periodic-enabled true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

*cs2*: Periodic log collection has been scheduled to run every hour.

cluster1::*> *system switch ethernet log show*
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       true        scheduled   never-run
cs2                                       true        scheduled   never-run
2 entries were displayed.
----
. Solicitar suporte para coleta de registros:
+
[source, cli]
----
system switch ethernet log collect-support-log -device <switch-name>
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log collect-support-log -device cs1*

*cs1*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log collect-support-log -device cs2*

*cs2*: Waiting for the next Ethernet switch polling cycle to begin support collection.

cluster1::*> *system switch ethernet log show
                                          Periodic    Periodic    Support
Switch                                    Log Enabled Log State   Log State

cs1                                       false       halted      initiated
cs2                                       true        scheduled   initiated
2 entries were displayed.
----
. Para visualizar todos os detalhes da coleta de logs, incluindo a ativação, a mensagem de status, o carimbo de data/hora anterior e o nome do arquivo da coleta periódica, bem como o status da solicitação, a mensagem de status e o carimbo de data/hora anterior e o nome do arquivo da coleta de suporte, utilize o seguinte comando:
+
[source, cli]
----
system switch ethernet log show -instance
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show -instance*

                    Switch Name: cs1
           Periodic Log Enabled: true
            Periodic Log Status: Periodic log collection has been scheduled to run every hour.
    Last Periodic Log Timestamp: 3/11/2024 11:02:59
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:14:20
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz

                    Switch Name: cs2
           Periodic Log Enabled: false
            Periodic Log Status: Periodic collection has been halted.
    Last Periodic Log Timestamp: 3/11/2024 11:05:18
          Periodic Log Filename: cluster1:/mroot/etc/log/shm-cluster-info.tgz
          Support Log Requested: false
             Support Log Status: Successfully gathered support logs - see filename for their location.
     Last Support Log Timestamp: 3/11/2024 11:18:54
           Support Log Filename: cluster1:/mroot/etc/log/shm-cluster-log.tgz
2 entries were displayed.
----


--
.ONTAP 9.14.1 e anteriores
--
. Para configurar a coleta de logs, execute o seguinte comando para cada switch.  Você será solicitado a inserir o nome do switch, o nome de usuário e a senha para a coleta de logs.
+
*NOTA:* Se responder `y` Na solicitação de especificação do usuário, certifique-se de que o usuário tenha as permissões necessárias, conforme descrito em<<Antes de começar>> .

+
[source, cli]
----
system switch ethernet log setup-password
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*

Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----



NOTE: Para CL 5.11.1, crie o usuário *cumulus* e responda *y* à seguinte mensagem: Deseja especificar um usuário diferente de admin para a coleta de logs?  {s|n}: *s*

. [[passo 2]] Para solicitar a coleta de logs de suporte e habilitar a coleta periódica, execute o seguinte comando.  Isso inicia os dois tipos de coleta de logs: a detalhada `Support` registros e uma coleta horária de `Periodic` dados.
+
[source, cli]
----
system switch ethernet log modify -device <switch-name> -log-request true
----
+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
+
Aguarde 10 minutos e verifique se a coleta de logs foi concluída:

+
[source, cli]
----
system switch ethernet log show
----


--
====

CAUTION: Se algum status de erro for relatado pelo recurso de coleta de logs (visível na saída de `system switch ethernet log show` ), verlink:log-collection-troubleshoot.html["Solução de problemas na coleta de logs"] Para obter mais detalhes.

.O que vem a seguir?
link:config-snmpv3.html["Configurar SNMPv3 (Opcional)"].
