---
permalink: switch-cshm/monitor-verify.html 
sidebar: sidebar 
keywords: verify, monitor, cluster, management, network, switches, heath, monitor 
summary: Saiba como verificar se o monitoramento de um switch Ethernet está funcionando. 
---
= Verifique o monitoramento dos switches Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O monitor de integridade do switch Ethernet (CSHM) tenta monitorar automaticamente os switches que ele descobre; no entanto, o monitoramento pode não acontecer automaticamente se os switches não estiverem configurados corretamente. Você deve verificar se o monitor de integridade está configurado corretamente para monitorar seus switches.



== Confirme o monitoramento dos switches Ethernet conetados

Para confirmar se os switches Ethernet conetados estão sendo monitorados, execute:

[source, cli]
----
system switch ethernet show
----
Se a `Model` coluna exibir *OTHER* ou o `IS Monitored` campo exibir *false*, o ONTAP não poderá monitorar o switch. Um valor de *OTHER* normalmente indica que o ONTAP não suporta esse switch para monitoramento de integridade.

O `IS Monitored` campo é definido como *false* pelo motivo especificado no `Reason` campo.

[NOTE]
====
Se um switch não estiver listado na saída do comando, o ONTAP provavelmente não o descobriu. Confirme se o switch está cabeado corretamente. Se necessário, pode adicionar o interrutor manualmente. link:manage-monitor.html["Gerenciar o monitoramento de switches Ethernet"]Consulte para obter mais detalhes.

====


== Confirme se as versões do firmware e do RCF estão atualizadas

Certifique-se de que o comutador está a executar o firmware suportado mais recente e de que foi aplicado um ficheiro de configuração de referência (RCF) compatível. Mais informações estão disponíveis no https://mysupport.netapp.com/site/downloads["Página de transferências do suporte da NetApp"^].

Por padrão, o monitor de integridade usa SNMPv2c com a string da comunidade *cshm1!* para monitoramento, mas SNMPv3 também pode ser configurado.

Se você precisar alterar a cadeia de carateres padrão da comunidade SNMPv2c, certifique-se de que a string de comunidade SNMPv2c desejada tenha sido configurada no switch.

[source, cli]
----
system switch ethernet modify -device SwitchA -snmp-version SNMPv2c -community-or-username newCommunity!
----

NOTE: link:config-snmpv3.html["Opcional: Configurar SNMPv3"]Consulte para obter detalhes sobre como configurar o SNMPv3 para uso.



== Confirme a conexão de rede de gerenciamento

Verifique se a porta de gerenciamento do switch está conetada à rede de gerenciamento.

Uma conexão de porta de gerenciamento correta é necessária para que o ONTAP execute consultas SNMP e coleta de logs.
