---
permalink: switch-cshm/monitor-troubleshoot.html 
sidebar: sidebar 
keywords: cshm, cluster, storage, switch logs, debugging, collection 
summary: Solucione alertas de monitoramento de integridade do switch Ethernet gerados pelo CSHM em seu cluster ONTAP. 
---
= Solucionar problemas de alertas para o monitor de integridade do switch Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Solucione problemas relacionados a alertas gerados pelo monitor de integridade do Ethernet (CSHM) quando uma falha, risco ou condição crítica for detectada em um switch de rede no seu cluster ONTAP.

Caso sejam acionados alertas, o status de integridade do sistema será relatado como degradado para o cluster.  Os alertas gerados incluem as informações necessárias para que você possa responder à degradação da integridade do sistema.

Para visualizar os alertas disponíveis do monitor de integridade do switch Ethernet, execute o comando: `system health alert definition show -monitor ethernet-switch`

Consulte o artigo da Knowledge Base https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Cluster_Switch_Health_Monitor_CSHM_Alert_Resolution_Guide["Guia de Resolução de Alertas do Monitor de Saúde do Switch"^] para obter detalhes avançados sobre a resolução de alertas.
