---
permalink: switch-cshm/monitor-manage.html 
sidebar: sidebar 
keywords: create, remove, switch, cluster, monitor, health, management 
summary: Saiba como criar manualmente, alterar as configurações de monitoramento padrão e excluir switches Ethernet do monitoramento. 
---
= Gerenciar o monitoramento de switches Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na maioria dos casos, os switches Ethernet são automaticamente descobertos pelo ONTAP e monitorados pelo CSHM. O arquivo de configuração de referência (RCF) aplicado ao switch, entre outras coisas, ativa o protocolo de descoberta de Cisco (CDP) e/ou o protocolo de descoberta de camada de enlace (LLDP). No entanto, talvez seja necessário adicionar manualmente um switch que não seja descoberto ou remover um switch que não esteja mais em uso. Também pode parar a monitorização ativa mantendo o interrutor na configuração, como durante a manutenção.



== Crie uma entrada de switch para que o ONTAP possa monitorá-la

Use o `system switch ethernet create` comando para configurar e ativar manualmente o monitoramento de um switch Ethernet especificado. Isso é útil se o ONTAP não adicionar o switch automaticamente ou se você removeu o switch anteriormente e deseja adicioná-lo novamente.

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
Um exemplo típico é adicionar um switch chamado [deviceName], com endereço IP 1,2.3,4 e credenciais SNMPv2c definidas como *cshm1!*. Use `-type storage-network` em vez de `-type cluster-network` se você estiver configurando um switch de armazenamento.



== Desative a monitorização sem eliminar o interrutor

Se você quiser pausar ou parar o monitoramento de um determinado switch, mas ainda mantê-lo para monitoramento futuro, modifique seu `is-monitoring-enabled-admim` parâmetro em vez de excluí-lo.

Por exemplo:

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
Isso permite que você preserve os detalhes e a configuração do switch sem gerar novos alertas ou redescobertas.



== Remova um switch que você não precisa mais

Utilize `system switch ethernet delete` para eliminar um interrutor que tenha sido desligado ou que já não seja necessário:

[source, cli]
----
system switch ethernet delete -device DeviceName
----
Por padrão, esse comando só será bem-sucedido se o ONTAP não detetar o switch atualmente através do CDP ou do LLDP. Para remover um switch descoberto, use o `-force` parâmetro:

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
 `-force`Quando o é usado, o switch pode ser readicionado automaticamente se o ONTAP o detetar novamente.
