---
permalink: switch-nvidia-sn2100-storage/configure-software-sn2100-storage.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: Visão geral do processo de configuração de software para switches de armazenamento NVIDIA SN2100. 
---
= Fluxo de trabalho de instalação de software para switches de storage NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar e configurar o software para um switch NVIDIA SN2100, siga estas etapas:

. link:install-cumulus-mode-sn2100-storage.html["Instale o Cumulus Linux no modo Cumulus"] ou link:install-onie-mode-sn2100-storage.html["Instale o Cumulus Linux no modo ONIE"].
+
Você pode instalar o SO Cumulus Linux (CL) quando o switch estiver executando o Cumulus Linux ou ONIE.

. link:install-rcf-sn2100-storage.html["Instale o script Reference Configuration File (ficheiro de configuração de referência)"].
+
Existem dois scripts RCF disponíveis para aplicativos de agrupamento e armazenamento.

. link:setup-install-cshm-file.html["Instale o arquivo CSHM"].
+
Você pode instalar o arquivo de configuração aplicável para o monitoramento de integridade do switch Ethernet dos switches de cluster NVIDIA.


