---
permalink: switch-nvidia-sn2100-storage/configure-overview-sn2100-storage.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: Antes de configurar os interrutores NVIDIA SN2100, reveja a descrição geral do procedimento. 
---
= Visão geral do processo de configuração para switches de armazenamento NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O NVIDIA SN2100 é um switch Ethernet que permite alternar dados entre controladores e compartimentos de disco.



== Visão geral da configuração inicial

Para configurar um switch NVIDIA SN2100 em sistemas que executam o ONTAP, siga estas etapas:

. link:install-hardware-sn2100-storage.html["Instale o hardware do switch NVIDIA SN2100"].
+
As instruções estão disponíveis no _Guia de Instalação do comutador NVIDIA_.

. link:configure-sn2100-storage.html["Configure o interrutor"].
+
As instruções estão disponíveis na documentação do NVIDIA.

. link:cabling-considerations-sn2100-storage.html["Analise as considerações sobre cabeamento e configuração"].
+
Revise os requisitos para conexões óticas, o adaptador QSA e a velocidade do switchport.

. link:install-cable-shelves-sn2100-storage.html["Cabo NS224 prateleiras como storage conetado a switch"].
+
Siga estes procedimentos se você tiver um sistema no qual os NS224 compartimentos de unidades precisem ser cabeados como storage conectado ao switch (não storage com conexão direta).

. link:install-cumulus-mode-sn2100-storage.html["Instale o Cumulus Linux no modo Cumulus"] ou link:install-onie-mode-sn2100-storage.html["Instale o Cumulus Linux no modo ONIE"].
+
Você pode instalar o SO Cumulus Linux (CL) quando o switch estiver executando o Cumulus Linux ou ONIE.

. link:install-rcf-sn2100-storage.html["Instale o script Reference Configuration File (ficheiro de configuração de referência)"].
+
Existem dois scripts RCF disponíveis para aplicativos de agrupamento e armazenamento.

. link:setup-install-cshm-file.html["Instale o arquivo CSHM"].
+
Você pode instalar o arquivo de configuração aplicável para o monitoramento de integridade do switch Ethernet dos switches de cluster NVIDIA.





== Informações adicionais

Antes de iniciar a instalação ou manutenção, certifique-se de rever o seguinte:

* link:configure-reqs-sn2100-storage.html["Requisitos de configuração"]
* link:components-sn2100-storage.html["Componentes e números de peça"]
* link:required-documentation-sn2100-storage.html["Documentação necessária"]

