---
permalink: switch-nvidia-sn2100-storage/install-cumulus-mode-sn2100-storage.html 
sidebar: sidebar 
keywords: install cumulus mode, sn2100 SN2100 switches setup, cumulus linux, cumulus mode 
summary: 'O SO Cumulus Linux (CL) pode ser instalado quando o switch está executando Cumulus Linux ou ONIE.' 
---
= Instale o Cumulus Linux no modo Cumulus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para instalar o SO Cumulus Linux (CL) quando o switch estiver em execução no modo Cumulus.


NOTE: O SO Cumulus Linux (CL) pode ser instalado quando o switch está executando o Cumulus Linux ou ONIE (link:install-onie-mode-sn2100-storage.html["Instale no modo ONIE"]consulte ).

.Antes de começar
Certifique-se de que o seguinte esteja disponível:

* Conhecimento do Linux de nível intermediário.
* Familiaridade com edição de texto básica, permissões de arquivo UNIX e monitoramento de processos. Uma variedade de editores de texto são pré-instalados, `vi` incluindo e `nano`.
* Acesso a um shell Linux ou UNIX. Se você estiver executando o Windows, use um ambiente Linux como sua ferramenta de linha de comando para interagir com o Cumulus Linux.
* O requisito de taxa de transmissão deve ser definido como 115200 no switch do console serial para acesso ao console do switch NVIDIA SN2100, como segue:
+
** 115200 baud
** 8 bits de dados
** 1 bit de paragem
** paridade: nenhuma
** controle de fluxo: nenhum




.Sobre esta tarefa
Tenha em atenção o seguinte:


NOTE: Cada vez que o Cumulus Linux é instalado, toda a estrutura do sistema de arquivos é apagada e reconstruída.


CAUTION: A senha padrão para a conta de usuário do Cumulus é *Cumulus*. A primeira vez que você fizer login no Cumulus Linux, você deve alterar essa senha padrão. Certifique-se de atualizar quaisquer scripts de automação antes de instalar uma nova imagem. O Cumulus Linux fornece opções de linha de comando para alterar a senha padrão automaticamente durante o processo de instalação.

.Passos
. Inicie sessão no interrutor.
+
O login pela primeira vez no switch requer nome de usuário/senha do *Cumulus*/*Cumulus* com `sudo` o Privileges.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
====
. Verifique a versão Cumulus Linux:
+
`net show system`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show system*
Hostname......... cumulus
Build............ *Cumulus Linux 4.4.3*
Uptime........... 0:08:20.860000
Model............ Mlnx X86
CPU.............. x86_64 Intel Atom C2558 2.40GHz
Memory........... 8GB
Disk............. 14.7GB
ASIC............. Mellanox Spectrum MT52132
Ports............ 16 x 100G-QSFP28
Part Number...... MSN2100-CB2FC
Serial Number.... MT2105T05177
Platform Name.... x86_64-mlnx_x86-r0
Product Name..... MSN2100
ONIE Version..... 2019.11-5.2.0020-115200
Base MAC Address. 04:3F:72:43:92:80
Manufacturer..... Mellanox
----
====
. Configure o nome do host, o endereço IP, a máscara de sub-rede e o gateway padrão. O novo nome de host só se torna efetivo após reiniciar a sessão console/SSH.
+

NOTE: Um switch Cumulus Linux fornece pelo menos uma porta de gerenciamento Ethernet dedicada `eth0` chamada . Esta interface é especificamente para uso de gerenciamento fora da banda. Por padrão, a interface de gerenciamento usa DHCPv4 para endereçamento.

+

CAUTION: Não use um sublinhado (_), apóstrofo (') ou carateres não-ASCII no nome do host.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net add hostname sw1*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip address 10.233.204.71*
cumulus@cumulus:mgmt:~$ *net add interface eth0 ip gateway 10.233.204.1*
cumulus@cumulus:mgmt:~$ *net pending*
cumulus@cumulus:mgmt:~$ *net commit*
----
====
+
Este comando modifica os `/etc/hostname` ficheiros e `/etc/hosts`.

. Confirme se o nome do host, o endereço IP, a máscara de sub-rede e o gateway padrão foram atualizados.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *hostname sw1*
cumulus@sw1:mgmt:~$ *ifconfig eth0*
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.233.204.71  netmask 255.255.254.0  broadcast 10.233.205.255
inet6 fe80::bace:f6ff:fe19:1df6  prefixlen 64  scopeid 0x20<link>
ether b8:ce:f6:19:1d:f6  txqueuelen 1000  (Ethernet)
RX packets 75364  bytes 23013528 (21.9 MiB)
RX errors 0  dropped 7  overruns 0  frame 0
TX packets 4053  bytes 827280 (807.8 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 device memory 0xdfc00000-dfc1ffff

cumulus@sw1::mgmt:~$ *ip route show vrf mgmt*
default via 10.233.204.1 dev eth0
unreachable default metric 4278198272
10.233.204.0/23 dev eth0 proto kernel scope link src 10.233.204.71
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
====
. Configure o fuso horário usando o modo interativo NTP.
+
.. Em um terminal, execute o seguinte comando:
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *sudo dpkg-reconfigure tzdata*
----
.. Siga as opções do menu no ecrã para selecionar a área geográfica e a região.
.. Para definir o fuso horário para todos os serviços e daemons, reinicie o switch.
.. Verifique se a data e a hora do switch estão corretas e atualize, se necessário.


. Instale o Cumulus Linux 4,4.3:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*
----
+
O instalador inicia a transferência. Digite *y* quando solicitado.

. Reinicie o switch NVIDIA SN2100:
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. A instalação é iniciada automaticamente e as seguintes telas do GRUB aparecem. *Não* faça seleções:
+
** Cumulus-Linux GNU/Linux
** ONIE: Instale os
** CUMULUS-INSTALL
** Cumulus-Linux GNU/Linux


. Repita os passos 1 a 4 para iniciar sessão.
. Verifique se a versão Cumulus Linux é 4,4.3:
+
`net show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u0
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3"*
----
====
. Crie um novo usuário e adicione esse usuário ao `sudo` grupo. Este usuário só se torna efetivo após a sessão console/SSH ser reiniciada.
+
`sudo adduser --ingroup netedit admin`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user `admin’ ...
Adding new user `admin’ (1001) with group `netedit' ...
Creating home directory `/home/admin’ ...
Copying files from `/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ exit
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.3u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
====


.O que se segue?
link:install-rcf-sn2100-storage.html["Instale ou atualize o script RCF"] .
