---
permalink: switch-nvidia-sn2100-storage/install-onie-mode-sn2100-storage.html 
sidebar: sidebar 
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode 
summary: 'O SO Cumulus Linux (CL) pode ser instalado quando o switch está executando Cumulus Linux ou ONIE.' 
---
= Instale o Cumulus Linux no modo ONIE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para instalar o SO Cumulus Linux (CL) quando o switch estiver em execução no modo ONIE.


NOTE: O SO Cumulus Linux (CL) pode ser instalado quando o switch está executando o Cumulus Linux ou ONIE (link:install-cumulus-mode-sn2100-storage.html["Instale no modo Cumulus"]consulte ).

.Sobre esta tarefa
Você pode instalar o Cumulus Linux usando o Open Network Install Environment (ONIE) que permite a descoberta automática de uma imagem do instalador de rede. Isso facilita o modelo de sistema de proteção de switches com uma escolha de sistema operacional, como o Cumulus Linux. A maneira mais fácil de instalar o Cumulus Linux com ONIE é com descoberta HTTP local.


NOTE: Se o seu host estiver habilitado para IPv6, verifique se ele está executando um servidor da Web. Se o seu host estiver habilitado para IPv4, verifique se ele está executando o DHCP além de um servidor da Web.

Este procedimento demonstra como atualizar o Cumulus Linux após o administrador ter inicializado no ONIE.

.Passos
. Baixe o arquivo de instalação Cumulus Linux para o diretório raiz do servidor web. Renomeie este arquivo `onie-installer`.
. Conete o host à porta Ethernet de gerenciamento do switch usando um cabo Ethernet.
. Ligue o interrutor. O switch faz o download do instalador de imagem ONIE e inicializa. Após a conclusão da instalação, o prompt de login do Cumulus Linux aparece na janela do terminal.
+

NOTE: Cada vez que o Cumulus Linux é instalado, toda a estrutura do sistema de arquivos é apagada e reconstruída.

. Reinicie o switch SN2100:
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. Pressione a tecla *ESC* na tela GNU GRUB para interromper o processo de inicialização normal, selecione *ONIE* e pressione *Enter*.
. Na próxima tela exibida, selecione *ONIE: Install os*.
. O processo de descoberta do instalador ONIE é executado procurando a instalação automática. Pressione *Enter* para interromper temporariamente o processo.
. Quando o processo de descoberta for interrompido:
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. Se o serviço DHCP estiver em execução na rede, verifique se o endereço IP, a máscara de sub-rede e o gateway padrão estão corretamente atribuídos:
+
`ifconfig eth0`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
====
. Se o esquema de endereçamento IP for definido manualmente, faça o seguinte:
+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. Repita o passo 9 para verificar se as informações estáticas foram introduzidas corretamente.
. Instale o Cumulus Linux:
+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. Depois de concluída a instalação, inicie sessão no interrutor:
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
====
. Verifique a versão Cumulus Linux:
+
`net show version`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----
====


.O que se segue?
Depois de instalar o Cumulus Linux no modo ONIE, você link:install-rcf-sn2100-storage.html["Instalar ou atualizar o script RCF"].
