---
permalink: switch-nvidia-sn2100-storage/migrate-cisco-storage-switch-sn2100-storage.html 
sidebar: sidebar 
keywords: migrating to a storage switch with NVIDIA SN2100 storage switches, how to migrate 
summary: É possível migrar switches Cisco mais antigos de um cluster ONTAP para switches de armazenamento NVIDIA SN2100 sem interrupções. 
---
= Migre de um switch de armazenamento Cisco para um switch de armazenamento NVIDIA SN2100.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode migrar switches Cisco mais antigos de um cluster ONTAP para switches de armazenamento NVIDIA SN2100. Este é um procedimento não disruptivo.



== Requisitos de revisão

Os seguintes switches de armazenamento são suportados:

* Cisco Nexus 9336C-FX2
* Cisco Nexus 3232C
* Veja o https://hwu.netapp.com/["Hardware Universe"^] Para obter detalhes completos sobre as portas suportadas e suas configurações.


.Antes de começar
Certifique-se de ter o seguinte:

* O cluster existente está configurado corretamente e funcionando.
* Todas as portas de armazenamento estão em estado ativo para garantir operações sem interrupções.
* Os switches de armazenamento NVIDIA SN2100 estão configurados e operando na versão correta do Cumulus Linux instalada com o arquivo de configuração de referência (RCF) aplicado.
* A configuração de rede de armazenamento existente apresenta as seguintes características:
+
** Um cluster NetApp redundante e totalmente funcional, utilizando switches Cisco mais antigos.
** Conectividade de gerenciamento e acesso ao console tanto para os switches Cisco mais antigos quanto para os novos.
** Todas as LIFs do cluster estão ativas e conectadas às suas portas de origem.
** As portas ISL foram habilitadas e cabeadas entre os switches Cisco mais antigos e entre os novos switches.


* Veja o https://hwu.netapp.com/["Hardware Universe"^] Para obter detalhes completos sobre as portas suportadas e suas configurações.
* Algumas das portas estão configuradas em switches NVIDIA SN2100 para operar em 100 GbE.
* Você planejou, migrou e documentou a conectividade de 100 GbE dos nós para os switches de armazenamento NVIDIA SN2100.




== Migre os switches

.Sobre os exemplos
Neste procedimento, os switches de armazenamento Cisco Nexus 9336C-FX2 são usados ​​como exemplos de comandos e saídas.

Os exemplos neste procedimento utilizam a seguinte nomenclatura de interruptor e nó:

* Os switches de armazenamento Cisco Nexus 9336C-FX2 existentes são _S1_ e _S2_.
* Os novos switches de armazenamento NVIDIA SN2100 são _sw1_ e _sw2_.
* Os nós são _node1_ e _node2_.
* Os LIFs do cluster são _node1_clus1_ e _node1_clus2_ no nó 1, e _node2_clus1_ e _node2_clus2_ no nó 2, respectivamente.
* O `cluster1::*>` O prompt indica o nome do cluster.
* As portas de rede utilizadas neste procedimento são _e5a_ e _e5b_.
* As portas de breakout têm o formato: swp1s0-3.  Por exemplo, quatro portas de breakout em swp1 são _swp1s0_, _swp1s1_, _swp1s2_ e _swp1s3_.
* Primeiro, a chave S2 é substituída pela chave sw2 e, em seguida, a chave S1 é substituída pela chave sw1.
+
** Os cabos entre os nós e o switch S2 são então desconectados do switch S2 e reconectados ao switch S2.
** Os cabos entre os nós e o switch S1 são então desconectados do switch S1 e reconectados ao switch sw1.






=== Etapa 1: Prepare-se para a migração

. Se o AutoSupport estiver ativado, suprima a criação automática de casos invocando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
onde _x_ é a duração da janela de manutenção em horas.

. Altere o nível de privilégio para avançado, digitando *y* quando solicitado a continuar:
+
`set -privilege advanced`

+
A mensagem avançada (*>) é exibida.

. Determine o status administrativo ou operacional de cada interface de armazenamento:
+
Cada porta deve exibir "habilitado" para `Status` .





=== Etapa 2: Configurar cabos e portas

. Exibir os atributos da porta de rede:
+
`storage port show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. Verifique se as portas de armazenamento em cada nó estão conectadas aos switches de armazenamento existentes da seguinte maneira (da perspectiva dos nós) usando o comando:
+
`network device-discovery show -protocol lldp`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/1           -
node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/2           -
----
====
. Nos switches S1 e S2, certifique-se de que as portas de armazenamento e os switches estejam conectados da seguinte maneira (do ponto de vista dos switches) usando o comando:
+
`show lldp neighbors`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/1         121         S                    e0c
node2                 Eth1/2         121         S                    e0c
SHFGD1947000186       Eth1/10        120         S                    e0a         
SHFGD1947000186       Eth1/11        120         S                    e0a         
SHFGB2017000269       Eth1/12        120         S                    e0a         
SHFGB2017000269       Eth1/13        120         S                    e0a

S2# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability          Port ID
node1                 Eth1/1         121         S                   e5b
node2                 Eth1/2         121         S                   e5b
SHFGD1947000186       Eth1/10        120         S                   e0b         
SHFGD1947000186       Eth1/11        120         S                   e0b         
SHFGB2017000269       Eth1/12        120         S                   e0b         
SHFGB2017000269       Eth1/13        120         S                   e0b
----
====
. No switch sw2, desligue as portas conectadas às portas de armazenamento e aos nós dos gabinetes de discos.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net add interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Mova as portas de armazenamento do controlador e dos gabinetes de discos do switch antigo S2 para o novo switch sw2, usando a cablagem apropriada compatível com o NVIDIA SN2100.
. No switch sw2, ative as portas conectadas às portas de armazenamento dos nós e aos gabinetes de discos.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. Verifique se as portas de armazenamento em cada nó estão agora conectadas aos switches da seguinte maneira, da perspectiva dos nós:
+
`network device-discovery show -protocol lldp`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface      Platform
----------- ------ ------------------------- -------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1           -

node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp2           -
----
====
. Verifique os atributos da porta de rede:
+
`storage port show`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. No switch sw2, verifique se todas as portas de armazenamento do nó estão ativas:
+
`net show interface`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. No switch sw1, desligue as portas conectadas às portas de armazenamento dos nós e aos gabinetes de discos.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. Mova as portas de armazenamento do controlador e os gabinetes de discos do switch antigo S1 para o novo switch sw1, usando a cablagem apropriada compatível com o NVIDIA SN2100.
. No switch sw1, ative as portas conectadas às portas de armazenamento dos nós e aos gabinetes de discos.
+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. Verifique se as portas de armazenamento em cada nó estão agora conectadas aos switches da seguinte maneira, da perspectiva dos nós:
+
`network device-discovery show -protocol lldp`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    sw1 (b8:ce:f6:19:1b:96)   swp1            -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1            -

node2      /lldp
            e0c    sw1  (b8:ce:f6:19:1b:96)  swp2            -
            e5b    sw2  (b8:ce:f6:19:1a:7e)  swp2            -
----
====




=== Etapa 3: Verifique a configuração

. Verifique a configuração final:
+
`storage port show`

+
Cada porta deve exibir "habilitado" para `State` e habilitado para `Status` .

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. No switch sw2, verifique se todas as portas de armazenamento do nó estão ativas:
+
`net show interface`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. Verifique se ambos os nós possuem uma conexão com cada switch:
+
`net show lldp`

+
.Mostrar exemplo
[%collapsible]
====
O exemplo a seguir mostra os resultados apropriados para ambas as opções:

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e0c
swp2       100G   Trunk/L2  node2                  e0c
swp3       100G   Trunk/L2  SHFFG1826000112        e0a
swp4       100G   Trunk/L2  SHFFG1826000112        e0a
swp5       100G   Trunk/L2  SHFFG1826000102        e0a
swp6       100G   Trunk/L2  SHFFG1826000102        e0a

cumulus@sw2:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e5b
swp2       100G   Trunk/L2  node2                  e5b
swp3       100G   Trunk/L2  SHFFG1826000112        e0b
swp4       100G   Trunk/L2  SHFFG1826000112        e0b
swp5       100G   Trunk/L2  SHFFG1826000102        e0b
swp6       100G   Trunk/L2  SHFFG1826000102        e0b
----
====


. Altere o nível de privilégio de volta para administrador:
+
`set -privilege admin`

. Se você desativou a criação automática de casos, reative-a enviando uma mensagem do AutoSupport :
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.O que vem a seguir?
Depois de migrar seus switches, você pode link:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"].
