---
permalink: switch-nvidia-sn2100-storage/required-documentation-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: Para instalação e manutenção do switch NVIDIA SN2100, certifique-se de consultar toda a documentação recomendada. 
---
= Requisitos de documentação para switches NVIDIA SN2100
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalação e manutenção do switch NVIDIA SN2100, certifique-se de consultar toda a documentação recomendada.

A tabela a seguir lista a documentação disponível para os switches NVIDIA SN2100.

[cols="1,2"]
|===
| Título | Descrição 


 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/install-hardware-sn2100-cluster.html["_Configure e configure seus switches NVIDIA SN2100_"^]
 a| 
Este manual descreve como configurar e instalar seus switches NVIDIA SN2100, incluindo a instalação do Cumulus Linux e dos RCFs aplicáveis.



 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100-storage/migrate-cisco-storage-switch-sn2100-storage.html["_Migrar de um switch de armazenamento Cisco para um switch de armazenamento NVIDIA SN2100_"^]
 a| 
Descreve como migrar de ambientes que usam switches de armazenamento Cisco para ambientes que usam switches de armazenamento NVIDIA SN2100.



 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html["_Migre para um cluster comutado de dois nós com switches de cluster NVIDIA SN2100_"^]
 a| 
Descreve como migrar para um ambiente comutado de dois nós usando switches de cluster NVIDIA SN2100.



 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100-storage/replace-sn2100-switch-storage.html["_Substituir um switch de armazenamento NVIDIA SN2100_"^]
 a| 
Descreve o procedimento para substituir um switch de armazenamento NVIDIA SN2100 defeituoso e para fazer o download do Cumulus Linux e do arquivo de configuração de referência.

|===