---
permalink: switch-nvidia-sn2100-storage/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for sn2100 switches' 
summary: Você pode usar este procedimento para instalar o arquivo de configuração aplicável para o monitoramento de integridade do cluster de switches de armazenamento NVIDIA SN2100. 
---
= Instale o arquivo de configuração do Monitor de Saúde do Switch Ethernet.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para instalar o arquivo de configuração aplicável para monitoramento da integridade do switch Ethernet em switches de cluster NVIDIA .  Os modelos suportados são:

* MSN2100-CB2FC
* MSN2100-CB2RC
* X190006-PE
* X190006-PI



NOTE: Este procedimento de instalação aplica-se ao ONTAP 9.10.1 e versões posteriores.

.Antes de começar
* Verifique se você precisa baixar o arquivo de configuração executando o seguinte comando: `system switch ethernet show` e verificando se *OUTRO* é exibido para o seu modelo.
+
Se o seu modelo ainda estiver exibindo *OUTRO* após a aplicação do arquivo de configuração, entre em contato com o suporte da NetApp .

* Certifique-se de que o cluster ONTAP esteja ativo e em funcionamento.
* Habilite o SSH para usar todos os recursos disponíveis no CSHM.
* Limpe o `/mroot/etc/cshm_nod/nod_sign/` diretório em todos os nós:
+
.. Entre no shell do nó:
+
`system node run -node <name>`

.. Alteração para privilégios avançados:
+
`priv set advanced`

.. Liste os arquivos de configuração em `/etc/cshm_nod/nod_sign` diretório.  Se o diretório existir e contiver arquivos de configuração, ele listará os nomes dos arquivos.
+
`ls /etc/cshm_nod/nod_sign`

.. Exclua todos os arquivos de configuração correspondentes aos modelos de switch conectados.
+
Caso não tenha certeza, remova todos os arquivos de configuração dos modelos compatíveis listados acima e, em seguida, baixe e instale os arquivos de configuração mais recentes para esses mesmos modelos.

+
`rm /etc/cshm_nod/nod_sign/<filename>`

.. Confirme se os arquivos de configuração excluídos não estão mais no diretório:
+
`ls /etc/cshm_nod/nod_sign`





.Passos
. Baixe o arquivo zip de configuração do monitor de integridade do switch Ethernet, de acordo com a versão do ONTAP correspondente.  Este arquivo está disponível em https://mysupport.netapp.com/site/info/nvidia-cluster-switch["Switches Ethernet NVIDIA"^] página.
+
.. Na página de download do software NVIDIA SN2100, selecione *Arquivo CSHM da NVIDIA*.
.. Na página de Atenção/Leitura Obrigatória, selecione a caixa de seleção para concordar.
.. Na página do Contrato de Licença do Usuário Final, selecione a caixa de seleção para concordar e clique em *Aceitar e Continuar*.
.. Na página de download do arquivo CSHM da Nvidia, selecione o arquivo de configuração aplicável.  Os seguintes arquivos estão disponíveis:




[role="tabbed-block"]
====
.ONTAP 9.15.1 e posterior
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip


--
.ONTAP 9.11.1 a 9.14.1
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip


--
====
. [[passo 2]]Faça o upload do arquivo zip correspondente para o seu servidor web interno.
. Acesse as configurações do modo avançado a partir de um dos sistemas ONTAP no cluster.
+
`set -privilege advanced`

. Execute o comando de configuração do monitor de integridade do switch.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor*
----
. Verifique se a saída do comando termina com o seguinte texto para a sua versão do ONTAP :


[role="tabbed-block"]
====
.ONTAP 9.15.1 e posterior
--
O monitoramento de integridade do switch Ethernet instalou o arquivo de configuração.

--
.ONTAP 9.11.1 a 9.14.1
--
O SHM instalou o arquivo de configuração.

--
.ONTAP 9.10.1
--
O pacote CSHM foi baixado e processado com sucesso.

--
====
Caso ocorra algum erro, entre em contato com o suporte da NetApp .

. [[passo 6]]Aguarde até o dobro do intervalo de sondagem do monitor de integridade do switch Ethernet, determinado executando `system switch ethernet polling-interval show` , antes de concluir a próxima etapa.
. Execute o comando `system switch ethernet configure-health-monitor show` No sistema ONTAP , certifique-se de que os switches do cluster sejam descobertos com o campo monitorado definido como *Verdadeiro* e o campo do número de série não mostrando *Desconhecido*.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor show*
----


.O que vem a seguir?
Após instalar o arquivo CSHM, você podelink:../switch-cshm/config-overview.html["configurar monitoramento de integridade do switch"] .
